### ISSUE TITLE
Sentry-python cannot run upgrade

### ISSUE THREAD

**Issue by slaffcheff** [getsentry/sentry#10947]
Hello, folks! Trying to install sentry on-premise using the python method but when I try to run the upgrade and I hit huge error (everything is done as docs says):

```
(sentry) root@d10e23c3b55f:~# SENTRY_CONF=/etc/sentry sentry upgrade
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/options/store.py", line 165, in get_store
    value = self.model.objects.get(key=key.name).value
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 84, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 115, in get_new_connection
    return Database.connect(**conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

13:15:49 [ERROR] sentry: option.failed-lookup (key=u'system.url-prefix')
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/options/store.py", line 165, in get_store
    value = self.model.objects.get(key=key.name).value
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 84, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 115, in get_new_connection
    return Database.connect(**conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

13:15:50 [INFO] sentry.utils.raven.SentryInternalClient: Not capturing exception due to filters: <class 'django.db.utils.OperationalError'>
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/options/store.py", line 165, in get_store
    value = self.model.objects.get(key=key.name).value
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 84, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 115, in get_new_connection
    return Database.connect(**conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

13:15:50 [ERROR] sentry: option.failed-lookup (key=u'system.url-prefix')
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/options/store.py", line 165, in get_store
    value = self.model.objects.get(key=key.name).value
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 84, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 115, in get_new_connection
    return Database.connect(**conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

13:15:50 [INFO] sentry.utils.raven.SentryInternalClient: Not capturing exception due to filters: <class 'django.db.utils.OperationalError'>
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 64, in worker
    tsdb.incr(tsdb.models.internal, full_key, count=amount)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/services.py", line 91, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 214, in incr
    self.incr_multi([(model, key)], timestamp, count, environment_id)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 239, in incr_multi
    client.hincrby(hash_key, hash_field, count)
  File "/www/sentry/local/lib/python2.7/site-packages/redis/client.py", line 1865, in hincrby
    return self.execute_command('HINCRBY', name, key, amount)
  File "/www/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 333, in execute_command
    buf = self._get_command_buffer(host_id, args[0])
  File "/www/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 351, in _get_command_buffer
    buf = CommandBuffer(host_id, connect, self.auto_batch)
  File "/www/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 90, in __init__
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 109, in connect
    self.connection.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 446, in connect
    self.on_connect()
  File "/www/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/www/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: Client sent AUTH, but no password is set
13:15:50 [ERROR] sentry.errors: Unable to incr internal metric
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 64, in worker
    tsdb.incr(tsdb.models.internal, full_key, count=amount)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/services.py", line 91, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 214, in incr
    self.incr_multi([(model, key)], timestamp, count, environment_id)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 239, in incr_multi
    client.hincrby(hash_key, hash_field, count)
  File "/www/sentry/local/lib/python2.7/site-packages/redis/client.py", line 1865, in hincrby
    return self.execute_command('HINCRBY', name, key, amount)
  File "/www/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 333, in execute_command
    buf = self._get_command_buffer(host_id, args[0])
  File "/www/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 351, in _get_command_buffer
    buf = CommandBuffer(host_id, connect, self.auto_batch)
  File "/www/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 90, in __init__
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 109, in connect
    self.connection.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 446, in connect
    self.on_connect()
  File "/www/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/www/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: Client sent AUTH, but no password is set
13:15:50 [ERROR] sentry.errors: Unable to incr internal metric
Error in sys.excepthook:
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/raven/base.py", line 274, in handle_exception
    self.captureException(exc_info=exc_info, level='fatal')
  File "/www/sentry/local/lib/python2.7/site-packages/raven/base.py", line 814, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 46, in capture
    return super(SentryInternalClient, self).capture(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 297, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/raven/base.py", line 641, in capture
    self.send(**data)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 75, in send
    key = ProjectKey.get_default(settings.SENTRY_PROJECT)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/models/projectkey.py", line 121, in get_default
    )[0]
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 84, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 115, in get_new_connection
    return Database.connect(**conn_params)
  File "/www/sentry/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?


Original exception was:
Traceback (most recent call last):
  File "/www/sentry/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 125, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 152, in configure
    skip_service_validation=skip_service_validation
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 321, in initialize_app
    setup_services(validate=not skip_service_validation)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 344, in setup_services
    service.validate()
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/services.py", line 91, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/buffer/redis.py", line 71, in validate
    raise InvalidConfiguration(six.text_type(e))
sentry.exceptions.InvalidConfiguration: Client sent AUTH, but no password is set
```

Note that this is initial installation. Sentry dashboard and server / service doesn't run at this point. I'm kinda stuck.

**Comment by mattrobenolt** [comment]
It’s clearly failing to communicate to both Redis and Postgres. Connection information needs to be configured.

**Comment by mattrobenolt** [comment]
> Client sent AUTH, but no password is set

Your Redis is running, but yelling about this. 

> could not connect to server: No such file or directory
>	Is the server running locally and accepting
>	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Your Postgres seems to not be running. At least not on the normal Unix socket.

There’s not really anything wrong here with Sentry, hence why I closed this. This is misconfiguration or things running incorrectly on your end.
