### ISSUE TITLE
Sentry crashes on enabling authenticator for 2fa

### ISSUE THREAD

**Issue by mayukuse24** [getsentry/sentry#11020]
## Important Details

Running Sentry with the following environment

* On-Premise docker [Version 9.0]
* Upgraded from 8.16 to 9.0 before attempting enabling 2FA.

## Description

Sentry crashes when enabling 2FA via authenticator for a member. However 2FA does get enabled and works as expected on refreshing Sentry.

## Steps to Reproduce

1. go to settings->account->security
2. enable authenticator app
3. finish the process of setting up.

Error Trace with breadcrumbs :- 

```
Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
  at ba(/usr/src/sentry/node_modules/fbjs/lib/invariant.js:42:1)
  at D(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:14:174)
  at v(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:179:58)
  at h(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:177:269)
  at g(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:178:27)
  at R(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:184:330)
  at G(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:182:155)
  at x(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:181:377)
  at n(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:181:221)
  at B(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:180:80)
  at v(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:179:34)
  at enqueueSetState(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:110:32)
  at setState(/usr/src/sentry/node_modules/react/cjs/react.production.min.js:12:211)
  at handleRequestSuccess(./app/components/asyncComponent.jsx:128:10)
  at apply(./app/components/asyncComponent.jsx:113:16)
  at apply(./app/api.jsx:62:21)
  at fire(/usr/src/sentry/node_modules/jquery/dist/jquery.js:3099:1)
  at resolveWith(/usr/src/sentry/node_modules/jquery/dist/jquery.js:3211:1)
  at done(/usr/src/sentry/node_modules/jquery/dist/jquery.js:8264:1)
  at apply(/usr/src/sentry/node_modules/jquery/dist/jquery.js:8605:1)
  at XMLHttpRequest.r(/usr/src/sentry/node_modules/raven-js/src/raven.js:374:1)
```
![screenshot 2018-12-12 at 6 59 10 pm](https://user-images.githubusercontent.com/9818793/49872843-4ee82980-fe40-11e8-8561-01b2a70f8241.png)

------------------------------------------------------------

```
TypeError: Cannot read property 'id' of undefined
  at renderBody(./app/components/modals/recoveryOptionsModal.jsx:86:53)
  at renderComponent(./app/components/asyncComponent.jsx:228:16)
  at fn(./app/components/asyncComponent.jsx:232:17)
  at render(./app/components/asyncComponent.jsx:239:14)
  at l(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:131:323)
  at Wa(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:138:280)
  at e(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:176:99)
  at f(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:176:376)
  at G(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:182:155)
  at x(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:181:377)
  at n(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:181:221)
  at B(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:180:80)
  at v(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:179:34)
  at enqueueSetState(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:110:32)
  at setState(/usr/src/sentry/node_modules/react/cjs/react.production.min.js:12:211)
  at handleRequestSuccess(./app/components/asyncComponent.jsx:128:10)
  at apply(./app/components/asyncComponent.jsx:113:16)
  at apply(./app/api.jsx:62:21)
  at fire(/usr/src/sentry/node_modules/jquery/dist/jquery.js:3099:1)
  at resolveWith(/usr/src/sentry/node_modules/jquery/dist/jquery.js:3211:1)
  at done(/usr/src/sentry/node_modules/jquery/dist/jquery.js:8264:1)
  at apply(/usr/src/sentry/node_modules/jquery/dist/jquery.js:8605:1)
  at XMLHttpRequest.r(/usr/src/sentry/node_modules/raven-js/src/raven.js:374:1)
```

![screenshot 2018-12-12 at 7 02 02 pm](https://user-images.githubusercontent.com/9818793/49872900-7dfe9b00-fe40-11e8-895a-d9eac0503f6f.png)

------------------------------------------------------------

```
TypeError: Cannot convert undefined or null to object
  at Function.keys(<anonymous>)
  at renderError(./app/components/asyncComponent.jsx:198:37)
  at renderComponent(./app/components/asyncComponent.jsx:227:16)
  at fn(./app/components/asyncComponent.jsx:232:17)
  at render(./app/components/asyncComponent.jsx:239:14)
  at l(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:131:323)
  at Wa(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:138:280)
  at e(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:176:99)
  at f(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:176:376)
  at G(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:182:155)
  at x(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:181:377)
  at n(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:181:221)
  at B(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:180:80)
  at v(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:179:34)
  at enqueueSetState(/usr/src/sentry/node_modules/react-dom/cjs/react-dom.production.min.js:110:32)
  at setState(/usr/src/sentry/node_modules/react/cjs/react.production.min.js:12:211)
  at handleRequestSuccess(./app/components/asyncComponent.jsx:128:10)
  at apply(./app/components/asyncComponent.jsx:113:16)
  at apply(./app/api.jsx:62:21)
  at fire(/usr/src/sentry/node_modules/jquery/dist/jquery.js:3099:1)
  at resolveWith(/usr/src/sentry/node_modules/jquery/dist/jquery.js:3211:1)
  at done(/usr/src/sentry/node_modules/jquery/dist/jquery.js:8264:1)
  at apply(/usr/src/sentry/node_modules/jquery/dist/jquery.js:8605:1)
  at XMLHttpRequest.r(/usr/src/sentry/node_modules/raven-js/src/raven.js:374:1)
```
![screenshot 2018-12-12 at 7 03 44 pm](https://user-images.githubusercontent.com/9818793/49872969-abe3df80-fe40-11e8-9aa5-a12cf69a05e4.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
