### ISSUE TITLE
Cannot configure sentry filestore to upload to private s3 buckets

### ISSUE THREAD

**Issue by ms-choudhary** [getsentry/sentry#11033]
## Important Details

How are you running Sentry?

* [ ] Other [briefly describe your environment]

Sentry on Kubernetes using [stable helm chart](https://github.com/helm/charts/tree/master/stable/sentry)

Helm Chart version: 0.5.0
App version: 9.0

Values.yaml:
```
config:
  configYml: |
    filestore.backend: s3
    filestore.options:
      bucket_name: sentry-filestore
      region_name: ap-south-1
      signature_version: 's3v4'
```

## Description

[What happened]
Sentry fails to upload files to s3 with error "An error occurred (AccessDenied) when calling the PutObject operation: Access Denied", even though the user has full access. 

## Steps to Reproduce

1. Add filestore backend config to configYml in values.yaml (pasted above)
2. Install sentry via helm on kubernetes:
```
helm install --name sentry stable/sentry -f values.yaml
```
3. Try to upload sourcemaps
```
sentry-cli releases files "xyz" upload-sourcemaps ./sourcemaps
```

Good items to include here include:

- Include a stacktrace or other logs when relevant
```
100.109.222.30 - - [12/Dec/2018:14:27:14 +0000] "GET /api/0/projects/sentry/go/releases/abcd/files/?cursor= HTTP/1.1" 200 557 "-" "sentry-cli/1.37.0"
14:27:15 [DEBUG] s3transfer.utils: Acquiring 0
14:27:15 [DEBUG] s3transfer.tasks: UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f9bb5aebb90>}) about to wait for the following futures []
14:27:15 [DEBUG] s3transfer.tasks: UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f9bb5aebb90>}) done waiting for dependent futures
14:27:15 [DEBUG] s3transfer.tasks: Executing task UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f9bb5aebb90>}) with kwargs {'osutil': <s3transfer.utils.OSUtils object at 0x7f9bb5ac3810>, 'client': <botocore.client.S3 object at 0x7f9bb5ead650>, 'config': <boto3.s3.transfer.TransferConfig object at 0x7f9bb5ac3850>, 'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f9bb5aebb90>, 'request_executor': <s3transfer.futures.BoundedExecutor object at 0x7f9bb5ac3410>}
14:27:15 [DEBUG] s3transfer.futures: Submitting task PutObjectTask(transfer_id=0, {'extra_args': {'ContentType': 'application/octet-stream', 'ACL': 'public-read'}, 'bucket': 'sentry-filestore', 'key': '17877/52035/976a880b8dfb449d8f3279641051d8d2'}) to executor <s3transfer.futures.BoundedExecutor object at 0x7f9bb5ac3410> for transfer request: 0.
14:27:15 [DEBUG] s3transfer.utils: Acquiring 0
14:27:15 [DEBUG] s3transfer.tasks: PutObjectTask(transfer_id=0, {'extra_args': {'ContentType': 'application/octet-stream', 'ACL': 'public-read'}, 'bucket': 'sentry-filestore', 'key': '17877/52035/976a880b8dfb449d8f3279641051d8d2'}) about to wait for the following futures []
14:27:15 [DEBUG] s3transfer.utils: Releasing acquire 0/None
14:27:15 [DEBUG] s3transfer.tasks: PutObjectTask(transfer_id=0, {'extra_args': {'ContentType': 'application/octet-stream', 'ACL': 'public-read'}, 'bucket': 'sentry-filestore', 'key': '17877/52035/976a880b8dfb449d8f3279641051d8d2'}) done waiting for dependent futures
14:27:15 [DEBUG] s3transfer.tasks: Executing task PutObjectTask(transfer_id=0, {'extra_args': {'ContentType': 'application/octet-stream', 'ACL': 'public-read'}, 'bucket': 'sentry-filestore', 'key': '17877/52035/976a880b8dfb449d8f3279641051d8d2'}) with kwargs {'extra_args': {'ContentType': 'application/octet-stream', 'ACL': 'public-read'}, 'client': <botocore.client.S3 object at 0x7f9bb5ead650>, 'bucket': 'sentry-filestore', 'key': '17877/52035/976a880b8dfb449d8f3279641051d8d2', 'fileobj': <s3transfer.utils.ReadFileChunk object at 0x7f9bb5af5090>}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python2.7/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
14:27:15 [DEBUG] s3transfer.tasks: Exception raised.
14:27:15 [DEBUG] s3transfer.utils: Releasing acquire 0/None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 87, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 170, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/project_release_files.py", line 177, in post
    file.putfile(fileobj)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 260, in putfile
    blob = FileBlob.from_file(blob_fileobj)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 119, in from_file
    storage.save(blob.path, fileobj)
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 49, in save
    name = self._save(name, content)
  File "/usr/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 507, in _save
    self._save_content(obj, content, parameters=parameters)
  File "/usr/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 522, in _save_content
    obj.upload_fileobj(content, ExtraArgs=put_parameters)
  File "/usr/local/lib/python2.7/site-packages/boto3/s3/inject.py", line 513, in object_upload_fileobj
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/usr/local/lib/python2.7/site-packages/boto3/s3/inject.py", line 431, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python2.7/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by ms-choudhary** [comment]
Figured out that by default sentry has ACL: `public-read`, which doesn't work for private buckets. 
Works if we add following configuration:

```
config:
  configYml: |
    filestore.backend: s3
    filestore.options:
      bucket_name: sentry-filestore
      region_name: ap-south-1
      signature_version: 's3v4'
      acl: private
```

**Comment by acdha** [comment]
In case anyone else hits this, it's no longer `acl` but `default_acl` — I opened https://github.com/getsentry/sentry-docs/pull/956 to update the docs
