### ISSUE TITLE
 [ERROR] root: Unable to fetch ProjectKey for internal project

### ISSUE THREAD

**Issue by wujunze** [getsentry/sentry#11095]
docker-compose  up  
see error
help me  Thanks
```shell
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
web_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
web_1        |     return self.dispatch(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
web_1        |     return view_func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 223, in dispatch
web_1        |     return self.handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
web_1        |     response = view_func(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
web_1        |     return func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 157, in handle
web_1        |     return super(AuthLoginView, self).handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 236, in handle
web_1        |     return super(BaseView, self).dispatch(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
web_1        |     return handler(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 175, in get
web_1        |     org = Organization.get_default()
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 161, in get_default
web_1        |     )[0]
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
web_1        |     return list(qs)[0]
web_1        | IndexError: list index out of range
web_1        | 08:12:48 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/error_500.py", line 22, in get_embed_config
web_1        |     )[0]
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
web_1        |     return list(qs)[0]
web_1        | IndexError: list index out of range
web_1        | 08:12:48 [ERROR] root: Unable to fetch ProjectKey for internal project
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/templatetags/sentry_react.py", line 67, in _get_public_dsn
web_1        |     )[0]
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
web_1        |     return list(qs)[0]
web_1        | IndexError: list index out of range
web_1        | 08:12:48 [ERROR] root: Unable to fetch ProjectKey for internal project
```

**Comment by sklochkov** [comment]
In my (limited) experience such error happens when the first database upgrade operation during installation failed, e. g. due to citext absence. The simple solution would be to prepare a new, clean database with all grants in place & citext extension added and run the database upgrade process again.

**Comment by wujunze** [comment]
Thanks  @sklochkov     
I use docker-compose     I try  upgrade web    but   error

**Comment by ZuSe** [comment]
I am running into the same error with sentry 8.22, psql 10 and redis 3.2.
Are you sure it isnt more a general problem with the migrations?

**Comment by x007007007** [comment]
I have same problem

**Comment by nlyf** [comment]
The same issue

**Comment by Andrej1A** [comment]
I had the same issue after failed installation steps. I deleted the sentry and Postgres docker image and created it again. This solved it for me.

Check your docker images, stop and deleted all previously created (sentry + postgres):
```
docker container ls -a
docker container stop <container_id>
docker container rm <container_id>
```

Save your used docker image name in an environment variable:
```
REPOSITORY=sentry-onpremise
```

Start redis:
```
docker run \
  --detach \
  --name sentry-redis \
  redis:3.2-alpine
```

Start postgres:
```
docker run \
  --detach \
  --name sentry-postgres \
  --env POSTGRES_PASSWORD=secret \
  --env POSTGRES_USER=sentry \
  postgres:9.5
```

Start exim4 for outbound mail:
```
docker run \
  --detach \
  --name sentry-smtp \
  tianon/exim4
```

Test your sentry image is working. This command should output the sentry help:
```
docker run \
  --rm ${REPOSITORY} \
  --help
```

Generate a secret key:
```
docker run \
  --rm ${REPOSITORY} \
  config generate-secret-key
```

Save the output (the secret key) from the last command in an environment variable:
```
SENTRY_SECRET_KEY='<output_from_last_command>'
```

IMPORTANT: 
Check again you have set your REPOSITORY and SENTRY_SECRET_KEY environment variable.
```
echo $REPOSITORY
echo $SENTRY_SECRET_KEY
```

Upgrade your sentry. This command should start with a fresh migration and ask you during the process for a mail and password you would like to create for your installation:
```
docker run \
  --rm -it \
  --link sentry-redis:redis \
  --link sentry-postgres:postgres \
  --link sentry-smtp:smtp \
  --env SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY} \
  ${REPOSITORY} \
upgrade
```

The important part is to link the container. The [sentry docker installation documentation](https://docs.sentry.io/server/installation/docker/) tells this, but they don't do it in their examples.

**Comment by wujunze** [comment]
reinstall
