### ISSUE TITLE
IntegrityError, foreign key issue when receiving messages

### ISSUE THREAD

**Issue by pferreir** [getsentry/sentry#1146]
I am occasionally getting this error in my sentry instance:

```python
2014-03-13 10:24:17,529 DEBG 'sentry-worker' stdout output:
[2014-03-13 09:24:17,523: ERROR/MainProcess] Task sentry.tasks.index.index_event[057e01e6-4bfc-42f6-9dab-ce5ab0bc71ce] raised exception: IntegrityError('insert or update on table "sentry_searchdocument" violates foreign key constraint "group_id_refs_id_875eadf9"\nDETAIL:  Key (group_id)=(83) is not present in table "sentry_groupedmessage".\n',)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/celery-3.0.24-py2.6.egg/celery/task/trace.py", line 233, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/celery-3.0.24-py2.6.egg/celery/task/trace.py", line 420, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/sentry-6.4.4-py2.6.egg/sentry/tasks/index.py", line 18, in index_event
    app.search.index(event.group, event)
  File "/usr/lib/python2.6/site-packages/sentry-6.4.4-py2.6.egg/sentry/search/django/backend.py", line 58, in index
    'date_changed': group.last_seen,
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/models/manager.py", line 146, in get_or_create
    return self.get_query_set().get_or_create(**kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/models/query.py", line 501, in get_or_create
    six.reraise(*exc_info)
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/models/query.py", line 491, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/backends/postgresql_psycopg2/base.py", line 56, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/lib/python2.6/site-packages/Django-1.5.5-py2.6.egg/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)
IntegrityError: insert or update on table "sentry_searchdocument" violates foreign key constraint "group_id_refs_id_875eadf9"
DETAIL:  Key (group_id)=(83) is not present in table "sentry_groupedmessage".
```

Any clue as to what may be causing this?

Thanks!

**Comment by dcramer** [comment]
Closing in favor of #1036
