### ISSUE TITLE
Add a DingTalk Integration 

### ISSUE THREAD

**Issue by wujunze** [getsentry/sentry#11711]
## Summary

DingTalk is a very popular productivity productivity software like Slack

## Motivation
I hope Sentry authorities can integrate DingTalk notifications into Sentry by default, which will help more developers to make better use of Sentry

## Thanks
![image](https://user-images.githubusercontent.com/12997869/51730566-e46b1000-20b2-11e9-8e8f-87bb1f98aac7.png)
![image](https://user-images.githubusercontent.com/12997869/51730573-ecc34b00-20b2-11e9-950b-1b0cb7ad16b7.png)

**Comment by wujunze** [comment]
pip link https://pypi.org/project/sentry-dingtalk-notification/

**Comment by markstory** [comment]
There are already a few dingtalk plugins for use in on-premise. Is your ask to have them available on sentry.io?

**Comment by shinynz** [comment]
@wujunze
 Failed to load plugin 'sentry_dingtalk':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 29, in register_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/sentry_dingtalk/plugin.py", line 8, in <module>
    import sentry_DingTalk
ImportError: No module named sentry_DingTalk

**Comment by buffge** [comment]
waiting for it

**Comment by sentaur-athena** [comment]
Keeping open to gather interest. Please thumbs up if you're also interested in this integration.
We don't have it any where in the roadmap.
