### ISSUE TITLE
Cannot import name process_resource_change

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry#11759]
## Important Details

I am running Sentry on-premise from the master branch (3e0e0bbd57167f5254e457cf4ceb8009fad5ee33) as per the "Python" on-premise installation instructions.

Tried to revert a few days back but it's only generating more / other errors.

## Description

Celery seems to be unable to process an event which causes an error which causes an event (to Sentry itself) which causes an error which causes an event... and so on.

## Steps to Reproduce

1. Start Sentry
2. Submit an event through the API or an client SDK
3. Watch Celery go absolutely nuts

```
Jan 29 10:03:29 observ supervisord: sentry-worker Traceback (most recent call last):
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
Jan 29 10:03:29 observ supervisord: sentry-worker     R = retval = fun(*args, **kwargs)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
Jan 29 10:03:29 observ supervisord: sentry-worker     return self.run(*args, **kwargs)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/src/sentry-dev/src/sentry/tasks/base.py", line 54, in _wrapped
Jan 29 10:03:29 observ supervisord: sentry-worker     result = func(*args, **kwargs)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/src/sentry-dev/src/sentry/tasks/store.py", line 397, in save_event
Jan 29 10:03:29 observ supervisord: sentry-worker     event = manager.save(project_id, assume_normalized=True)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/src/sentry-dev/src/sentry/event_manager.py", line 1013, in save
Jan 29 10:03:29 observ supervisord: sentry-worker     event=event, hashes=hashes, release=release, **kwargs
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/src/sentry-dev/src/sentry/event_manager.py", line 1321, in _save_aggregate
Jan 29 10:03:29 observ supervisord: sentry-worker     **kwargs
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
Jan 29 10:03:29 observ supervisord: sentry-worker     return self.get_queryset().create(**kwargs)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
Jan 29 10:03:29 observ supervisord: sentry-worker     obj.save(force_insert=True, using=self.db)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/src/sentry-dev/src/sentry/models/group.py", line 280, in save
Jan 29 10:03:29 observ supervisord: sentry-worker     super(Group, self).save(*args, **kwargs)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
Jan 29 10:03:29 observ supervisord: sentry-worker     force_update=force_update, update_fields=update_fields)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
Jan 29 10:03:29 observ supervisord: sentry-worker     update_fields=update_fields, raw=raw, using=using)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
Jan 29 10:03:29 observ supervisord: sentry-worker     response = receiver(signal=self, sender=sender, **named)
Jan 29 10:03:29 observ supervisord: sentry-worker   File "/var/www/sentry/src/sentry-dev/src/sentry/models/signals.py", line 12, in resource_changed
Jan 29 10:03:29 observ supervisord: sentry-worker ImportError: cannot import name process_resource_change
Jan 29 10:03:29 observ supervisord: sentry-worker 09:03:29 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[a6bc9d7f-cc81-430a-8cf3-5ab215d2efdb] raised unexpected: ImportError('cannot import name process_resource_change',) (data={u'hostname': 'celery@observ', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'event_id': u'be79fbaf3d2f4371991d58f985a4dd6a', 'cache_key': u'e:be79fbaf3d2f4371991d58f985a4dd6a:2', 'start_time': 1548752609.749988, 'project_id': 2, 'data': None}", u'id': 'a6bc9d7f-cc81-430a-8cf3-5ab215d2efdb'})
```

### What you expected to happen

The event to be processed.

### Possible Solution

I thought it might have something to do with the task name being not the same as the others (https://github.com/stayallive/sentry/commit/3ea776dd3a49c26b0b75c28115a67a41c147f47e). But really I have no clue yet.

**Comment by untitaker** [comment]
I had the same issue. You need to delete `src/sentry/models/signals.pyc`, or just clear all `*.pyc` files.

**Comment by stayallive** [comment]
@untitaker thanks for the lightning response! That certainly does seem to fix it ❤️
