### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by alga** [getsentry/sentry#1227]
I got this in the error.log when accessing the account notifications page:

```
Internal Server Error: /sentry/account/settings/notifications/
Traceback (most recent call last):
  File "/opt/sentry/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/../django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/web/decorators.py", line 164, in wrapped
    return func(request, *args, **kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/../django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/web/frontend/accounts.py", line 237, in notification_settings
    for project in sorted(project_list, key=lambda x: (x.team.name, x.name))
  File "/opt/sentry/lib/python2.7/site-packages/sentry/web/frontend/accounts.py", line 237, in <lambda>
    for project in sorted(project_list, key=lambda x: (x.team.name, x.name))
AttributeError: 'NoneType' object has no attribute 'name'
```

The only project with null team in the database is the Sentry (Internal) one.  We are running Sentry 6.4.4.

**Comment by mattrobenolt** [comment]
Unlikely this is a problem anymore, but please reopen if I'm wrong.
