### ISSUE TITLE
DatabaseError: missing FROM-clause entry for table "sentry_messagefiltervalue"

### ISSUE THREAD

**Issue by bjmc** [getsentry/sentry#1266]
Running Sentry 6.4.4 with a PostgreSQL database, when attempting to access `/<team>/<project>/?server_name=<server>&sort=accel_60`, Sentry throws a 500 Internal Server error. Traceback information from the logs is included below. Accessing `/<team>/<project>/?server_name=<server>` works fine, with no error.

    Internal Server Error: /<team>/<project>/
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 113, in get_response
        response = callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry/web/decorators.py", line 164, in wrapped
        return func(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry/web/decorators.py", line 117, in _wrapped
        return func(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry/web/frontend/groups.py", line 377, in group_list
        }, request)
      File "/usr/local/lib/python2.7/dist-packages/sentry/web/helpers.py", line 161, in render_to_response
        response = HttpResponse(render_to_string(template, context, request))
      File "/usr/local/lib/python2.7/dist-packages/sentry/web/helpers.py", line 157, in render_to_string
        return loader.render_to_string(template, context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 172, in render_to_string
        return t.render(Context(dictionary))
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
        return self._render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
        return self.nodelist.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
        bit = self.render_node(node, context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
        return node.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 124, in render
        return compiled_parent._render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
        return self.nodelist.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
        bit = self.render_node(node, context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
        return node.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 124, in render
        return compiled_parent._render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
        return self.nodelist.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
        bit = self.render_node(node, context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
        return node.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 63, in render
        result = block.nodelist.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
        bit = self.render_node(node, context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
        return node.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 63, in render
        result = block.nodelist.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
        bit = self.render_node(node, context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
        return node.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 63, in render
        result = block.nodelist.render(context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
        bit = self.render_node(node, context)
      File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
        return node.render(context)
      File "/usr/local/lib/python2.7/dist-packages/templatetag_sugar/node.py", line 19, in render
        return self.function(context, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry/templatetags/sentry_helpers.py", line 217, in paginator
        result = paginate_func(request, queryset_or_list, per_page, endless=True)
      File "/usr/local/lib/python2.7/dist-packages/paging/helpers.py", line 24, in paginate
        'paginator': paginator.get_context(page),
      File "/usr/local/lib/python2.7/dist-packages/paging/paginators.py", line 87, in get_context
        paginator = self.page(page)
      File "/usr/local/lib/python2.7/dist-packages/paging/paginators.py", line 73, in page
        _page = EndlessPage(list(self.object_list[bottom:top]), number, self)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1562, in __iter__
        query = iter(self.query)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 72, in __iter__
        self._execute_query()
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 86, in _execute_query
        self.cursor.execute(self.sql, self.params)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 58, in execute
        six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
        return self.cursor.execute(query, args)
    DatabaseError: missing FROM-clause entry for table "sentry_messagefiltervalue"
    LINE 18: ... 5  AND "sentry_groupedmessage"."status" = 0  AND "sentry_me...
                                                                ^

**Comment by dcramer** [comment]
Closing this as it references a seriously outdated version of Sentry and its likely this isn't a current problem
