### ISSUE TITLE
Azure Devops Integration: 400 Bad Request Invalid Request

### ISSUE THREAD

**Issue by mkjoerg** [getsentry/sentry#12675]
When I try to connect to azure devops platform in the interface:
![image](https://user-images.githubusercontent.com/12080409/55701732-9dfc3080-59d4-11e9-8521-eddd70f85daf.png)

I get the following error message.
![image](https://user-images.githubusercontent.com/12080409/55701750-ace2e300-59d4-11e9-8c62-d86435239bf3.png)

Is there something wrong from my side? Can I debug this further somehow?
Or is there something wrong with the parameters for the integration?

**Comment by markstory** [comment]
Are you using sentry.io or running sentry on-premise?

**Comment by mkjoerg** [comment]
Sorry forgot to mention. We are currently running sentry 9.1 on premise, which includes the new Azure DevOps Integration.

**Comment by mkjoerg** [comment]
For non german readers, the error message says:

The syntax of the request was not recognized.

**Comment by mkjoerg** [comment]
Thank you, I wasn't aware of those settings. I am pretty sure, that these are the missing parameters. I will close this for now and test later.

**Comment by mkjoerg** [comment]
I have now properly created the Azure DevOps Application and provided the client secret and id as config. When I configure the integration, Azure DevOps is able to log in and asks me if I want to give access. After I hit yes, the flow continues and I get to a sentry error page.
![image](https://user-images.githubusercontent.com/12080409/55871488-0260f080-5b8b-11e9-8704-ce8a290b5385.png)

```log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/pipeline_advancer.py", line 48, in handle
    return pipeline.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 217, in current_step
    pipeline=self,
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 97, in dispatch
    return nested_pipeline.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 217, in current_step
    pipeline=self,
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/identity/oauth2.py", line 237, in dispatch
    return pipeline.next_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 229, in next_step
    return self.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 217, in current_step
    pipeline=self,
  File "/usr/local/lib/python2.7/site-packages/sentry/identity/oauth2.py", line 341, in dispatch
    return pipeline.next_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 229, in next_step
    return self.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 207, in current_step
    return self.finish_pipeline()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 79, in finish_pipeline
    return self.parent_pipeline.next_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 229, in next_step
    return self.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 217, in current_step
    pipeline=self,
  File "/usr/local/lib/python2.7/site-packages/sentry/integrations/vsts/integration.py", line 454, in dispatch
    access_token = state['data']['access_token']
KeyError: 'access_token'
```
Is this a configuration error from my side or is this related to the plugin? Azure DevOps Application has all scopes, sentry requests and client id and secret are

**Comment by markstory** [comment]
That key missing indicates that Azure didn't finish the Oauth exchange correctly as it should reply with an access token.

**Comment by mkjoerg** [comment]
What could be the root cause of that? Can my settings in the Azure DevOps Application be the root cause or are there may be errors in the integration itself. Is there a way to get more output if I enable more versatile logging?

**Comment by markstory** [comment]
I'm not sure. We setup our Azure application long ago and it is working well. I don't think there is any additional logging levels that could be enabled. You do have the source code and could add more logging to figure out the problem though.

**Comment by mkjoerg** [comment]
Ok thank you. I will dig a little bit deeper, closing this, due to the fact, that it could be related to my own setup.

**Comment by ferreirix** [comment]
@mkjoerg I'm facing the same issue [here](https://github.com/getsentry/sentry/blob/501655b23ff3e12fde0704cc6e9eaa11f1e33f2d/src/sentry/integrations/vsts/integration.py#L460). Did you manage to find the solution? tks!

**Comment by mkjoerg** [comment]
@ferreirix 

First you need to configure an additional application in your azure devops with the appropriate settings.

You can do this under: https://app.vsaex.visualstudio.com/app/register

Auth Redirect URL: https://<your-sentry-domain>/extensions/vsts/setup/
![image](https://user-images.githubusercontent.com/12080409/70167842-df5df080-16c7-11ea-9808-1d802bc2b4e8.png)

![image](https://user-images.githubusercontent.com/12080409/70167854-e553d180-16c7-11ea-94c0-3fc2a6137e75.png)


When you are done you should see the following points:

![image](https://user-images.githubusercontent.com/12080409/70167898-fc92bf00-16c7-11ea-97cb-7e6eca943775.png)

After this you have to place two properties in your **config.yml** of sentry:

vsts.client-id: 'XXXXX'
vsts.client-secret: 'XXXXX'

The client-id = **App ID** from Devops
The client-secret = **Client Secret** from Devops (Long string)

After you have configured this it should work fine. The only downside is, that signing in with Azure Devops seems to be only possible with a premium version. But you can still link issues and stuff.

Hope this helps, took me a while to fix.

**Comment by ferreirix** [comment]
I registed the app on vsts and fiddled with generated url because i can't access the **config.yml** or set env vars, but that may be the actual reason. will find a way out. thanks a lot!

**Comment by mkjoerg** [comment]
@ferreirix as far as I know, there is a hard requirement for these settings.
