### ISSUE TITLE
KeyError: 'id' in GitHub social auth flow

### ISSUE THREAD

**Issue by sds** [getsentry/sentry#1273]
I've hit this both on the latest stable release (6.4.4 at time of writing) and master (a8b535c7b9d58ad57baab4eaeb069583997e6422).

I've added the following configuration settings to my `sentry.conf.py` (using the default `SOCIAL_AUTH_PIPELINE`):

```
GITHUB_APP_ID = '...'
GITHUB_API_SECRET = '...'
GITHUB_ORGANIZATION = '...'
```

Trying to login with GitHub, I get the following error: 

```
Internal Server Error: /account/settings/social/complete/github/
Traceback (most recent call last):
  File "/var/lib/sentry/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/social_auth/decorators.py", line 29, in wrapper
    return func(request, request.social_auth_backend, *args, **kwargs)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/social_auth/views.py", line 41, in complete
    return complete_process(request, backend, *args, **kwargs)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/social_auth/views.py", line 107, in complete_process
    user = auth_complete(request, backend, *args, **kwargs)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/social_auth/views.py", line 190, in auth_complete
    return backend.auth_complete(user=user, request=request, *args, **kwargs)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 864, in auth_complete
    *args, **kwargs)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 932, in do_auth
    return authenticate(*args, **kwargs)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 60, in authenticate
    user = backend.authenticate(**credentials)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 111, in authenticate
    kwargs['uid'] = self.get_user_id(kwargs['details'], response)
  File "/var/lib/sentry/env/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 219, in get_user_id
    return response[self.ID_KEY]
KeyError: 'id'
```

I imagine there's something incorrect with the default pipeline setup, but I'm having trouble finding relevant documentation. Are there additional settings I need to specify?

**Comment by aadis** [comment]
Same here

**Comment by dcramer** [comment]
Social auth is being removed so I'm closing out this ticket.
