### ISSUE TITLE
sentry upgrade wrong.

### ISSUE THREAD

**Issue by tinfot** [getsentry/sentry#12779]
SENTRY_CONF=/etc/sentry sentry upgrade
Traceback (most recent call last):
  File "/usr/bin/sentry", line 11, in <module>
    load_entry_point('sentry', 'console_scripts', 'sentry')()
  File "/apps/sentry/src/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/apps/sentry/src/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/apps/sentry/src/sentry/runner/__init__.py", line 125, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/apps/sentry/src/sentry/runner/settings.py", line 156, in configure
    skip_service_validation=skip_service_validation
  File "/apps/sentry/src/sentry/runner/initializer.py", line 267, in initialize_app
    bootstrap_options(settings, config['options'])
  File "/apps/sentry/src/sentry/runner/initializer.py", line 140, in bootstrap_options
    from sentry.options import load_defaults
  File "/apps/sentry/src/sentry/options/__init__.py", line 10, in <module>
    from .store import OptionsStore
  File "/apps/sentry/src/sentry/options/store.py", line 20, in <module>
    from sentry.db.models.query import create_or_update
  File "/apps/sentry/src/sentry/db/models/__init__.py", line 11, in <module>
    from .base import *  # NOQA
  File "/apps/sentry/src/sentry/db/models/base.py", line 20, in <module>
    from .fields.bounded import BoundedBigAutoField
  File "/apps/sentry/src/sentry/db/models/fields/__init__.py", line 19, in <module>
    from .uuid import *  # NOQA
  File "/apps/sentry/src/sentry/db/models/fields/uuid.py", line 9, in <module>
    from psycopg2.extensions import register_adapter
  File "/usr/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /usr/lib/python2.7/site-packages/psycopg2/_psycopg.so: invalid ELF header

**Comment by markstory** [comment]
>  ImportError: /usr/lib/python2.7/site-packages/psycopg2/_psycopg.so: invalid ELF header

You might need to re-install psycopg2.

**Comment by tinfot** [comment]
SENTRY_CONF=/etc/sentry sentry upgrade
Traceback (most recent call last):
  File "/usr/bin/sentry", line 11, in <module>
    load_entry_point('sentry', 'console_scripts', 'sentry')()
  File "/apps/sentry/src/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/apps/sentry/src/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/apps/sentry/src/sentry/runner/__init__.py", line 125, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/apps/sentry/src/sentry/runner/settings.py", line 156, in configure
    skip_service_validation=skip_service_validation
  File "/apps/sentry/src/sentry/runner/initializer.py", line 274, in initialize_app
    apply_legacy_settings(settings)
  File "/apps/sentry/src/sentry/runner/initializer.py", line 477, in apply_legacy_settings
    url_prefix = options.get('system.url-prefix', silent=True)
  File "/apps/sentry/src/sentry/options/manager.py", line 152, in get
    result = self.store.get(opt, silent=silent)
  File "/apps/sentry/src/sentry/options/store.py", line 73, in get
    result = self.get_store(key, silent=silent)
  File "/apps/sentry/src/sentry/options/store.py", line 167, in get_store
    except (self.model.DoesNotExist, ProgrammingError, OperationalError):
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.func.__name__] = self.func(instance)
  File "/apps/sentry/src/sentry/options/store.py", line 59, in model
    from sentry.models.option import Option
  File "/apps/sentry/src/sentry/models/__init__.py", line 14, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/apps/sentry/src/sentry/utils/imports.py", line 62, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/apps/sentry/src/sentry/models/authenticator.py", line 17, in <module>
    from u2flib_server import u2f
  File "/usr/lib/python2.7/site-packages/u2flib_server/u2f.py", line 28, in <module>
    from u2flib_server import u2f_v2
  File "/usr/lib/python2.7/site-packages/u2flib_server/u2f_v2.py", line 28, in <module>
    from u2flib_server.jsapi import (RegisterRequest, RegisterResponse,
  File "/usr/lib/python2.7/site-packages/u2flib_server/jsapi.py", line 28, in <module>
    from u2flib_server.utils import websafe_decode, sha_256
  File "/usr/lib/python2.7/site-packages/u2flib_server/utils.py", line 30, in <module>
    from cryptography import x509
  File "/usr/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
ImportError: cannot import name certificate_transparency

**Comment by markstory** [comment]
Looks like you might need to reinstall dependencies.

**Comment by tinfot** [comment]
> Looks like you might need to reinstall dependencies.

OK，I will reinstall, Thanks : )

**Comment by bushiquanquan** [comment]
我执行SENTRY_CONF=/etc/sentry yarn dev也报类似的错，请问楼主重新安装哪些包？
success Folder in sync.
06:08:19 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
Traceback (most recent call last):
  File "/www/sentry/bin/sentry", line 11, in <module>
    load_entry_point('sentry', 'console_scripts', 'sentry')()
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/runner/decorators.py", line 73, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/runner/__init__.py", line 125, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/runner/settings.py", line 156, in configure
    skip_service_validation=skip_service_validation
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/runner/initializer.py", line 319, in initialize_app
    register_plugins(settings)
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/runner/initializer.py", line 23, in register_plugins
    from sentry.plugins import plugins
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/plugins/__init__.py", line 20, in <module>
    from sentry.plugins.base import *  # NOQA
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/plugins/base/__init__.py", line 10, in <module>
    from .bindings import BindingManager
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/plugins/base/bindings.py", line 5, in <module>
    from sentry.plugins import providers
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/plugins/providers/__init__.py", line 5, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/utils/imports.py", line 62, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/plugins/providers/dummy/__init__.py", line 5, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/utils/imports.py", line 62, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/plugins/providers/dummy/repository.py", line 3, in <module>
    from sentry.plugins.providers.repository import RepositoryProvider
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/plugins/providers/repository.py", line 9, in <module>
    from sentry.api.serializers import serialize
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/api/__init__.py", line 3, in <module>
    from .client import ApiClient
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/api/client.py", line 8, in <module>
    from sentry.auth.superuser import Superuser
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/auth/__init__.py", line 3, in <module>
    from .provider import *  # NOQA
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/auth/provider.py", line 6, in <module>
    from .view import ConfigureView
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/auth/view.py", line 6, in <module>
    from sentry.web.frontend.base import BaseView
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/web/frontend/base.py", line 15, in <module>
    from sentry.api.serializers import serialize
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/api/serializers/__init__.py", line 4, in <module>
    from .models import *  # NOQA
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/api/serializers/models/__init__.py", line 5, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/utils/imports.py", line 62, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/api/serializers/models/project.py", line 23, in <module>
    from sentry.grouping.strategies.configurations import DEFAULT_CONFIG as DEFAULT_GROUPING_CONFIG
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/grouping/strategies/__init__.py", line 15, in <module>
    _import_all()
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/grouping/strategies/__init__.py", line 9, in _import_all
    __import__('%s.%s' % (__name__, module))
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/grouping/strategies/combined.py", line 53, in <module>
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/grouping/strategies/combined.py", line 15, in dispatch_strategy
  File "/Users/yuanhuihui01/Documents/code/sentry/src/sentry/grouping/strategies/base.py", line 36, in lookup_strategy
    raise LookupError('Unknown strategy %r' % strategy_id)
LookupError: Unknown strategy 'stacktrace:v1'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
