### ISSUE TITLE
Sentry 9.1 upload-dif no such file or directory in worker

### ISSUE THREAD

**Issue by gboor** [getsentry/sentry#12939]
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version 9.1], via Kubernetes, with the stable helm chart

## Description

I tried to use sentry-cli to upload-dif;

`sentry-cli upload-dif -t breakpad DataPusherService.sym`

it hangs forever and the worker produces the following error (in both its own log and in sentry's internal project);

```
[Errno 2] No such file or directory: u'/var/lib/sentry/files/90/976d/8b07fd41aba16421c274a5c6be'
```

The directory mentioned indeed does not exist, but is apparently also not created.

## Steps to Reproduce

1. Install Sentry 9.1 with the stable helm chart
2. Create some project
3. Set up sentry-cli
4. Try a sentry-cli upload-dif on a .sym file

Good items to include here include:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 72, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 67, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 72, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 67, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/assemble.py", line 27, in assemble_dif
    file_type='project.dif')
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/assemble.py", line 123, in assemble_file
    temp_file = file.assemble_from_file_blob_ids(file_blob_ids, checksum)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 463, in assemble_from_file_blob_ids
    for chunk in blob.getfile().chunks():
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 329, in getfile
    return storage.open(self.path)
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 33, in open
    return self._open(name, mode)
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 159, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/var/lib/sentry/files/90/976d/8b07fd41aba16421c274a5c6be'
```

### What you expected to happen

File should be uploaded

**Comment by zsc8917zsc** [comment]
Make your local database and sentry volumes Docker volumes have to be created manually
`docker volume create --name=sentry-data && docker volume create --name=sentry-postgres`

`  volumes:
    - sentry-data:/var/lib/sentry/files`

**Comment by gboor** [comment]
This is a deployment on Kubernetes using https://github.com/helm/charts/tree/master/stable/sentry

It might be a persistent volume issue, in which case the problem is with the chart maintainer. I have opened an issue there as well.

If this issue is indeed down to volumes and not a bug in Sentry itself, this ticket can be closed. I can't currently fully ascertain what causes this.

**Comment by guyromb** [comment]
any suggestion how to solve this? @gboor 
I am facing the same issue

**Comment by gboor** [comment]
It seems that the problem is with the storage back-end, not with Sentry itself, so this might be the wrong place for this ticket.

Potential fix is already here;

https://github.com/helm/charts/pull/11153

but not yet merged.

I will close this ticket, as it's clearly not a Sentry problem.
