### ISSUE TITLE
IndexError on creation of new Project

### ISSUE THREAD

**Issue by bountyx** [getsentry/sentry#13027]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [v10]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Creating a new project yields a IndexError as follows: 

```
21:09:55 [ERROR] root: signal.failure (receiver=u'<function record_user_context_received at 0x11412b578>')
21:09:55 worker  | Traceback (most recent call last):
21:09:55 worker  |   File "/Users/dev/Projects/test-sentry/sentry/src/sentry/signals.py", line 45, in send_robust
21:09:55 worker  |     response = receiver(signal=self, sender=sender, **named)
21:09:55 worker  |   File "/Users/dev/Projects/test-sentry/sentry/src/sentry/receivers/onboarding.py", line 261, in record_sourcemaps_received
21:09:55 worker  |     user = Organization.objects.get(id=project.organization_id).get_default_owner()
21:09:55 worker  |   File "/Users/dev/Projects/test-sentry/sentry/src/sentry/models/organization.py", line 217, in get_default_owner
21:09:55 worker  |     self._default_owner = self.get_owners()[0]
21:09:55 worker  |   File "/Users/dev/.virtualenvs/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
21:09:55 worker  |     return list(qs)[0]
21:09:55 worker  | IndexError: list index out of range
21:09:55 worker  | 21:09:55 [ERROR] root: signal.failure (receiver=u'<function record_sourcemaps_received at 0x11412b5f0>')
21:09:56 worker  | %3|1556744996.546|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[fe80::1%lo0]:9092 failed: Connection refused
21:09:56 worker  | %3|1556744996.546|ERROR|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[fe80::1%lo0]:9092 failed: Connection refused
```

## Steps to Reproduce

1. Launch server via sentry devserver --workers
2. Follow on-boarding steps
3. Notice after attempted creation of project during on boarding, an error is thrown, see stack trace above.

Version (commit) 4f6ee73456d6eff4793a03ffa1a38d2c03214de5

### What you expected to happen

No error during project creation

### Possible Solution

I suspect it has something to do with trimmed function names commit 665778c079c8b718d788741b6305434bc2d78fd3

**Comment by bountyx** [comment]
Seems fixed now
