### ISSUE TITLE
Error after upgrade to 9.1.1

### ISSUE THREAD

**Issue by nijel** [getsentry/sentry#13035]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other [pip installed sentry 9.1.1]

## Description

After upgrade to 9.1.1 several requests start to fail with:

```
Traceback (most recent call last):
  File "/home/admin/sentry/.venv/local/lib/python2.7/site-packages/sentry/api/base.py", line 90, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/home/admin/sentry/.venv/local/lib/python2.7/site-packages/sentry/api/base.py", line 190, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/admin/sentry/.venv/local/lib/python2.7/site-packages/sentry/api/endpoints/project_group_index.py", line 191, in get
    context = serialize(results, request.user, serializer())
  File "/home/admin/sentry/.venv/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 38, in serialize
    return [serializer(o, attrs=attrs.get(o, {}), user=user, **kwargs) for o in objects]
  File "/home/admin/sentry/.venv/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 53, in __call__
    return self.serialize(obj, attrs, user, **kwargs)
  File "/home/admin/sentry/.venv/local/lib/python2.7/site-packages/sentry/api/serializers/models/group.py", line 512, in serialize
    result = super(StreamGroupSerializer, self).serialize(obj, attrs, user)
  File "/home/admin/sentry/.venv/local/lib/python2.7/site-packages/sentry/api/serializers/models/group.py", line 364, in serialize
    'title': obj.title,
  File "/home/admin/sentry/.venv/local/lib/python2.7/site-packages/sentry/models/group.py", line 487, in title
    return et.get_title(self.get_event_metadata())
  File "/home/admin/sentry/.venv/local/lib/python2.7/site-packages/sentry/models/group.py", line 482, in get_event_metadata
    return self.data['metadata']
KeyError: 'metadata'
```

## Steps to Reproduce

1. Have events from old version which did not write metadata
2. Upgrade to 9.1.1
3. Browse the project

### Possible Solution

The problem is caused by https://github.com/getsentry/sentry/pull/12112 which removed compatibility with those data.

**Comment by marekrmac** [comment]
Is there any way to solve this problem? We updated sentry from 7.x to 9.1.1 and browsing issues is impossible because of this error.

**Comment by BYK** [comment]
@marekrmac @nijel  - this is because the upgrade is from a very old version. I'll look into ways for at least not throwing an exception but that would still yield some funky event information.

sentry.io doesn't keep events past 90 days and this is actually what we suggest people to do too. If you are not concerned about past data, you can try running `sentry cleanup --days 0` to clean all the old events (or put any other number than `0` but you may still run into this issue in that case). See https://docs.sentry.io/server/cli/cleanup/ for more options around that.

Would the clean-up path work for you both?

**Comment by nijel** [comment]
Our sentry installation was really in bad shape prior to upgrade, so the cleanup didn't work well (mostly due to lack of space). After fixing that the removal of *all* old issues did make it work, but still it's unpleasant situation when all past issues are gone.

**Comment by marekrmac** [comment]
Clean-up path worked for me. Thank you for your help.

**Comment by BYK** [comment]
@nijel I totally understand the frustration around losing old issues. We'll be looking into smoother upgrade experiences (with some limitations around time and order) for the future.

Since both of you were able to resolve the issue, I'm closing the task and will be adding the `sentry cleanup` tip either to docs or upgrade process itself.
