### ISSUE TITLE
sentry upgrade error

### ISSUE THREAD

**Issue by xiatian** [getsentry/sentry#13196]
centos7.2 python2.7.5
`pip install -U sentry`

After install, run `SENTRY_CONF=/etc/sentry sentry upgrade`

Error:
Traceback (most recent call last):
  File "/data/sentry/bin/sentry", line 10, in <module>
    sys.exit(main())
  File "/data/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/data/sentry/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/data/sentry/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/data/sentry/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/sentry/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/data/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/sentry/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/data/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 125, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/data/sentry/lib/python2.7/site-packages/sentry/runner/settings.py", line 156, in configure
    skip_service_validation=skip_service_validation
  File "/data/sentry/lib/python2.7/site-packages/sentry/runner/initializer.py", line 319, in initialize_app
    register_plugins(settings)
  File "/data/sentry/lib/python2.7/site-packages/sentry/runner/initializer.py", line 23, in register_plugins
    from sentry.plugins import plugins
  File "/data/sentry/lib/python2.7/site-packages/sentry/plugins/__init__.py", line 21, in <module>
    from sentry.plugins.bases import *  # NOQA
  File "/data/sentry/lib/python2.7/site-packages/sentry/plugins/bases/__init__.py", line 4, in <module>
    from .issue2 import IssueTrackingPlugin2  # NOQA
  File "/data/sentry/lib/python2.7/site-packages/sentry/plugins/bases/issue2.py", line 19, in <module>
    from sentry.plugins.endpoints import PluginGroupEndpoint
  File "/data/sentry/lib/python2.7/site-packages/sentry/plugins/endpoints.py", line 7, in <module>
    from sentry.api.bases.group import GroupEndpoint
  File "/data/sentry/lib/python2.7/site-packages/sentry/api/bases/__init__.py", line 6, in <module>
    from .organization_events import *  # NOQA
  File "/data/sentry/lib/python2.7/site-packages/sentry/api/bases/organization_events.py", line 4, in <module>
    from sentry.api.event_search import get_snuba_query_args, InvalidSearchQuery
  File "/data/sentry/lib/python2.7/site-packages/sentry/api/event_search.py", line 127, in <module>
    """)
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/grammar.py", line 69, in __init__
    exprs, first = self._expressions_from_rules(rules, decorated_custom_rules)
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/grammar.py", line 106, in _expressions_from_rules
    return RuleVisitor(custom_rules).visit(tree)
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/nodes.py", line 227, in visit
    reraise(VisitationError, VisitationError(exc, exc_class, node), tb)
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/nodes.py", line 217, in visit
    return method(node, [self.visit(n) for n in node])
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/grammar.py", line 371, in visit_regex
    verbose='X' in flags)
  File "/data/sentry/lib/python2.7/site-packages/parsimonious/expressions.py", line 274, in __init__
    (verbose and re.X))
  File "/data/sentry/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/data/sentry/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
parsimonious.exceptions.VisitationError: error: nothing to repeat

Parse tree:
<Node called "regex" matching "~r"\"((?:[^\"]|(?<=\\)[\"])*)?\""s
">  <-- *** We were here. ***
    <Node matching "~">
    <Node called "spaceless_literal" matching "r"\"((?:[^\"]|(?<=\\)[\"])*)?\""">
        <RegexNode matching "r"\"((?:[^\"]|(?<=\\)[\"])*)?\""">
    <RegexNode matching "s">
    <Node called "_" matching "
    ">
        <Node called "meaninglessness" matching "
        ">
            <RegexNode matching "
            ">

**Comment by markstory** [comment]
> centos7.2 python2.7.5

We don't support centos at all.
