### ISSUE TITLE
Opsgenie integration test returns internal error

### ISSUE THREAD

**Issue by sgsharma** [getsentry/sentry#13202]
## Important Details

How are you running Sentry?

* [X ] On-Premise docker [Version 9.1]

## Description

Opsgenie integration test results in:

```
Test Results:
"There was an internal error with the Plugin"
```

## Steps to Reproduce

1. Add Opsgenie plugin to project with API Key and API URL
2. Click on test plugin

Good items to include here include:

Docker logs for the web container show:
```
10.222.55.77 - - [14/May/2019:17:07:12 +0000] "PUT /api/0/projects/sentry/<project>/plugins/opsgenie/ HTTP/1.1" 200 1889 "http://<servername>.ghdna.io:9000/settings/sentry/projects/<project>/alerts/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
17:07:13 [INFO] sentry.eventstream.base: post_process.skip.raw_event (event_id=2944027L)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/project_plugin_details.py", line 56, in post
    test_results = plugin.test_configuration(project)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 183, in test_configuration
    return self.notify(notification)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 76, in notify
    r.label for r in notification.rules])
TypeError: notify_users() got an unexpected keyword argument 'triggering_rules'
17:07:13 [ERROR] root: Plugin(opsgenie) raised an error during test
10.222.55.77 - - [14/May/2019:17:07:13 +0000] "POST /api/0/projects/sentry/<project>/plugins/opsgenie/ HTTP/1.1" 200 481 "http://<servername>.ghdna.io:9000/settings/sentry/projects/<project>/alerts/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
```

The configuration is entirely standard running sentry 9.1

### What you expected to happen

An Opsgenie alert should be triggered

**Comment by markstory** [comment]
Fixed in getsentry/sentry-opsgenie#14
