### ISSUE TITLE
Unable to create GitLab integration

### ISSUE THREAD

**Issue by shresthsumanifesca** [getsentry/sentry#13245]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Sentry 9.1.1]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When I try to link my project, everything works until the last step where I get:

## Steps to Reproduce

![1](https://user-images.githubusercontent.com/50139944/57857925-657c1d80-77f0-11e9-84ff-69e483329562.PNG)
![2](https://user-images.githubusercontent.com/50139944/57857926-657c1d80-77f0-11e9-91d3-62cf38fee581.PNG)

**Comment by markstory** [comment]
How could someone reproduce the problem you're having? It looks like you're running sentry on-premise with on-premise gitlab. Have you tried looking in the logs for both applications?

**Comment by thomxc** [comment]
Currently running into these problems as well. I looks like a problem with (unsecure) redirect_uri's. The screenshots of OP show a base url with IP:port format. We are using an unsecure base URL as well. Is that something you could try to reproduce @markstory ? 

I will try to look into the code when I get the chance to actually back this with some source.

**Comment by markstory** [comment]
I don't really have the time to dedicate to try and reproduce these kinds of problems. If you could get me a stacktrace from the 500 I can take a look at that.

**Comment by shresthsumanifesca** [comment]
> I don't really have the time to dedicate to try and reproduce these kinds of problems. If you could get me a stacktrace from the 500 I can take a look at that.

> 11:27:26 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://116.202.23.112:8002/organizations/sentry/integrations/gitlab/setup/' ip_address=u'80.88.23.155' method=u'GET')
80.88.23.155 - - [23/May/2019:11:27:26 +0000] "GET /organizations/sentry/integrations/gitlab/setup/? HTTP/1.1" 200 8009 "http://116.202.23.112:8002/settings/sentry/integrations/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
11:27:28 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://116.202.23.112:8002/extensions/gitlab/setup/?completed_installation_guide' ip_address=u'80.88.23.155' method=u'GET')
80.88.23.155 - - [23/May/2019:11:27:28 +0000] "GET /extensions/gitlab/setup/?completed_installation_guide HTTP/1.1" 200 10972 "http://116.202.23.112:8002/organizations/sentry/integrations/gitlab/setup/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
11:27:34 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://116.202.23.112:8002/extensions/gitlab/setup/?completed_installation_guide' ip_address=u'80.88.23.155' method=u'POST')
11:27:34 [INFO] sentry.integration.gitlab: gitlab.setup.installation-config-view.success (base_url=u'https://git.ifesca.cloud' verify_ssl=True client_id=u'4f5f5578a53e03ce0c6eceb1cf27dfa335ad3ffd4fe8605b5a19d3607cdb88ff')
80.88.23.155 - - [23/May/2019:11:27:34 +0000] "POST /extensions/gitlab/setup/?completed_installation_guide HTTP/1.1" 302 1152 "http://116.202.23.112:8002/extensions/gitlab/setup/?completed_installation_guide" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
11:27:36 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://116.202.23.112:8002/extensions/gitlab/setup/?code=1a731eeac52a6428a249c1f2e23d5cf9d26540732e676d43f39b4a362fe8b42f&state=e5fa31873ce64d16831837bcbca06ce3' ip_address=u'80.88.23.155' method=u'GET')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/pipeline_advancer.py", line 48, in handle
    return pipeline.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 217, in current_step
    pipeline=self,
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 97, in dispatch
    return nested_pipeline.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 217, in current_step
    pipeline=self,
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/identity/oauth2.py", line 237, in dispatch
    return pipeline.next_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 229, in next_step
    return self.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 217, in current_step
    pipeline=self,
  File "/usr/local/lib/python2.7/site-packages/sentry/identity/oauth2.py", line 325, in dispatch
    data = self.exchange_token(request, pipeline, code)
  File "/usr/local/lib/python2.7/site-packages/sentry/identity/oauth2.py", line 283, in exchange_token
    req = safe_urlopen(self.access_token_url, data=data, verify_ssl=verify_ssl)
  File "/usr/local/lib/python2.7/site-packages/sentry/http.py", line 124, in safe_urlopen
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/sentry/net/http.py", line 154, in request
    response = _Session.request(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: SafeHTTPSConnectionPool(host='git.ifesca.cloud', port=443): Max retries exceeded with url: /oauth/token (Caused by NewConnectionError('<sentry.net.http.SafeHTTPSConnection object at 0x7f8d3681e450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
11:27:56 [ERROR] django.request: Internal Server Error: /extensions/gitlab/setup/ (status_code=500 request=<WSGIRequest: GET u'/extensions/gitlab/setup/?code=1a731eeac52a6428a249c1f2e23d5cf9d26540732e676d43f39b4a362fe8b42f&state=e5fa31873ce64d16831837bcbca06ce3'>)
80.88.23.155 - - [23/May/2019:11:27:36 +0000] "GET /extensions/gitlab/setup/?code=1a731eeac52a6428a249c1f2e23d5cf9d26540732e676d43f39b4a362fe8b42f&state=e5fa31873ce64d16831837bcbca06ce3 HTTP/1.1" 500 7298 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"

**Comment by markstory** [comment]
Sentry can't make an HTTPs connection to GitLab. You'll need to get that sorted or disable SSL verification.

**Comment by BYK** [comment]
Closing due to inactivity.
