### ISSUE TITLE
sentry reported an error: You do not have permission to perform this action. (http status: 403)

### ISSUE THREAD

**Issue by ldco2016** [getsentry/sentry#13287]
## Important Details

How are you running Sentry?

I am running a script from `package.json`, `"build": "nps build",`.

* [ ] On-Premise docker [Version xyz]
* [x ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I ran `npm run build` and I got the following error:

```
8 { Error: Command failed: ENGAL_ENDPOINT=dv APPCENTER_KEY=f743d50f-82fa-4b23-b602-2a318b875480 ENGAL_VERSION=3.6.2-1819 APPCENTER_PLATFORM=android npm run setup && cd android && ./gradlew assembleDevRelease -PversionName=3.6.2-1819 -PversionCode=1819 && cd ..
    15:32:28 error: API request failed
    15:32:28   caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
    15:32:28 
    15:32:28 FAILURE: Build failed with an exception.
    15:32:28 
    15:32:28 * Where:
    15:32:28 Script '/Users/ncis/Jenkins/Jenkins-Workspaces/ENGAL/ENGAL/node_modules/react-native-sentry/sentry.gradle' line: 154
    15:32:28 
    15:32:28 * What went wrong:
    15:32:28 Execution failed for task ':app:bundleDevReleaseJsAndAssetsdev-releaseSentryUpload'.
    15:32:28 > Process 'command 'node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1
    15:32:28 
    15:32:28 * Try:
    15:32:28 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    15:32:28 
    15:32:28 * Get more help at https://help.gradle.org
    15:32:28 
    15:32:28 BUILD FAILED in 4m 49s
    15:32:28 
    15:32:28     at ChildProcess.exithandler (child_process.js:206:12)
    15:32:28     at emitTwo (events.js:106:13)
    15:32:28     at ChildProcess.emit (events.js:191:7)
    15:32:28     at maybeClose (internal/child_process.js:877:16)
    15:32:28     at Socket.<anonymous> (internal/child_process.js:334:11)
    15:32:28     at emitOne (events.js:96:13)
    15:32:28     at Socket.emit (events.js:188:7)
    15:32:28     at Pipe._handle.close [as _onclose] (net.js:498:12)
    15:32:28   killed: false,
    15:32:28   code: 1,
    15:32:28   signal: null,
    15:32:28   cmd: 'ENGAL_ENDPOINT=dv APPCENTER_KEY=f743d50f-82fa-4b23-b602-2a318b875480 ENGAL_VERSION=3.6.2-1819 APPCENTER_PLATFORM=android npm run setup && cd android && ./gradlew assembleDevRelease -PversionName=3.6.2-1819 -PversionCode=1819 && cd ..' }
    15:32:28 ============================= Copying APK to Dist =============================
    15:32:35 nps is executing `ios.build` : node node_modules/rimraf/bin.js dist/*.ipa && babel-node scripts/ios/build.js
    15:32:58 ############################# DEV Build IOS Start #############################
    15:32:58 ENGAL_ENDPOINT=dv APPCENTER_KEY=e53bdbfb-dbdd-4ab9-8b4c-9d391e602cfa ENGAL_VERSION=3.6.2-1819 APPCENTER_PLATFORM=ios npm run setup && xcodebuild -workspace ios/ENGAL.xcworkspace -configuration Release -scheme DEV -derivedDataPath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGAL/ENGAL/ios/build -archivePath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGAL/ENGAL/ios/build/Archive/DEV.xcarchive archive -UseModernBuildSystem=NO && xcodebuild -archivePath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGAL/ENGAL/ios/build/Archive/DEV.xcarchive -exportPath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/dist -exportOptionsPlist /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/dev.plist -exportArchive
    15:40:19 ** ARCHIVE FAILED **
    15:40:19 
    15:40:19 
    15:40:19 The following build commands failed:
    15:40:19 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images build/Build/Intermediates.noindex/ArchiveIntermediates/DEV/IntermediateBuildFilesPath/ENGAL.build/Release-iphoneos/DEV.build/Script-6BE83F58202A54D500662052.sh
    15:40:19 (1 failure)
    15:40:20 child_process.js:526
    15:40:20     throw err;
    15:40:20     ^
    15:40:20 
    15:40:20 Error: Command failed: ENGAL_ENDPOINT=dv APPCENTER_KEY=e53bdbfb-dbdd-4ab9-8b4c-9d391e602cfa ENGAGE_VERSION=3.6.2-1819 APPCENTER_PLATFORM=ios npm run setup && xcodebuild -workspace ios/ENGAL.xcworkspace -configuration Release -scheme DEV -derivedDataPath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/ios/build -archivePath /Users/ncis/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/ios/build/Archive/DEV.xcarchive archive -UseModernBuildSystem=NO && xcodebuild -archivePath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/ios/build/Archive/DEV.xcarchive -exportPath /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/dist -exportOptionsPlist /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/dev.plist -exportArchive
    15:40:20 ** ARCHIVE FAILED **
    15:40:20 
    15:40:20 
    15:40:20 The following build commands failed:
    15:40:20 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images build/Build/Intermediates.noindex/ArchiveIntermediates/DEV/IntermediateBuildFilesPath/ENGAL.build/Release-iphoneos/DEV.build/Script-6BE83F58202A54D500662052.sh
    15:40:20 (1 failure)
    15:40:20 
    15:40:20     at checkExecSyncError (child_process.js:483:13)
    15:40:20     at execSync (child_process.js:523:13)
    15:40:20     at /Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/build.js:155:5
    15:40:20     at Array.forEach (native)
    15:40:20     at run (/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/build.js:117:16)
    15:40:20     at Object.<anonymous> (/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/scripts/ios/build.js:166:1)
    15:40:20     at Module._compile (module.js:570:32)
    15:40:20     at loader (/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/node_modules/babel-register/lib/node.js:144:5)
    15:40:20     at Object.require.extensions.(anonymous function) [as .js] (/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/node_modules/babel-register/lib/node.js:154:7)
    15:40:20     at Module.load (module.js:487:32)
    15:40:20 The script called "ios.build" which runs "node node_modules/rimraf/bin.js dist/*.ipa && babel-node scripts/ios/build.js" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.7.1/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
    15:40:20 The script called "build" which runs "nps android.build && nps ios.build && nps finish" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.7.1/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
    15:40:20 npm ERR! code ELIFECYCLE
    15:40:20 npm ERR! errno 1
    15:40:20 npm ERR! ENGAL@3.6.2-1651.1 build: `nps build`
    15:40:20 npm ERR! Exit status 1
    15:40:20 npm ERR! 
    15:40:20 npm ERR! Failed at the NFIBEngage@3.6.2-1651.1 build script.
    15:40:20 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    15:40:20 
    15:40:20 npm ERR! A complete log of this run can be found in:
    15:40:20 npm ERR!     /Users/ncis/.npm/_logs/2019-05-17T20_40_20_977Z-debug.log
    15:40:21 Build step 'Execute shell' marked build as failure
    15:40:21 Set build name.
    15:40:21 New build name is 'JS! ENGAL 3.6.2-1651.1+114'
    15:40:21 Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: 'JS! ENGAL 3.6.2-1651.1+114', new value: 'JS! ENGAL 3.6.2-1651.1+114'
    15:40:23 Archiving artifacts
    15:40:27 Finished: FAILURE
```

## Steps to Reproduce

git clone https://CortesD@bitbucket.nfib.org/scm/enga/engage-application.mobile.git
Run `npm install`
Run `npm run build`

I expected for there to be a successful build.

### Possible Solution

I am not sure what is going on, I tried by just changing the script to `npm run-scripts build` but it just hangs when I run that.

I then did a `rm -rf node_modules` and then a `npm install` and then `react-native run-ios` and then I was no longer able to open the app in simulator at all with this error:

   ```
 error: API request failed
    
      caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
    
    
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry build/Build/Intermediates.noindex/NFIBEngage.build/Debug-iphonesimulator/PROD.build/Script-05334972DCA04E3B97F129C0.sh

```

**Comment by markstory** [comment]
>    caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)

Looks like you don't have an API key setup to talk to sentry. The [sentry-cli docs](https://docs.sentry.io/cli/configuration/) cover how to get an authentication token working.

**Comment by BYK** [comment]
Closing due to inactivity.
