### ISSUE TITLE
Error when I execute "sentry createuser ..." => hub = Hub.current => AttributeError: 'NoneType' object has no attribute 'current'

### ISSUE THREAD

**Issue by harobed** [getsentry/sentry#13479]
Hi,

I use `sentry:9.1.1` Docker image.

I execute this line:

```
# sentry upgrade --noinput
# sentry createuser --email admin@example.com --password password --superuser --no-input
09:07:34 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
09:07:38 [INFO] sentry.plugins.github: apps-not-configured
User created: admin@example.com
Added to organization: sentry
Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(Thread-1, stopped daemon 139932343858944)>>
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/excepthook.py", line 23, in sentry_sdk_excepthook
    hub = Hub.current
AttributeError: 'NoneType' object has no attribute 'current'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/lib/python2.7/threading.py", line 814, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/local/lib/python2.7/traceback.py", line 241, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'
```

I don't understand why I have this error : 

```
    hub = Hub.current
AttributeError: 'NoneType' object has no attribute 'current'
```

I found the same subject here: https://github.com/getsentry/sentry-python/issues/334

How can I fix this error?

Note: after this error I can signin with success to Sentry.

Best regards,
Stéphane

**Comment by untitaker** [comment]
Yeah it's a bug in the SDK... I think it's harmless and we just need to catch it down if it happens.
