### ISSUE TITLE
Problem fetching event data

### ISSUE THREAD

**Issue by deejay1** [getsentry/sentry#1392]
When trying to access /foo/bar-2/group/22857/events/latest/json/ I get an internal server error:

```python
[ERROR] Internal Server Error: /foo/bar-2/group/22857/events/latest/json/
Traceback (most recent call last):
  File "/home/sentry/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sentry/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 176, in _wrapped
    return func(request, *args, **kwargs)
  File "/home/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/groups.py", line 494, in group_event_details_json
    return HttpResponse(json.dumps(event.as_dict()), mimetype='application/json')
  File "/home/sentry/lib/python2.7/site-packages/sentry/models/event.py", line 177, in as_dict
    data['culprit'] = self.group.culprit
AttributeError: 'NoneType' object has no attribute 'culprit'
```

Also no event data is visible at foo/bar-2/group/22857/ (graph, status, last seen and the side bar are visible)

Sentry version 7.1.3

**Comment by deejay1** [comment]
So what's the current status? (seeing the revert) From looking at the database schema I don't see the "culprit" field anywhere (database is MySQL)

**Comment by deejay1** [comment]
Maybe this is related?

```python
[ERROR] Unable to process log entry: This is forbidden when an 'atomic' block is active.
Traceback (most recent call last):
  File "/home/sentry/local/lib/python2.7/site-packages/raven/contrib/django/models.py", line 173, in sentry_exception_handler
    client.captureException(exc_info=sys.exc_info(), request=request)
  File "/home/sentry/local/lib/python2.7/site-packages/raven/base.py", line 658, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/home/sentry/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 160, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/home/sentry/local/lib/python2.7/site-packages/raven/base.py", line 510, in capture
    self.send(**data)
  File "/home/sentry/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 16, in send
    transaction.rollback()
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/transaction.py", line 145, in rollback
    get_connection(using).rollback()
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 179, in rollback
    self.validate_no_atomic_block()
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 367, in validate_no_atomic_block
    "This is forbidden when an 'atomic' block is active.")
TransactionManagementError: This is forbidden when an 'atomic' block is active.
```

**Comment by dcramer** [comment]
That revert was a mistake, its actually not reverted

**Comment by dcramer** [comment]
We no longer use raven.contrib.django in Sentry. If you're seeing that  you're pre 7.1

**Comment by deejay1** [comment]
This is weird, because I just did a clean install from pypi (dropping the entire virtualenv first) and:
```
$ pip list
amqp (1.0.13)
anyjson (0.3.3)
BeautifulSoup (3.2.1)
billiard (2.7.3.34)
celery (3.0.25)
cffi (0.8.6)
cryptography (0.7.2)
cssselect (0.9.1)
cssutils (0.9.10)
distribute (0.6.24)
Django (1.6.10)
django-bitfield (1.7.1)
django-celery (3.0.23)
django-crispy-forms (1.2.8)
django-paging (0.2.5)
django-picklefield (0.3.1)
django-recaptcha (1.0.3)
django-social-auth (0.7.28)
django-statsd-mozilla (0.3.8.7)
django-sudo (1.1.2)
django-templatetag-sugar (1.0)
djangorestframework (2.3.14)
email-reply-parser (0.2.0)
enum34 (0.9.23)
gunicorn (0.17.4)
httplib2 (0.9)
ipaddr (2.1.11)
kombu (2.5.16)
logan (0.5.10)
lxml (3.4.1)
Markdown (2.4.1)
mysqlclient (1.3.4)
nydus (0.10.8)
oauth2 (1.5.211)
pip (6.0.6)
progressbar (2.3)
protobuf (2.5.0)
pyasn1 (0.1.7)
pycparser (2.10)
Pygments (1.6)
pyOpenSSL (0.14)
python-dateutil (1.5)
python-memcached (1.53)
python-openid (2.2.5)
pytz (2014.10)
raven (5.1.1)
redis (2.10.3)
riak (2.2.0)
riak-pb (2.0.0.16)
sentry (7.1.4)
setproctitle (1.1.8)
simplejson (3.3.3)
six (1.9.0)
South (1.0.1)
statsd (1.0.0)
toronado (0.0.6)
ua-parser (0.3.6)
urllib3 (1.7.1)
```

And I still get that error...

**Comment by dcramer** [comment]
I'm not sure we actually pushed a release with the group.culprit fix.

The issue in this case is that the group you're looking at has no event, so it cant dump the  data.

**Comment by deejay1** [comment]
OK, I've resolved the problem by dumping data from the DB and importing it into a new one, it must have been broken during one of the previous migrations, when it was running from the master branch.
If anyone else hits similar problems then:
```bash
# Dump the data
mysqldump --no-create-db --no-create-info DATABASE  > dump.sql
# Create a new DB and populate it by running sentry
# Truncate the "new data"
mysql -Nse 'show tables' NEW_DATABASE | while read table; do mysql -e "SET FOREIGN_KEY_CHECKS = 0; truncate table $table" sentry; done

# Import old data
mysql NEW_DATABASE < dump.sql
```
