### ISSUE TITLE
Oops! On fresh install

### ISSUE THREAD

**Issue by markkimsal** [getsentry/sentry#13975]
I installed sentry from docker with the instructions here:

*  On-Premise docker [docker :latest]
* https://github.com/docker-library/docs/tree/master/sentry

## Description

Oops error when loading the page for the first time.

`
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
    return super(AuthLoginView, self).handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
    return super(BaseView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range

`

## Steps to Reproduce

1. https://github.com/docker-library/docs/tree/master/sentry

The initial `upgrade` command stoped after 429 migrations, I didn't realize there were more.  I tried to "createuser" after these 429 migrations and got this "list index out of range" error.  Now when I create more users I get duplicate key errors (probably because I'm using the same email).

Note that this happens when I simply try to load the system, not when I try to login.

I tried to make another user with different email and the same exception happens.

Sentry is trying to load a default organization when none exists

models/organization.py
`
    @classmethod
    def get_default(cls):
        """
        Return the organization used in single organization mode.
        """
        return cls.objects.filter(
            status=OrganizationStatus.ACTIVE,
        )[0]
`

**Comment by markkimsal** [comment]
I destroyed the pgsl docker container, rebuilt, re-ran upgrade and createuser and same error.  Still had to run upgrade multiple times.  It might be running out of ram, but that shouldn't affect pgsql.

**Comment by markkimsal** [comment]
I finally got a fresh install to create an org.

If the system does *not* ask you to create a user during upgrade you are screwed.  the `createuser` command does not create an org and will fault if there is not an org.

```
 > sentry:0465_sync
 > sentry:0466_auto__add_platformexternalissue__add_unique_platformexternalissue_grou
 > sentry:0467_backfill_integration_status
 > sentry:0468_auto__add_field_projectdebugfile_code_id__add_index_projectdebugfile_p
 > sentry:0468_recent_search
 > sentry:0469_fix_state
 > sentry:0470_org_saved_search
 > sentry:0471_global_saved_search_types
 > sentry:0472_auto__add_field_sentryapp_author
Created internal Sentry project (slug=internal, id=1)

Would you like to create a user account now? [Y/n]: y
Email: me@me
Password:
Repeat for confirmation: 
Should this user be a superuser? [y/N]: y
User created:  me@me
Added to organization: sentry
Running migrations for sentry.nodestore:
 - Migrating forwards to 0001_initial.
 > sentry.nodestore:0001_initial

```

You need about 6 GB of ram to execute the django migrations.  Maybe it's time to squash migrations back to 0001 ?

It's something to do with the receivers not being connected to `post_syncdb` on subsequent runs of upgrade that fail because of OOM.

**Comment by markkimsal** [comment]
It would be great if the creatuser command could catch index error and create the sample organization (it's already checking if the system is in single org mode).  Or if it could just do get_or_create

```
    org, _ = Organization.objects.get_or_create(
        slug='sentry', defaults={
            'name': 'Sentry',
        }
    )```
