### ISSUE TITLE
Error processing 'add_tags' on 'GroupManager'

### ISSUE THREAD

**Issue by YunseokJANG** [getsentry/sentry#1405]
I tested with 'raven test DSN?timeout=N', and it display 'success'. However, every time I tried to write a log, I faced same types of error.(I fixed all the others, but not this one..) Here is the following.

15:26:16 worker.1 | AssertionError: Key is not an int
15:30:29 worker.1 | [2015-01-27 15:30:29,291: ERROR/PoolWorker-2] Data not available in preprocess_event (cache_key=e:f532f822bae3472788f702d581e2e089)
15:30:29 worker.1 | [2015-01-27 15:30:29,296: WARNING/PoolWorker-2] here
15:30:29 worker.1 | [ERROR] Error processing 'add_tags' on 'GroupManager': Key is not an int
15:30:29 worker.1 | Traceback (most recent call last):
15:30:29 worker.1 |   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/utils/safe.py", line 26, in safe_execute
15:30:29 worker.1 |     result = func(*args, **kwargs)
15:30:29 worker.1 |   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/models/group.py", line 103, in add_tags
15:30:29 worker.1 |     tsdb.incr_multi(tsdb_keys)
15:30:29 worker.1 |   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/tsdb/base.py", line 91, in incr_multi
15:30:29 worker.1 |     self.incr(model, key, timestamp, count)
15:30:29 worker.1 |   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/tsdb/dummy.py", line 18, in incr
15:30:29 worker.1 |     assert isinstance(key, (int, long)), 'Key is not an int'
15:30:29 worker.1 | AssertionError: Key is not an int

It seems like getting something from cache first (I'm using redis as a cache).
I think I mis-wrote(or missed) few configurations, but I cannot guess which value is wrong...

**Comment by YunseokJANG** [comment]
oops. SENTRY_BUFFER_OPTIONS param was wrong.
