### ISSUE TITLE
Django integration is not working with Django 2.1 and sentry-sdk==0.10.2

### ISSUE THREAD

**Issue by dmitry-saritasa** [getsentry/sentry#14124]
#13607  Important Details
Python 3.5.8
Django 2.1
Sentry SDK 0.10.2

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

After I followed the instructions here
https://sentry.io/for/django/

and run 
```
python3 manage.py runserver_plus 0.0.0.0:8000
```
It crashed.

**console output**

```
[localhost] local: python3 manage.py runserver_plus 0.0.0.0:8000  --reloader-type stat --pm
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/dmitry/.pyenv/versions/3.6.8/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dmitry/Projects/analytics/backend/config/__init__.py", line 2, in <module>
    from .celery import app as celery_app
  File "/home/dmitry/Projects/analytics/backend/config/celery.py", line 13, in <module>
    backend=settings.CELERY_BACKEND,
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/dmitry/.pyenv/versions/3.6.8/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/dmitry/Projects/analytics/backend/config/settings/local.py", line 6, in <module>
    from .development import *
  File "/home/dmitry/Projects/analytics/backend/config/settings/development.py", line 128, in <module>
    integrations=[DjangoIntegration],
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/sentry_sdk/hub.py", line 84, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/sentry_sdk/client.py", line 93, in __init__
    options["integrations"], with_defaults=options["default_integrations"]
  File "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/sentry_sdk/integrations/__init__.py", line 82, in setup_integrations
    type(integration).setup_once()
AttributeError: type object 'type' has no attribute 'setup_once'

```

**Comment by untitaker** [comment]
You are missing parenthesis in your init. Check again.

**Comment by dmitry-saritasa** [comment]
You're right. Dumb mistake!
