### ISSUE TITLE
charts: db-init job exits

### ISSUE THREAD

**Issue by Spellchaser** [getsentry/sentry#14338]
## How are you running Sentry?
* On-Premise docker [Deploying Sentry through official helm-chart version 9.1.1]

## Description

New postgres schema, deploy helm chart for sentry, db-init job runs `sentry upgrade --noinput` under the hood. 

https://github.com/getsentry/sentry/blob/master/src/sentry/south_migrations/0015_auto__add_field_message_project__add_field_messagecountbyminute_projec.py#L12

## Steps to Reproduce

Deploy helm chart with configs or run `sentry upgrade --noinput`

Logs from db-init and stacktrace
```
18:19:57 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
18:20:01 [INFO] sentry.plugins.github: apps-not-configured
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for sentry:
 - Migrating forwards to 0472_auto__add_field_sentryapp_author.
 > sentry:0015_auto__add_field_message_project__add_field_messagecountbyminute_projec
Error in migration: sentry:0015_auto__add_field_message_project__add_field_messagecountbyminute_projec
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 75, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 30, in _upgrade
    ignore_ghost_migrations=True,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 125, in handle_noargs
    management.call_command('south_migrate', **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/south_migrate.py", line 105, in handle
    ignore_ghosts=ignore_ghosts,
  File "/usr/local/lib/python2.7/site-packages/south/migration/__init__.py", line 231, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 291, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 132, in migrate
    result = self.run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 241, in run
    return super(Forwards, self).run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 85, in run_migration
    migration_function()
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 61, in <lambda>
    return (lambda: direction(orm))
  File "/usr/local/lib/python2.7/site-packages/sentry/south_migrations/0015_auto__add_field_message_project__add_field_messagecountbyminute_projec.py", line 12, in forwards
    db.delete_unique('sentry_groupedmessage', ['checksum', 'logger', 'view'])
  File "/usr/local/lib/python2.7/site-packages/south/db/generic.py", line 53, in _cache_clear
    return func(self, table, *args, **opts)
  File "/usr/local/lib/python2.7/site-packages/south/db/generic.py", line 666, in delete_unique
    (table_name, columns))
ValueError: Cannot find a UNIQUE constraint on table sentry_groupedmessage, columns ['checksum', 'logger', 'view']
```

psql output
```
appsdb=> \dt
                                List of relations
       Schema        |            Name             | Type  |        Owner        
---------------------+-----------------------------+-------+---------------------
 tel_sentry_postgres | auth_group                  | table | tel_sentry_postgres
 tel_sentry_postgres | auth_group_permissions      | table | tel_sentry_postgres
 tel_sentry_postgres | auth_permission             | table | tel_sentry_postgres
 tel_sentry_postgres | auth_user                   | table | tel_sentry_postgres
 tel_sentry_postgres | django_admin_log            | table | tel_sentry_postgres
 tel_sentry_postgres | django_content_type         | table | tel_sentry_postgres
 tel_sentry_postgres | django_session              | table | tel_sentry_postgres
 tel_sentry_postgres | django_site                 | table | tel_sentry_postgres
 tel_sentry_postgres | sentry_filtervalue          | table | tel_sentry_postgres
 tel_sentry_postgres | sentry_groupedmessage       | table | tel_sentry_postgres
 tel_sentry_postgres | sentry_message              | table | tel_sentry_postgres
 tel_sentry_postgres | sentry_messagecountbyminute | table | tel_sentry_postgres
 tel_sentry_postgres | sentry_messagefiltervalue   | table | tel_sentry_postgres
 tel_sentry_postgres | sentry_messageindex         | table | tel_sentry_postgres
 tel_sentry_postgres | sentry_project              | table | tel_sentry_postgres
 tel_sentry_postgres | sentry_projectmember        | table | tel_sentry_postgres
 tel_sentry_postgres | south_migrationhistory      | table | tel_sentry_postgres
(20 rows)

appsdb=> \d sentry_groupedmessage
                             Table "tel_sentry_postgres.sentry_groupedmessage"
   Column   |           Type           |                             Modifiers                              
------------+--------------------------+--------------------------------------------------------------------
 id         | bigint                   | not null default nextval('sentry_groupedmessage_id_seq'::regclass)
 logger     | character varying(64)    | not null
 class_name | character varying(128)   | 
 level      | integer                  | not null
 message    | text                     | not null
 traceback  | text                     | 
 view       | character varying(200)   | 
 checksum   | character varying(32)    | not null
 status     | integer                  | not null
 times_seen | integer                  | not null
 last_seen  | timestamp with time zone | not null
 first_seen | timestamp with time zone | not null
 data       | text                     | 
 score      | integer                  | not null
Indexes:
    "sentry_groupedmessage_pkey" PRIMARY KEY, btree (id)
    "sentry_groupedmessage_logger_6620e83ff8553a25_uniq" UNIQUE CONSTRAINT, btree (logger, view, checksum)
    "sentry_groupedmessage_checksum" btree (checksum)
    "sentry_groupedmessage_checksum_like" btree (checksum varchar_pattern_ops)
    "sentry_groupedmessage_class_name" btree (class_name)
    "sentry_groupedmessage_class_name_like" btree (class_name varchar_pattern_ops)
    "sentry_groupedmessage_first_seen" btree (first_seen)
    "sentry_groupedmessage_last_seen" btree (last_seen)
    "sentry_groupedmessage_level" btree (level)
    "sentry_groupedmessage_logger" btree (logger)
    "sentry_groupedmessage_logger_like" btree (logger varchar_pattern_ops)
    "sentry_groupedmessage_status" btree (status)
    "sentry_groupedmessage_times_seen" btree (times_seen)
    "sentry_groupedmessage_view" btree (view)
    "sentry_groupedmessage_view_like" btree (view varchar_pattern_ops)
Check constraints:
    "sentry_groupedmessage_level_check" CHECK (level >= 0)
    "sentry_groupedmessage_status_check" CHECK (status >= 0)
    "sentry_groupedmessage_times_seen_check" CHECK (times_seen >= 0)
Referenced by:
    TABLE "sentry_messagefiltervalue" CONSTRAINT "group_id_refs_id_1fb6dc4e" FOREIGN KEY (group_id) REFERENCES sentry_groupedmessage(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_message" CONSTRAINT "group_id_refs_id_249fad1d" FOREIGN KEY (group_id) REFERENCES sentry_groupedmessage(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_messagecountbyminute" CONSTRAINT "group_id_refs_id_b6354eb4" FOREIGN KEY (group_id) REFERENCES sentry_groupedmessage(id) DEFERRABLE INITIALLY DEFERRED
```

### What you expected to happen

The PSQL should not fail and kill the migration if the unique constraint doesn't exist.

### Possible Solution

Check for unique constraint before trying to remove it

**Comment by Spellchaser** [comment]
Is there a reason all delete_unique fail if they don't exist?

There's some safety code here:
https://github.com/getsentry/sentry/blob/master/src/sentry/south_migrations/0034_auto__add_unique_option_key__del_unique_option_value_key__del_unique_g.py#L11-L15

In the general case I would think that we do no-op if it doesn't exist

**Comment by Spellchaser** [comment]
Also once I got past the delete unique, I'm running into add constraint errors too!

`django.db.utils.ProgrammingError: ProgrammingError('constraint "owner_id_refs_id_5fcf21c1" for relation "sentry_project" already exists\n',)
SQL: ALTER TABLE "sentry_project" ADD CONSTRAINT "owner_id_refs_id_5fcf21c1" FOREIGN KEY ("owner_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;`
from https://github.com/getsentry/sentry/blob/master/src/sentry/south_migrations/0018_auto__chg_field_project_owner.py#L14

Full trace
```
# sentry upgrade --noinput
15:46:03 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
15:46:07 [INFO] sentry.plugins.github: apps-not-configured
Syncing...
Creating tables ...
Creating table django_admin_log
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table django_content_type
Creating table django_session
Creating table django_site
Creating table south_migrationhistory
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for sentry:
 - Migrating forwards to 0472_auto__add_field_sentryapp_author.
 > sentry:0001_initial
 > sentry:0002_auto__del_field_groupedmessage_url__chg_field_groupedmessage_view__chg
 > sentry:0003_auto__add_field_message_group__del_field_groupedmessage_server_name
 > sentry:0004_auto__add_filtervalue__add_unique_filtervalue_key_value
 > sentry:0005_auto
 > sentry:0006_auto
 > sentry:0007_auto__add_field_message_site
 > sentry:0008_auto__chg_field_message_view__add_field_groupedmessage_data__chg_field
 > sentry:0009_auto__add_field_message_message_id
 > sentry:0010_auto__add_messageindex__add_unique_messageindex_column_value_object_id
 > sentry:0011_auto__add_field_groupedmessage_score
 > sentry:0012_auto
 > sentry:0013_auto__add_messagecountbyminute__add_unique_messagecountbyminute_group_
 > sentry:0014_auto
 > sentry:0014_auto__add_project__add_projectmember__add_unique_projectmember_project
 > sentry:0015_auto__add_field_message_project__add_field_messagecountbyminute_projec
 > sentry:0016_auto__add_field_projectmember_is_superuser
 > sentry:0017_auto__add_field_projectmember_api_key
 > sentry:0018_auto__chg_field_project_owner
FATAL ERROR - The following SQL query failed: ALTER TABLE "sentry_project" ADD CONSTRAINT "owner_id_refs_id_5fcf21c1" FOREIGN KEY ("owner_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
The error was: ProgrammingError('constraint "owner_id_refs_id_5fcf21c1" for relation "sentry_project" already exists\n',)
SQL: ALTER TABLE "sentry_project" ADD CONSTRAINT "owner_id_refs_id_5fcf21c1" FOREIGN KEY ("owner_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
Error in migration: sentry:0018_auto__chg_field_project_owner
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/receivers/core.py", line 31, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/receivers/core.py", line 50, in create_default_projects
    verbosity=verbosity,
  File "/usr/local/lib/python2.7/site-packages/sentry/receivers/core.py", line 67, in create_default_project
    user = User.objects.filter(is_superuser=True)[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 387, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 74, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
```

**Comment by BYK** [comment]
So this is quite weird. Are you upgrading from an earlier version or is this a fresh install? Also what Postgres version are you using?

Also pinging @okgolove as we don't maintain the helm charts but he does :) The helm charts are not "official" as they are not backed by Sentry but by the community FYI.

**Comment by okgolove** [comment]
Hi! As far as I understand this is not the chart issue?

**Comment by Spellchaser** [comment]
Nope it's not a chart issue, essentially running `sentry upgrade --noinput`
has many stop points.

Postgres version: 10.9.2_1.0.0

**Comment by BYK** [comment]
@okgolove - Maybe we should make the chart enforce a Postgres version as they can easily be breaking like in this case?

@Spellchaser - AFAIK we only support 9.5+ for now and I know the onpremise repo works well both with 9.5 and 9.6, would you mind trying with one of those?

@mattrobenolt - Am I wrong to assume we do not yet support Postgres 10?

**Comment by okgolove** [comment]
@BYK currently 9.6.2 Postgresql is using as chart dependency. You can't change the postgresql chart version because it is hardcoded.

**Comment by Spellchaser** [comment]
@okgolove External Postgresql is supported via the configs? 

By setting the [condition](https://github.com/helm/charts/blob/master/stable/sentry/requirements.yaml#L5) and configuring the [Postgres configs](https://github.com/helm/charts/blob/master/stable/sentry/values.yaml#L184-L194) to point to an external

**Comment by okgolove** [comment]
@Spellchaser nice catch. I misses that part, now it's really supported :)
When I started use the chart it hadn't been supported.

**Comment by mattrobenolt** [comment]
> Am I wrong to assume we do not yet support Postgres 10?

We don't officially and that's just because we don't use it ourselves. We use 9.6, so we can't really confirm or deny pg 10+ in all scenarios. But it's most likely fine.

I assume the issues here are related to our migration framework, South, being really bad. It's unfortunate, and we're working to get away from it. But it's just really bad. Especially in places like this.

The names it generates for constraints and indices isn't really deterministic. It uses a function in Python `hash()` which is fundamentally not deterministic, which sometimes leads to it creating an index with one name, then when referencing it in the future, it's trying to generate the same name, but because `hash()` isn't deterministic, it might return a different name.

**Comment by Spellchaser** [comment]
The root cause is because the django `connection.settings_dict` returned doesn't have a field called `SCHEMA`. Here's a sample dump of `connection.settings_dict`:
```
{'ENGINE': 'sentry.db.postgres', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'appsdb', 'TEST_MIRROR': None, 'CONN_MAX_AGE': 0, 'TEST_NAME': None, 'TIME_ZONE': 'UTC', 'TEST_COLLATION': None, 'OPTIONS': {'autocommit': True}, 'HOST': 'snipped.dns.snip.com', 'USER': 'tel_sentry_postgres', 'TEST_CHARSET': None, 'PASSWORD': 'snipped', 'PORT': '4331'}
```
This is called by  `_get_schema_name` and is called by the get constraints sql in `_fill_constraint_cache`. This reports that there are no constraints for any table which is why I've been getting all these errors.

**Comment by mattrobenolt** [comment]
```
>>> from django.db import connection
>>> connection.settings_dict
>>> 'SCHEMA' in connection.settings_dict
False
```

Where do you see this even being filled? This is against a production instance which runs against 9.6.

**Comment by mattrobenolt** [comment]
Are you able to do something like this?

```
>>> from south.db.generic import DatabaseOperations
>>> ops = DatabaseOperations('default')
>>> ops._fill_constraint_cache('sentry', 'sentry_groupedmessage')
>>> ops._constraint_cache
{'sentry': {'sentry_groupedmessage': {u'status': set([(u'CHECK', u'sentry_groupedmessage_status_check')]), u'short_id': set([(u'CHECK', u'sentry_groupedmessage_short_id_check')]), u'level': set([(u'CHECK', u'sentry_groupedmessage_level_check')]), u'num_comments': set([(u'CHECK', u'sentry_groupedmessage_num_comments_check')]), u'times_seen': set([(u'CHECK', u'sentry_groupedmessage_times_seen_check')]), u'first_release_id': set([(u'FOREIGN KEY', u'first_release_id_refs_id_d035a570')]), u'project_id': set([(u'FOREIGN KEY', u'project_id_refs_id_12bef79feaf653de')]), u'id': set([(u'PRIMARY KEY', u'sentry_groupedmessage_pkey')])}}}
```

**Comment by Spellchaser** [comment]
I eventually got it to work pretty flawlessly by setting my default connection dict. After getting past the migrations, everything seems to work. 

Unfortunately I'm not dedicating more time to troubleshoot.

Also not sure how to hook in the configured settings
```
# python -i /etc/sentry/sentry.conf.py 
>>> from django.db import connection
>>> connection.settings_dict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/django/db/__init__.py", line 34, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 196, in __getitem__
    self.ensure_defaults(alias)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 170, in ensure_defaults
    conn = self.databases[alias]
  File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.func.__name__] = self.func(instance)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
>>> 
```
