### ISSUE TITLE
`sentry --config=myconf.py start` does not work

### ISSUE THREAD

**Issue by zombat** [getsentry/sentry#1438]
Starting sentry with a config file in a custom location other than `~/.sentry/sentry.conf.py` does not seem to work with the current version 7.3.2. The error that comes up is this: 

```
Traceback (most recent call last):
  File "/home/sentry/virtualenv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/home/sentry/virtualenv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/sentry/virtualenv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/sentry/virtualenv/local/lib/python2.7/site-packages/sentry/services/http.py", line 34, in load
    import sentry.wsgi
  File "/home/sentry/virtualenv/local/lib/python2.7/site-packages/sentry/wsgi.py", line 20, in <module>
    configure()
  File "/home/sentry/virtualenv/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 399, in configure
    initializer=initialize_app,
  File "/home/sentry/virtualenv/local/lib/python2.7/site-packages/logan/runner.py", line 89, in configure_app
    raise ValueError("Configuration file does not exist at %r" % (config_path,))
ValueError: Configuration file does not exist at '/home/sentry/.sentry/sentry.conf.py'
```

The problem seems to be the `configure()` call in `sentry/wsgi.py` without any parameters so that `config_path` will be `None` in `configure_app()` in `sentry/utils/runner.py`. 

I searched older issues and found two that seemed to have the same problem but they could solve it after fixing errors in their settings. But that does not seem to be the problem here, as far as I can tell.

**Comment by fjorgemota** [comment]
+1

**Comment by juniorrocha** [comment]
Edit the file  /home/sentry/virtualenv/local/lib/python2.7/site-packages/sentry/utils/runner.py and go to the line 89.
Put the right path (/etc/sentry.conf.py for example).
Restart sentry.

Be happy.

**Comment by kikimor** [comment]
+1

**Comment by dcramer** [comment]
@kikimor this is already fixed in master

**Comment by juniorrocha** [comment]
Awesome! Thanks @dcramer

**Comment by fjorgemota** [comment]
Great (and awesome too), thanks, @dcramer! :D
