### ISSUE TITLE
gunicorn threading problems in 7.3.1/7.3.2

### ISSUE THREAD

**Issue by vitaliyf** [getsentry/sentry#1440]
Upgraded to 7.3.2 (from 7.1.x) and started getting this:

```
[ERROR] DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140159498786560 and this is thread id 92317968.
Traceback (most recent call last):
  File "/opt/sentry7/env/lib/python2.7/site-packages/sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/opt/sentry7/env/lib/python2.7/site-packages/sentry/event_manager.py", line 244, in save
    project = Project.objects.get_from_cache(id=project)
  File "/opt/sentry7/env/lib/python2.7/site-packages/sentry/db/models/manager.py", line 209, in get_from_cache
    result = self.get(**kwargs)
  File "/opt/sentry7/env/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/sentry7/env/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/opt/sentry7/env/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/opt/sentry7/env/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/sentry7/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/opt/sentry7/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/opt/sentry7/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/sentry7/env/lib/python2.7/site-packages/django/db/backends/__init__.py", line 157, in cursor
    self.validate_thread_sharing()
  File "/opt/sentry7/env/lib/python2.7/site-packages/django/db/backends/__init__.py", line 499, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident()))
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140159498786560 and this is thread id 92317968.
```

Downgrade to 7.3.0 makes the problem go away, so this must be related to https://github.com/getsentry/sentry/commit/17be420953de02ca76ad114a47d33649417a6ea3

gunicorn's github has a couple tickets on this (such as https://github.com/benoitc/gunicorn/issues/879), but they seem to center around Django 1.7 which Sentry isn't using.  They also mention trying preload=False

We are using MySQL backend.

**Comment by dcramer** [comment]
You could try setting 'preload': False in SENTRY_WEB_OPTIONS

We dont have a great way to reliable test this, but if that fixes it we can commit the change to the defaults.

**Comment by dcramer** [comment]
I think we'll also make it a goal for 7.4 or 7.5 to drop gunicorn, but that's a bit trickier and may require a different startup strategy for sentry.

**Comment by caljess599** [comment]
We are experiencing this too, in Sentry 7.4.1 -- and setting `preload: False` does not provide a workaround.  
```
[ERROR] Error processing 'get_rules' on 'JavascriptPlugin': DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140226130962240 and this is thread id 140225907429776.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 323, in __exit__
    connection.close()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 187, in close
    self.validate_thread_sharing()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 499, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident()))
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140226130962240 and this is thread id 140225907429776.
```

**Comment by hit9** [comment]
Any updates on this ?

**Comment by hit9** [comment]
With gevent, I have tried add this to conf.py

```python
from gevent import monkey
monkey.patch_all()
```

**Comment by dcramer** [comment]
Please re-open if anyone has new data, and specifically sees this on 7.5.0.

**Comment by atleta** [comment]
I'm seeing this in 7.7.0 when trying to open the (and getting http 500 errors, even the root url won't load)

```
Top level Sentry exception caught - failed creating log record
Error processing %r on %r: %s
Traceback (most recent call last):
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/handlers/logging.py", line 65, in emit
    return self._emit(record)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/contrib/django/handlers.py", line 29, in _emit
    return super(SentryHandler, self)._emit(record, request=request)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/handlers/logging.py", line 176, in _emit
    extra=extra, date=date, **kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 39, in capture
    return super(SentryInternalClient, self).capture(*args, **kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 157, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/base.py", line 521, in capture
    self.send(**data)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 50, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 209, in get_from_cache
    result = self.get(**kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 157, in cursor
    self.validate_thread_sharing()
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 499, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident()))
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id -145291584 and this is thread id 188172604.

[2015-08-12 17:32:26 +0000] [20286] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/sentry/../gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/sentry/../gunicorn/workers/ggevent.py", line 159, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/sentry/../gunicorn/workers/async.py", line 112, in handle_request
    for item in respiter:
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/middleware.py", line 37, in __call__
    self.handle_exception(environ)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/middleware.py", line 71, in handle_exception
    return self.client.captureException()
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/base.py", line 676, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 39, in capture
    return super(SentryInternalClient, self).capture(*args, **kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 157, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/raven/base.py", line 521, in capture
    self.send(**data)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 50, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 209, in get_from_cache
    result = self.get(**kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 157, in cursor
    self.validate_thread_sharing()
  File "/usr/local/lib/sentry/env/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 499, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident()))
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id -145291584 and this is thread id 188172604.
```

This is an instance I tried to upgrade from 6.4.4, but it shouldn't make a difference. (Unfortunately I cannot downgrade, as one of the migrations fail when I try to migrate back to the state of 7.5.0.)

**Comment by dcramer** [comment]
@atleta you can try running with uwsgi as a quick workaround: https://docs.getsentry.com/on-premise/server/nginx/#proxying-uwsgi

**Comment by atleta** [comment]
@dcramer Cool, works OK with uwsgi. Thanks.
