### ISSUE TITLE
No default organization created - docker tutorial

### ISSUE THREAD

**Issue by Spellchaser** [getsentry/sentry#14423]
Followed the instructions for docker afaik. When I try to hit the login page I get an error
```
Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!
```
The `sentry_organization` table is empty
`SENTRY_SINGLE_ORGANIZATION=True` from the defaults

Traces from the web pod
```
172.17.0.1 - - [15/Aug/2019:21:35:32 +0000] "GET /auth/login/ HTTP/1.1" 500 5580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
127.0.0.1 - - [16/Aug/2019:14:21:55 +0000] "GET /auth/login HTTP/1.1" 301 275 "-" "curl/7.52.1"
172.17.0.1 - - [16/Aug/2019:14:22:07 +0000] "GET / HTTP/1.1" 302 467 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
    return super(AuthLoginView, self).handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
    return super(BaseView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
14:22:07 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
172.17.0.1 - - [16/Aug/2019:14:22:07 +0000] "GET /auth/login/ HTTP/1.1" 500 5580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
```

docker ps
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
f5eab8338199        sentry              "/entrypoint.sh run …"   47 hours ago        Up 47 hours         0.0.0.0:9000->9000/tcp   sentry-web-01
41243a2c2d1b        tianon/exim4        "docker-entrypoint.s…"   2 days ago          Up 2 days           25/tcp                   sentry-smtp
de52acb1befe        postgres:9.5        "docker-entrypoint.s…"   2 days ago          Up 2 days           5432/tcp                 sentry-postgres
819a11e4bc86        redis:3.2-alpine    "docker-entrypoint.s…"   2 days ago          Up 2 days           6379/tcp                 sentry-redis
```

docker version
```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

psql
```
sentry=# \dt sentry_organization
               List of relations
 Schema |        Name         | Type  | Owner  
--------+---------------------+-------+--------
 public | sentry_organization | table | sentry
(1 row)

sentry=# SELECT * FROM sentry_organization;
 id | name | status | date_added | slug | flags | default_role 
----+------+--------+------------+------+-------+--------------
(0 rows)
```

**Comment by mattrobenolt** [comment]
This is mostly likely because the upgrade process ran out of memory while running so it didn't finish.

**Comment by Spellchaser** [comment]
The logs from the upgrade seem to have completed.

```
$ docker run --rm -it --link sentry-redis:redis   --link sentry-postgres:postgres   --link sentry-smtp:smtp   --env SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}   ${REPOSITORY} upgrade
18:30:36 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
18:30:39 [INFO] sentry.plugins.github: apps-not-configured
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for sentry:
 - Migrating forwards to 0472_auto__add_field_sentryapp_author.
 > sentry:0300_auto__add_processingissue__add_unique_processingissue_project_checksum
 > sentry:0301_auto__chg_field_environment_project_id__chg_field_releaseenvironment_p
 > sentry:0302_merge_environments
 > sentry:0303_fix_release_new_group_counts
 > sentry:0304_auto__add_deploy
 > sentry:0305_auto__chg_field_authidentity_data__chg_field_useroption_value__chg_fie
 > sentry:0306_auto__add_apigrant__add_apiauthorization__add_unique_apiauthorization_
 > sentry:0307_auto__add_field_apigrant_scope_list__add_field_apitoken_scope_list__ad
 > sentry:0308_auto__add_versiondsymfile__add_unique_versiondsymfile_dsym_file_versio
 > sentry:0308_backfill_scopes_list
 > sentry:0309_fix_application_state
 > sentry:0310_auto__add_field_savedsearch_owner
 > sentry:0311_auto__add_releaseheadcommit__add_unique_releaseheadcommit_repository_i
 > sentry:0312_create_missing_emails
 > sentry:0313_auto__add_field_commitauthor_external_id__add_unique_commitauthor_orga
 > sentry:0314_auto__add_distribution__add_unique_distribution_release_name__add_fiel
 > sentry:0315_auto__add_field_useroption_organization__add_unique_useroption_user_or
 > sentry:0316_auto__del_field_grouptagvalue_project__del_field_grouptagvalue_group__
 > sentry:0317_drop_grouptagvalue_constraints
 > sentry:0318_auto__add_field_deploy_notified
 > sentry:0319_auto__add_index_deploy_notified
 > sentry:0320_auto__add_index_eventtag_date_added
 > sentry:0321_auto__add_field_projectkey_rate_limit_count__add_field_projectkey_rate
 > sentry:0321_auto__add_unique_environment_organization_id_name
 > sentry:0322_merge_0321_migrations
 > sentry:0323_auto__add_unique_releaseenvironment_organization_id_release_id_environ
 > sentry:0324_auto__add_field_eventuser_name__add_field_userreport_event_user_id
 > sentry:0325_auto__add_scheduleddeletion__add_unique_scheduleddeletion_app_label_mo
 > sentry:0326_auto__add_field_groupsnooze_count__add_field_groupsnooze_window__add_f
 > sentry:0327_auto__add_field_release_commit_count__add_field_release_last_commit_id
 > sentry:0328_backfill_release_stats
 > sentry:0329_auto__del_dsymsymbol__del_unique_dsymsymbol_object_address__del_global
 > sentry:0330_auto__add_field_grouphash_state
 > sentry:0331_auto__del_index_releasecommit_project_id__del_index_releaseenvironment
 > sentry:0332_auto__add_featureadoption__add_unique_featureadoption_organization_fea
 > sentry:0333_auto__add_field_groupresolution_type__add_field_groupresolution_actor_
 > sentry:0334_auto__add_field_project_platform
 > sentry:0334_auto__add_scheduledjob
 > sentry:0335_auto__add_field_groupsnooze_actor_id
 > sentry:0336_auto__add_field_user_last_active
 > sentry:0337_fix_out_of_order_migrations
 > sentry:0338_fix_null_user_last_active
 > sentry:0339_backfill_first_project_feature
 > sentry:0340_auto__add_grouptombstone__add_field_grouphash_group_tombstone_id
 > sentry:0341_auto__add_organizationintegration__add_unique_organizationintegration_
 > sentry:0342_projectplatform
 > sentry:0343_auto__add_index_groupcommitresolution_commit_id
 > sentry:0344_add_index_ProjectPlatform_last_seen
 > sentry:0345_add_citext
 > sentry:0346_auto__del_field_tagkey_project__add_field_tagkey_project_id__del_uniqu
 > sentry:0347_auto__add_index_grouptagvalue_project_id__add_index_grouptagvalue_grou
 > sentry:0348_fix_project_key_rate_limit_window_unit
 > sentry:0349_drop_constraints_filterkey_filtervalue_grouptagkey
 > sentry:0350_auto__add_email
 > sentry:0351_backfillemail
 > sentry:0352_add_index_release_coalesce_date_released_date_added
 > sentry:0353_auto__del_field_eventuser_project__add_field_eventuser_project_id__del
 > sentry:0354_auto__chg_field_commitfilechange_filename
 > sentry:0355_auto__add_field_organizationintegration_config__add_field_organization
 > sentry:0356_auto__add_useridentity__add_unique_useridentity_user_identity__add_ide
 > sentry:0357_auto__add_projectteam__add_unique_projectteam_project_team
 > sentry:0358_auto__add_projectsymcachefile__add_unique_projectsymcachefile_project_
 > sentry:0359_auto__add_index_tagvalue_project_id_key_last_seen
 > sentry:0360_auto__add_groupshare
 > sentry:0361_auto__add_minidumpfile
 > sentry:0362_auto__add_userip__add_unique_userip_user_ip_address
 > sentry:0363_auto__add_grouplink__add_unique_grouplink_group_id_linked_type_linked_
 > sentry:0364_backfill_grouplink_from_groupcommitresolution
 > sentry:0365_auto__del_index_eventtag_project_id_key_id_value_id
 > sentry:0366_backfill_first_project_heroku
 > sentry:0367_auto__chg_field_release_ref__chg_field_release_version
 > sentry:0368_auto__add_deletedorganization__add_deletedteam__add_deletedproject
 > sentry:0369_remove_old_grouphash_last_processed_event_data
Cleaning obsolete data from <HostInfo db='0' host='redis' host_id=0 password='' port='6379' ssl=False ssl_options=None unix_socket_path=None>...
Done cleaning 0 obsolete entries from <HostInfo db='0' host='redis' host_id=0 password='' port='6379' ssl=False ssl_options=None unix_socket_path=None>.
 > sentry:0370_correct_groupsnooze_windows
 > sentry:0371_auto__add_servicehook
 > sentry:0371_auto__del_minidumpfile
 > sentry:0372_resolve_migration_conflict
 > sentry:0373_backfill_projectteam
 > sentry:0374_auto__del_useridentity__del_unique_useridentity_user_identity__del_ide
 > sentry:0375_auto__add_identityprovider__add_unique_identityprovider_type_organizat
 > sentry:0376_auto__add_userpermission__add_unique_userpermission_user_permission
 > sentry:0377_auto__add_pullrequest__add_unique_pullrequest_repository_id_key__add_i
 > sentry:0378_delete_outdated_projectteam
 > sentry:0379_auto__add_unique_projectteam_project
 > sentry:0380_auto__chg_field_servicehook_url
 > sentry:0381_auto__del_field_deletedproject_team_name__del_field_deletedproject_tea
 > sentry:0382_auto__add_groupenvironment__add_unique_groupenvironment_group_id_envir
 > sentry:0383_auto__chg_field_project_team
 > sentry:0384_auto__del_unique_projectteam_project
 > sentry:0385_auto__add_field_rule_environment_id
 > sentry:0386_auto__del_unique_project_team_slug
 > sentry:0387_auto__add_field_groupassignee_team__chg_field_groupassignee_user
 > sentry:0388_auto__add_field_environmentproject_is_hidden
 > sentry:0389_auto__add_field_groupenvironment_first_release_id__add_index_groupenvi
 > sentry:0390_auto__add_field_userreport_environment
 > sentry:0391_auto__add_fileblobowner__add_unique_fileblobowner_blob_organization__a
 > sentry:0392_auto__add_projectownership
 > sentry:0393_auto__add_assistantactivity__add_unique_assistantactivity_user_guide_i
 > sentry:0394_auto__chg_field_project_team
 > sentry:0395_auto__add_releaseprojectenvironment__add_unique_releaseprojectenvironm
 > sentry:0396_auto__del_field_project_team
 > sentry:0397_auto__add_latestrelease__add_unique_latestrelease_repository_id_enviro
 > sentry:0397_auto__add_unique_identity_idp_user
 > sentry:0398_auto__add_pullrequestcommit__add_unique_pullrequestcommit_pull_request
 > sentry:0399_auto__chg_field_user_last_login__add_unique_identity_idp_user
 > sentry:0400_auto__add_projectredirect__add_unique_projectredirect_organization_red
 > sentry:0401_auto__chg_field_projectdsymfile_uuid
 > sentry:0402_auto__add_field_organizationintegration_date_added__add_field_identity
 > sentry:0403_auto__add_teamavatar
 > sentry:0404_auto__del_unique_environment_project_id_name
 > sentry:0405_auto__add_field_user_flags
 > sentry:0406_auto__add_projectavatar
 > sentry:0407_auto__add_field_identityprovider_external_id__add_unique_identityprovi
 > sentry:0408_identity_provider_external_id
 > sentry:0409_auto__add_field_releaseprojectenvironment_last_deploy_id
 > sentry:0410_auto__del_unique_identityprovider_type_organization
 > sentry:0411_auto__add_field_projectkey_data
 > sentry:0412_auto__chg_field_file_name
 > sentry:0413_auto__add_externalissue__add_unique_externalissue_organization_id_inte
 > sentry:0414_backfill_release_project_environment_last_deploy_id
 > sentry:0415_auto__add_relay
 > sentry:0416_auto__del_field_identityprovider_organization__add_field_identityprovi
 > sentry:0417_migrate_identities
Deleting 0 idps with no external_id
0 idps left
0 identities
Deleting 0 bad ids
0 identities left
0 new IDPs and 0 new IDs
 > sentry:0418_delete_old_idps
 > sentry:0419_auto__add_unique_identityprovider_type_external_id
 > sentry:0420_auto__chg_field_identityprovider_organization_id
 > sentry:0421_auto__del_field_identityprovider_organization_id__del_unique_identityp
 > sentry:0422_auto__add_grouphashtombstone__add_unique_grouphashtombstone_project_ha
 > sentry:0423_auto__add_index_grouphashtombstone_deleted_at
 > sentry:0424_auto__add_field_integration_status
 > sentry:0425_auto__add_index_pullrequest_organization_id_merge_commit_sha
 > sentry:0425_remove_invalid_github_idps
 > sentry:0426_auto__add_sentryappinstallation__add_sentryapp__add_field_user_is_sent
 > sentry:0427_auto__add_eventattachment__add_unique_eventattachment_project_id_event
 > sentry:0428_auto__add_index_eventattachment_project_id_date_added
 > sentry:0429_auto__add_integrationexternalproject__add_unique_integrationexternalpr
 > sentry:0430_auto__add_field_organizationintegration_status
 > sentry:0431_auto__add_field_externalissue_metadata
 > sentry:0432_auto__add_field_relay_is_internal
 > sentry:0432_auto__add_index_userreport_date_added__add_index_eventattachment_date_
 > sentry:0433_auto__add_field_relay_is_internal__add_field_userip_country_code__add_
 > sentry:0434_auto__add_discoversavedqueryproject__add_unique_discoversavedqueryproj
 > sentry:0435_auto__add_field_discoversavedquery_created_by
 > sentry:0436_rename_projectdsymfile_to_projectdebugfile
 > sentry:0437_auto__add_field_sentryapp_status
 > sentry:0438_auto__add_index_sentryapp_status__chg_field_sentryapp_proxy_user__chg_
 > sentry:0439_auto__chg_field_sentryapp_owner
 > sentry:0440_auto__del_unique_projectdebugfile_project_debug_id__add_index_projectd
 > sentry:0441_auto__add_field_projectdebugfile_data
 > sentry:0442_auto__add_projectcficachefile__add_unique_projectcficachefile_project_
 > sentry:0443_auto__add_field_organizationmember_token_expires_at
 > sentry:0443_auto__del_dsymapp__del_unique_dsymapp_project_platform_app_id__del_ver
 > sentry:0444_auto__add_sentryappavatar__add_field_sentryapp_redirect_url__add_field
 > sentry:0445_auto__add_promptsactivity__add_unique_promptsactivity_user_feature_org
 > sentry:0446_auto__add_index_promptsactivity_project_id
 > sentry:0447_auto__del_field_promptsactivity_organization__add_field_promptsactivit
 > sentry:0448_auto__add_field_sentryapp_is_alertable
 > sentry:0449_auto__chg_field_release_owner
 > sentry:0450_auto__del_grouphashtombstone__del_unique_grouphashtombstone_project_ha
 > sentry:0451_auto__del_field_projectbookmark_project_id__add_field_projectbookmark_
 > sentry:0452_auto__add_field_sentryapp_events
 > sentry:0452_auto__del_field_releaseenvironment_organization_id__del_field_releasee
 > sentry:0453_auto__add_index_releasefile_release_name
 > sentry:0454_resolve_duplicate_0452
 > sentry:0455_auto__add_field_groupenvironment_first_seen
 > sentry:0456_auto__add_dashboard__add_unique_dashboard_organization_title__add_widg
 > sentry:0457_auto__add_field_savedsearch_is_global__chg_field_savedsearch_project__
 > sentry:0457_auto__add_monitorcheckin__add_monitor__add_index_monitor_type_next_che
 > sentry:0458_global_searches_data_migration
 > sentry:0459_global_searches_unique_constraint
 > sentry:0460_auto__add_field_servicehook_organization_id
 > sentry:0461_event_attachment_indexes
 > sentry:0462_auto__add_servicehookproject
 > sentry:0462_releaseenvironment_project_id
 > sentry:0463_backfill_service_hook_project
 > sentry:0464_auto__add_sentryappcomponent__add_field_sentryapp_schema
 > sentry:0464_groupenvironment_foreignkeys
 > sentry:0465_sync
 > sentry:0466_auto__add_platformexternalissue__add_unique_platformexternalissue_grou
 > sentry:0467_backfill_integration_status
 > sentry:0468_auto__add_field_projectdebugfile_code_id__add_index_projectdebugfile_p
 > sentry:0468_recent_search
 > sentry:0469_fix_state
 > sentry:0470_org_saved_search
 > sentry:0471_global_saved_search_types
 > sentry:0472_auto__add_field_sentryapp_author
Running migrations for sentry.nodestore:
 - Migrating forwards to 0001_initial.
 > sentry.nodestore:0001_initial
Running migrations for sentry.search:
 - Migrating forwards to 0002_auto__del_searchtoken__del_unique_searchtoken_document_field_token__de.
 > sentry.search:0001_initial
 > sentry.search:0002_auto__del_searchtoken__del_unique_searchtoken_document_field_token__de
Running migrations for social_auth:
 - Migrating forwards to 0004_auto__del_unique_usersocialauth_provider_uid__add_unique_usersocialaut.
 > social_auth:0001_initial
 > social_auth:0002_auto__add_unique_nonce_timestamp_salt_server_url__add_unique_associati
 > social_auth:0003_auto__del_nonce__del_unique_nonce_server_url_timestamp_salt__del_assoc
 > social_auth:0004_auto__del_unique_usersocialauth_provider_uid__add_unique_usersocialaut
Running migrations for sentry.tagstore:
 - Migrating forwards to 0008_auto__chg_field_tagkey_environment_id.
 > sentry.tagstore:0001_initial
 > sentry.tagstore:0002_auto__del_tagkey__del_unique_tagkey_project_id_environment_id_key__del
 > sentry.tagstore:0003_auto__add_tagkey__add_unique_tagkey_project_id_environment_id_key__add
 > sentry.tagstore:0004_auto__del_tagkey__del_unique_tagkey_project_id_environment_id_key__del
 > sentry.tagstore:0005_auto__add_tagvalue__add_unique_tagvalue_project_id__key_value__add_ind
 > sentry.tagstore:0006_auto__del_unique_eventtag_event_id_key_value__add_unique_eventtag_proj
 > sentry.tagstore:0007_auto__chg_field_tagkey_environment_id__chg_field_tagkey_project_id__ch
 > sentry.tagstore:0008_auto__chg_field_tagkey_environment_id
Running migrations for sentry_plugins.hipchat_ac:
 - Migrating forwards to 0002_auto__del_mentionedevent.
 > sentry_plugins.hipchat_ac:0001_initial
 > sentry_plugins.hipchat_ac:0002_auto__del_mentionedevent
Running migrations for sentry_plugins.jira_ac:
 - Migrating forwards to 0001_initial.
 > sentry_plugins.jira_ac:0001_initial

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > crispy_forms
 > debug_toolbar
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > sudo
 > south

Migrated:
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
 - sentry.tagstore
 - sentry_plugins.hipchat_ac
 - sentry_plugins.jira_ac
Creating missing DSNs
Correcting Group.num_comments counter
```

**Comment by Spellchaser** [comment]
Running sentry upgrade again:
```
$ docker exec -ti sentry-web-01 bash
root@f5eab8338199:/# sentry upgrade 
19:03:26 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
19:03:29 [INFO] sentry.plugins.github: apps-not-configured
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for sentry:
- Nothing to migrate.
Running migrations for sentry.nodestore:
- Nothing to migrate.
Running migrations for sentry.search:
- Nothing to migrate.
Running migrations for social_auth:
- Nothing to migrate.
Running migrations for sentry.tagstore:
- Nothing to migrate.
Running migrations for sentry_plugins.hipchat_ac:
- Nothing to migrate.
Running migrations for sentry_plugins.jira_ac:
- Nothing to migrate.

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > crispy_forms
 > debug_toolbar
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > sudo
 > south

Migrated:
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
 - sentry.tagstore
 - sentry_plugins.hipchat_ac
 - sentry_plugins.jira_ac
Creating missing DSNs
Correcting Group.num_comments counter
root@f5eab8338199:/# echo $?
0
```
