### ISSUE TITLE
Sentry Migrations error.

### ISSUE THREAD

**Issue by sixdays** [getsentry/sentry#1450]
pip install -U sentry
worked fined. 

sentry upgrade, not so much.

(sentry)root@hrafninn:/var/www/sentry# sentry --config=/etc/sentry.conf.py upgrade
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for djcelery:
- Nothing to migrate.
 - Loading initial data for djcelery.
Installed 0 object(s) from 0 fixture(s)
Running migrations for django:
- Nothing to migrate.
 - Loading initial data for django.
Installed 0 object(s) from 0 fixture(s)
Running migrations for sentry:
 - Migrating forwards to 0165_auto__del_unique_file_name_checksum.
 > sentry:0157_auto__add_authidentity__add_unique_authidentity_auth_provider_ident__a
FATAL ERROR - The following SQL query failed: ALTER TABLE `sentry_authidentity` ADD CONSTRAINT `user_id_refs_id_78163ab5` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`);
The error was: (1825, "Failed to add the foreign key constraint on table 'sentry_authidentity'. Incorrect options in FOREIGN KEY constraint 'sentry/user_id_refs_id_78163ab5'")
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   - no dry run output for delete_unique_column() due to dynamic DDL, sorry
   = DROP TABLE `sentry_authidentity` CASCADE; []
   = DROP TABLE `sentry_authprovider` CASCADE; []

 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: sentry:0157_auto__add_authidentity__add_unique_authidentity_auth_provider_ident__a
Traceback (most recent call last):
  File "/var/www/sentry/bin/sentry", line 9, in <module>
    load_entry_point('sentry==7.4.0', 'console_scripts', 'sentry')()
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 420, in main
    initializer=initialize_app,
  File "/var/www/sentry/local/lib/python2.7/site-packages/logan/runner.py", line 169, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/management/commands/upgrade.py", line 34, in handle
    verbosity=options['verbosity'],
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/var/www/sentry/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 37, in new_execute
    return original_func(self, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 85, in run_migration
    south.db.db.execute_deferred_sql()
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/db/generic.py", line 318, in execute_deferred_sql
    self.execute(sql)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/var/www/sentry/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/sentry/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1825, "Failed to add the foreign key constraint on table 'sentry_authidentity'. Incorrect options in FOREIGN KEY constraint 'sentry/user_id_refs_id_78163ab5'")
(sentry)root@hrafninn:/var/www/sentry#

**Comment by dcramer** [comment]
What database engine is this?

**Comment by sixdays** [comment]
Oh, sorry. 

MySQL 5.6.19a running on RDS.
(ps. thx for a great system and an inspiring blog ;) )

**Comment by jagadeeshv16** [comment]
Hello,
     I am facing same issue here.

**Comment by zhyg** [comment]
Hi, same issue, MySQL version:
mysql  Ver 14.14 Distrib 5.6.22, for osx10.10 (x86_64) using  EditLine wrapper
thx

**Comment by dcramer** [comment]
You won't like this, but basically you'll have to update to 7.4.1, manually remove the added table(s), and then run upgrade.

drop table sentry_authidentity;
drop table sentry_authprovider;

**Comment by sixdays** [comment]
That's it! I'm going to swim from Europe straight over the ocean and insult you. In person ;) 

Thanks for a speedy resolve!
