### ISSUE TITLE
Cannot install using pip (CentOS 7)

### ISSUE THREAD

**Issue by MrMoronIV** [getsentry/sentry#14734]
```
python3 -m pip install -U virtualenv
virtualenv /sentry
source /sentry/bin/activate
pip install -U sentry
```

```
    ERROR: Command errored out with exit status 1:
     command: /sentry/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_w625ism/BeautifulSoup/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_w625ism/BeautifulSoup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-_w625ism/BeautifulSoup/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_w625ism/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

also tried using regular pip, which is python 2.7. Also tried `--no-cache-dir` flag but still the same error.

Started out with docker, but that just went horribly wrong with high load on server and had to reboot, docker has never been my favorite. I guess the package has to be updated by you guys for this bug to go away?

**Comment by untitaker** [comment]
You are using Python 3. If you have tried with Python 2.7 as well it will produce an entirely different error.

**Comment by MrMoronIV** [comment]
Hmmm, I did `virtualenv -p /usr/bin/python /sentry` now and it seems to be working
