### ISSUE TITLE
AttributeError in interfaces/http.py

### ISSUE THREAD

**Issue by wreckah** [getsentry/sentry#1513]
```python
[ERROR] Error processing 'to_curl' on 'Http': 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sentry/interfaces/http.py", line 218, in to_curl
    data = urlencode(format_body(data))
  File "/usr/local/lib/python2.7/dist-packages/sentry/interfaces/http.py", line 43, in format_body
    for k, v in value.iteritems()
  File "/usr/local/lib/python2.7/dist-packages/sentry/interfaces/http.py", line 43, in <genexpr>
    for k, v in value.iteritems()
AttributeError: 'NoneType' object has no attribute 'encode'
```

Commit: 8fce8b8382f0141f72e48666750b332b207dbdc0

**Comment by dcramer** [comment]
Improved how this is handled in cb2fb99d332394a20b070a5b4f8db589c30cbd4d

**Comment by rasca** [comment]
Just a similar same error in 7.5.0:

```
sentry.interfaces.http in <genexpr>
Error processing 'to_curl' on 'Http': 'bool' object has no attribute 'encode'

Stacktrace (most recent call last):

  File "sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "sentry/interfaces/http.py", line 222, in to_curl
    data = urlencode(format_body(data))
  File "sentry/interfaces/http.py", line 43, in format_body
    for k, v in value.iteritems()
  File "sentry/interfaces/http.py", line 43, in <genexpr>
    for k, v in value.iteritems()
```

**Comment by endelwar** [comment]
Just seen on 7.7.4
```
sentry.interfaces.http in <genexpr>
Error processing 'to_curl' on 'Http': 'dict' object has no attribute 'encode'

Stacktrace (most recent call last):

  File "sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "sentry/interfaces/http.py", line 222, in to_curl
    data = urlencode(format_body(data))
  File "sentry/interfaces/http.py", line 43, in format_body
    for k, v in value.iteritems()
  File "sentry/interfaces/http.py", line 43, in <genexpr>
    for k, v in value.iteritems()
```

**Comment by mattrobenolt** [comment]
You should upgrade to 8.0.0rc1. Pretty confident this issue doesn't exist there anymore.
