### ISSUE TITLE
The red event-count remains at 1 event though the graph shows many more events

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#1515]
For all my events the red counter shows a single record.  However many of them are produced several times.

The picture shows one of such cases.

![capture du 2015-04-28 11 46 44](https://cloud.githubusercontent.com/assets/270825/7373973/9f939b2e-ed9d-11e4-96b2-c35cf56432f2.png)

**Comment by dcramer** [comment]
I'm going to assume this is self-hosted? If so it's likely you're not running the workers correctly (i.e. celerybeat isnt running)

**Comment by mvaled** [comment]
Yes.  Self-hosted.  However when I restart the workers I see the following in the logs:

    [2015-04-28 15:45:27,093: ERROR/Beat] Removing corrupted schedule file 'celerybeat-schedule': DBAccessError(13, 'Permission denied')
    Traceback (most recent call last):
      File "/srv/sentry/local/lib/python2.7/site-packages/celery/beat.py", line 368, in setup_schedule
	writeback=True)
      File "/usr/lib/python2.7/shelve.py", line 239, in open
	return DbfilenameShelf(filename, flag, protocol, writeback)
      File "/usr/lib/python2.7/shelve.py", line 223, in __init__
	Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
      File "/usr/lib/python2.7/anydbm.py", line 85, in open
	return mod.open(file, flag, mode)
      File "/usr/lib/python2.7/dbhash.py", line 18, in open
	return bsddb.hashopen(file, flag, mode)
      File "/usr/lib/python2.7/bsddb/__init__.py", line 364, in hashopen
	d.open(file, db.DB_HASH, flags, mode)
    DBAccessError: (13, 'Permission denied')
    [ERROR] DbfilenameShelf instance has no attribute 'dict'
    Traceback (most recent call last):
      File "/srv/sentry/local/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform
	return repr(value)
      File "/srv/sentry/lib/python2.7/UserDict.py", line 172, in __repr__
	return repr(dict(self.iteritems()))
      File "/srv/sentry/lib/python2.7/UserDict.py", line 110, in iteritems
	for k in self:
      File "/srv/sentry/lib/python2.7/UserDict.py", line 97, in __iter__
	for k in self.keys():
      File "/usr/lib/python2.7/shelve.py", line 101, in keys
	return self.dict.keys()
    AttributeError: DbfilenameShelf instance has no attribute 'dict'

**Comment by dcramer** [comment]
That error is telling you "perrmission denied" on the "celerybeat-schedule" file. You need to fix the permissions or run it as the correct user.

**Comment by mvaled** [comment]
I didn't know about that file... Does it use the same `SENTRY_FILESTORE_OPTIONS`?

**Comment by dcramer** [comment]
It's nothing related to any of the Sentry settings. It's placed in the CWD when you run the celery command, and simply tracks when things were run

**Comment by mvaled** [comment]
I changed the [CELERYBEAT_SCHEDULE_FILENAME](http://celery.readthedocs.org/en/latest/configuration.html#celerybeat-schedule-filename) to a well known name and the error went away.  Thanks.

**Comment by mvaled** [comment]
Hi @dcramer, 

The same symptom:  Red counter remains at 1, but graph shows way more events.

![capture du 2015-07-15 10 05 09](https://cloud.githubusercontent.com/assets/270825/8700316/0dd414ce-2ad9-11e5-992b-bd311e91d788.png)

This time, however, the workers seem be to running fine (except for rate limiting events):

```
manu@m:~$ sudo tail -f /var/log/upstart/workers.log
[2015-07-15 13:45:57,974: INFO/Worker-3] Notification for project 6 dropped due to rate limiting
Notification for project 6 dropped due to rate limiting
[2015-07-15 13:46:19,334: INFO/Worker-3] Notification for project 6 dropped due to rate limiting
Notification for project 6 dropped due to rate limiting
[2015-07-15 13:46:20,222: INFO/Worker-2] Notification for project 6 dropped due to rate limiting
Notification for project 6 dropped due to rate limiting
[2015-07-15 13:46:20,874: INFO/Worker-3] Notification for project 6 dropped due to rate limiting
Notification for project 6 dropped due to rate limiting
[2015-07-15 13:46:21,796: INFO/Worker-2] Notification for project 6 dropped due to rate limiting
```
My sentry deployment is currently using commit 79f880e from a couple days ago.

**Comment by dcramer** [comment]
Your workers are not running correctly.  Most likely celerybeat is not running.
