### ISSUE TITLE
Fresh install has indexing errors

### ISSUE THREAD

**Issue by tvanrielwendrich** [getsentry/sentry#15256]
## Important Details

How are you running Sentry?
Docker `getsentry/sentry`

## Description
list index out of range errors

## Steps to Reproduce

1. install sentry.

Good items to include here include:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 227, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 212, in handle
    return super(AuthLoginView, self).handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 240, in handle
    return super(BaseView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 230, in get
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 161, in get_default
    return cls.objects.filter(status=OrganizationStatus.ACTIVE)[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 201, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

### What you expected to happen
that sentry would work in docker

### Possible Solution
a good error explaining why sentry isn't working, if my DB is wrong, or if I have made a huge mistake.

**Comment by tvanrielwendrich** [comment]
Seems like this might be related to https://github.com/getsentry/onpremise/issues/187.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

**Comment by dragon-yuan** [comment]
+1
