### ISSUE TITLE
After upgrade to 7.5.0 Sentry stopped save evenets.

### ISSUE THREAD

**Issue by Nihn** [getsentry/sentry#1538]
Hi, after upgarding from 7.4.3 to 7.5.0 event's aren't logged anymore. All of them come with project id = 1 which we don't have in our database.

**Comment by dcramer** [comment]
The default project generally ends up at id = 1. You can change this using SENTRY_PROJECT.

**Comment by Nihn** [comment]
@dcramer  Yes and i have set it to 22... And anyway no events come (I have 18 projects in my sentry with log with event rate ~500/minute.)

**Comment by dcramer** [comment]
You should check the workers. If events arent processing something isn't running/connecting correctly.

**Comment by Nihn** [comment]
Workers are running but it seems that they try to log everything after project 1.

**Comment by Nihn** [comment]
```
[2015-05-27 06:48:21,825: ERROR/MainProcess] Project matching query does not exist.
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 244, in save
    # default the culprit to the url
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 209, in get_from_cache
    result = self.get(**kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: Project matching query does not exist.
```

**Comment by Nihn** [comment]
I force it to work by:
downgrading sentry to 7.4.3
running sentry upgrade (which fails)
update to 7.5.1
restart only sentry (not workers)

and now events from other projects comming but logs are still full of these errors.

**Comment by dcramer** [comment]
It looks like there's an issue with the internal project not being at ID=1, but that is unrelated to your workers not processing other events

**Comment by Nihn** [comment]
Before upgrade internal Sentry events respected my SENTRY_PROJECT setting. I have some of them under right endpoint.

**Comment by dcramer** [comment]
You need to restart all services every time you upgrade Sentry. If you fail to restart something it will not only reference potentially invalid schema, but it will also run invalid code in memory. This can cause any number of obscure issues.

7.5.2 should fix SENTRY_PROJECT

**Comment by Nihn** [comment]
After upgrade there are errors:
```
[2015-05-27 07:16:40,240: ERROR/MainProcess] Task sentry.tasks.process_buffer.process_pending[5c286198-904f-43bc-9817-d19f23e39d80] raised unexpected: ResponseError("wrong number of arguments for 'set' command",)
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 25, in _wrapped
    result = func(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/tasks/process_buffer.py", line 22, in process_pending
    app.buffer.process_pending()
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/buffer/redis.py", line 92, in process_pending
    if not self.conn.set(lock_key, '1', nx=True, ex=60):
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../nydus/db/base.py", line 132, in __call__
    return self.__cluster.execute(self.__path, args, kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../nydus/db/base.py", line 78, in execute
    results.append(func(*args, **kwargs))
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 1055, in set
    return self.execute_command('SET', *pieces)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/connection.py", line 574, in read_response
    raise response
ResponseError: wrong number of arguments for 'set' command
```
I know it's bad solution but it is the only way I can still getting some events...

**Comment by Nihn** [comment]
@dcramer  All Redis settings are set according to documentation: https://sentry.readthedocs.org/en/latest/buffer/index.html#the-redis-backend
Still only way to make it works is to use old worker (7.4.3) with new sentry (7.5.2).

**Comment by Nihn** [comment]
Ok, it turned out that Redis was out of date. New sentry needs at least 2.6.12 when the one in Wheezy repo is 2.4.14

**Comment by dcramer** [comment]
Yeah. We didn't really call that out in the CHANGES file, I'll add that.
