### ISSUE TITLE
Unreported error

### ISSUE THREAD

**Issue by RDIL** [getsentry/sentry#15391]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [X] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I run sentry on my Flask server, and an error was thrown:
```none
2019-11-01 13:55:17  [sentry] DEBUG: Sending event, type:null level:error event_id:redacted project:redacted host:sentry.io
2019-11-01 13:55:17 2019-11-01 13:55:17,524 : ERROR : Exception on /redactedRoute [GET]#012Traceback (most recent call last):#012  File "site-packages/flask/app.py", line 2446, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/site-packages/flask/app.py", line 1951, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/site-packages/flask/app.py", line 1820, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/site-packages/flask/_compat.py", line 39, in reraise#012    raise value#012  File "/site-packages/flask/app.py", line 1949, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/site-packages/flask/app.py", line
2019-11-01 13:55:17 
2019-11-01 13:55:17  [sentry] INFO: event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x7f78f50cc598>) dropped event ({'level': 'error', 'exception': {'values': [{'module': None, 'type': 'TypeError', 'value': "func_obfuscated_7812789() missing 1 required positional argument: 'field_obfuscated_824998234'", 'mechanism': {'type': 'logging', 'handled': True}, 'stacktrace': {'frames': [{'filename': 'flask/app.py', 'abs_path': '/site-packages/flask/app.py', 'function': 'wsgi_app', 'module': 'flask.app', 'lineno': 2446, 'pre_context': ['        ctx = self.request_context(environ)', '        error = None', '        try:', '            try:', '                ctx.push()'], 'context_line': '                response = self.full_dispatch_request()', 'post_context': ['            except Exception as e:', '                error = e', '                response = self.handle_exception(e)', '            except:  # noqa: B001', '      
2019-11-01 13:55:17 
```
Yet my dashboard displays the yay no errors animation.
Please help!
And yes, I did redact some sensitive info

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

### What you expected to happen

I should see the error

**Comment by RDIL** [comment]
Oh it looks like it was because the release wasn't published
