### ISSUE TITLE
Ionic 4/Sentry Integration

### ISSUE THREAD

**Issue by ceaheart** [getsentry/sentry#15408]
I've already documented the following error in another post: 

Sentry: build path does not exist C:\Users\Chris{project name}\platforms\android\www
This is not an Ionic project, please check out:
https://docs.sentry.io/clients/javascript/sourcemaps/ 1
to find out how to correctly upload sourcemaps for your project.

My issue now is that adding Sentry to any Ionic 4 base project causes the build to fail.  I start getting really strange errors as soon as I add Sentry - 

:app:lintVitalReleaseError processing C:\Users\Chris\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.10.0\4e2c5fa04648ec9772c63e2101c53af6504e624e\jackson-core-2.10.0.jar:module-info.class: broken class file?

Exception in thread "main" java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at com.google.devtools.build.android.desugar.CoreLibraryRewriter.reader(CoreLibraryRewriter.java:44)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:388)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280) FAILED
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

Execution failed for task ':app:transformClassesWithDesugarForRelease'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\3.jar --output C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\desugar\release\5.jar --input C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\1.jar --output C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\desugar\release\3.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\CordovaLib\build\intermediates\intermediate-jars\release\classes.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\classes\release --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\0.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\1.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\2.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\3.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\4.jar --bootclasspath_entry C:\Users\Chris\AppData\Local\Android\sdk\platforms\android-27\android.jar --bootclasspath_entry C:\Users\Chris\AppData\Local\Android\sdk\platforms\android-27\optional\org.apache.http.legacy.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\resources.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\jsse.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\jce.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\charsets.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfr.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}

Again, this is just a simple Ionic 4 app, no customizations other than adding Sentry.

**Comment by HazAT** [comment]
Are you running Cordova 9?
We got a few reports that it’s not working there.
If so we need time to add support for it, in the meantime, please just use @sentry/browser to catch all js errors.
