### ISSUE TITLE
ImportError: No module named sentry.utils.distutils while doing pip install -e .

### ISSUE THREAD

**Issue by jonbesga** [getsentry/sentry#15446]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [X] Other [briefly describe your environment]

## Description

I'm following the [installation from source instructions](https://docs.sentry.io/development/contribute/environment/) because I'd like to start contributing to Sentry. I made my virtual environment for Python 2 using virtualenv but I noticed I'm unable to install the package

## Steps to Reproduce

1. pip install -e .

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
  ERROR: Command errored out with exit status 1:
   command: /home/jon/Projects/sentry-dev/sentry/.venv/bin/python2.7 /home/jon/Projects/sentry-dev/sentry/.venv/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpKmt9Vl
       cwd: /home/jon/Projects/sentry-dev/sentry
  Complete output (19 lines):
  Traceback (most recent call last):
    File "/home/jon/Projects/sentry-dev/sentry/.venv/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/jon/Projects/sentry-dev/sentry/.venv/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/jon/Projects/sentry-dev/sentry/.venv/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-yZv8cg/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-yZv8cg/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-yZv8cg/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-yZv8cg/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 46, in <module>
      from sentry.utils.distutils import (
  ImportError: No module named sentry.utils.distutils
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/jon/Projects/sentry-dev/sentry/.venv/bin/python2.7 /home/jon/Projects/sentry-dev/sentry/.venv/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpKmt9Vl Check the logs for full command output.
```

### What you expected to happen

I think the issue is be because the `ROOT` variable in setup.py is pointing to `/home/jon/Projects/sentry-dev/sentry/.venv/lib/python2.7/site-packages/pip/_vendor/pep517` instead of to the root of the package

### Possible Solution

Replace:

`ROOT = os.path.realpath(os.path.join(os.path.dirname(sys.modules["__main__"].__file__)))`

for:

`ROOT = os.path.realpath(os.path.join(os.path.dirname(__file__)))`

**Comment by jonbesga** [comment]
Okay, just realized the Makefile includes `PIP_OPTS := --no-use-pep517 --disable-pip-version-check` and it skips the problem.

**Comment by BYK** [comment]
@jonbesga so do you think this issue can be closed or there's still something needing to be fixed?
