### ISSUE TITLE
Error Creating the Config File

### ISSUE THREAD

**Issue by Galaxy42** [getsentry/sentry#1565]
When I run this command on Ubuntu 15.04:
 

> sudo sentry init /etc/sentry.conf.py

I get a traceback error, which says:

> Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: urllib3<1.8.0,>=1.7.1

What can I do?

**Comment by dcramer** [comment]
It's most likely that your python environment is not active or you've set it up different from the instructions.
