### ISSUE TITLE
null value in column "checksum" violates not-null constraint

### ISSUE THREAD

**Issue by BenGriffiths** [getsentry/sentry#1571]
I have installed sentry and I'm trying to post errors, however I keep getting an error in sentry.

Everything seems to work fine outside of the API - sentry caught errors for itself before I installed Postfix and it did that just fine.

The worker posts the following (Looks like it's not providing a checksum):

```
Error processing '_save_aggregate' on 'EventManager': null value in column "checksum" violates not-null constraint
DETAIL:  Failing row contains (33, php, 10, Here is some debug information, http://www.mysite.com/permission-manage..., null, 0, 1, 2015-06-24 17:19:55+00, 2015-06-24 17:19:55+00, null, 1435166395, 2, 0, 0, null, 2015-06-24 17:19:55+00, f, php, 0).
Traceback (most recent call last):
  File "/home/ben/sentry-master/src/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/home/ben/sentry-master/src/sentry/event_manager.py", line 439, in _save_aggregate
    **kwargs
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ben/sentry-master/src/sentry/models/group.py", line 147, in save
    super(Group, self).save(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
IntegrityError: null value in column "checksum" violates not-null constraint
DETAIL:  Failing row contains (33, php, 10, Here is some debug information, http://www.mysite.com/permission-manage..., null, 0, 1, 2015-06-24 17:19:55+00, 2015-06-24 17:19:55+00, null, 1435166395, 2, 0, 0, null, 2015-06-24 17:19:55+00, f, php, 0).

[2015-06-24 17:19:55,519: ERROR/Worker-2] Error processing '_save_aggregate' on 'EventManager': null value in column "checksum" violates not-null constraint
DETAIL:  Failing row contains (33, php, 10, Here is some debug information, http://www.mysite.com/permission-manage..., null, 0, 1, 2015-06-24 17:19:55+00, 2015-06-24 17:19:55+00, null, 1435166395, 2, 0, 0, null, 2015-06-24 17:19:55+00, f, php, 0).
Traceback (most recent call last):
  File "/home/ben/sentry-master/src/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/home/ben/sentry-master/src/sentry/event_manager.py", line 439, in _save_aggregate
    **kwargs
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ben/sentry-master/src/sentry/models/group.py", line 147, in save
    super(Group, self).save(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
IntegrityError: null value in column "checksum" violates not-null constraint
DETAIL:  Failing row contains (33, php, 10, Here is some debug information, http://www.mysite.com/permission-manage..., null, 0, 1, 2015-06-24 17:19:55+00, 2015-06-24 17:19:55+00, null, 1435166395, 2, 0, 0, null, 2015-06-24 17:19:55+00, f, php, 0).

[ERROR] Not capturing event due to unsafe stacktrace:
{'date': datetime.datetime(2015, 6, 24, 17, 19, 55, 519737), 'exc_info': (<class 'django.db.utils.IntegrityError'>, IntegrityError('null value in column "checksum" violates not-null constraint\nDETAIL:  Failing row contains (33, php, 10, Here is some debug information, http://www.mysite.com/permission-manage..., null, 0, 1, 2015-06-24 17:19:55+00, 2015-06-24 17:19:55+00, null, 1435166395, 2, 0, 0, null, 2015-06-24 17:19:55+00, f, php, 0).\n',), <traceback object at 0x7f35ff4a0320>), 'data': {'message': u'Error processing \'_save_aggregate\' on \'EventManager\': null value in column "checksum" violates not-null constraint\nDETAIL:  Failing row contains (33, php, 10, Here is some debug information, http://www.mysite.com/permission-manage..., null, 0, 1, 2015-06-24 17:19:55+00, 2015-06-24 17:19:55+00, null, 1435166395, 2, 0, 0, null, 2015-06-24 17:19:55+00, f, php, 0).\n', 'sentry.interfaces.Message': {'message': u'Error processing %r on %r: %s', 'params': ("'_save_aggregate'", "'EventManager'", 'IntegrityError(\'null value in column "checksum" violates not-null constraint\\nDETAIL:  Failing row contains (33, php, 10, Here is some debug information, http://www.mysite.com/permission-manage..., null, 0, 1, 2015-06-24 17:19:55+00, 2015-06-24 17:19:55+00, null, 1435166395, 2, 0, 0, null, 2015-06-24 17:19:55+00, f, php, 0).\\n\',)')}, 'logger': 'sentry', 'level': 40}, 'stack': None, 'extra': {'func_args': (), 'thread': 139870088959808, 'func_module': 'sentry.event_manager', 'process': 30598, 'threadName': 'MainThread', 'filename': 'safe.py', 'processName': 'Worker-2', 'pathname': '/home/ben/sentry-master/src/sentry/utils/safe.py', 'lineno': 46, 'asctime': '2015-06-24 17:19:55,519', 'func_kwargs': {'first_seen': datetime.datetime(2015, 6, 24, 17, 19, 55, tzinfo=<UTC>), 'culprit': u'http://www.mysite.com/permission-management', 'time_spent_count': 0, 'level': 10, 'message': u'Here is some debug information', 'tags': [[u'environment', u'alpha'], [u'server', u'alpha.elementaryhr.com'], ('level', 'debug'), ('logger', u'php'), ('server_name', u'Initial-Droplet'), ('site', u'alpha.elementaryhr.com'), ('browser', u'Safari 8.0'), ('device', 'Other'), ('os', u'Mac OS X 10.10.3'), ('url', u'http://www.mysite.com/permission-management')], 'event': <Event at 0x7f35fe627690: id=None, project_id=2L, group_id=None>, 'time_spent_total': 0, 'platform': u'php', 'hashes': ['15bc5369748ea2504ec1a88863283fd2'], 'logger': u'php', 'last_seen': datetime.datetime(2015, 6, 24, 17, 19, 55, tzinfo=<UTC>)}}}
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/ben/sentry-master/src/sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/home/ben/sentry-master/src/sentry/event_manager.py", line 339, in save
    **group_kwargs
TypeError: 'NoneType' object is not iterable
[2015-06-24 17:19:55,538: ERROR/Worker-2] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/ben/sentry-master/src/sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/home/ben/sentry-master/src/sentry/event_manager.py", line 339, in save
    **group_kwargs
TypeError: 'NoneType' object is not iterable
```

**Comment by dcramer** [comment]
That column no longer exists in master.

Did you upgrade but forget to perform the upgrade command?
