### ISSUE TITLE
UnicodeEncodeError when replaying a request with Chinese characters in data

### ISSUE THREAD

**Issue by messense** [getsentry/sentry#1595]
I have some Chinese characters in post data, when I replayed a request it ended up with UnicodeEncodeError. Traceback:

```
Traceback (most recent call last):
  File "/home/ops/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ops/venv/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 220, in wrapped
    return prv_func(request, organization_slug=organization_slug, project_id=project_id, group=group, *args, **kwargs)
  File "/home/ops/venv/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 236, in wrapped
    return func(request, *args, **kwargs)
  File "/home/ops/venv/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 182, in _wrapped
    return func(request, *args, **kwargs)
  File "/home/ops/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ops/venv/local/lib/python2.7/site-packages/sentry/web/frontend/events.py", line 64, in replay_event
    headers=form.cleaned_data['headers'],
  File "/home/ops/venv/local/lib/python2.7/site-packages/sentry/replays.py", line 37, in replay
    conn.request(self.method, full_url, data, self.headers or {})
  File "/usr/lib/python2.7/httplib.py", line 959, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 993, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 818, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 790, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 353-357: ordinal not in range(128)
```

**Comment by messense** [comment]
Since replay requests feature got removed, I am closing this.
