### ISSUE TITLE
[ERROR] Internal Server Error: /manage/teams/

### ISSUE THREAD

**Issue by ram-nadella** [getsentry/sentry#1600]
Seeing the Internal Server Error page when I navigate to /manage/teams/

Rest of the app appears to be working fine. Here is the backtrace:

```
[ERROR] Internal Server Error: /manage/teams/
Traceback (most recent call last):
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry-7.6.0-py2.7.egg/sentry/web/decorators.py", line 236, in wrapped
    return func(request, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry-7.6.0-py2.7.egg/sentry/web/decorators.py", line 245, in wrapped
    return func(request, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry-7.6.0-py2.7.egg/sentry/web/frontend/admin.py", line 283, in manage_teams
    }, request)
  File "/www/sentry/lib/python2.7/site-packages/sentry-7.6.0-py2.7.egg/sentry/web/helpers.py", line 126, in render_to_response
    response = HttpResponse(render_to_string(template, context, request))
  File "/www/sentry/lib/python2.7/site-packages/sentry-7.6.0-py2.7.egg/sentry/web/helpers.py", line 122, in render_to_string
    return loader.render_to_string(template, context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 140, in render
    return self._render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/www/sentry/lib/python2.7/site-packages/django_templatetag_sugar-1.0-py2.7.egg/templatetag_sugar/node.py", line 19, in render
    return self.function(context, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry-7.6.0-py2.7.egg/sentry/templatetags/sentry_helpers.py", line 224, in paginator
    result = paginate_func(request, queryset_or_list, per_page, endless=True)
  File "/www/sentry/lib/python2.7/site-packages/django_paging-0.2.5-py2.7.egg/paging/helpers.py", line 24, in paginate
    'paginator': paginator.get_context(page),
  File "/www/sentry/lib/python2.7/site-packages/django_paging-0.2.5-py2.7.egg/paging/paginators.py", line 87, in get_context
    paginator = self.page(page)
  File "/www/sentry/lib/python2.7/site-packages/django_paging-0.2.5-py2.7.egg/paging/paginators.py", line 73, in page
    _page = EndlessPage(list(self.object_list[bottom:top]), number, self)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/www/sentry/lib/python2.7/site-packages/Django-1.6.11-py2.7.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/www/sentry/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/www/sentry/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1055, "'sentry.sentry_team.organization_id' isn't in GROUP BY")
```

**Comment by dcramer** [comment]
Sounds like you haven't applied migrations. Definitely not seeing this in master, and I dont recall any recent changes.

**Comment by ram-nadella** [comment]
@dcramer I am running 7.6 which is what was installed by `pip install -U sentry[mysql]`.

The error is a MySQL error, and it's saying the a certain column is missing in the GROUP BY clause of the SQL statement. Not sure how this would be related to migrations and I ran `migrate` and everything checks out okay.

```
(sentry)-bash$ sentry --conf=/etc/sentry.conf.py migrate
Running migrations for django:
- Nothing to migrate.
 - Loading initial data for django.
Installed 0 object(s) from 0 fixture(s)
Running migrations for sentry:
- Nothing to migrate.
 - Loading initial data for sentry.
Installed 0 object(s) from 0 fixture(s)
Running migrations for nodestore:
- Nothing to migrate.
 - Loading initial data for nodestore.
Installed 0 object(s) from 0 fixture(s)
Running migrations for search:
- Nothing to migrate.
 - Loading initial data for search.
Installed 0 object(s) from 0 fixture(s)
Running migrations for social_auth:
- Nothing to migrate.
 - Loading initial data for social_auth.
Installed 0 object(s) from 0 fixture(s)
```

**Comment by dcramer** [comment]
It's not clear to me what's actually wrong here as we're not doing anything beyond Django's ORM. It's possible its generating an invalid query.

We're not MySQL users, so while I'll accept this might be broken, it's unlikely we'll be fixing it at this time.

**Comment by mattrobenolt** [comment]
plz reopen if this is still an issue.
