### ISSUE TITLE
setup.py contains imports to sentry which is not available since it's not installed yet

### ISSUE THREAD

**Issue by nymann** [getsentry/sentry#16137]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [X] Other [briefly describe your environment]

## Description
This issue is regarding `pip3 install git+https://github.com/getsentry/sentry.git`
The `setup.py` file contains an import reference to sentry itself which is not installed at that point: https://github.com/getsentry/sentry/blob/master/setup.py#L45
This results in:

```
Collecting git+https://github.com/getsentry/sentry
  Cloning https://github.com/getsentry/sentry to c:\users\REDACTED\appdata\local\temp\pip-req-build-y35fexby
  Running command git clone -q https://github.com/getsentry/sentry 'C:\Users\REDACTED\AppData\Local\Temp\pip-req-build-y35fexby'
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command REDACTEDout with exit status 1:
   command: 'c:\users\REDACTED\appdata\local\programs\python\python37-32\python.exe' 'c:\users\REDACTED\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\REDACTED\AppData\Local\Temp\tmpvkptp7lu'
       cwd: C:\Users\REDACTED\AppData\Local\Temp\pip-req-build-y35fexby
  Complete output (18 lines):
  Traceback (most recent call last):
    File "c:\users\REDACTED\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
      main()
    File "c:\users\REDACTED\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\REDACTED\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\REDACTED\AppData\Local\Temp\pip-build-env-31av2e9h\overlay\Lib\site-packages\setuptools\build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\REDACTED\AppData\Local\Temp\pip-build-env-31av2e9h\overlay\Lib\site-packages\setuptools\build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "C:\Users\REDACTED\AppData\Local\Temp\pip-build-env-31av2e9h\overlay\Lib\site-packages\setuptools\build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\REDACTED\AppData\Local\Temp\pip-build-env-31av2e9h\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 45, in <module>
      from sentry.utils.distutils import (
  ModuleNotFoundError: No module named 'sentry'
  ----------------------------------------
```
## Steps to Reproduce

1. `pip3 install git+https://github.com/getsentry/sentry.pip`

### What you expected to happen

`sentry` gets installed.

**Comment by joshuarli** [comment]
Hi! This should be fixed in https://github.com/getsentry/sentry/pull/16184.

If you look at the old PIP_OPTS in the Makefile, we were installing sentry with `--no-use-pep517` for a while now.

**Comment by mattrobenolt** [comment]
You’re also trying to use python 3.7 which is gonna fail for many other different ways. We still use python 2.7.

And lastly, it looks like you’re also trying to install on Windows, which is also unsupported. That may have an unknown set of other issues. @BYK might have more insights there though.

**Comment by BYK** [comment]
Unfortunately, Sentry won't work on Windows directly (w/o WSL or Docker) as it relies on certain libraries with C-bindings only available on Linux. UWSGI is the top one but there are other like libkafka etc. I tried this before and I don't recommend anyone else to try. Just use Docker based installs via https://github.com/getsentry/onpremise and save yourself some time and headaches :D
