### ISSUE TITLE
Add integration of personal account of bitbucket

### ISSUE THREAD

**Issue by FerumFlex** [getsentry/sentry#16208]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.2]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

[What happened]
I am trying to add integration sentry with bitbucket. Login and select personal account. But got this error in logs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 90, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 190, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/integrations/bitbucket/installed.py", line 22, in post
    data = BitbucketIntegrationProvider().build_integration(state)
  File "/usr/local/lib/python2.7/site-packages/sentry/integrations/bitbucket/integration.py", line 176, in build_integration
    'name': principal_data['username'],
KeyError: 'username'

```

## Steps to Reproduce
1. Go to settings
2. Open integrations 3rd party
3. Try to add bitbucket integration
4. Select personal account

### What you expected to happen
Should add my integration to sentry.

### Possible Solution
Use of .get

**Comment by FerumFlex** [comment]
it was fixed, just checked code base
