### ISSUE TITLE
mock-related error when running Sentry upgrade for v7.6.2

### ISSUE THREAD

**Issue by mwcz** [getsentry/sentry#1622]
$ pip install -U sentry
    ... all installs successful
    Cleaning up...
    $ sentry upgrade
    Traceback (most recent call last):
      File "/home/sentry/.virtualenvs/sentry/bin/sentry", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
        @_call_aside
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
        f(*args, **kwargs)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
        ws.require(__requires__)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'funcsigs' distribution was not found and is required by mock

It seems that `mock` doesn't declare its dependency on `funcsigs`.  This isn't a Sentry problem, but in case anyone else runs into the same problem, this solved it:

    $ pip install funcsigs

**Comment by aurium** [comment]
Can't understand... the problem persists.
```
(sentry)root@linux:~# pip install -U funcsigs
Requirement already up-to-date: funcsigs in /opt/sentry/lib/python2.7/site-packages
(sentry)root@linux:~# sentry init /opt/sentry/sentry.conf.py
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'funcsigs' distribution was not found and is required by mock
```

**Comment by dcramer** [comment]
Try uninstalling the lib and reinstalling. pip has issues sometimes

**Comment by aurium** [comment]
This is weird...
```
# pip uninstall mock
# pip uninstall funcsigs
# sentry init /opt/sentry/sentry.conf.py
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 5, in <module>
(...)
pkg_resources.DistributionNotFound: The 'funcsigs' distribution was not found and is required by mock
```
WTF!? It acts like if `mock` was installed.

```
# pip install mock
Collecting mock
/opt/sentry/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached mock-1.3.0-py2.py3-none-any.whl
Collecting funcsigs (from mock)
  Using cached funcsigs-0.4-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in /opt/sentry/lib/python2.7/site-packages (from mock)
Requirement already satisfied (use --upgrade to upgrade): six>=1.7 in /opt/sentry/lib/python2.7/site-packages (from mock)
Installing collected packages: funcsigs, mock
Successfully installed funcsigs-0.4 mock-1.3.0
# pip install funcsigs
Requirement already satisfied (use --upgrade to upgrade): funcsigs in /opt/sentry/lib/python2.7/site-packages
# sentry init /opt/sentry/sentry.conf.py
(...)
pkg_resources.DistributionNotFound: The 'funcsigs' distribution was not found and is required by mock
```
nop... :-(

**Comment by dcramer** [comment]
I'm not entirely sure. YOu should try reinstall the entire virtualenv possibly.

I also see you're running as root in the above which in general isnt a good practice so it's possible theres some conflicts there.

**Comment by aurium** [comment]
Ok. Trying it again...

**Comment by aurium** [comment]
Don't ask me way but it is working. :-)

I still using root, but i reinstall Sentry with pip. Nothing change on my process, so, i can't say where was the problem. :-/

**Comment by WillGhost** [comment]
just  `pip install funcsigs` It is works
