### ISSUE TITLE
Sentry upgrade 8.10-9.1.2 failed at migration 0291_merge_legacy_releases, TransactionManagementError

### ISSUE THREAD

**Issue by bwesen** [getsentry/sentry#16294]
Hi, I tried to upgrade Sentry 8.10 to 9.1.2, I'm using the docker container release.

I upgraded the containers and ran sentry upgrade and it processed a bunch of migrations until it stopped at 0291_merge_legacy_releases with the dreaded TransactionManagementError without further information... I read some previous issues about this during the 8.* development and failed migrations due to Python versions and regexps.. But this is now 9.* and I thought it had been solved :) 

Python version in the sentry docker image is 2.7.16.

There was a question if it was OK to prune some stale things, and it said I have to answer yes, so I did (see below).

I can rerun sentry upgrade, but it gives the same error again and again then..

```
root@a5eca4a5f0a5:/# sentry upgrade
14:15:52 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
14:15:56 [INFO] sentry.plugins.github: apps-not-configured
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for sentry:
 - Migrating forwards to 0472_auto__add_field_sentryapp_author.
 > sentry:0276_auto__add_field_user_session_nonce
 > sentry:0277_auto__add_commitfilechange__add_unique_commitfilechange_commit_filenam
 > sentry:0278_auto__add_releaseproject__add_unique_releaseproject_project_release__a
 > sentry:0279_populate_release_orgs_and_projects
Releases: 100% |#############################################################################################################################################################################################################################################| Time: 0:00:05
 > sentry:0280_auto__add_field_releasecommit_organization_id
 > sentry:0281_populate_release_commit_organization_id
 > sentry:0282_auto__add_field_releasefile_organization__add_field_releaseenvironment
 > sentry:0283_populate_release_environment_and_release_file_organization
Progress: 100% |#############################################################################################################################################################################################################################################| Time: 0:00:00
 > sentry:0284_auto__del_field_release_project__add_field_release_project_id__chg_fie
 > sentry:0285_auto__chg_field_release_project_id__chg_field_releasefile_project_id
 > sentry:0286_drop_project_fk_release_release_file
 > sentry:0287_auto__add_field_releaseproject_new_groups
 > sentry:0288_set_release_project_new_groups_to_zero
 > sentry:0289_auto__add_organizationavatar
 > sentry:0290_populate_release_project_new_groups
Releases: 100% |#############################################################################################################################################################################################################################################| Time: 0:00:01
 > sentry:0291_merge_legacy_releases
The following content types are stale and need to be deleted:

    sentry | dsymobject
    sentry | dsymsymbol
    sentry | dsymsdk
    sentry | globaldsymfile
    sentry | projectdsymfile
    sentry | dsymbundle

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 75, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 30, in _upgrade
    ignore_ghost_migrations=True,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 125, in handle_noargs
    management.call_command('south_migrate', **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/south_migrate.py", line 105, in handle
    ignore_ghosts=ignore_ghosts,
  File "/usr/local/lib/python2.7/site-packages/south/migration/__init__.py", line 231, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 291, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 132, in migrate
    result = self.run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 241, in run
    return super(Forwards, self).run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 92, in run_migration
    south.db.db.rollback_transaction()
  File "/usr/local/lib/python2.7/site-packages/south/db/generic.py", line 1046, in rollback_transaction
    transaction.leave_transaction_management(using=self.db_alias)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 78, in leave_transaction_management
    get_connection(using).leave_transaction_management()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 310, in leave_transaction_management
    "This code isn't under transaction management")
django.db.transaction.TransactionManagementError: This code isn't under transaction management
```

**Comment by bwesen** [comment]
Hm, I reran this a couple of times more and then suddenly it passed. So as I can't reproduce anymore, I can't give any more info on this and thus we might as well close it again...
