### ISSUE TITLE
sentry upgrade ImportError

### ISSUE THREAD

**Issue by TheRatG** [getsentry/sentry#16350]
## Important Details

How are you running Sentry?

* [ ] Other pip

## Description

Tried update sentry.

## Steps to Reproduce

```
pip install sentry --upgrade
pip install sentry-plugins --upgrade
sentry upgrade
```

```
09:47:52 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
Traceback (most recent call last):
  File "/www/sentry/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 164, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 29, in inner
    configure()
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 127, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 153, in configure
    skip_service_validation=skip_service_validation,
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 306, in initialize_app
    django.setup()
  File "/www/sentry/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/www/sentry/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/www/sentry/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry_plugins/hipchat_ac/models.py", line 380, in <module>
    from .plugin import disable_plugin_for_tenant
  File "/www/sentry/local/lib/python2.7/site-packages/sentry_plugins/hipchat_ac/plugin.py", line 8, in <module>
    from sentry.plugins import plugins
ImportError: cannot import name plugins
```

**Comment by BYK** [comment]
If this is for the latest version of Sentry, `sentry-plugins` are now baked into the main package and trying to install the `sentry-plugins` package will cause issues like this.

**Comment by TheRatG** [comment]
Ok, thanks. I suppose it's quite impossible to use pip sentry now, too many dependencies like snuba, clickhouse. I will try to install and use onpremise.

**Comment by BYK** [comment]
>Ok, thanks. I suppose it's quite impossible to use pip sentry now, too many dependencies like snuba, clickhouse.

Not impossible but it is a lot more involved. Hope the on-premise setup helps you get up and running. Please let us know if you encounter any issues.
