### ISSUE TITLE
Update Requests Library

### ISSUE THREAD

**Issue by passitor** [getsentry/sentry#1650]
I am attempting to install Sentry on a FreeBSD 10.1 machine, which does not support SSLv3. However, it appears that the version of requests that is installed with a `pip install sentry` is using an old urllib3 version that breaks when it cannot find SSLv3.

```
Traceback (most recent call last):
  File "/opt/sentry/env/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/sentry/env/lib/python2.7/site-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/opt/sentry/env/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/opt/sentry/env/lib/python2.7/site-packages/pip/download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "/opt/sentry/env/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/opt/sentry/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 70, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

Apparently this has been fixed in more recent versions, but sentry's setup.py limits requests to `<2.6.0`. Is it possible for this to be changed to a more recent version?

As another benefit, the 2.7 branch of requests uses a new [release process](http://docs.python-requests.org/en/latest/community/release-process/) that may make maintaining that dependency more straightforward for the Sentry team.

**Comment by dcramer** [comment]
We can bump the version but we always will lock to aminor release

Happy to know which version of Requests addresses this? Alternatively I'll probably try the latest and ensure we have no issues there.
