### ISSUE TITLE
DB::Exception: Unknown field found while parsing JSONEachRow format: _tags_flattened

### ISSUE THREAD

**Issue by omaraltayyan** [getsentry/sentry#16718]
## Important Details

How are you running Sentry?

On-Premise docker [Version 10.0.0]

Docker version 18.09.7, build 2d0083d
docker-compose version 1.25.0, build 0a186604

## Description

an exception is being raised continually in the `sentry_onpremise_snuba-consumer_1` container

## Steps to Reproduce

1. installed sentry on an AWS EC2 instance, starting with version 10 right away
2. attempted to run ./install.sh a few days after installation (to update slack integration)
3. one of the snuba consumer containers goes through a boot loop showing the following exception:

i tried running ./install.sh again but it didn't help

```
+ '[' consumer = bash ']'
+ '[' c = - ']'
+ '[' consumer = api ']'
+ snuba consumer --help
+ set -- snuba consumer --auto-offset-reset=latest --max-batch-time-ms 750
+ exec gosu snuba snuba consumer --auto-offset-reset=latest --max-batch-time-ms 750
2020-01-30 08:27:22,672 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 312}
2020-01-30 08:27:23,671 Flushing 693 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=312, hi=1004)}): forced:False size:False time:True
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 11, in <module>
    load_entry_point('snuba', 'console_scripts', 'snuba')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 160, in consumer
    consumer.run()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 137, in run
    self._run_once()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 142, in _run_once
    self._flush()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 233, in _flush
    self.worker.flush_batch(self.__batch_results)
  File "/usr/src/snuba/snuba/consumer.py", line 98, in flush_batch
    self.__writer.write(inserts)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 95, in write
    raise ClickHouseError(int(code), type, message)
snuba.clickhouse.http.ClickHouseError: [117] DB::Exception: Unknown field found while parsing JSONEachRow format: _tags_flattened: (at row 1)
```

some other values in the installation logs:

```
[WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
08:22:59 [INFO] sentry.plugins.github: apps-not-configured
^[[36;1mOperations to perform:^[[0m
^[[1m  Apply all migrations: ^[[0madmin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
^[[36;1mRunning migrations:^[[0m
  Applying sentry.0027_exporteddata...^[[32;1m OK^[[0m
Creating missing DSNs
Correcting Group.num_comments counter
Cleaning up...
```

```
reparing to unpack .../sensible-utils_0.0.12_all.deb ...
Unpacking sensible-utils (0.0.12) ...
Setting up cron (3.0pl1-134+deb10u1) ...
Selecting previously unselected package cron.
Preparing to unpack .../cron_3.0pl1-134+deb10u1_amd64.deb ...
Unpacking cron (3.0pl1-134+deb10u1) ...
Adding group `crontab' (GID 101) ...
Setting up sensible-utils (0.0.12) ...
Done.
Setting up cron (3.0pl1-134+deb10u1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Adding group `crontab' (GID 101) ...
Done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Removing intermediate container 26811ceb1526
```

i didn't include the whole log since everything else is just regular docker image building and pulling.

### What you expected to happen
containers to work normally

### Possible Solution

possibly some data migration or removal is required? i don't mind losing data about events since we are still in a testing phase.

**Comment by omaraltayyan** [comment]
the issue disappeared after doing a git pull and running ./install.sh again, the on-premise should really consider doing a git-pull while running the install script, but i guess that's not an issue for this repo
