### ISSUE TITLE
Migration Error upgrading from 7.4.3 to 7.7.0

### ISSUE THREAD

**Issue by LeaFin** [getsentry/sentry#1672]
I got this Migration Error:
<code>
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for django:
- Nothing to migrate.
 - Loading initial data for django.
Installed 0 object(s) from 0 fixture(s)
Running migrations for sentry:
 - Migrating forwards to 0190_auto__add_field_release_new_groups.
 > sentry:0166_auto__chg_field_user_id__add_field_apikey_allowed_origins
 > sentry:0167_auto__add_field_authprovider_flags
 > sentry:0168_unfill_projectkey_user
 - Migration 'sentry:0168_unfill_projectkey_user' is marked for no-dry-run.
 > sentry:0169_auto__del_field_projectkey_user
 > sentry:0170_auto__add_organizationmemberteam__add_unique_organizationmemberteam_te
FATAL ERROR - The following SQL query failed: ALTER TABLE `sentry_organizationaccessrequest` ADD CONSTRAINT `team_id_refs_id_ea6e538b` FOREIGN KEY (`team_id`) REFERENCES `sentry_team` (`id`);
The error was: (1005, "Can't create table 'db_sentry.#sql-1189_10c431' (errno: 150)")
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   - no dry run output for delete_foreign_key() due to dynamic DDL, sorry
   = ALTER TABLE `sentry_organizationmember_teams` DROP COLUMN `is_active` CASCADE; []
   - no dry run output for delete_foreign_key() due to dynamic DDL, sorry
   = ALTER TABLE `sentry_organization` DROP COLUMN `flags` CASCADE; []
   - no dry run output for delete_unique_column() due to dynamic DDL, sorry
   = DROP TABLE `sentry_organizationaccessrequest` CASCADE; []

 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: sentry:0170_auto__add_organizationmemberteam__add_unique_organizationmemberteam_te
The following content types are stale and need to be deleted:

    sentry | grouptag
    sentry | searchtoken
    sentry | projectcountbyminute
    sentry | searchdocument
    sentry | groupcountbyminute

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/home/www-data/sentry/env/bin/sentry", line 9, in <module>
    load_entry_point('sentry==7.7.0', 'console_scripts', 'sentry')()
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 448, in main
    initializer=initialize_app,
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/logan/runner.py", line 193, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/management/commands/upgrade.py", line 34, in handle
    verbosity=options['verbosity'],
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/migration/migrators.py", line 85, in run_migration
    south.db.db.execute_deferred_sql()
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/db/generic.py", line 318, in execute_deferred_sql
    self.execute(sql)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/www-data/sentry/env/local/lib/python2.7/site-packages/sentry/../MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1005, "Can't create table 'db_sentry.#sql-1189_10c431' (errno: 150)")
</code>

**Comment by dcramer** [comment]
To be honest, I'm not sure. We're not officially supporting MySQL on the Sentry team so I'm closing this out. If you find a solution and we can contribute it upstream let me know as we're happy to get it more stable.
