### ISSUE TITLE
pip install sentry==9.1.2 more_itertools/more.py yield from iterable SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by patsevanton** [getsentry/sentry#17232]
cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

sudo yum install -y epel-release rpmdevtools mc
sudo yum install -y python2-pip 
pip install sentry==9.1.2

```
Collecting more-itertools>=4.0.0 (from pytest<3.6.0,>=3.5.0->sentry==9.1.2)
  Downloading https://files.pythonhosted.org/packages/a0/47/6ff6d07d84c67e3462c50fa33bf649cda859a8773b53dc73842e84455c05/more-itertools-8.2.0.tar.gz (82kB)
    100% |████████████████████████████████| 92kB 9.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-90Mqui/more-itertools/setup.py", line 5, in <module>
        from more_itertools import __version__
      File "more_itertools/__init__.py", line 1, in <module>
        from .more import *  # noqa
      File "more_itertools/more.py", line 480
        yield from iterable
                 ^
    SyntaxError: invalid syntax
```

**Comment by patsevanton** [comment]
![image](https://user-images.githubusercontent.com/10828883/75093935-8f991200-55b0-11ea-9177-f61572947b83.png)

**Comment by mattrobenolt** [comment]
I know this might sound misleading, but I think this is because your version of pip is way too old. 8.1.2 is ancient in Python years. I’d suggest updating that because the error you have shouldn’t be a problem and I think newer pip handles it correctly.
