### ISSUE TITLE
You're trying to run a very old release of Beautiful Soup under Python 3

### ISSUE THREAD

**Issue by patsevanton** [getsentry/sentry#17231]
cat /etc/redhat-release 
Fedora release 31 (Thirty One)

python --version
Python 3.7.4

```
pip install --user sentry
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9giqaq7r/BeautifulSoup/setup.py", line 3
        "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."
                                                                                                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9giqaq7r/BeautifulSoup/
```

**Comment by untitaker** [comment]
Sentry requires python 2

**Comment by patsevanton** [comment]
Ok. Thanks!
