### ISSUE TITLE
django.db.utils.ProgrammingError: (1146, "Table 'sentry.south_migrationhistory' doesn't exist")

### ISSUE THREAD

**Issue by iiiusky** [getsentry/sentry#17309]
## Important Details

How are you running Sentry?

* [ ] Saas (sentry.io)
* [ ] On-Premise docker [Version xyz]
* [x] Other [briefly describe your environment]

## Description

[What happened]

## Steps to Reproduce

```
(sentry) root@blog:~/.sentry# sentry upgrade
14:20:19 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
14:20:22 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/root/sentry/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/root/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 164, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/root/sentry/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/sentry/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/sentry/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/sentry/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/sentry/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/root/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/sentry/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 168, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/root/sentry/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 121, in _upgrade
    _migrate_from_south(verbosity)
  File "/root/sentry/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 93, in _migrate_from_south
    if not _has_south_history(connection):
  File "/root/sentry/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 80, in _has_south_history
    cursor.execute("SELECT 1 FROM south_migrationhistory LIMIT 1")
  File "/root/sentry/lib/python2.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 467, in execute
    return real_execute(self, sql, params)
  File "/root/sentry/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/sentry/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/sentry/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/root/sentry/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/root/sentry/lib/python2.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/sentry/lib/python2.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/sentry/lib/python2.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'sentry.south_migrationhistory' doesn't exist")

```

**Comment by MichaelIT** [comment]
any update?

**Comment by iiiusky** [comment]
> any update?

My first installation》

**Comment by lc273734858** [comment]
I have the same error

**Comment by jorpiell** [comment]
Same error here

**Comment by 77629296** [comment]
Same error here

**Comment by ZoneForZero** [comment]
I have the same error

**Comment by tzq582905** [comment]
You are now resolved?

**Comment by lc273734858** [comment]
> You are now resolved?

no...

**Comment by saifelse** [comment]
AFAIK based on https://forum.sentry.io/t/still-does-not-support-mysql/1483 , Sentry wasn't intended to run on MySQL only Postgres. The function that is erroring in `src/sentry/runner/commands/upgrade.py`:
```py
def _has_south_history(connection):
    cursor = connection.cursor()
    try:
        cursor.execute("SELECT 1 FROM south_migrationhistory LIMIT 1")
    except ProgrammingError as exc:
        if 'relation "south_migrationhistory" does not exist' in six.text_type(exc):
            return False
        raise
    return True
```

Is targeting a specific error message returned by postgres:
> relation "south_migrationhistory" does not exist

It looks like MySQL is returning a similar, but different error of:
> Table 'sentry.south_migrationhistory' doesn't exist

Changing the function to have:
```py
        if "Table 'sentry.south_migrationhistory' doesn't exist" in six.text_type(exc):
            return False
```

might fix your issue, but who knows what else will go wrong...

**Comment by BYK** [comment]
Please follow the issue template and provide as much information as possible. Closing as this issue is woefully incomplete and not actionable in its current state.

@saifelse - thanks for the useful info.

**Comment by frank0718** [comment]
same error ， wtf！！

**Comment by frank0718** [comment]
after sentry init 
USE sentry django migrate  

NOT sentry upgrade

**Comment by tzq582905** [comment]
> after sentry init
> USE sentry django migrate
> 
> NOT sentry upgrade

thx , i will try
