### ISSUE TITLE
[ERROR] celery.worker.job: Task sentry.tasks.email.send_email[8449f284-71a7-4c3c-b829-6499741857a5] raised unexpected: gaierror(-2, 'Name or service not known') (data={u'hostname': 'celery@sentry-worker-667fc658b9-258k2', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f56f686bb10>}", u'id': '8449f284-71a7-4c3c-b829-6499741857a5'})

### ISSUE THREAD

**Issue by hector-ruiz** [getsentry/sentry#17327]
I have this error, on k8s using a chart of helm:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 155, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 150, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/email.py", line 76, in send_email
    send_messages([message])
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/email.py", line 436, in send_messages
    sent = connection.send_messages(messages)
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 48, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python2.7/smtplib.py", line 317, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python2.7/smtplib.py", line 292, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
21:58:25 [ERROR] celery.worker.job: Task sentry.tasks.email.send_email[27163b96-9e64-4f6d-bfb8-02614c88d356] raised unexpected: gaierror(-2, 'Name or service not known') (data={u'hostname': 'celery@sentry-worker-667fc658b9-258k2', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f56f686ba50>}", u'id': '27163b96-9e64-4f6d-bfb8-02614c88d356'})

**Comment by mattrobenolt** [comment]
This error is just simply saying it can't resolve the DNS record for your SMTP server. I don't know why that is or what you're doing, but you should start there. It's unrelated to sentry though.

**Comment by hector-ruiz** [comment]
Thanks!
