### ISSUE TITLE
Much events, but no events...

### ISSUE THREAD

**Issue by Stayallive** [getsentry/sentry#1762]
I seem to have a wierd issue after the update to 7.7.0.

![image](https://cloud.githubusercontent.com/assets/1090754/9248471/5ea53898-41bc-11e5-912e-20d5c34b7f8c.png)

When looking at the dashboard there are no error, just a few resolved ones. Also no muted errors...

When I resolved the unresolved errors (which all have 1 at the count) the amount of events dropped from 180k to 50k...

I have no clue what to do... sentry runs fine, except it's eating my CPU like a madman. I tried clearing Redis and restarting the services (multiple times). Any clue on where to look?

**Comment by dcramer** [comment]
I can't see how the charts would be wrong. You may check your logs as it's likely the Sentry project really is generating a lot of errors.

**Comment by Stayallive** [comment]
@dcramer Yes that is exactly what is happening, checked the logs and it's spamming the following at an alarming rate. Any clue on what I can do?

```
ResponseError: Command # 7 (ZADD b:p b:k:sentry.group:6b17068df4215c38e77f89a569c9b119 1439564924.3) of pipeline caused error: value is not a valid float
[2015-08-14 15:08:44,340: ERROR/Worker-3] Error processing '_save_aggregate' on 'EventManager': Command # 7 (ZADD b:p b:k:sentry.group:6b17068df4215c38e77f89a569c9b119 1439564924.3) of pipeline caused error: value is not a valid float
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 521, in _save_aggregate
    is_regression = self._process_existing_aggregate(group, event, kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 584, in _process_existing_aggregate
    }, extra)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/buffer/redis.py", line 94, in incr
    pipe.execute()
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 2492, in _execute_transaction
    self.raise_first_error(commands, response)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 2526, in raise_first_error
    raise r
ResponseError: Command # 7 (ZADD b:p b:k:sentry.group:6b17068df4215c38e77f89a569c9b119 1439564924.3) of pipeline caused error: value is not a valid float
[ERROR] Not capturing event due to unsafe stacktrace:
{'date': datetime.datetime(2015, 8, 14, 15, 8, 44, 340485), 'exc_info': (<class 'redis.exceptions.ResponseError'>, ResponseError(u'Command # 7 (ZADD b:p b:k:sentry.group:6b17068df4215c38e77f89a569c9b119 1439564924.3) of pipeline caused error: value is not a valid float',), <traceback object at 0x7f77e58ab098>), 'data': {'message': u"Error processing '_save_aggregate' on 'EventManager': Command # 7 (ZADD b:p b:k:sentry.group:6b17068df4215c38e77f89a569c9b119 1439564924.3) of pipeline caused error: value is not a valid float", 'sentry.interfaces.Message': {'message': u'Error processing %r on %r: %s', 'params': ("'_save_aggregate'", "'EventManager'", "ResponseError(u'Command # 7 (ZADD b:p b:k:sentry.group:6b17068df4215c38e77f89a569c9b119 1439564924.3) of pipeline caused error: value is not a valid float',)")}, 'logger': 'sentry', 'level': 40}, 'stack': None, 'extra': {'func_args': (), 'thread': 140153043871552, 'func_module': 'sentry.event_manager', 'process': 13448, 'threadName': 'MainThread', 'filename': 'safe.py', 'processName': 'Worker-3', 'pathname': '/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/safe.py', 'lineno': 46, 'asctime': '2015-08-14 15:08:44,340', 'func_kwargs': {'first_seen': datetime.datetime(2015, 8, 14, 15, 7, 22, tzinfo=<UTC>), 'logger': u'sentry', 'culprit': u'sentry.event_manager in save', 'time_spent_count': 0, 'level': 40, 'message': u"'NoneType' object is not iterable", 'time_spent_total': 0, 'platform': u'python', 'hashes': ['d0dea1756e90c8263647b5e7b60f880e'], 'event': <Event at 0x7f77e83a99d0: id=None, project_id=1L, group_id=None>, 'last_seen': datetime.datetime(2015, 8, 14, 15, 7, 22, tzinfo=<UTC>)}}}
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 383, in save
    **group_kwargs
TypeError: 'NoneType' object is not iterable
[2015-08-14 15:08:44,345: ERROR/Worker-3] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 383, in save
    **group_kwargs
TypeError: 'NoneType' object is not iterable
```

**Comment by mattrobenolt** [comment]
What version of redis are you using?

**Comment by mattrobenolt** [comment]
And redis-py, for that matter. I'm pretty sure I know what's wrong, but want to confirm. :)

**Comment by mattrobenolt** [comment]
It's related to this change: https://github.com/getsentry/sentry/commit/328ead0ccad4cd1e9385716d221fede899d6e156

**Comment by Stayallive** [comment]
@mattrobenolt: `redis_version:2.8.4` and for redis-py I believe `2.10.3` (got that for `pip show redis`, not sure how to see the version else :innocent:).

**Comment by mattrobenolt** [comment]
It seems like something is conflicting here. Either you're running the wrong version of nydus or your workers are still on 7.5.x, or some weird combination of this. :confused:

**Comment by mattrobenolt** [comment]
What it seems like to me is that you're running the newer version of nydus (0.11.x), but an older version of the worker code.

**Comment by Stayallive** [comment]
Any clues on how to fix this... I restarted the workers multiple times and upgraded sentry & packages multiple times (with and without sentry running)... I have no clue what to do else...

**Comment by dcramer** [comment]
It could be an issue with Nydus, though unlikely as you'd have to try hard to install the wrong dependencies. Reinstall the dependencies per the instructions to confirm.

pip freeze | grep nydus

**Comment by Stayallive** [comment]
Reinstalled everything with `pip install -U sentry --force-reinstall`.

One issue resolved at least...

![image](https://cloud.githubusercontent.com/assets/1090754/9283570/176363fa-42d5-11e5-92b8-328a9d8f6dce.png)

I can see the events pooring in now... but yeah... they are still pooring in...

`pip freeze | grep nydus` => `nydus==0.11.0`
