### ISSUE TITLE
sentry cleanup - IntegrityError

### ISSUE THREAD

**Issue by romanlv** [getsentry/sentry#1785]
after upgrading to version 7.7.0
added cron task `sentry --config=/opt/sentry/conf/sentry.conf.py cleanup --days=30`  (didn't have it in 6.x)

getting error: 

```
...
Removing TagValue for days=30 project=*
Removing Alert for days=30 project=*
Traceback (most recent call last):
  File "/opt/sentry/virtualenv/bin/sentry", line 9, in <module>
    load_entry_point('sentry==7.7.0', 'console_scripts', 'sentry')()
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/sentry-7.7.0-py2.7.egg/sentry/utils/runner.py", line 448, in main
    initializer=initialize_app,
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/logan/runner.py", line 193, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/raven-5.5.0-py2.7.egg/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/sentry-7.7.0-py2.7.egg/sentry/management/commands/cleanup.py", line 155, in handle
    self.bulk_delete(model, dtfield)
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/sentry-7.7.0-py2.7.egg/sentry/management/commands/cleanup.py", line 93, in bulk_delete
    self._postgres_bulk_speed_delete(model, dtfield, days=days)
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/sentry-7.7.0-py2.7.egg/sentry/management/commands/cleanup.py", line 87, in _postgres_bulk_speed_delete
    chunk_size=chunk_size,
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/sentry/virtualenv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 51, in execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: update or delete on table "sentry_alert" violates foreign key constraint "alert_id_refs_id_318c5c87" on table "sentry_alertrelatedgroup"
DETAIL:  Key (id)=(1) is still referenced from table "sentry_alertrelatedgroup".
```

**Comment by dcramer** [comment]
That table should no longer exist. Did you run 'upgrade' ?

**Comment by romanlv** [comment]
Yes, I run 'upgrade'

**Comment by dcramer** [comment]
jk we still have that table

**Comment by dcramer** [comment]
You can truncate the sentry_alert and sentry_alertrelatedgroup tables
