### ISSUE TITLE
set-commits fails intermittently

### ISSUE THREAD

**Issue by thomasheartman** [getsentry/sentry#17973]
Hi! 

First off, not sure whether this goes to the community forums or here, but the more I flesh this out, the more it feels like a bug. Feel free to tell me otherwise if you disagree.

# Problem

I've got an issue where the `set-commits` command of the Sentry-CLI fails fairly often, but not always. We run it from CI on our self-hosted GitLab server, and this goes both for the pure CLI version and the webpack plugin. We use on on-prem Sentry solution.

Because it only fails sometimes, I can't reproduce it reliably, and right now, I'm unable to trigger an error with debug level logging. However, here's the error log I do get (log level: info):

```
> Analyzing 3 sources
> Rewriting sources
> Adding source map references
> Bundled 3 files for upload
> Uploaded release files to Sentry
error: API request failed
  caused by: [56] Failure when receiving data from the peer
(node:261) UnhandledPromiseRejectionWarning: Error: Command failed: /builds/<group>/<subgroup>/<project>/node_modules/@sentry/cli/sentry-cli releases set-commits vmprov@a37b3c23dc81f9604b8d9be211ac2c3d8a885d09 --auto
  INFO    2020-03-27 16:56:34.398052283 +00:00 Loaded config from /builds/<group>/<subgroup>/<project>/.sentryclirc
  INFO    2020-03-27 16:56:34.398113291 +00:00 sentry-cli was invoked with the following command line: "/builds/<group>/<subgroup>/<project>/node_modules/@sentry/cli/sentry-cli" "releases" "set-commits" "vmprov@a37b3c23dc81f9604b8d9be211ac2c3d8a885d09" "--auto"
  INFO    2020-03-27 16:56:34.453539552 +00:00 Resolving HEAD (<other project>@HEAD)
  INFO    2020-03-27 16:56:34.458569383 +00:00 Resolving HEAD (<this project>@HEAD)
  INFO    2020-03-27 16:56:34.458912792 +00:00   -> found matching revision a37b3c23dc81f9604b8d9be211ac2c3d8a885d09
error: API request failed
  caused by: [56] Failure when receiving data from the peer
    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It's the same error that appears every time:
```
error: API request failed
  caused by: [56] Failure when receiving data from the peer
```
But I don't know what to do about it.

-----

If you need more information, just let me know, and I will do my best to get you what you need.

Thanks!

**Comment by thomasheartman** [comment]
Thanks for moving the issue! 

So it sounds as if the issue might lie with our internal setup, then. I'll keep watching this and see what comes up. For now, I can only wait for another one to fail (as it's only sometimes), but I've set the logs to debug, so when it does, I should have a better idea of what happened.

Thank you!

**Comment by thomasheartman** [comment]
Just a little update on my part here. After setting the log level to debug, we encountered the issue again. I'm pasting the last part of the logs below in the hopes that it might help.

<details>
<summary>Debug logs</summary>

```
 +00:00 request POST https://sentry.<company>.tld/api/0/projects/<company>/<project>/releases/
  DEBUG   2020-04-14 09:37:22.293936015 +00:00 using token authentication
  DEBUG   2020-04-14 09:37:22.293950327 +00:00 json body: {"version":"<project>@6c3e5a97c94bd19437c841f716c00af1238aeada","projects":["<project>"]}
  DEBUG   2020-04-14 09:37:22.293959557 +00:00 retry number 0, max retries: 0
  DEBUG   2020-04-14 09:37:22.294078559 +00:00 > POST /api/0/projects/<company>/<project>/releases/ HTTP/1.1
  DEBUG   2020-04-14 09:37:22.294090457 +00:00 > Host: sentry.<company>.tld
  DEBUG   2020-04-14 09:37:22.294095539 +00:00 > Accept: */*
  DEBUG   2020-04-14 09:37:22.294100465 +00:00 > Connection: TE
  DEBUG   2020-04-14 09:37:22.294105286 +00:00 > TE: gzip
  DEBUG   2020-04-14 09:37:22.294110289 +00:00 > User-Agent: sentry-cli/1.52.1
  DEBUG   2020-04-14 09:37:22.294128396 +00:00 > Authorization: Bearer <token>
  DEBUG   2020-04-14 09:37:22.294137790 +00:00 > Content-Type: application/json
  DEBUG   2020-04-14 09:37:22.294144034 +00:00 > Content-Length: 91
+-----------------------------------------------+
| Repository                     | Revision     |
+-----------------------------------------------+
| <group> / <subgroup> / <repo>  | 6c3e5a97c94b |
+-----------------------------------------------+
  DEBUG   2020-04-14 09:37:22.348490070 +00:00 < HTTP/1.1 208 Unknown Status Code
  DEBUG   2020-04-14 09:37:22.348521798 +00:00 < Content-Length: 612
  DEBUG   2020-04-14 09:37:22.348533635 +00:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization
  DEBUG   2020-04-14 09:37:22.348540140 +00:00 < X-Content-Type-Options: nosniff
  DEBUG   2020-04-14 09:37:22.348546271 +00:00 < Content-Language: en
  DEBUG   2020-04-14 09:37:22.348552052 +00:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2020-04-14 09:37:22.348557524 +00:00 < Vary: Accept-Language, Cookie
  DEBUG   2020-04-14 09:37:22.348563004 +00:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2020-04-14 09:37:22.348568265 +00:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2020-04-14 09:37:22.348573766 +00:00 < Access-Control-Allow-Origin: <origins>
  DEBUG   2020-04-14 09:37:22.348579411 +00:00 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2020-04-14 09:37:22.348585583 +00:00 < Content-Type: application/json
  DEBUG   2020-04-14 09:37:22.348590870 +00:00 < X-Frame-Options: deny
  DEBUG   2020-04-14 09:37:22.348609810 +00:00 response status: 208
  DEBUG   2020-04-14 09:37:22.348622432 +00:00 body: {"dateReleased":null,"newGroups":0,"commitCount":0,"url":null,"data":{},"lastDeploy":null,"deployCount":0,"dateCreated":"2020-04-14T09:37:22.154449Z","lastEvent":null,"version":"<project>@6c3e5a97c94bd19437c841f716c00af1238aeada","firstEvent":null,"lastCommit":null,"shortVersion":"<project>@6c3e5a97c94bd19437c841f716c00af1238aeada","authors":[],"owner":null,"versionInfo":{"buildHash":"6c3e5a97c94bd19437c841f716c00af1238aeada","version":{"raw":"6c3e5a97c94bd19437c841f716c00af1238aeada"},"description":"6c3e5a97c94b","package":"<project>"},"ref":null,"projects":[{"slug":"<project>","name":"<project>"}]}
  DEBUG   2020-04-14 09:37:22.348926463 +00:00 request PUT https://sentry.<company>.tld/api/0/organizations/<company>/releases/<project>@6c3e5a97c94bd19437c841f716c00af1238aeada/
  DEBUG   2020-04-14 09:37:22.348935087 +00:00 using token authentication
  DEBUG   2020-04-14 09:37:22.348944519 +00:00 json body: {"refs":[{"repository":"<group> / <subgroup> / <repo>","commit":"6c3e5a97c94bd19437c841f716c00af1238aeada","previousCommit":null}]}
  DEBUG   2020-04-14 09:37:22.348949982 +00:00 retry number 0, max retries: 0
  DEBUG   2020-04-14 09:37:22.349048732 +00:00 > PUT /api/0/organizations/<company>/releases/<project>@6c3e5a97c94bd19437c841f716c00af1238aeada/ HTTP/1.1
  DEBUG   2020-04-14 09:37:22.349055093 +00:00 > Host: sentry.<company>.tld
  DEBUG   2020-04-14 09:37:22.349059870 +00:00 > Accept: */*
  DEBUG   2020-04-14 09:37:22.349064878 +00:00 > Connection: TE
  DEBUG   2020-04-14 09:37:22.349069481 +00:00 > TE: gzip
  DEBUG   2020-04-14 09:37:22.349074316 +00:00 > User-Agent: sentry-cli/1.52.1
  DEBUG   2020-04-14 09:37:22.349091162 +00:00 > Authorization: Bearer <token>
  DEBUG   2020-04-14 09:37:22.349096221 +00:00 > Content-Type: application/json
  DEBUG   2020-04-14 09:37:22.349101163 +00:00 > Content-Length: 154
  DEBUG   2020-04-14 09:37:22.353614053 +00:00 error: running update nagger
error: API request failed
  caused by: [56] Failure when receiving data from the peer
  DEBUG   2020-04-14 09:37:22.353997471 +00:00 client close; no transport to shut down  (from sentry)
```

</details>

**Comment by BYK** [comment]
@thomasheartman is this still an issue?

**Comment by thomasheartman** [comment]
Hey! Thanks for following up on this. I'm not on the team anymore, so I don't know. Last I remember it would still happen intermittently, but retriggering the CI/CD pipeline would usually fix it.

As such, I don't think it's a major issue at the moment, and I'm happy to come back and re-report it if I run across it again. Feel free to close the issue if you think that's the way to go. Cheers!

**Comment by BYK** [comment]
@thomasheartman thanks a lot for the reply! I'll go ahead and close this in the meantime as it is not certain that this is still an issue and something we can fix. Please do report back if it becomes a nuisance though!
