### ISSUE TITLE
django.db.transaction.TransactionManagementError: This code isn't under transaction management

### ISSUE THREAD

**Issue by harshul4274** [getsentry/sentry#18588]
## Important Details
Migrations intermittently failed while upgrading from sentry 8.20 to 9.1.2

How are you running Sentry?
On Kubernetes with using docker image

## Description

[What happened]
When i sentry upgrading 8.20 to 9.1.2 on kubernetes and i fired command on sentry pod "sentry upgrade" to show me error like django.db.transaction.TransactionManagementError: This code isn't under transaction management

I don't know what is issued.

Good items to include here include:
I share logs of sentry upgrade
-----------------------------------------
07:29:22 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
07:29:26 [INFO] sentry.plugins.github: apps-not-configured
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for sentry:
 - Migrating forwards to 0472_auto__add_field_sentryapp_author.
 > sentry:0365_auto__del_index_eventtag_project_id_key_id_value_id
FATAL ERROR - The following SQL query failed: DROP INDEX CONCURRENTLY sentry_eventtag_project_id_42979ba214ba3c43
The error was: ProgrammingError('index "sentry_eventtag_project_id_42979ba214ba3c43" does not exist\n',)
SQL: DROP INDEX CONCURRENTLY sentry_eventtag_project_id_42979ba214ba3c43
FATAL ERROR - The following SQL query failed: DROP INDEX sentry_eventtag_project_id_42979ba214ba3c43
The error was: ProgrammingError('index "sentry_eventtag_project_id_42979ba214ba3c43" does not exist\n',)
SQL: DROP INDEX sentry_eventtag_project_id_42979ba214ba3c43
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 75, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 30, in _upgrade
    ignore_ghost_migrations=True,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 125, in handle_noargs
    management.call_command('south_migrate', **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/south_migrate.py", line 105, in handle
    ignore_ghosts=ignore_ghosts,
  File "/usr/local/lib/python2.7/site-packages/south/migration/__init__.py", line 231, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 291, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 132, in migrate
    result = self.run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 241, in run
    return super(Forwards, self).run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 92, in run_migration
    south.db.db.rollback_transaction()
  File "/usr/local/lib/python2.7/site-packages/south/db/generic.py", line 1046, in rollback_transaction
    transaction.leave_transaction_management(using=self.db_alias)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 78, in leave_transaction_management
    get_connection(using).leave_transaction_management()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 310, in leave_transaction_management
    "This code isn't under transaction management")
django.db.transaction.TransactionManagementError: This code isn't under transaction management

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
