### ISSUE TITLE
Worker job error: list index out of range

### ISSUE THREAD

**Issue by mkleins** [getsentry/sentry#18631]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 10.1.0.dev

## Description

An error occured on the worker container (celery) after an upgrade with `./install.sh` command : 

```
[ERROR] celery.worker.job: Task sentry.tasks.digests.deliver_digest[73aaa5ef-f934-4aca-b3f7-b515576db519] raised unexpected: IndexError('list index out of range',) (data={u'hostname': 'celery@af460de7f408', u'name': 'sentry.tasks.digests.deliver_digest', u'args': "('mail:p:24', 1588174028.19995)", u'internal': False, u'kwargs': '{}', u'id': '73aaa5ef-f934-4aca-b3f7-b515576db519'})
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
return self.run(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 169, in _inner
reraise(*exc_info)
File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 164, in _inner
return f(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped
result = func(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/sentry/tasks/digests.py", line 43, in deliver_digest
project, target_type, target_identifier = split_key(key)
File "/usr/local/lib/python2.7/site-packages/sentry/digests/notifications.py", line 26, in split_key
target_type = ActionTargetType(key_parts[3])

```

### What you expected to happen

I tried to remove containers but it doesnt work. I saw modifications 12 days ago on notification.py file https://github.com/getsentry/sentry/commit/8e335c7b070cb6d2e9dc1fdc3ce7e1964469346f. Maybe  the beginning of a solution.

**Comment by mkleins** [comment]
It was a problem with old containers. Fixed here https://github.com/getsentry/onpremise/issues/472#issuecomment-624719355
