### ISSUE TITLE
ingest-consumer container causes: Server closed the connection unexpectedly

### ISSUE THREAD

**Issue by tm1000** [getsentry/sentry#18732]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 10.1.0.dev087a67ca

## Description

At first I thought this issue was related to #18492 but the user didn't post their traceback so I can't tell if it's related. This was an upgrade from 9.1.2 to 10.1.0. Every so often the ingest-consumer throws a python error.

sys.argv shows: `["/usr/local/bin/sentry","run","ingest-consumer","--all-consumer-types"]`

If ingest-consumer container is idle for x minutes postgres will disconnect the connection as 'idle', the next command to postgres will cause a fatal error in python

The error is as follows:

```
OperationalError: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n',)
SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."forced_color", "sentry_project"."organization_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event", "sentry_project"."flags", "sentry_project"."platform" FROM "sentry_project...
  File "sentry", line 8, in <module>
    sys.exit(main())
  File "sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "sentry/runner/decorators.py", line 68, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "sentry/runner/commands/run.py", line 461, in ingest_consumer
    get_ingest_consumer(consumer_types=consumer_types, **options).run()
  File "sentry/utils/batching_kafka_consumer.py", line 212, in run
    self._run_once()
  File "sentry/utils/batching_kafka_consumer.py", line 217, in _run_once
    self._flush()
  File "sentry/utils/batching_kafka_consumer.py", line 333, in _flush
    self.worker.flush_batch(self.__batch_results)
  File "sentry/ingest/ingest_consumer.py", line 72, in flush_batch
    projects = {p.id: p for p in Project.objects.get_many_from_cache(projects_to_fetch)}
  File "sentry/db/models/manager.py", line 427, in get_many_from_cache
    db_results = {getattr(x, key): x for x in self.filter(**{key + "__in": db_lookup_values})}
  File "django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
```

The SQL it's trying to execute is:
```
SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."forced_color", "sentry_project"."organization_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event", "sentry_project"."flags", "sentry_project"."platform" FROM "sentry_project" WHERE "sentry_project"."id" IN (%s)
```

Logs from the ingest container:
```
17:21:50 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
17:21:53 [INFO] sentry.plugins.github: apps-not-configured
17:22:13 [INFO] batching-kafka-consumer: New partitions assigned: [TopicPartition{topic=ingest-attachments,partition=0,offset=-1001,error=None}, TopicPartition{topic=ingest-events,partition=0,offset=-1001,error=None}, TopicPartition{topic=ingest-transactions,partition=0,offset=-1001,error=None}]
17:22:14 [INFO] batching-kafka-consumer: Flushing 3 items (from {(u'ingest-events', 0): [55L, 57L]}): forced:False size:False time:True
17:22:14 [INFO] batching-kafka-consumer: Worker flush took 83ms
17:23:36 [INFO] batching-kafka-consumer: Flushing 1 items (from {(u'ingest-events', 0): [58L, 58L]}): forced:False size:False time:True
17:23:36 [INFO] batching-kafka-consumer: Worker flush took 10ms
17:26:14 [INFO] batching-kafka-consumer: Flushing 1 items (from {(u'ingest-events', 0): [59L, 59L]}): forced:False size:False time:True
17:26:14 [INFO] batching-kafka-consumer: Worker flush took 12ms
17:45:10 [INFO] batching-kafka-consumer: Flushing 2 items (from {(u'ingest-events', 0): [60L, 61L]}): forced:False size:False time:True
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 68, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/run.py", line 461, in ingest_consumer
    get_ingest_consumer(consumer_types=consumer_types, **options).run()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/batching_kafka_consumer.py", line 212, in run
    self._run_once()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/batching_kafka_consumer.py", line 217, in _run_once
    self._flush()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/batching_kafka_consumer.py", line 333, in _flush
    self.worker.flush_batch(self.__batch_results)
  File "/usr/local/lib/python2.7/site-packages/sentry/ingest/ingest_consumer.py", line 72, in flush_batch
    projects = {p.id: p for p in Project.objects.get_many_from_cache(projects_to_fetch)}
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 427, in get_many_from_cache
    db_results = {getattr(x, key): x for x in self.filter(**{key + "__in": db_lookup_values})}
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
django.db.utils.OperationalError: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n',)
SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."forced_color", "sentry_project"."organization_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event", "sentry_project"."flags", "sentry_project"."platform" FROM "sentry_project" WHERE "sentry_project"."id" IN (%s)
```

There's no connection resets/errors in postgres.

I've run these commands manually and they work quickly
```
sentry=# SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."forced_color", "sentry_project"."organization_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event", "sentry_project"."flags", "sentry_project"."platform" FROM "sentry_project" WHERE "sentry_project"."id" IN ('28');
 id |      slug      |      name      | forced_color | organization_id | public |          date_added           | status |      first_event       | flags |  platform
----+----------------+----------------+--------------+-----------------+--------+-------------------------------+--------+------------------------+-------+------------
 28 | testing | testing |              |               1 | f      | 2020-05-08 18:11:22.621085+00 |      0 | 2020-05-11 15:58:46+00 |     3 | ruby-rails
(1 row)
```

### What you expected to happen

The ingest container should not crash on unexpected disconnects?

### Possible Solution

This appears to be an idle disconnect. It's probably not noticeable on heavily used Sentry systems (like sentry.io). Where-as ingest is sitting around not doing anything and then will try to talk to posgres but gets suddenly disconnected (because posgres already terminated the connection due to idle timeout).

You can see that ingest is able to process:
```
17:22:14 [INFO] batching-kafka-consumer: Flushing 3 items (from {(u'ingest-events', 0): [55L, 57L]}): forced:False size:False time:True
17:22:14 [INFO] batching-kafka-consumer: Worker flush took 83ms
17:23:36 [INFO] batching-kafka-consumer: Flushing 1 items (from {(u'ingest-events', 0): [58L, 58L]}): forced:False size:False time:True
17:23:36 [INFO] batching-kafka-consumer: Worker flush took 10ms
17:26:14 [INFO] batching-kafka-consumer: Flushing 1 items (from {(u'ingest-events', 0): [59L, 59L]}): forced:False size:False time:True
17:26:14 [INFO] batching-kafka-consumer: Worker flush took 12ms
```

However when it gets to the next entry:
```
17:45:10 [INFO] batching-kafka-consumer: Flushing 2 items (from {(u'ingest-events', 0): [60L, 
```
It fails. It did nothing (idled) for 19 minutes. This is consistent with all of the logs from all of the failed containers.

```
17:46:14 [INFO] batching-kafka-consumer: Flushing 1 items (from {(u'ingest-events', 0): [65L, 65L]}): forced:False size:False time:True
17:46:14 [INFO] batching-kafka-consumer: Worker flush took 15ms
18:11:33 [INFO] batching-kafka-consumer: Flushing 1 items (from {(u'ingest-events', 0): [66L, 66L]}): forced:False size:False time:True
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
```

As far as I can tell once docker restarts the container it immediately processes what it wasn't able to in the last run

The solution here would probably be to check if the disconnect was due to "server closed the connection " and retry.

**Comment by tm1000** [comment]
Narrowing this down one could even write a retry wrapper around File "sentry/ingest/ingest_consumer.py", line 72, in flush_batch (https://github.com/getsentry/sentry/blob/master/src/sentry/ingest/ingest_consumer.py#L72)

As thats the only place this fails

**Comment by tm1000** [comment]
FYI this is also in swarm. I've tried moving the ingest container into the same host as postgres and it has the same issues randomly. Postgres has no errors and is not disconnected. No other containers in the stack have this issue. Only the ingest container.

**Comment by tm1000** [comment]
Perhaps could write a retry wrapper around File "sentry/ingest/ingest_consumer.py", line 72, in flush_batch (https://github.com/getsentry/sentry/blob/master/src/sentry/ingest/ingest_consumer.py#L72)

It seems silly as postgres should never lose it's connect (and it seems like only the client is having an issue) but there probably needs to be some sort of try/catch/retry here

As thats the only place this fails

**Comment by tm1000** [comment]
Updates. Our NOC engineer looked into this for me and came across this: https://success.docker.com/article/ipvs-connection-timeout-issue

Setting the values of postgres.conf to:
```
tcp_keepalives_idle = 600
tcp_keepalives_interval = 600
tcp_keepalives_count = 15
```

Fixed this issue and the container no longer crashes. Going to close this issue now!
