### ISSUE TITLE
the sentry webpage shows exception infos much later than the time that they are actually reported by frontend pages

### ISSUE THREAD

**Issue by nju-Nicko** [getsentry/sentry#18856]
## Important Details

How are you running Sentry?

On-Premise Sentry
version 9.1.1

## Description

I met a problem that the sentry webpage shows exception infos much later than when they are reported by our frontend pages. For example, an exception is thrown by our frontend page at 9.00 am, we can't see this exception info on sentry-webpage until 9.20 am.
I found many `SoftTimeLimitExceeded` errors in sentry-worker's log. The detail is as below:
````python
06:34:51 [WARNING] celery.worker.job: Soft time limit (60s) exceeded for sentry.tasks.store.process_event[65fdcf90-ba30-4ab9-bef6-b37d734f7f54]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sentry/http.py", line 182, in fetch_file
    **kwargs
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/sentry/net/http.py", line 154, in request
    response = _Session.request(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/site-packages/sentry/net/http.py", line 68, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/site-packages/sentry/net/socket.py", line 115, in safe_create_connection
    sock.connect(sa)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib64/python2.7/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
SoftTimeLimitExceeded: SoftTimeLimitExceeded()
06:34:51 [ERROR] sentry.http: SoftTimeLimitExceeded()
06:34:52 [WARNING] sentry.http: source.disabled (url=u'https://marketinghd.eastmoney.com/fsc/js/chunk-vendors.b4fd93cd.js' timeout=5 type=u'fetch_timeout')
06:34:52 [WARNING] sentry.http: source.disabled (url=u'https://marketinghd.eastmoney.com/fsc/js/chunk-vendors.b4fd93cd.js' type=u'unknown_error')
06:34:54 [WARNING] sentry.http: source.disabled (url=u'https://marketinghd.eastmoney.com/fsc/js/chunk-vendors.b4fd93cd.js' timeout=5 type=u'fetch_timeout')
06:34:54 [WARNING] sentry.http: source.disabled (url=u'https://marketinghd.eastmoney.com/fsc/js/chunk-vendors.b4fd93cd.js' timeout=5 type=u'fetch_timeout')
06:34:56 [WARNING] sentry.http: source.disabled (url=u'https://marketinghd.eastmoney.com/fsc/js/chunk-vendors.b4fd93cd.js' timeout=5 type=u'fetch_timeout')
06:34:56 [WARNING] sentry.http: source.disabled (url=u'https://marketinghd.eastmoney.com/fsc/js/chunk-vendors.b4fd93cd.js' timeout=5 type=u'fetch_timeout')
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/billiard/pool.py", line 645, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(65,)
06:34:56 [ERROR] celery.worker.job: Task sentry.tasks.store.process_event[65fdcf90-ba30-4ab9-bef6-b37d734f7f54] raised unexpected: TimeLimitExceeded(65,) (data={u'hostname': 'celery@10-205-41-101', u'name': 'sentry.tasks.store.process_event', u'args': '[]', u'internal': False, u'kwargs': "{'event_id': u'd8bd1c5103014e7dbc54458155530fdf', 'start_time': 1589521825.289552, 'cache_key': u'e:d8bd1c5103014e7dbc54458155530fdf:23'}", u'id': '65fdcf90-ba30-4ab9-bef6-b37d734f7f54'})
06:34:56 [ERROR] celery.worker.job: Hard time limit (65s) exceeded for sentry.tasks.store.process_event[65fdcf90-ba30-4ab9-bef6-b37d734f7f54]
06:34:57 [ERROR] multiprocessing: Process 'Worker-99' pid:17322 exited with 'signal 9 (SIGKILL)'
````

### What you expected to happen
The sentry-webpage should show exception infos immediately after they are thrown.

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by nju-Nicko** [comment]
and now we throw exception in frontend page at about 17.00 pm. It has been 18.00 pm now, we still can't see the exception info from sentry web-page.

**Comment by BYK** [comment]
This sounds like your workers are unable to keep up with the load.

Also, please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
