### ISSUE TITLE
v8 actually requires python-redis > 2.8

### ISSUE THREAD

**Issue by beeftornado** [getsentry/sentry#1886]
Was upgrading from 7.7-dev. I pulled latest master and built and ran and it failed with attached exception. I resolved it by upgrading to latest redis module 2.10.3 (I had been on 2.8). The ">2.7" requirement in setup.py needs to be bumped I think. I don't know which minimum version will work because I jumped from 2.8 to 2.10.

```
Traceback (most recent call last):
  File "/mnt/pyenv/versions/sentry/lib/python2.7/site-packages/logan-0.7.1-py2.7.egg/logan/runner.py", line 116, in settings_callb
ack
    'settings': settings,
  File "/mnt/sentry/repo/src/sentry/utils/runner.py", line 293, in initialize_app
    from sentry.app import env
  File "/mnt/sentry/repo/src/sentry/app.py", line 30, in <module>
    buffer = get_instance(settings.SENTRY_BUFFER, settings.SENTRY_BUFFER_OPTIONS)
  File "/mnt/sentry/repo/src/sentry/app.py", line 24, in get_instance
    cls = import_string(path)
  File "/mnt/sentry/repo/src/sentry/utils/imports.py", line 37, in import_string
    result = _cache[path]
  File "/mnt/sentry/repo/src/sentry/utils/imports.py", line 20, in __missing__
    module = __import__(module_name, {}, {}, [class_name], -1)
  File "/mnt/sentry/repo/src/sentry/buffer/redis.py", line 14, in <module>
    from rb import Cluster
  File "/mnt/pyenv/versions/sentry/lib/python2.7/site-packages/rb-0.9.2-py2.7.egg/rb/__init__.py", line 10, in <module>
    from rb.cluster import Cluster
  File "/mnt/pyenv/versions/sentry/lib/python2.7/site-packages/rb-0.9.2-py2.7.egg/rb/cluster.py", line 5, in <module>
    SSLConnection is None
NameError: name 'SSLConnection' is not defined
sentry-web_02: ERROR (abnormal termination)
sentry-web_03: ERROR (abnormal termination)
sentry-web_00: ERROR (abnormal termination)
sentry-web_01: ERROR (abnormal termination)
sentry-web_04: ERROR (abnormal termination)
sentry-worker: started
```

**Comment by dcramer** [comment]
I bumped minimum to what we have in prod atm
