### ISSUE TITLE
java.lang.IllegalArgumentException: Magic v0 does not support record headers

### ISSUE THREAD

**Issue by caiqing0204** [getsentry/sentry#19337]
Recently, I am using Sentry, but there is a problem with the Kafka cluster, and I cannot update to the latest Kafka (2.5), so I would like to ask you for a look, thank you.

`
[2020-06-12 18:54:16,760] ERROR [ReplicaManager broker=1] Error processing append operation on partition events-0 (kafka.server.ReplicaManager)
java.lang.IllegalArgumentException: Magic v0 does not support record headers
        at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:412)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:451)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:604)
        at kafka.log.LogValidator$.$anonfun$convertAndAssignOffsetsNonCompressed$3(LogValidator.scala:246)
        at kafka.log.LogValidator$.$anonfun$convertAndAssignOffsetsNonCompressed$3$adapted(LogValidator.scala:241)
        at scala.collection.TraversableViewLike$Filtered.$anonfun$foreach$5(TraversableViewLike.scala:221)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableViewLike$Transformed.foreach(IterableViewLike.scala:47)
        at scala.collection.IterableViewLike$Transformed.foreach$(IterableViewLike.scala:47)
        at scala.collection.IterableViewLike$AbstractTransformed.foreach(IterableViewLike.scala:43)
        at scala.collection.TraversableViewLike$Filtered.foreach(TraversableViewLike.scala:220)
        at scala.collection.TraversableViewLike$Filtered.foreach$(TraversableViewLike.scala:219)
        at scala.collection.IterableViewLike$$anon$8.foreach(IterableViewLike.scala:123)
        at kafka.log.LogValidator$.$anonfun$convertAndAssignOffsetsNonCompressed$1(LogValidator.scala:241)
        at kafka.log.LogValidator$.$anonfun$convertAndAssignOffsetsNonCompressed$1$adapted(LogValidator.scala:237)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at kafka.log.LogValidator$.convertAndAssignOffsetsNonCompressed(LogValidator.scala:237)
        at kafka.log.LogValidator$.validateMessagesAndAssignOffsets(LogValidator.scala:99)
        at kafka.log.Log.liftedTree1$1(Log.scala:1074)
        at kafka.log.Log.$anonfun$append$2(Log.scala:1059)
        at kafka.log.Log.append(Log.scala:2318)
        at kafka.log.Log.appendAsLeader(Log.scala:1002)
        at kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:969)
        at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:957)
        at kafka.server.ReplicaManager.$anonfun$appendToLocalLog$4(ReplicaManager.scala:794)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
        at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
        at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:782)
        at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:506)
        at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:582)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:128)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:70)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by caiqing0204** [comment]
问题解决
