### ISSUE TITLE
TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#1943]
https://beta.getsentry.com/sentry/javascript/group/79308663/

```
TypeError: Cannot read property '1' of undefined
  at call (./app/views/organizationStats/index.jsx:203:56)
  at each (~/jquery/dist/jquery.js:374)
  at call (./app/views/organizationStats/index.jsx:201:8)
  at each (~/jquery/dist/jquery.js:382)
  at processProjectData (./app/views/organizationStats/index.jsx:198:6)
...
(5 additional frame(s) were not displayed)
```

**Comment by dcramer** [comment]
This is probably because of the shitty way I implemented the state transitions here.

```
          this.state.rawProjectData[statName] = data;
          this.state.projectsRequestsPending -= 1;
          this.setState({
            rawProjectData: this.state.rawProjectData,
            projectsRequestsPending: this.state.projectsRequestsPending
          });
```

**Comment by dcramer** [comment]
Not sure if this is still an issue?

**Comment by benvinegar** [comment]
The issue hasn't been seen in > 2 months, so I'm going to close.
