### ISSUE TITLE
The sentry configuration deployed by kubernetes sends emails with errors

### ISSUE THREAD

**Issue by StevensGitHub** [getsentry/sentry#19594]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 155, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 150, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/email.py", line 76, in send_email
    send_messages([message])
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/email.py", line 436, in send_messages
    sent = connection.send_messages(messages)
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 48, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python2.7/smtplib.py", line 317, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python2.7/smtplib.py", line 292, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 99] Cannot assign requested address
03:55:38 [ERROR] celery.worker.job: Task sentry.tasks.email.send_email[1de30e31-5e9b-478f-934a-bdfa5aa250fe] raised unexpected: error(99, 'Cannot assign requested address') (data={u'hostname': 'celery@sentry-worker-74b57ff78d-gxlbr', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7fd64cefa390>}", u'id': '1de30e31-5e9b-478f-934a-bdfa5aa250fe'})

**Comment by BYK** [comment]
Please follow the issue template so we can help you easier. In its current form, this issue is not actionable so closing.

Also, please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
