### ISSUE TITLE
Migration does not pass

### ISSUE THREAD

**Issue by letnab** [getsentry/sentry#19831]
version 9.0.0 to 9.1.2
sentry:9.1.2 install from pip on bare metal server

`# sentry  --config=/home/sentry/.sentry upgrade
12:06:35 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for sentry:
 - Migrating forwards to 0472_auto__add_field_sentryapp_author.
 > sentry:0424_initial
FATAL ERROR - The following SQL query failed: CREATE TABLE "sentry_apiapplication" ("id" bigserial NOT NULL PRIMARY KEY, "client_id" varchar(64) NOT NULL UNIQUE, "client_secret" text NOT NULL, "owner_id" integer NOT NULL, "name" varchar(64) NOT NULL, "status" integer CHECK ("status" >= 0) NOT NULL, "allowed_origins" text NULL, "redirect_uris" text NOT NULL, "homepage_url" varchar(200) NULL, "privacy_url" varchar(200) NULL, "terms_url" varchar(200) NULL, "date_added" timestamp with time zone NOT NULL)
The error was: ProgrammingError('\xd0\x9e\xd0\xa8\xd0\x98\xd0\x91\xd0\x9a\xd0\x90:  \xd0\xbe\xd1\x82\xd0\xbd\xd0\xbe\xd1\x88\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 "sentry_apiapplication" \xd1\x83\xd0\xb6\xd0\xb5 \xd1\x81\xd1\x83\xd1\x89\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd1\x83\xd0\xb5\xd1\x82\n',)
SQL: CREATE TABLE "sentry_apiapplication" ("id" bigserial NOT NULL PRIMARY KEY, "client_id" varchar(64) NOT NULL UNIQUE, "client_secret" text NOT NULL, "owner_id" integer NOT NULL, "name" varchar(64) NOT NULL, "status" integer CHECK ("status" >= 0) NOT NULL, "allowed_origins" text NULL, "redirect_uris" text NOT NULL, "homepage_url" varchar(200) NULL, "privacy_url" varchar(200) NULL, "terms_url" varchar(200) NULL, "date_added" timestamp with time zone NOT NULL)
Error in migration: sentry:0424_initial
The following content types are stale and need to be deleted:

    sentry | dsymapp
    sentry | versiondsymfile
    sentry | projectdsymfile
    sentry | grouphashtombstone

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: no
Traceback (most recent call last):
  File "/home/sentry/sentry_app/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 75, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 30, in _upgrade
    ignore_ghost_migrations=True,
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 125, in handle_noargs
    management.call_command('south_migrate', **options)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/management/commands/south_migrate.py", line 105, in handle
    ignore_ghosts=ignore_ghosts,
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/migration/__init__.py", line 231, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/migration/migrators.py", line 291, in migrate_many
    result = self.migrate(migration, database)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/migration/migrators.py", line 132, in migrate
    result = self.run(migration, database)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/migration/migrators.py", line 241, in run
    return super(Forwards, self).run(migration, database)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/migration/migrators.py", line 85, in run_migration
    migration_function()
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/migration/migrators.py", line 61, in <lambda>
    return (lambda: direction(orm))
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/south_migrations/0424_initial.py", line 41, in forwards
    ('date_added', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now)),
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/db/generic.py", line 53, in _cache_clear
    return func(self, table, *args, **opts)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/db/generic.py", line 369, in create_table
    "columns": ', '.join([col for col in columns if col]),
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/south/db/generic.py", line 288, in execute
    cursor.execute(sql, params)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 487, in execute
    return real_execute(self, sql, params)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
    raise_the_exception(self.db, e)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
    return func(self, *args, **kwargs)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
    return func(self, sql, *args, **kwargs)
  File "/home/sentry/sentry_app/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 74, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.ProgrammingError: ProgrammingError('\xd0\x9e\xd0\xa8\xd0\x98\xd0\x91\xd0\x9a\xd0\x90:  \xd0\xbe\xd1\x82\xd0\xbd\xd0\xbe\xd1\x88\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 "sentry_apiapplication" \xd1\x83\xd0\xb6\xd0\xb5 \xd1\x81\xd1\x83\xd1\x89\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd1\x83\xd0\xb5\xd1\x82\n',)
SQL: CREATE TABLE "sentry_apiapplication" ("id" bigserial NOT NULL PRIMARY KEY, "client_id" varchar(64) NOT NULL UNIQUE, "client_secret" text NOT NULL, "owner_id" integer NOT NULL, "name" varchar(64) NOT NULL, "status" integer CHECK ("status" >= 0) NOT NULL, "allowed_origins" text NULL, "redirect_uris" text NOT NULL, "homepage_url" varchar(200) NULL, "privacy_url" varchar(200) NULL, "terms_url" varchar(200) NULL, "date_added" timestamp with time zone NOT NULL)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):(sentry_app) `

**Comment by BYK** [comment]
Closing due to staleness. This also looks like a database configuration issue (locale?) and moreover it is using a custom setup with very old versions of Sentry which we no longer support.
