### ISSUE TITLE
django.db.utils.ProgrammingError: UndefinedTable

### ISSUE THREAD

**Issue by sunhaokk** [getsentry/sentry#20120]
When sentry upgrade,  i get this err.

(python27) [root@backend .sentry]# sentry upgrade
07:47:29 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
/root/.conda/envs/python27/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
07:47:31 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/root/.conda/envs/python27/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 174, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 121, in _upgrade
    _migrate_from_south(verbosity)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 93, in _migrate_from_south
    if not _has_south_history(connection):
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 80, in _has_south_history
    cursor.execute("SELECT 1 FROM south_migrationhistory LIMIT 1")
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 487, in execute
    return real_execute(self, sql, params)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 81, in inner
    raise_the_exception(self.db, e)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 79, in inner
    return func(self, *args, **kwargs)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 99, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    return func(self, sql, *args, **kwargs)
  File "/root/.conda/envs/python27/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 77, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: UndefinedTable('\xe9\x94\x99\xe8\xaf\xaf:  \xe5\x85\xb3\xe7\xb3\xbb "south_migrationhistory" \xe4\xb8\x8d\xe5\xad\x98\xe5\x9c\xa8\nLINE 1: SELECT 1 FROM south_migrationhistory LIMIT 1\n                      ^\n',)
SQL: SELECT 1 FROM south_migrationhistory LIMIT 1

**Comment by BYK** [comment]
Please use the issue template, provide all the information requested there and file this under [getsentry/onpremise](https://github.com/getsentry/onpremise). Closing since this issue is not actionable in this state.
