### ISSUE TITLE
Migration fail when upgrade 10 => 20.6

### ISSUE THREAD

**Issue by cucxabong** [getsentry/sentry#20357]
## Important Details

How are you running Sentry?
Kubernetes (Sentry version 10.0.0)

## Description

Error logs when running `sentry upgrade --noinput`
```
Running migrations:
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sentry.0025_organizationaccessrequest_requester... OK
  Applying sentry.0026_delete_event... OK
  Applying sentry.0027_exporteddata... OK
  Applying sentry.0028_user_reports... OK
  Applying sentry.0029_discover_query_upgrade... OK
  Applying sentry.0030_auto_20200201_0039... OK
  Applying sentry.0031_delete_alert_rules_and_incidents... OK
....
Applying sentry.0051_fix_auditlog_pickled_data...None
09:36:57 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Team') factory=<function __simple_class_factory_compat at 0x7fb1f493bb50> attrs=[])
None
....
09:37:11 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Team') factory=<function __simple_class_factory_compat at 0x7fb1f493bb50> attrs=[])
^M                                                                               ^MAudit Log Entrys: N/A% |                                       | ETA:  --:--:--^M
                                       ^MAudit Log Entrys: N/A% |                                       | ETA:  --:--:--^M                                                                               ^MA
udit Log Entrys:  49% |####################                     | ETA: 0:00:13^M                                                                               ^MAudit Log Entrys: 100% |###################
#####################| Time: 0:00:13
 OK
  Applying sentry.0052_organizationonboardingtask_completion_seen... OK
  Applying sentry.0053_migrate_alert_task_onboarding... OK
  Applying sentry.0054_create_key_transaction... OK
  Applying sentry.0055_query_subscription_status... OK
^M                                                                               ^MDiscover Saved Querys: N/A% |                                  | ETA:  --:--:--^M
                                       ^MDiscover Saved Querys: 100% |###################################| Time: 0:00:00
  Applying sentry.0056_remove_old_functions... OK
  Applying sentry.0057_remove_unused_project_flag... OK
  Applying sentry.0058_project_issue_alerts_targeting... OK
  Applying sentry.0059_add_new_sentry_app_features... OK
```

## Steps to Reproduce
Using docker image with sentry version 20.6 & do rolling-upgrade

**Comment by cucxabong** [comment]
more message maybe relate
```
09:44:06 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Event') factory=<function __simple_class_factory_compat at 0x7efcc844cbd0> attrs=[])
celery@infrastructure-sentry-8cc9dfcd8-7r6jd ready.
Traceback (most recent call last):
  File "/opt/python2-venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/python2-venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/python2-venv/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 171, in _inner
    reraise(*exc_info)
  File "/opt/python2-venv/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 166, in _inner
    return f(*args, **kwargs)
  File "/opt/python2-venv/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped
    result = func(*args, **kwargs)
  File "/opt/python2-venv/local/lib/python2.7/site-packages/sentry/tasks/digests.py", line 55, in deliver_digest
    with digests.digest(key, minimum_delay=minimum_delay) as records:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/python2-venv/local/lib/python2.7/site-packages/sentry/digests/backends/redis.py", line 216, in digest
    response,
  File "/opt/python2-venv/local/lib/python2.7/site-packages/sentry/utils/compat/__init__.py", line 22, in map
    return list(_map(a, b, *c))
  File "/opt/python2-venv/local/lib/python2.7/site-packages/sentry/digests/backends/redis.py", line 212, in <lambda>
    if key__value__timestamp[1] is not None
  File "/opt/python2-venv/local/lib/python2.7/site-packages/sentry/digests/codecs.py", line 21, in decode
    return pickle.loads(zlib.decompress(value))
  File "/opt/python2-venv/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 412, in __model_unpickle_compat
    return model_unpickle(model_id)
  File "/opt/python2-venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 1807, in model_unpickle
    model = apps.get_model(*model_id)
  File "/opt/python2-venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 205, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/opt/python2-venv/local/lib/python2.7/site-packages/django/apps/config.py", line 172, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'sentry' doesn't have a 'Event' model.
09:44:06 [ERROR] celery.worker.job: Task sentry.tasks.digests.deliver_digest[5b8ef66c-c83c-447c-9e50-3e8abdfcfcec] raised unexpected: LookupError("App 'sentry' doesn't have a 'Event' model.",) (data={u'hostname': 'celery@infrastructure-sentry-8cc9dfcd8-7r6jd', u'name': 'sentry.tasks.digests.deliver_digest', u'args': "('mail:p:1', 1598262240.059749)", u'internal': False, u'kwargs': '{}', u'id': '5b8ef66c-c83c-447c-9e50-3e8abdfcfcec'})
```

**Comment by BYK** [comment]
Hi, are you able to try with a more recent version of Sentry, such as 20.10.1?

**Comment by mkondratev** [comment]
I confirm the error on 20.10.1 after migration from 9.1.2 to 20.10.1:

```
worker_1                       | 18:04:37 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Event') factory=<function __simple_class_factory_compat at 0x7f9f1f3116e0> attrs=[])
worker_1                       | Traceback (most recent call last):
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 412, in trace_task
worker_1                       |     R = retval = fun(*args, **kwargs)
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
worker_1                       |     return self.run(*args, **kwargs)
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 186, in _inner
worker_1                       |     reraise(*exc_info)
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 181, in _inner
worker_1                       |     return f(*args, **kwargs)
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped
worker_1                       |     result = func(*args, **kwargs)
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/digests.py", line 55, in deliver_digest
worker_1                       |     with digests.digest(key, minimum_delay=minimum_delay) as records:
worker_1                       |   File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
worker_1                       |     return self.gen.next()
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry/digests/backends/redis.py", line 216, in digest
worker_1                       |     response,
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry/utils/compat/__init__.py", line 22, in map
worker_1                       |     return list(_map(a, b, *c))
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry/digests/backends/redis.py", line 212, in <lambda>
worker_1                       |     if key__value__timestamp[1] is not None
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry/digests/codecs.py", line 21, in decode
worker_1                       |     return pickle.loads(zlib.decompress(value))
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry/monkey/pickle.py", line 97, in py3_compat_pickle_loads
worker_1                       |     return original_pickle_loads(*args, **kwargs)
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 430, in __model_unpickle_compat
worker_1                       |     return model_unpickle(model_id)
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 1807, in model_unpickle
worker_1                       |     model = apps.get_model(*model_id)
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 205, in get_model
worker_1                       |     return app_config.get_model(model_name, require_ready=require_ready)
worker_1                       |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 172, in get_model
worker_1                       |     "App '%s' doesn't have a '%s' model." % (self.label, model_name))
worker_1                       | LookupError: App 'sentry' doesn't have a 'Event' model.
worker_1                       | 18:04:37 [ERROR] celery.app.trace: Task sentry.tasks.digests.deliver_digest[9e73250c-5fe4-49a9-b1e0-96789320732c] raised unexpected: LookupError("App 'sentry' doesn't have a 'Event' model.",) (data={u'internal': False, u'traceback': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 186, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 181, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/digests.py", line 55, in deliver_digest\n    with digests.digest(key, minimum_delay=minimum_delay) as records:\n  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "/usr/local/lib/python2.7/site-packages/sentry/digests/backends/redis.py", line 216, in digest\n    response,\n  File "/usr/local/lib/python2.7/site-packages/sentry/utils/compat/__init__.py", line 22, in map\n    return list(_map(a, b, *c))\n  File "/usr/local/lib/python2.7/site-packages/sentry/digests/backends/redis.py", line 212, in <lambda>\n    if key__value__timestamp[1] is not None\n  File "/usr/local/lib/python2.7/site-packages/sentry/digests/codecs.py", line 21, in decode\n    return pickle.loads(zlib.decompress(value))\n  File "/usr/local/lib/python2.7/site-packages/sentry/monkey/pickle.py", line 97, in py3_compat_pickle_loads\n    return original_pickle_loads(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 430, in __model_unpickle_compat\n    return model_unpickle(model_id)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 1807, in model_unpickle\n    model = apps.get_model(*model_id)\n  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 205, in get_model\n    return app_config.get_model(model_name, require_ready=require_ready)\n  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 172, in get_model\n    "App \'%s\' doesn\'t have a \'%s\' model." % (self.label, model_name))\nLookupError: App \'sentry\' doesn\'t have a \'Event\' model.\n', u'name': 'sentry.tasks.digests.deliver_digest', u'args': "(u'mail:p:8', 1605117191.619707)", u'kwargs': '{}', u'description': u'raised unexpected', u'hostname': '03d7ded63960', u'id': '9e73250c-5fe4-49a9-b1e0-96789320732c', u'exc': 'LookupError("App \'sentry\' doesn\'t have a \'Event\' model.",)'})
```

**Comment by BYK** [comment]
This seems like queues not drained before the upgrade started. We have given a longer timeout now when shutting down the old instance but there may still be events stuck. I recommend backing up your Redis data and then flushing it and starting with a clean Redis database.

You may have some data loss but it should not be too important (but just in case, back it up first)
