### ISSUE TITLE
sentry upgrade fail!  redis packages is error! ImportError: cannot import name b.

### ISSUE THREAD

**Issue by ZoneForZero** [getsentry/sentry#20835]
## Important Details

How are you running Sentry?

python 20.9.0
![image](https://user-images.githubusercontent.com/34958622/93456998-07de7080-f911-11ea-97c7-5b3c9183dc8a.png)

## Description

[What happened]
1. pip install -r requirement-base.txt
2. pip install --editable .
![image](https://user-images.githubusercontent.com/34958622/93456814-c77ef280-f910-11ea-94b1-38a0fa057a68.png)
So far no abnormalities have occurred
3. sentry upgrade
![image](https://user-images.githubusercontent.com/34958622/93457085-2ba1b680-f911-11ea-8685-73673ea3783b.png)
sentry upgrade
10:10:37 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.2) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
Traceback (most recent call last):
  File "/usr/bin/sentry", line 11, in <module>
    load_entry_point('sentry', 'console_scripts', 'sentry')()
  File "/root/sentry-new/sentry/src/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/sentry-new/sentry/src/sentry/runner/decorators.py", line 29, in inner
    configure()
  File "/root/sentry-new/sentry/src/sentry/runner/__init__.py", line 129, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/root/sentry-new/sentry/src/sentry/runner/settings.py", line 158, in configure
    skip_service_validation=skip_service_validation,
  File "/root/sentry-new/sentry/src/sentry/runner/initializer.py", line 310, in initialize_app
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/sentry-new/sentry/src/sentry/eventstream/__init__.py", line 7, in <module>
    from .base import EventStream
  File "/root/sentry-new/sentry/src/sentry/eventstream/base.py", line 7, in <module>
    from sentry.tasks.post_process import post_process_group
  File "/root/sentry-new/sentry/src/sentry/tasks/post_process.py", line 15, in <module>
    from sentry.utils.redis import redis_clusters
  File "/root/sentry-new/sentry/src/sentry/utils/redis.py", line 16, in <module>
    from rediscluster import RedisCluster
  File "/usr/lib/python2.7/site-packages/rediscluster/__init__.py", line 7, in <module>
    from .client import StrictRedisCluster, RedisCluster
  File "/usr/lib/python2.7/site-packages/rediscluster/client.py", line 10, in <module>
    from .connection import ClusterConnectionPool, ClusterReadOnlyConnectionPool
  File "/usr/lib/python2.7/site-packages/rediscluster/connection.py", line 11, in <module>
    from .nodemanager import NodeManager
  File "/usr/lib/python2.7/site-packages/rediscluster/nodemanager.py", line 12, in <module>
    from redis._compat import b, unicode, bytes, long, basestring
ImportError: cannot import name b

### What you expected to happen
Initialize the system successfully

### Possible Solution
I think it is a redis-related dependency package conflict, but I am not sure which version should be used

**Comment by BYK** [comment]
Hi @ZoneForZero, we do not support running Sentry this way so unfortunately this is not something we can help with. You may ask over at [the forum](https://forum.sentry.io) but it is unlikely that you'd get an answer. I'd strongly recommend using the Docker images we publish for running Sentry.
