### ISSUE TITLE
Assertion error on minidump processing

### ISSUE THREAD

**Issue by lz1irq** [getsentry/sentry#21011]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 9.1.2

## Description

When uploading a minidump file from a C++ app, no new issue (or event in an existing issue) appears.
We have debug symbols uploaded for the the build that is generating the issue.
The following stack trace appears in the worker log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 138, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 133, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/store.py", line 291, in process_event
    event_id=event_id, process_task=process_event)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/store.py", line 217, in _do_process_event
    new_data = process_stacktraces(data)
  File "/usr/local/lib/python2.7/site-packages/sentry/stacktraces.py", line 383, in process_stacktraces
    if processor.preprocess_step(processing_task):
  File "/usr/local/lib/python2.7/site-packages/sentry/lang/native/plugin.py", line 178, in preprocess_step
    referenced_images=referenced_images,
  File "/usr/local/lib/python2.7/site-packages/sentry/lang/native/symbolizer.py", line 133, in __init__
    with_conversion_errors=True)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/debugfile.py", line 606, in get_symcaches
    project, debug_ids, ProjectSymCacheFile, on_dif_referenced)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/debugfile.py", line 711, in _get_caches_impl
    project, to_update.values(), cls)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/debugfile.py", line 738, in _update_cachefiles
    file, cache, err = self._update_cachefile(debug_file, tf.name, cls)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/debugfile.py", line 788, in _update_cachefile
    file.putfile(cache.open_stream())
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 434, in putfile
    offset=offset,
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 902, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 860, in as_sql
    for obj in self.query.objs
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 350, in get_db_prep_save
    prepared=False)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 342, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/fields/bounded.py", line 37, in get_prep_value
    assert value <= self.MAX_VALUE
AssertionError
08:27:52 [ERROR] celery.worker.job: Task sentry.tasks.store.process_event[3747fc89-bd52-4c76-812c-dc79fe48c2e1] raised unexpected: AssertionError() (data={u'hostname': 'celery@4fe30ae3b4c2', u'name': 'sentry.tasks.store.process_event', u'args': '[]', u'internal': False,
 u'kwargs': "{'event_id': u'5e54b31fd2794873b732d743e1944886', 'start_time': 1601281643.030409, 'cache_key': u'e:5e54b31fd2794873b732d743e1944886:15'}", u'id': '3747fc89-bd52-4c76-812c-dc79fe48c2e1'})
```
We can provide the dump file itself privately if necessary.

EDIT: So colleagues did some testing, if they upload a crash dump from a build that Sentry doesn't have debug symbols for, it's fine, since it doesn't get processed. However, when they upload the debug symbols we get the same stack trace.

**Comment by BYK** [comment]
Are you able to try this with a newer version of Sentry as there have been a lot of work on this area and we are not providing support for 9.1.2 anymore.
