### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2112]
https://app.getsentry.com/sentry/sentry/group/56856043/

```
TypeError: 'NoneType' object is not iterable
  File "sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "sentry/event_manager.py", line 442, in save
    **group_kwargs
```

**Comment by mattrobenolt** [comment]
So this is happening when `safe_execute` errors and returns `None`, and it errors unpacking into `group, is_new, is_regression, is_sample`

```python
>>> a, b = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not iterable
```
