### ISSUE TITLE
Sentry ratelimit cannot be changed when using self-hosted

### ISSUE THREAD

**Issue by drook** [getsentry/sentry#21159]
## Important Details

How are you running Sentry?

On-Premise wo/ Docker, version 20.8.0

## Description
Sentry ratelimit cannot be changed when running on premises

## Steps to Reproduce

1. Go to web-interface, Admin/Settings
2. Set a non-zero ratelimit.
3. Get an error.

````
Oct  6 07:18:49 jsentry sentry[4128]: 10.100.33.5 - - [06/Oct/2020:04:18:49 +0000] "GET /api/0/internal/options/ HTTP/1.1" 200 20407 "https://sentry.findmykids.org/manage/settings/" "Mozilla/5.0 (X11; FreeBSD amd64; rv:76.0) Gecko/20100101 Firefox/76.0"
Oct  6 07:19:09 jsentry sentry[4128]: Traceback (most recent call last):
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/api/base.py", line 134, in handle_exception
Oct  6 07:19:09 jsentry sentry[4128]:     response = super(Endpoint, self).handle_exception(exc)
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/djangorestframework-3.6.4-py2.7.egg/rest_framework/views.py", line 449, in handle_exception
Oct  6 07:19:09 jsentry sentry[4128]:     self.raise_uncaught_exception(exc)
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/api/base.py", line 247, in dispatch
Oct  6 07:19:09 jsentry sentry[4128]:     response = handler(request, *args, **kwargs)
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/api/endpoints/system_options.py", line 74, in put
Oct  6 07:19:09 jsentry sentry[4128]:     options.set(k, v)
Oct  6 07:19:09 jsentry sentry[4128]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/options/manager.py", line 83, in set
Oct  6 07:19:09 jsentry sentry[4128]:     "%r cannot be changed at runtime because it is configured on disk" % key
Oct  6 07:19:09 jsentry sentry[4128]: AssertionError: u'system.url-prefix' cannot be changed at runtime because it is configured on disk
Oct  6 07:19:09 jsentry sentry[4128]: 10.100.33.5 - - [06/Oct/2020:04:19:09 +0000] "PUT /api/0/internal/options/ HTTP/1.1" 500 746 "https://sentry.findmykids.org/manage/settings/" "Mozilla/5.0 (X11; FreeBSD amd64; rv:76.0) Gecko/20100101 Firefox/76.0"
````

### What you expected to happen
Ratelimit should be changeable from web-interface.

### Possible Solution
Stop sending system.url-prefix in PUT request ?

**Comment by BYK** [comment]
This seems to be the same issue in https://forum.sentry.io/t/config-yml-vs-manage-settings/10025.

Will look into this soon, thanks a lot for reporting!

**Comment by chadwhitacre** [comment]
I'm able to repro locally when `system.url-prefix` is set via `config.yml`.
