### ISSUE TITLE
HASH: Out of overflow pages.  Increase page size/error: cannot add item to database

### ISSUE THREAD

**Issue by drook** [getsentry/sentry#21158]
## Important Details

How are you running Sentry?

On-Premise wo/ Docker, version 20.8.0

## Description
Got an error: error: cannot add item to database
Immediately after this sentry stopped processing events.

## Steps to Reproduce

Have no idea what's triggering this.

Sentry log:
````
Oct  5 22:28:16 jsentry sentry[4128]: 10.100.33.5 - - [05/Oct/2020:19:28:16 +0000] "GET / HTTP/1.1" 302 454 "-" "check_http/v2.3.3 (nagios-plugins 2.3.3)"
Oct  5 22:28:52 jsentry sentry[4134]: HASH: Out of overflow pages.  Increase page size
Oct  5 22:28:52 jsentry sentry[4134]: celery beat v4.1.1 (latentcall) is starting.
Oct  5 22:28:52 jsentry sentry[4134]: __    -    ... __   -        _
Oct  5 22:28:52 jsentry sentry[4134]: LocalTime -> 2020-10-01 12:51:07
Oct  5 22:28:52 jsentry sentry[4134]: Configuration ->
Oct  5 22:28:52 jsentry sentry[4134]:     . broker -> redis://10.100.33.5:6379/0
Oct  5 22:28:52 jsentry sentry[4134]:     . loader -> celery.loaders.app.AppLoader
Oct  5 22:28:52 jsentry sentry[4134]:     . scheduler -> celery.beat.PersistentScheduler
Oct  5 22:28:52 jsentry sentry[4134]:     . db -> /tmp/sentry-celerybeat
Oct  5 22:28:52 jsentry sentry[4134]:     . logfile -> [stderr]@%WARNING
Oct  5 22:28:52 jsentry sentry[4134]:     . maxinterval -> 5.00 minutes (300s)
Oct  5 22:28:52 jsentry sentry[4134]: Traceback (most recent call last):
Oct  5 22:28:52 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/celery-4.1.1-py2.7.egg/celery/apps/beat.py", line 109, in start_scheduler
Oct  5 22:28:52 jsentry sentry[4134]:     service.start()
Oct  5 22:28:52 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/celery-4.1.1-py2.7.egg/celery/beat.py", line 560, in start
Oct  5 22:28:52 jsentry sentry[4134]:     self.scheduler._do_sync()
Oct  5 22:28:52 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/celery-4.1.1-py2.7.egg/celery/beat.py", line 339, in _do_sync
Oct  5 22:28:52 jsentry sentry[4134]:     self.sync()
Oct  5 22:28:52 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/celery-4.1.1-py2.7.egg/celery/beat.py", line 510, in sync
Oct  5 22:28:52 jsentry sentry[4134]:     self._store.sync()
Oct  5 22:28:52 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/shelve.py", line 169, in sync
Oct  5 22:28:52 jsentry sentry[4134]:     self[key] = entry
Oct  5 22:28:52 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/shelve.py", line 133, in __setitem__
Oct  5 22:28:52 jsentry sentry[4134]:     self.dict[key] = f.getvalue()
Oct  5 22:28:52 jsentry sentry[4134]: error: cannot add item to database
Oct  5 22:28:52 jsentry sentry[4134]: 19:28:52 [CRITICAL] celery.beat: beat raised exception <class 'dbm.error'>: error('cannot add item to database',)
Oct  5 22:28:53 jsentry sentry[4134]: Traceback (most recent call last):
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry_sdk-0.16.5-py2.7.egg/sentry_sdk/integrations/excepthook.py", line 59, in sentry_sdk_excepthook
Oct  5 22:28:53 jsentry sentry[4134]:     hub.capture_event(event, hint=hint)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry_sdk-0.16.5-py2.7.egg/sentry_sdk/hub.py", line 323, in capture_event
Oct  5 22:28:53 jsentry sentry[4134]:     rv = client.capture_event(event, hint, scope)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry_sdk-0.16.5-py2.7.egg/sentry_sdk/client.py", line 327, in capture_event
Oct  5 22:28:53 jsentry sentry[4134]:     event_opt = self._prepare_event(event, hint, scope)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry_sdk-0.16.5-py2.7.egg/sentry_sdk/client.py", line 158, in _prepare_event
Oct  5 22:28:53 jsentry sentry[4134]:     event_ = scope.apply_to_event(event, hint)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry_sdk-0.16.5-py2.7.egg/sentry_sdk/scope.py", line 58, in wrapper
Oct  5 22:28:53 jsentry sentry[4134]:     return fn(self, *args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry_sdk-0.16.5-py2.7.egg/sentry_sdk/scope.py", line 353, in apply_to_event
Oct  5 22:28:53 jsentry sentry[4134]:     return _drop(event, event_processor, "event processor")
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry_sdk-0.16.5-py2.7.egg/sentry_sdk/scope.py", line 308, in _drop
Oct  5 22:28:53 jsentry sentry[4134]:     logger.info("%s (%s) dropped event (%s)", ty, cause, event)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/logging/__init__.py", line 1174, in info
Oct  5 22:28:53 jsentry sentry[4134]:     self._log(INFO, msg, args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/logging/__init__.py", line 1293, in _log
Oct  5 22:28:53 jsentry sentry[4134]:     self.handle(record)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/logging/__init__.py", line 1303, in handle
Oct  5 22:28:53 jsentry sentry[4134]:     self.callHandlers(record)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry_sdk-0.16.5-py2.7.egg/sentry_sdk/integrations/logging.py", line 83, in sentry_patched_callhandlers
Oct  5 22:28:53 jsentry sentry[4134]:     return old_callhandlers(self, record)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
Oct  5 22:28:53 jsentry sentry[4134]:     hdlr.handle(record)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/logging/__init__.py", line 766, in handle
Oct  5 22:28:53 jsentry sentry[4134]:     self.emit(record)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/logging/handlers.py", line 97, in emit
Oct  5 22:28:53 jsentry sentry[4134]:     logger.log(**kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/structlog-17.1.0-py2.7.egg/structlog/stdlib.py", line 102, in log
Oct  5 22:28:53 jsentry sentry[4134]:     return self._proxy_to_logger(_LEVEL_TO_NAME[level], event, *args, **kw)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/structlog-17.1.0-py2.7.egg/structlog/stdlib.py", line 119, in _proxy_to_logger
Oct  5 22:28:53 jsentry sentry[4134]:     **event_kw)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/structlog-17.1.0-py2.7.egg/structlog/_base.py", line 176, in _proxy_to_logger
Oct  5 22:28:53 jsentry sentry[4134]:     args, kw = self._process_event(method_name, event, event_kw)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/structlog-17.1.0-py2.7.egg/structlog/_base.py", line 136, in _process_event
Oct  5 22:28:53 jsentry sentry[4134]:     event_dict = proc(self._logger, method_name, event_dict)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/structlog-17.1.0-py2.7.egg/structlog/stdlib.py", line 275, in __call__
Oct  5 22:28:53 jsentry sentry[4134]:     event_dict["event"] = event_dict["event"] % args
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/UserDict.py", line 205, in __repr__
Oct  5 22:28:53 jsentry sentry[4134]:     return repr(dict(self.iteritems()))
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/UserDict.py", line 143, in iteritems
Oct  5 22:28:53 jsentry sentry[4134]:     for k in self:
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/UserDict.py", line 130, in __iter__
Oct  5 22:28:53 jsentry sentry[4134]:     for k in self.keys():
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/shelve.py", line 101, in keys
Oct  5 22:28:53 jsentry sentry[4134]:     return self.dict.keys()
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/shelve.py", line 79, in closed
Oct  5 22:28:53 jsentry sentry[4134]:     raise ValueError('invalid operation on closed shelf')
Oct  5 22:28:53 jsentry sentry[4134]: ValueError: invalid operation on closed shelf
Oct  5 22:28:53 jsentry sentry[4134]: 19:28:53 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
Oct  5 22:28:53 jsentry sentry[4134]: Traceback (most recent call last):
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/bin/sentry", line 11, in <module>
Oct  5 22:28:53 jsentry sentry[4134]:     load_entry_point('sentry==20.8.0', 'console_scripts', 'sentry')()
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/runner/__init__.py", line 166, in main
Oct  5 22:28:53 jsentry sentry[4134]:     cli(prog_name=get_prog(), obj={}, max_content_width=100)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
Oct  5 22:28:53 jsentry sentry[4134]:     return self.main(*args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
Oct  5 22:28:53 jsentry sentry[4134]:     rv = self.invoke(ctx)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
Oct  5 22:28:53 jsentry sentry[4134]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
Oct  5 22:28:53 jsentry sentry[4134]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
Oct  5 22:28:53 jsentry sentry[4134]:     return ctx.invoke(self.callback, **ctx.params)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
Oct  5 22:28:53 jsentry sentry[4134]:     return callback(*args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 17, in new_func
Oct  5 22:28:53 jsentry sentry[4134]:     return f(get_current_context(), *args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/runner/decorators.py", line 68, in inner
Oct  5 22:28:53 jsentry sentry[4134]:     return ctx.invoke(f, *args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
Oct  5 22:28:53 jsentry sentry[4134]:     return callback(*args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 17, in new_func
Oct  5 22:28:53 jsentry sentry[4134]:     return f(get_current_context(), *args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/runner/decorators.py", line 30, in inner
Oct  5 22:28:53 jsentry sentry[4134]:     return ctx.invoke(f, *args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
Oct  5 22:28:53 jsentry sentry[4134]:     return callback(*args, **kwargs)
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/runner/commands/run.py", line 250, in cron
Oct  5 22:28:53 jsentry sentry[4134]:     **options
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/celery-4.1.1-py2.7.egg/celery/apps/beat.py", line 81, in run
Oct  5 22:28:53 jsentry sentry[4134]:     self.start_scheduler()
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/celery-4.1.1-py2.7.egg/celery/apps/beat.py", line 109, in start_scheduler
Oct  5 22:28:53 jsentry sentry[4134]:     service.start()
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/celery-4.1.1-py2.7.egg/celery/beat.py", line 560, in start
Oct  5 22:28:53 jsentry sentry[4134]:     self.scheduler._do_sync()
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/celery-4.1.1-py2.7.egg/celery/beat.py", line 339, in _do_sync
Oct  5 22:28:53 jsentry sentry[4134]:     self.sync()
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/site-packages/celery-4.1.1-py2.7.egg/celery/beat.py", line 510, in sync
Oct  5 22:28:53 jsentry sentry[4134]:     self._store.sync()
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/shelve.py", line 169, in sync
Oct  5 22:28:53 jsentry sentry[4134]:     self[key] = entry
Oct  5 22:28:53 jsentry sentry[4134]:   File "/usr/local/lib/python2.7/shelve.py", line 133, in __setitem__
Oct  5 22:28:53 jsentry sentry[4134]:     self.dict[key] = f.getvalue()
Oct  5 22:28:53 jsentry sentry[4134]: dbm.error: cannot add item to database
````

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
