### ISSUE TITLE
Problem with opening event page

### ISSUE THREAD

**Issue by levalex** [getsentry/sentry#2138]
Request URL: /api/1/store/
Log:
```
[ERROR] Data not available in preprocess_event (cache_key=e:3908caf9242440568eeb8a0650e55205:1)
[ERROR] Data not available in preprocess_event (cache_key=e:4a8849148a3046848af7f5fe6c38e1a1:1)
[ERROR] Data not available in preprocess_event (cache_key=e:8c9d757334184a73a55bced0d2e9bf57:1)
[ERROR] Data not available in preprocess_event (cache_key=e:72fac615145b4ffca18317d620a9562e:1)
[ERROR] Data not available in preprocess_event (cache_key=e:edecde0e216744cfb462fdcedbd9e175:1)
[ERROR] Data not available in preprocess_event (cache_key=e:f2ede98d4fe1478d9aacbf8938272dc3:1)
[ERROR] Data not available in preprocess_event (cache_key=e:a70678ce5d9247018dc7bf32c3a2c2fd:1)
[ERROR] Data not available in preprocess_event (cache_key=e:9f2a1ebf192440f9a5339984605a909e:1)
[ERROR] Data not available in preprocess_event (cache_key=e:7d19aa3f55fc4391ad3c1e099a4db8e0:1)
[ERROR] Data not available in preprocess_event (cache_key=e:01c17db1dc204aa8b89bce088f479916:1)
[ERROR] Data not available in preprocess_event (cache_key=e:3f5a8e0ddbcc4090a8a2695fcbfbc92a:1)
[ERROR] Data not available in preprocess_event (cache_key=e:47de342f75e2480386aca7e8fd0e15d0:1)
[ERROR] Data not available in preprocess_event (cache_key=e:bc185c4612f2485da9c8babaa1151db5:1)
[ERROR] Data not available in preprocess_event (cache_key=e:9d4a64a01bd14fc0a484dce0334b0d6a:1)
[ERROR] Data not available in preprocess_event (cache_key=e:9b82a63b009743a5a4436422955f7cf4:1)
[ERROR] Data not available in preprocess_event (cache_key=e:6857134cb62b4129bb2261310518651a:1)
[ERROR] Data not available in preprocess_event (cache_key=e:396dbf95a444489ba8868ccc498a6955:1)
[ERROR] Data not available in preprocess_event (cache_key=e:7d526e955a094316924ddf03ed59fc92:1)
[ERROR] Data not available in preprocess_event (cache_key=e:4a6b7721450a4123bcb8c096bf4d22f3:1)
[ERROR] Data not available in preprocess_event (cache_key=e:687d15f515a946b99d8644a49e87d624:1)
[ERROR] Data not available in preprocess_event (cache_key=e:02c67549c2cf48bc956a3ac2190e5708:1)
[ERROR] Data not available in preprocess_event (cache_key=e:b4d317026a2e47048cfae68b11679f3c:1)
[ERROR] Data not available in preprocess_event (cache_key=e:dc982faa36fc4020baa0e7100198d7a2:1)
[ERROR] Data not available in preprocess_event (cache_key=e:04d22e57588a4d6ab1e8a3d46be125ea:1)
[ERROR] Data not available in preprocess_event (cache_key=e:ebbab3989a3e4500957472277c149f57:1)
[ERROR] Data not available in preprocess_event (cache_key=e:c1b7564c66a14cbebc59d83e0760fb6e:1)
[ERROR] Data not available in preprocess_event (cache_key=e:1dd6ea1779eb4e2ab6c5ccc62b24def1:1)
[ERROR] Data not available in preprocess_event (cache_key=e:891c17e31afc4a868357949834161e1e:1)
[ERROR] Data not available in preprocess_event (cache_key=e:975ac2543a5c459f9b6ec82a9d12388f:1)
[ERROR] Data not available in preprocess_event (cache_key=e:d4623d2766ce4d689a11784ea08a1a96:1)
[ERROR] Data not available in preprocess_event (cache_key=e:a4a9900f05244530926a2e3f695df6de:1)
[ERROR] Data not available in preprocess_event (cache_key=e:bb547b55040441d18c044f55c70aec9d:1)
[ERROR] Data not available in preprocess_event (cache_key=e:deeaac129bcf4be18d84feabb3ed7574:1)
Top level Sentry exception caught - failed creating log record
Data not available in preprocess_event (cache_key=%s)
Traceback (most recent call last):
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/raven-5.7.2-py2.7.egg/raven/handlers/logging.py", line 65, in emit
    return self._emit(record)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/raven-5.7.2-py2.7.egg/raven/contrib/django/handlers.py", line 29, in _emit
    return super(SentryHandler, self)._emit(record, request=request)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/raven-5.7.2-py2.7.egg/raven/handlers/logging.py", line 176, in _emit
    extra=extra, date=date, **kwargs)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 42, in capture
    return super(SentryInternalClient, self).capture(*args, **kwargs)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/raven-5.7.2-py2.7.egg/raven/contrib/django/client.py", line 162, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/raven-5.7.2-py2.7.egg/raven/base.py", line 523, in capture
    self.send(**data)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 59, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 236, in get_from_cache
    result = self.get(**kwargs)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/Django-1.6-py2.7.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/Django-1.6-py2.7.egg/django/db/models/query.py", line 301, in get
    num = len(clone)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/Django-1.6-py2.7.egg/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/Django-1.6-py2.7.egg/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/Django-1.6-py2.7.egg/django/db/models/query.py", line 230, in iterator
    obj = model(*row_data)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 50, in __init__
    super(BaseModel, self).__init__(*args, **kwargs)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/Django-1.6-py2.7.egg/django/db/models/base.py", line 419, in __init__
    signals.post_init.send(sender=self.__class__, instance=self)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/Django-1.6-py2.7.egg/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 137, in __post_init
    self.__cache_state(instance)
  File "/opt/sentry/env2/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 129, in __cache_state
    self.__cache[instance] = dict((f, getattr(instance, f)) for f in self.cache_fields)
  File "/usr/lib/python2.7/weakref.py", line 262, in __setitem__
    self.data[ref(key, self._remove)] = value
RuntimeError: maximum recursion depth exceeded
```
Database: empty database + `python manage.py upgrade`
Actions: trying to see details of example event

**Comment by dcramer** [comment]
Looks like some of the recursion detection isnt working, but do you have the SENTRY_CACHE configured correctly?

**Comment by moll** [comment]
Seeing the same thing after upgrading from v7.4 to v7.7, all other things being equal. Except Kombu with its `import kombu.five from monotonic` issue, but fixed that with locking it to 3.0.26...

**Comment by moll** [comment]
I'm running with `CELERY_ALWAYS_EAGER` set to `True` as I can't run background tasks. Could that be related?

**Comment by moll** [comment]
I've tracked this down to having
```
SENTRY_CACHE = "sentry.cache.django.DjangoCache"
```
with presumably no proper `CACHES` settings. Swapping it to the following fixed it for me:
```
SENTRY_CACHE = "sentry.cache.redis.RedisCache"
```

**Comment by dcramer** [comment]
Sentry requires both background workers and (at least) SENTRY_CACHE in production. It's likely you'll run into numerous other problems as well. 






On Mon, Nov 9, 2015 at 2:58 AM -0800, "Andri Möll" <notifications@github.com> wrote:












I've tracked this down to having

SENTRY_CACHE = "sentry.cache.django.DjangoCache"




with presumably no proper CACHES settings. Swapping it to the following fixed it for me:

SENTRY_CACHE = "sentry.cache.redis.RedisCache"

**Comment by moll** [comment]
> Sentry requires both background workers

Setting that CELERY EAGER var to true would work around that, right?

**Comment by dcramer** [comment]
@moll we dont support EAGER in production. It may sort of work, but more likely than not things will immediately break due to cron jobs/etc not running correctly. This is entirely ignoring the fact that some tasks are not fast and would lock up processes, and you likely wouldn't nearly have enough web workers.

**Comment by moll** [comment]
I'm okay with running it non-supported and slowing down web workers (or running in another thread on the same process if that's even possible and I learn Python enough to do so) as long as it technically works. So far seems to work okay for my small load. :-)
