### ISSUE TITLE
Problem with moving to Postgres

### ISSUE THREAD

**Issue by Stayallive** [getsentry/sentry#2169]
Since mysql support is dropping for 8.0 I figured I would try and move our current instance over... that went sublime untill...

```
[ERROR] Internal Server Error: /project/production/
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 236, in wrapped
    return func(request, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 182, in _wrapped
    return func(request, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/groups.py", line 314, in group_list
    }, request)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/helpers.py", line 127, in render_to_response
    response = HttpResponse(render_to_string(template, context, request))
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/web/helpers.py", line 122, in render_to_string
    return loader.render_to_string(template, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/template/base.py", line 613, in resolve
    new_obj = func(obj, *arg_vals)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/javascript.py", line 49, in to_json
    result = transform(obj, request=request)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/javascript.py", line 44, in transform
    return [t(o, request=request) for o in objects]
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/javascript.py", line 62, in __call__
    return self.transform(obj, request)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/javascript.py", line 152, in transform
    status = obj.get_status()
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/models/group.py", line 177, in get_status
    if self.status == GroupStatus.UNRESOLVED and self.is_over_resolve_age():
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/models/group.py", line 168, in is_over_resolve_age
    return self.last_seen < timezone.now() - timedelta(hours=int(resolve_age))
TypeError: can't compare offset-naive and offset-aware datetimes
```

I'm thinking this has something todo with the way [philipsoutham/py-mysql2pgsql](https://github.com/philipsoutham/py-mysql2pgsql) exports/imports the datetimes, can you guys give some pointers?

**Comment by dcramer** [comment]
I dont have a great answer. If you can find a way to convert them to UTC it should work fine.

We also provide an export/import commandset which could let you pull in everything except event data, assuming you can live with losing historical data.

**Comment by Stayallive** [comment]
Thanks @dcramer, I however noticed that the library I was using was not up-to-date in pip so I had an older version, thus an older config file for the migration... so after installing from master (and applying a [pr](https://github.com/philipsoutham/py-mysql2pgsql/pull/86)) there was a timezone configuration item available, set it to true and now we are running on postgres :+1:
