### ISSUE TITLE
Sentry timeouts on smtp send, consecutively errors that the timestamp is either corrupt or in the future !

### ISSUE THREAD

**Issue by AlirezaSadeghi** [getsentry/sentry#2218]
I'm trying to send a test mail to users from my custom sentry setup, this is the error I get when i actually click the "send test email": 

===================================================================
[ERROR] timed out
Traceback (most recent call last):
  File "/home/sentry/.virtualenvs/sentry_env/local/lib/python2.7/site-packages/sentry/models/organizationmember.py", line 182, in send_invite_email
    msg.send([self.get_email()])
  File "/home/sentry/.virtualenvs/sentry_env/local/lib/python2.7/site-packages/sentry/utils/email.py", line 189, in send
    self.send_all(messages, fail_silently=fail_silently)
  File "/home/sentry/.virtualenvs/sentry_env/local/lib/python2.7/site-packages/sentry/utils/email.py", line 194, in send_all
    return connection.send_messages(messages)
  File "/home/sentry/.virtualenvs/sentry_env/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "/home/sentry/.virtualenvs/sentry_env/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 48, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
timeout: timed out
Discarded invalid value for timestamp: datetime.datetime(2015, 10, 29, 14, 15, 8)
Traceback (most recent call last):
  File "/home/sentry/.virtualenvs/sentry_env/local/lib/python2.7/site-packages/sentry/coreapi.py", line 262, in validate_data
    process_data_timestamp(data)
  File "/home/sentry/.virtualenvs/sentry_env/local/lib/python2.7/site-packages/sentry/coreapi.py", line 227, in process_data_timestamp
    raise InvalidTimestamp('Invalid value for timestamp (in future): %r' % data['timestamp'])
InvalidTimestamp: Invalid value for timestamp (in future): datetime.datetime(2015, 10, 29, 14, 15, 8)
Discarded invalid value for timestamp: datetime.datetime(2015, 10, 29, 14, 15, 8)
Traceback (most recent call last):
  File "/home/sentry/.virtualenvs/sentry_env/local/lib/python2.7/site-packages/sentry/coreapi.py", line 262, in validate_data
    process_data_timestamp(data)
  File "/home/sentry/.virtualenvs/sentry_env/local/lib/python2.7/site-packages/sentry/coreapi.py", line 227, in process_data_timestamp
    raise InvalidTimestamp('Invalid value for timestamp (in future): %r' % data['timestamp'])
InvalidTimestamp: Invalid value for timestamp (in future): datetime.datetime(2015, 10, 29, 14, 15, 8)
Discarded invalid value for timestamp: datetime.datetime(2015, 10, 29, 14, 15, 8)

===================================================================

Notice I'm doing all these on 21st of October, but somehow, sentry does something inside to think it's 8 days in the future ! 

For reference, this is my SMTP config: 

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mandrillapp.com'
EMAIL_HOST_PASSWORD = 'WHATEVER'
EMAIL_HOST_USER = 'info@ronash.co'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_SENDER = 'info@ronash.co'
DEFAULT_FROM_EMAIL = 'info@ronash.co'
SERVER_EMAIL = 'info@ronash.co'

**Comment by dcramer** [comment]
The timestamp error is unrelated to email. Did you change the time zone setting?

Email you're going to have to dig into on your own, as the timeout isnt Sentry's fault (we use Mandrill ourselves and it works fine).

**Comment by AlirezaSadeghi** [comment]
@dcramer Timezone is set to UTC, I don't think letting the timezone be UTC would pose any problem would it ? And also even if it does, why the timestamp is in the future (8 days!)? how did that happen when I only installed sentry and clicked "Test email" without changing anything ? that really is an internal thing IMO, also the "date" command shows the right time so it's not the case where server's time is set incorrectly.
(... Also the time being in future might be the culprit of the failing email situation i guess).
Any ideas ?

**Comment by dcramer** [comment]
It def should be set to UTC (its possible to change it, but that likely breaks things).

Is it possible your client is sending future dates? What about the local system timezone? Maybe our internal client isnt accounting for things correctly?

**Comment by AlirezaSadeghi** [comment]
@dcramer Well timezone's definitely set to UTC.

Also it's worth noting that this issue is not being caused by the clients, It only happens when the system tries to send an email through SMTP. One particular case is when I try to send test from this page
http://sentry.domain.com/manage/status/mail/, the logs I've posted above are generated in /var/log/sentry-web.log.

I didn't understand this part of your comment : "Maybe our internal client isnt accounting for things correctly?", would you mind explaining further ?
Thanks !
