### ISSUE TITLE
Error when running `make bootstrap`:django.db.utils.OperationalError: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by Zuckjet** [getsentry/sentry#22317]
### version info

source code version: the newest master branch(newest commit id: de226c8363565bc89d67fd8c044de671cdf1cdfc)

docker version:
```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Docker Desktop version(MacOS): 2.5.0.1(49550)
Ddocker-compose version 1.27.4, build 40524192
MacOS version: Macos Catalina 10.15.4

### Steps to Reproduce
1. source .venv/bin/activate
2. make bootstrap (run this command will throw error)

### logs
```
Traceback (most recent call last):
  File "/Users/guest/2020/sentry/.venv/bin/sentry", line 11, in <module>
    load_entry_point('sentry', 'console_scripts', 'sentry')()
  File "/Users/guest/2020/sentry/src/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100) #zhu-111
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/guest/2020/sentry/src/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs) #zhu-222
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/guest/2020/sentry/src/sentry/runner/commands/upgrade.py", line 174, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore) #zhu-444
  File "/Users/guest/2020/sentry/src/sentry/runner/commands/upgrade.py", line 121, in _upgrade
    _migrate_from_south(verbosity)
  File "/Users/guest/2020/sentry/src/sentry/runner/commands/upgrade.py", line 93, in _migrate_from_south
    if not _has_south_history(connection):
  File "/Users/guest/2020/sentry/src/sentry/runner/commands/upgrade.py", line 78, in _has_south_history
    cursor = connection.cursor()
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/Users/guest/2020/sentry/src/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/Users/guest/2020/sentry/src/sentry/db/postgres/base.py", line 99, in _cursor
    return super(DatabaseWrapper, self)._cursor()
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    self.ensure_connection()
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 215, in ensure_connection
    self.connect()
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 215, in ensure_connection
    self.connect()
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 191, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/guest/2020/sentry/.venv/lib/python2.7/site-packages/psycopg2/__init__.py", line 131, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: fe_sendauth: no password supplied

make: *** [apply-migrations] Error 1
```

### more info
I also deploy sentry local about three weeks ago through onpremise. this issue is similar to [this one](https://github.com/getsentry/onpremise/issues/713). And I have tried all methods under that issue comment(such as delete sentry_postgres volume/container), but still cannot fix this error

**Comment by armenzg** [comment]
Thanks for filing. I will try to look into this tomorrow.

**Comment by armenzg** [comment]
@Zuckjet are you still facing this issue?

I run out of time this week to look into this issue but I would encourage you to print out the information from `connection = Database.connect(**conn_params)` to see if somehow the values are not being passed correctly. Restarting the whole host and starting from a clean `.venv` could help. If you could upgrade to Python 3 it would be ideal. I'm mostly interested to see if you can get a small test case to see why you're not able to connect to the Postgress container.

Also, we landed support for Python 3 by default this week. Let me know if you have any issues upgrading to it.

**Comment by Zuckjet** [comment]
upgrade to Python 3 solved this issue, thanks

**Comment by armenzg** [comment]
🎉 Thank you for switching over!
