### ISSUE TITLE
Upgrading fails with sentry 7.7.1 under windows

### ISSUE THREAD

**Issue by VolmerM** [getsentry/sentry#2234]
Hello,

I try to install sentry 7.7.1 with postgreSQL 8.4 under windows 7
I have install a redis service, the postgeSQL database, python 2.7.6 and sentry in an virtualenv
The communication to the database works, because with the "sentry syncdb --all" new tables will be created.

'''
 (elster_test3) C:\env\elster_test3\Scripts>sentry --config=settings.py upgrade
Syncing...
Creating tables ...
[ERROR] Internal project (id=1) does not exist
[ERROR] Internal project (id=1) does not exist
[ERROR] Internal project (id=1) does not exist
[ERROR] Internal project (id=1) does not exist
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\env\elster_test3\Scripts\sentry.exe\__main__.py", line 9, in <module>
  File "C:\env\elster_test3\lib\site-packages\sentry\utils\runner.py", line 448, in main
    initializer=initialize_app,
  File "C:\env\elster_test3\lib\site-packages\logan\runner.py", line 193, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "C:\env\elster_test3\lib\site-packages\django\core\management\__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "C:\env\elster_test3\lib\site-packages\django\core\management\__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\env\elster_test3\lib\site-packages\django\core\management\base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\env\elster_test3\lib\site-packages\raven\contrib\django\management\__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "C:\env\elster_test3\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "C:\env\elster_test3\lib\site-packages\sentry\management\commands\upgrade.py", line 34, in handle
    verbosity=options['verbosity'],
  File "C:\env\elster_test3\lib\site-packages\django\core\management\__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "C:\env\elster_test3\lib\site-packages\raven\contrib\django\management\__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "C:\env\elster_test3\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "C:\env\elster_test3\lib\site-packages\django\core\management\base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "C:\env\elster_test3\lib\site-packages\sentry\..\south\management\commands\syncdb.py", line 92, in handle_noargs
    syncdb.Command().execute(**options)
  File "C:\env\elster_test3\lib\site-packages\raven\contrib\django\management\__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "C:\env\elster_test3\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "C:\env\elster_test3\lib\site-packages\django\core\management\base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "C:\env\elster_test3\lib\site-packages\django\core\management\commands\syncdb.py", line 112, in handle_noargs
    emit_post_sync_signal(created_models, verbosity, interactive, db)
  File "C:\env\elster_test3\lib\site-packages\django\core\management\sql.py", line 216, in emit_post_sync_signal
    interactive=interactive, db=db)
  File "C:\env\elster_test3\lib\site-packages\django\dispatch\dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\env\elster_test3\lib\site-packages\django\contrib\auth\management\__init__.py", line 82, in create_permissions
    ctype = ContentType.objects.db_manager(db).get_for_model(klass)
  File "C:\env\elster_test3\lib\site-packages\django\contrib\contenttypes\models.py", line 47, in get_for_model
    defaults = {'name': smart_text(opts.verbose_name_raw)},
  File "C:\env\elster_test3\lib\site-packages\django\db\models\manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "C:\env\elster_test3\lib\site-packages\django\db\models\query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "C:\env\elster_test3\lib\site-packages\django\db\models\base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\env\elster_test3\lib\site-packages\django\db\models\base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "C:\env\elster_test3\lib\site-packages\django\dispatch\dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\env\elster_test3\lib\site-packages\sentry\receivers\stats.py", line 13, in record_instance_creation
    metrics.incr('objects.created.all')
  File "C:\env\elster_test3\lib\site-packages\sentry\utils\metrics.py", line 28, in incr
    tsdb.incr(tsdb.models.internal, key, count=amount)
  File "C:\env\elster_test3\lib\site-packages\sentry\tsdb\redis.py", line 96, in incr
    self.incr_multi([(model, key)], timestamp, count)
  File "C:\env\elster_test3\lib\site-packages\sentry\tsdb\redis.py", line 111, in incr_multi
    norm_rollup = normalize_to_rollup(timestamp, rollup)
  File "C:\env\elster_test3\lib\site-packages\sentry\tsdb\base.py", line 79, in normalize_to_rollup
    epoch = int(timestamp.strftime('%s'))
ValueError: Invalid format string
'''

My config file looks like this:
'''
# This file is just Python, with a touch of Django which means
# you can inherit and tweak settings to your hearts content.
from sentry.conf.server import *

import os.path

CONF_ROOT = os.path.dirname(__file__)

DATABASES = {
    'default': {
        # You can swap out the engine for MySQL easily by changing this value
        # to ``django.db.backends.mysql`` or to PostgreSQL with
        # ``sentry.db.postgres``

        # If you change this, you'll also need to install the appropriate python
        # package: psycopg2 (Postgres) or mysql-python
        #'ENGINE': 'django.db.backends.sqlite3',
        'ENGINE': 'django.db.backends.postgresql_psycopg2',

        #'NAME': os.path.join(CONF_ROOT, 'sentry.db'),
        'NAME': 'sentry',
        'USER': 'core',
        'PASSWORD': 'exam',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# You should not change this setting after your database has been created
# unless you have altered all schemas first
SENTRY_USE_BIG_INTS = True

#SENTRY_PUBLIC
#Should Sentry make all data publicly accessible
#This should only be used if you are installing Sentry behind your companys firewall.
#Defaults to False.
SENTRY_PUBLIC = True

# If you're expecting any kind of real traffic on Sentry, we highly recommend
# configuring the CACHES and Redis settings

###########
# General #
###########

# The administrative email for this installation.
# Note: This will be reported back to getsentry.com as the point of contact. See
# the beacon documentation for more information. This **must** be a string.

# SENTRY_ADMIN_EMAIL = 'your.name@example.com'
SENTRY_ADMIN_EMAIL = 'Martin.Volmer@elster.com'

# Instruct Sentry that this install intends to be run by a single organization
# and thus various UI optimizations should be enabled.
SENTRY_SINGLE_ORGANIZATION = True

SENTRY_PROJECT=1

#########
# Redis #
#########

# Generic Redis configuration used as defaults for various things including:
# Buffers, Quotas, TSDB

SENTRY_REDIS_OPTIONS = {
    'hosts': {
        0: {
            'host': '127.0.0.1',
            'port': 6379,
        }
    }
}

#########
# Cache #
#########

# If you wish to use memcached, install the dependencies and adjust the config
# as shown:
#
#   pip install python-memcached
#
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': ['127.0.0.1:11211'],
#     }
# }
#
# SENTRY_CACHE = 'sentry.cache.django.DjangoCache'

SENTRY_CACHE = 'sentry.cache.redis.RedisCache'

#########
# Queue #
#########

# See https://docs.getsentry.com/on-premise/server/queue/ for more
# information on configuring your queue broker and workers. Sentry relies
# on a Python framework called Celery to manage queues.

CELERY_ALWAYS_EAGER = False
BROKER_URL = 'redis://localhost:6379'

###############
# Rate Limits #
###############

# Rate limits apply to notification handlers and are enforced per-project
# automatically.

SENTRY_RATELIMITER = 'sentry.ratelimits.redis.RedisRateLimiter'

##################
# Update Buffers #
##################

# Buffers (combined with queueing) act as an intermediate layer between the
# database and the storage API. They will greatly improve efficiency on large
# numbers of the same events being sent to the API in a short amount of time.
# (read: if you send any kind of real data to Sentry, you should enable buffers)

SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'

##########
# Quotas #
##########

# Quotas allow you to rate limit individual projects or the Sentry install as
# a whole.

SENTRY_QUOTAS = 'sentry.quotas.redis.RedisQuota'

########
# TSDB #
########

# The TSDB is used for building charts as well as making things like per-rate
# alerts possible.

SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'

################
# File storage #
################

# Any Django storage backend is compatible with Sentry. For more solutions see
# the django-storages package: https://django-storages.readthedocs.org/en/latest/

SENTRY_FILESTORE = 'django.core.files.storage.FileSystemStorage'
SENTRY_FILESTORE_OPTIONS = {
    'location': '/tmp/sentry-files',
}

##############
# Web Server #
##############

# You MUST configure the absolute URI root for Sentry:
#SENTRY_URL_PREFIX = 'http://sentry.example.com'  # No trailing slash!
SENTRY_URL_PREFIX = 'http://localhost'

# If you're using a reverse proxy, you should enable the X-Forwarded-Proto
# header and uncomment the following settings
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True

SENTRY_WEB_HOST = '0.0.0.0'
SENTRY_WEB_PORT = 9000
SENTRY_WEB_OPTIONS = {
    'workers': 3,  # the number of gunicorn workers
    #'secure_scheme_headers': {'X-FORWARDED-PROTO': 'https'},
}

###############
# Mail Server #
###############

# For more information check Django's documentation:
#  https://docs.djangoproject.com/en/1.3/topics/email/?from=olddocs#e-mail-backends

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'localhost'
EMAIL_HOST_PASSWORD = ''
EMAIL_HOST_USER = ''
EMAIL_PORT = 25
EMAIL_USE_TLS = False

# The email address to send on behalf of
SERVER_EMAIL = 'root@localhost'

# If you're using mailgun for inbound mail, set your API key and configure a
# route to forward to /api/hooks/mailgun/inbound/
MAILGUN_API_KEY = ''

########
# etc. #
########

# If this file ever becomes compromised, it's important to regenerate your SECRET_KEY
# Changing this value will result in all current sessions being invalidated
SECRET_KEY = 'W34vrHG/JMR0372jYB80gqMAxKBCMLNlCTpbLIPByr3C6uC4vnWLMg=='
'''

Is there an installation guide for Windows?

**Comment by dcramer** [comment]
Sentry does not support Windows
