### ISSUE TITLE
Upgrade config fails caused by 'GLIBC_2.14' not found.

### ISSUE THREAD

**Issue by vernonzheng** [getsentry/sentry#2268]
I completed installing sentry 7.7.1 with python 2.7 on CentOS 6.2.

But when i tried to upgrade sentry config, it reported fail and error message as follows.

I checked the latest GLIBC version on my os is 2.12. So i guessed it may be caused by sentry 7.7.1 compiled in GLIBC 2.14 that is higher than the version in my os environment, then i tired a older sentry version as 7.3.2 , but it came to the same result.

What should i do to fix this?  Thanks.

```shell
(sentry)[root@112_50 sentry]# sentry --config=/etc/sentry.conf.py upgrade
Traceback (most recent call last):
  File "/www/sentry/lib/python2.7/site-packages/logan/runner.py", line 101, in settings_callback
    'settings': settings,
  File "/www/sentry/lib/python2.7/site-packages/sentry/utils/runner.py", line 313, in initialize_app
    settings, 'kombu.contrib.django', 'djkombu_queue')
  File "/www/sentry/lib/python2.7/site-packages/sentry/utils/runner.py", line 375, in skip_migration_if_applied
    migration = Migrations(app_name)[name]
  File "/www/sentry/lib/python2.7/site-packages/south/migration/base.py", line 64, in __call__
    self.instances[app_label] = super(MigrationsMetaclass, self).__call__(app_label_to_app_module(app_label), **kwds)
  File "/www/sentry/lib/python2.7/site-packages/south/migration/utils.py", line 41, in app_label_to_app_module
    app = models.get_app(app_label)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/loading.py", line 179, in get_app
    self._populate()
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/www/sentry/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/www/sentry/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 20, in <module>
    from sentry.utils.email import MessageBuilder, group_id_to_email
  File "/www/sentry/lib/python2.7/site-packages/sentry/utils/email.py", line 17, in <module>
    import toronado
  File "/www/sentry/lib/python2.7/site-packages/toronado/__init__.py", line 9, in <module>
    from lxml import html
  File "/www/sentry/lib/python2.7/site-packages/lxml/html/__init__.py", line 42, in <module>
    from lxml import etree
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib64/libxslt.so.1)
```

**Comment by mattrobenolt** [comment]
So my best guess is that a dependency was compiled against a version, then something since has been upgraded or downgraded to cause the mismatch. 

Could your try to reinstall both libxslt and lxml?

**Comment by dcramer** [comment]
Going to close this out as its not a Sentry bug and theres not much we can act on here.

**Comment by vernonzheng** [comment]
Finally, I downgraded its version to 6.4.4, and it worked well. 
Thanks anyway.
