### ISSUE TITLE
Add native view for Java exceptions

### ISSUE THREAD

**Issue by foal** [getsentry/sentry#2273]
Below the 'standard' view of Java exception that I can copy/paste to IDE to navigate in the code. It will be nice to have the same in the Sentry. Now I need to find out the application logs to locate the original exception. 

```
Caused by: java.lang.IllegalStateException: java.lang.ArrayIndexOutOfBoundsException: -1
        at org.jresearch.commons.gwt.server.service.DomainAdapter.mapAsCollection(DomainAdapter.java:96) ~[org.jresearch.commons.gwt.base-1.0.2-SNAPSHOT.jar:na]
        at org.jresearch.commons.gwt.server.service.DomainAdapter.mapAsList(DomainAdapter.java:79) ~[org.jresearch.commons.gwt.base-1.0.2-SNAPSHOT.jar:na]
        at com.jresearchsoft.booking.gwt.server.service.ServiceProviderServiceImpl.getEditableServiceProviders(ServiceProviderServiceImpl.java:102) ~[com.jresearchsoft.booking.gwt.model-1.0.0-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587) ~[gwt-servlet-2.7.0.jar:na]
        ... 46 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:418) ~[na:1.8.0_66]
        at java.util.ArrayList.get(ArrayList.java:431) ~[na:1.8.0_66]
        at com.jresearchsoft.booking.gwt.server.orika.BookingClassMappings.get(BookingClassMappings.java:299) ~[com.jresearchsoft.booking.gwt.model-1.0.0-SNAPSHOT.jar:na]
        at com.jresearchsoft.booking.gwt.server.orika.BookingClassMappings.access$200(BookingClassMappings.java:71) ~[com.jresearchsoft.booking.gwt.model-1.0.0-SNAPSHOT.jar:na]
        at com.jresearchsoft.booking.gwt.server.orika.BookingClassMappings$4.mapAtoB(BookingClassMappings.java:189) ~[com.jresearchsoft.booking.gwt.model-1.0.0-SNAPSHOT.jar:na]
        at com.jresearchsoft.booking.gwt.server.orika.BookingClassMappings$4.mapAtoB(BookingClassMappings.java:184) ~[com.jresearchsoft.booking.gwt.model-1.0.0-SNAPSHOT.jar:na]
        at ma.glasnost.orika.generated.Orika_ServiceProviderModel_ServiceProviderDto_Mapper2677199590656313$5.mapAtoB(Orika_ServiceProviderModel_ServiceProviderDto_Mapper2677199590656313$5.java) ~[na:na]
        at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:67) ~[orika-core-1.4.5.jar:na]
        at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:735) ~[orika-core-1.4.5.jar:na]
        at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:714) ~[orika-core-1.4.5.jar:na]
        at ma.glasnost.orika.impl.ConfigurableMapper.map(ConfigurableMapper.java:150) ~[orika-core-1.4.5.jar:na]
        at org.jresearch.commons.gwt.server.service.DomainAdapter.mapAsCollection(DomainAdapter.java:87) ~[org.jresearch.commons.gwt.base-1.0.2-SNAPSHOT.jar:na]
        ... 53 common frames omitted
```

**Comment by mattrobenolt** [comment]
@foal Do you mean inside the "Raw" view in the UI?

**Comment by foal** [comment]
I think yes - it is a most suitable place in UI for such exception view.

**Comment by tkaemming** [comment]
We recently (as part of [getsentry/raven-java@v7.0.0](https://github.com/getsentry/raven-java/tree/v7.0.0)) fixed the issues with missing filenames.

For example, what is shown in the console in this case using [getsentry/raven-java@v7.1.0](https://github.com/getsentry/raven-java/tree/v7.1.0) from [raven-java-examples](https://github.com/getsentry/raven-java-examples):

```
java.lang.ArithmeticException: / by zero
        at com.getsentry.example.Application.main(Application.java:13) ~[classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293) [exec-maven-plugin-1.4.0.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
```

… gets rendered in the web UI like this:

```
ArithmeticException: / by zero
    at java.lang.Thread.run(Thread.java:745)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at com.getsentry.example.Application.main(Application.java:13)
```

There are a few weird things going on here:

- The stacktrace is in the reverse order. I'm not sure if this is an issue rendering it on the server, or an issue with the data.
- The `invoke0` native method is sending a filename, but no line number and isn't being rendered as `Native Code` in the UI.
- The exception includes the full module path in the JVM trace, and isn't included in the payload sent to Sentry. This seems to be a rendering error.

Full JSON dump of the payload: [event.json.zip](https://github.com/getsentry/sentry/files/190156/event.json.zip)

**Comment by bretthoerner** [comment]
> The exception includes the full module path in the JVM trace, and isn't included in the payload sent to Sentry. This seems to be a rendering error.

Yeah, `module` (which holds `java.lang`) is being sent properly as a sibling key to `type` (which holds `ArithmeticException`). I assume we'd fix this at the frontend (or Sentry) level rather than sending `java.lang.ArithmeticException` as the `type`?

**Comment by bretthoerner** [comment]
For what it's worth, as the `raw` output stands today, it works well in IntelliJ. I think files + line numbers was the most critical fix.

That said, as you noted @ted, it would be useful to display in the "proper" Java order, and to add the module to the exception type. Tab depth, classpath bracket thing and native code don't have any real effect on it for me. I guess I can try out Eclipse also.

**Comment by tkaemming** [comment]
We fixed the ordering and module path with GH-2924. I'm expecting other issues to be a wash (native code, classpath details, tab depth) but we can reopen if those prove to be problematic.
