### ISSUE TITLE
Cannot send email with "mail.use-tls: true" config. ssl.SSLError: [SSL: DH_KEY_TOO_SMALL]

### ISSUE THREAD

**Issue by shinebayar-g** [getsentry/sentry#22869]
## Important Details

How are you running Sentry?

On-Premise 20.12.1
Ubuntu 20.04.1 LTS
Docker 20.10.0

## Description

I've configured SMTP settings for email invitation. Unfortunately if I enable `mail.use-tls: true` setting, Sentry cannot send any email.

## Steps to Reproduce

1. edit `sentry/config.yml` enable SMTP settings and set `mail.use-tls: true`
2. send email invitation.

Sentry logs:

```
web_1                                       | 07:45:47 [INFO] sentry.mail: mail.queued (message_type='organization.invite' organization_id=1 message_id='<20201225074545.23.49554@mydomain.com>' message_to=('user@mydomain.com',))
web_1                                       | 07:45:47 [INFO] sentry.audit.api: member.edit (ip_address='73.73.73.73' organization_id=1 object_id=2 entry_id=5 actor_label='admin@mydomain.com' actor_id=1)
nginx_1                                     | 192.168.0.1 - - [25/Dec/2020:07:45:47 +0000] "PUT /api/0/organizations/sentry/members/2/ HTTP/1.1" 200 2193 "https://sentry.mydomain.com/settings/sentry/members/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36" "73.73.73.73"
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
worker_1                                    |     R = retval = fun(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
worker_1                                    |     return self.run(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
worker_1                                    |     reraise(*exc_info)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise
worker_1                                    |     raise value
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
worker_1                                    |     return f(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/sentry/tasks/base.py", line 48, in _wrapped
worker_1                                    |     result = func(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/sentry/tasks/email.py", line 76, in send_email
worker_1                                    |     send_messages([message])
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/sentry/utils/email.py", line 408, in send_messages
worker_1                                    |     sent = connection.send_messages(messages)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
worker_1                                    |     new_conn_created = self.open()
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 69, in open
worker_1                                    |     self.connection.starttls(keyfile=self.ssl_keyfile, certfile=self.ssl_certfile)
worker_1                                    |   File "/usr/local/lib/python3.6/smtplib.py", line 771, in starttls
worker_1                                    |     server_hostname=self._host)
worker_1                                    |   File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
worker_1                                    |     _context=self, _session=session)
worker_1                                    |   File "/usr/local/lib/python3.6/ssl.py", line 817, in __init__
worker_1                                    |     self.do_handshake()
worker_1                                    |   File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake
worker_1                                    |     self._sslobj.do_handshake()
worker_1                                    |   File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
worker_1                                    |     self._sslobj.do_handshake()
worker_1                                    | ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:852)
worker_1                                    | 07:45:49 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[31cc18bd-bcc3-440f-bec9-d4704faadb92] raised unexpected: SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:852)') (data={'hostname': 'd721cd65b5b2', 'id': '31cc18bd-bcc3-440f-bec9-d4704faadb92', 'name': 'sentry.tasks.email.send_email', 'exc': "SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:852)')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/base.py", line 48, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/email.py", line 76, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.6/site-packages/sentry/utils/email.py", line 408, in send_messages\n    sent = connection.send_messages(messages)\n  File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 69, in open\n    self.connection.starttls(keyfile=self.ssl_keyfile, certfile=self.ssl_certfile)\n  File "/usr/local/lib/python3.6/smtplib.py", line 771, in starttls\n    server_hostname=self._host)\n  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket\n    _context=self, _session=session)\n  File "/usr/local/lib/python3.6/ssl.py", line 817, in __init__\n    self.do_handshake()\n  File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake\n    self._sslobj.do_handshake()\n  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake\n    self._sslobj.do_handshake()\nssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:852)\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f6a291725c0>}", 'description': 'raised unexpected', 'internal': False})
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
worker_1                                    |     (self._dns_host, self.port), self.timeout, **extra_kw)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
worker_1                                    |     raise err
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
worker_1                                    |     sock.connect(sa)
worker_1                                    | ConnectionRefusedError: [Errno 111] Connection refused
worker_1                                    |
worker_1                                    | During handling of the above exception, another exception occurred:
worker_1                                    |
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
worker_1                                    |     chunked=chunked)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
worker_1                                    |     self._validate_conn(conn)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
worker_1                                    |     conn.connect()
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
worker_1                                    |     conn = self._new_conn()
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
worker_1                                    |     self, "Failed to establish a new connection: %s" % e)
worker_1                                    | urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f6a28ef9f98>: Failed to establish a new connection: [Errno 111] Connection refused
worker_1                                    |
worker_1                                    | During handling of the above exception, another exception occurred:
worker_1                                    |
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/transport.py", line 326, in send_event_wrapper
worker_1                                    |     self._send_event(event)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/transport.py", line 234, in _send_event
worker_1                                    |     headers={"Content-Type": "application/json", "Content-Encoding": "gzip"},
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/transport.py", line 180, in _send_request
worker_1                                    |     headers=headers,
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 72, in request
worker_1                                    |     **urlopen_kw)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 150, in request_encode_body
worker_1                                    |     return self.urlopen(method, url, **extra_kw)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 324, in urlopen
worker_1                                    |     response = conn.urlopen(method, u.request_uri, **kw)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
worker_1                                    |     **response_kw)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
worker_1                                    |     **response_kw)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
worker_1                                    |     **response_kw)
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
worker_1                                    |     _stacktrace=sys.exc_info()[2])
worker_1                                    |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
worker_1                                    |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
worker_1                                    | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sentry.mydomain.com', port=443): Max retries exceeded with url: /api/1/store/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6a28ef9f98>: Failed to establish a new connection: [Errno 111] Connection refused',))
worker_1                                    | 07:45:49 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
relay_1                                     | 2020-12-25T07:45:51Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 60s
```

### What you expected to happen

I expect sending email successfully over encrypted network. However it doesn't work. if I set `mail.use-tls: false` Sentry can send email over plain HTTP.
I checked my SMTP server's credentials and SSL settings, they're working as expected.

**Comment by BYK** [comment]
Looks like your SMTP server is using a weak SSL cert: https://stackoverflow.com/a/38016392/90297
