### ISSUE TITLE
Pulling changes and applying migrations automatically fails when dev services are down

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#23162]
CC @billyvg 

It would be ideal to either not apply them when they're down OR to start them up.

```
[!!!]  It looks like some dependencies have changed that will require your intervention. Run the following to update:

    make apply-migrations

--> Applying migrations
sentry upgrade
g13:33:16 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
13:33:20 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/redis/connection.py", line 539, in connect
    sock = self._connect()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/redis/connection.py", line 596, in _connect
    raise err
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/redis/connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/src/sentry/buffer/redis.py", line 67, in validate
    client.ping()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/redis/client.py", line 1106, in ping
    return self.execute_command('PING')
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
    return old_execute_command(self, name, *args, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/rb/clients.py", line 488, in execute_command
    buf = self._get_command_buffer(host_id, args[0])
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/rb/clients.py", line 355, in _get_command_buffer
    buf = CommandBuffer(host_id, connect, self.auto_batch)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/rb/clients.py", line 91, in __init__
    self.connect()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/rb/clients.py", line 107, in connect
    self.connection = self._connect_func()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/rb/clients.py", line 353, in connect
    return self.connection_pool.get_connection(command_name, shard_hint=host_id)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/rb/clients.py", line 254, in get_connection
    con = real_pool.get_connection(command_name)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/.venv/bin/sentry", line 33, in <module>
    sys.exit(load_entry_point('sentry', 'console_scripts', 'sentry')())
  File "/Users/armenzg/code/sentry/src/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/armenzg/code/sentry/src/sentry/runner/decorators.py", line 29, in inner
    configure()
  File "/Users/armenzg/code/sentry/src/sentry/runner/__init__.py", line 129, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/Users/armenzg/code/sentry/src/sentry/runner/settings.py", line 158, in configure
    skip_service_validation=skip_service_validation,
  File "/Users/armenzg/code/sentry/src/sentry/runner/initializer.py", line 380, in initialize_app
    setup_services(validate=not skip_service_validation)
  File "/Users/armenzg/code/sentry/src/sentry/runner/initializer.py", line 422, in setup_services
    service.validate()
  File "/Users/armenzg/code/sentry/src/sentry/utils/services.py", line 105, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/Users/armenzg/code/sentry/src/sentry/buffer/redis.py", line 69, in validate
    raise InvalidConfiguration(six.text_type(e))
sentry.exceptions.InvalidConfiguration: Error 61 connecting to 127.0.0.1:6379. Connection refused.
make: *** [apply-migrations] Error 1
```

**Comment by BYK** [comment]
FYI `docker-compose` automatically handles dependencies (over at getsentry/onpremise).

**Comment by bc-sentry** [comment]
New devservices has configuration for apply-migration
