### ISSUE TITLE
Runserver not working?

### ISSUE THREAD

**Issue by Kronuz** [getsentry/sentry#2318]
`./manage.py runserver` is throwing an exception (`./manage.py start` works):

```python
Traceback (most recent call last):
  File "./manage.py", line 36, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 80, in handle
    self.run(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/sentry/management/commands/runserver.py", line 70, in run
    watcher_list = self.run_watchers(**options)
  File "/usr/local/lib/python2.7/site-packages/sentry/management/commands/runserver.py", line 51, in run_watchers
    env = self.get_env()
  File "/usr/local/lib/python2.7/site-packages/sentry/management/commands/runserver.py", line 38, in get_env
    'SENTRY_CONF': env.data['config'],
KeyError: 'config'
```

**Comment by dcramer** [comment]
``manage.py`` isnt part of Sentry and wouldn't be able to run as it requires the Sentry runtime bootstrapper (handled by Logan)
