### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by michailw** [getsentry/sentry#2329]
Centos 6.6, 64 bit
```
$ SENTRY_CONF=/www/sentry/sentry.conf.py sentry upgrade

/usr/lib64/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/logan/runner.py", line 116, in settings_callback
    'settings': settings,
  File "/usr/lib/python2.6/site-packages/sentry/utils/runner.py", line 298, in initialize_app
    install_plugins(settings)
  File "/usr/lib/python2.6/site-packages/sentry/utils/runner.py", line 234, in install_plugins
    from sentry.plugins import register
  File "/usr/lib/python2.6/site-packages/sentry/plugins/__init__.py", line 10, in <module>
    from sentry.plugins.base import *  # NOQA
  File "/usr/lib/python2.6/site-packages/sentry/plugins/base/__init__.py", line 14, in <module>
    from sentry.plugins.base.v1 import *  # NOQA
  File "/usr/lib/python2.6/site-packages/sentry/plugins/base/v1.py", line 18, in <module>
    from sentry.auth import access
  File "/usr/lib/python2.6/site-packages/sentry/auth/__init__.py", line 3, in <module>
    from .provider import *  # NOQA
  File "/usr/lib/python2.6/site-packages/sentry/auth/provider.py", line 5, in <module>
    from .view import ConfigureView
  File "/usr/lib/python2.6/site-packages/sentry/auth/view.py", line 6, in <module>
    from sentry.web.frontend.base import BaseView
  File "/usr/lib/python2.6/site-packages/sentry/web/frontend/base.py", line 15, in <module>
    from sentry.auth import access
  File "/usr/lib/python2.6/site-packages/sentry/auth/access.py", line 46
     return {s.replace(':', '_'): self.has_scope(s) for s in SCOPES}
                                                      ^
 SyntaxError: invalid syntax
```

**Comment by mattrobenolt** [comment]
Hey @michailw, unfortunately, we don't attempt to work with python 2.6. We require 2.7.
