### ISSUE TITLE
Error processing 'rule_notify' on 'MailPlugin': [Errno 111] Connection refused

### ISSUE THREAD

**Issue by andreas4all** [getsentry/sentry#2359]
I sending a message to Sentry and I have a rule to send notification to email. So I got this in logs in celery worker. Testing mail from settings was send correctly. I use own mail server with TLS. Sentry is in docker. Sentry is 7.7.0.

Do you have any ideas?

```
[2015-11-24 11:39:20,868: ERROR/Worker-2] Error processing 'rule_notify' on 'MailPlugin': [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 59, in rule_notify
    self.notify(notification)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 190, in notify
    context=context,
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 55, in _send_mail
    return msg.send()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/email.py", line 189, in send
    self.send_all(messages, fail_silently=fail_silently)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/email.py", line 194, in send_all
    return connection.send_messages(messages)
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 48, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
```

```
user@a43f5d89c3d4:~$ celery status
celery@a43f5d89c3d4: OK

1 node online.
```

**Comment by mattrobenolt** [comment]
Hey @andreas4all, this just simply means that the Sentry process can't reach your SMTP server. Are you sure your settings are correct and you can reach the mail server from that container?

**Comment by andreas4all** [comment]
yes I checked it. Ping works and I try also `openssl s_client -starttls snpm -connect mail.myserver.com -tls` and this works. As I write before, testing email from sentry web is sendet correctly.

**Comment by mattrobenolt** [comment]
So my only guess is that the configuration in the celery worker process is different from the web process. The test would have gotten sent by the web process, while this error is coming from the worker. 

But I'm going to close this since it's not an issue with Sentry, but an issue with your configuration/setup.

**Comment by andreas4all** [comment]
Thank you for your reply. Yes, I have different configuration on web and worker (different containers).
