### ISSUE TITLE
Error: Permission Denied : /manage/status/packages/

### ISSUE THREAD

**Issue by BYK** [getsentry/sentry#23805]
## Important Details

How are you running Sentry?

SaaS and self-hosted

## Description

https://sentry.io/organizations/sentry/issues/1548794848/?referrer=asana_plugin

```
Error: Permission Denied : /manage/status/packages/
  at callback (./app/views/permissionDenied.tsx:34:31)
  at componentDidMount (./app/views/permissionDenied.tsx:28:5)
  at handleError (./app/components/asyncComponent.tsx:327:10)
  at apply (./app/components/asyncComponent.tsx:272:16)
  at errorCb (./app/api.tsx:164:21)
...
(24 additional frame(s) were not displayed)
```

## Steps to Reproduce

Visit /manage/status/packages/

### What you expected to happen

/manage/status/packages/ to list the status of the packages

### Possible Solution

No idea at the moment.

**Comment by chadwhitacre** [comment]
Closing as stale, lmk if this is still relevant @BYK. 🙏
