### ISSUE TITLE
I fail to restore apitoken.scope_list from backup.json 

### ISSUE THREAD

**Issue by e2-robert** [getsentry/sentry#23989]
### Version Information

Version: *20.9.0*

### Steps to Reproduce

Have at least one API token set up.

1.Backup: `docker-compose run --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web export > sentry/backup.json`
2. Restore: `docker-compose run --rm -T web import /etc/sentry/backup.json`

### Expected Result

Restore without error.
`backup.json` should contain this line:
```
"scope_list": "[\"event:read\", \"project:read\", \"project:write\", \"event:write\", \"project:admin\", \"event:admin\"]",
```

### Actual Result

Error occurs: `DeserializationError: Expecting value`

### Logs

```
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/backup.py", line 15, in import_
    for obj in serializers.deserialize("json", src, stream=True, use_natural_keys=True):
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 88, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 181, in Deserializer
    raise base.DeserializationError.WithData(e, d['model'], d.get('pk'), field_value)
django.core.serializers.base.DeserializationError: Expecting value: line 1 column 2 (char 1): (sentry.apitoken:pk=6) field_value was '[u"event:read", u"project:read", u"project:write", u"event:write", u"project:admin", u"event:admin"]'
```

`backup.json` instead contained that line after backup:
```
    "scope_list": "[u'event:read', u'project:read', u'project:write', u'event:write', u'project:admin', u'event:admin']",
```

**Comment by BYK** [comment]
Duplicate of #23843

**Comment by BYK** [comment]
Meant to close when I marked as a duplicate.
