### ISSUE TITLE
ImportError: No module named buffer.redis

### ISSUE THREAD

**Issue by wanghe4096** [getsentry/sentry#2460]
I am mac os x 10.11.2
I can run 'python setup.py develop', It's pass. But execute 'sentry init&sentry upgrade' follow error: 

Traceback (most recent call last):
  File "/Users/wanghe/work/projects/sentry/env/lib/python2.7/site-packages/logan-0.7.1-py2.7.egg/logan/runner.py", line 116, in settings_callback
    'settings': settings,
  File "/Users/wanghe/work/projects/sentry/src/sentry/utils/runner.py", line 341, in initialize_app
    register_plugins(settings)
  File "/Users/wanghe/work/projects/sentry/src/sentry/utils/runner.py", line 256, in register_plugins
    from sentry.plugins import register
  File "/Users/wanghe/work/projects/sentry/src/sentry/plugins/__init__.py", line 10, in <module>
    from sentry.plugins.base import *  # NOQA
  File "/Users/wanghe/work/projects/sentry/src/sentry/plugins/base/__init__.py", line 11, in <module>
    from sentry.plugins.base.notifier import *  # NOQA
  File "/Users/wanghe/work/projects/sentry/src/sentry/plugins/base/notifier.py", line 13, in <module>
    from sentry.app import ratelimiter
  File "/Users/wanghe/work/projects/sentry/src/sentry/app.py", line 30, in <module>
    buffer = get_instance(settings.SENTRY_BUFFER, settings.SENTRY_BUFFER_OPTIONS)
  File "/Users/wanghe/work/projects/sentry/src/sentry/app.py", line 24, in get_instance
    cls = import_string(path)
  File "/Users/wanghe/work/projects/sentry/src/sentry/utils/imports.py", line 37, in import_string
    result = _cache[path]
  File "/Users/wanghe/work/projects/sentry/src/sentry/utils/imports.py", line 20, in __missing__
    module = __import__(module_name, {}, {}, [class_name], -1)

**Comment by dcramer** [comment]
Something is wrong with how you're built the app. It's possibly you're not in the virtualenv or the path is getting made relative/causing bad imports.

Try going through setup again and confirming things are correct. Also you may consider installing 8.0.0-rc1 instead

**Comment by wanghe4096** [comment]
thank you
