### ISSUE TITLE
TypeError: create_alert_rule() missing 1 required positional argument: 'owner'

### ISSUE THREAD

**Issue by krasnoperov** [getsentry/sentry#24639]
### Version Information

Version: Sentry 21.3.0 96d5172

### Steps to Reproduce

1. Download new sentry from https://github.com/getsentry/onpremise/archive/21.3.0.tar.gz
2. Configure, install with `./install.sh --no-user-prompt`, run `docker-compose up -d`
3. Create  new project.
2. Try to create new metrics alert https://sentry.terra.songsterr.com/organizations/sentry/alerts/draw/new/?referrer=alert_stream
3. Fill all fields, click on Save Rule.

### Expected Result

Alert created.

### Actual Result

Error shown: Unable to save. Internal Error ERRORID

### Logs

`docker logs --tail 14 sentry_onpremise_web_1`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/api/base.py", line 119, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/sentry/api/base.py", line 232, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/incidents/endpoints/project_alert_rule_index.py", line 97, in post
    alert_rule = serializer.save()
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 215, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.6/site-packages/sentry/incidents/endpoints/serializers.py", line 536, in create
    **validated_data,
TypeError: create_alert_rule() missing 1 required positional argument: 'owner'
```

Internal sentry projects catches:

`TypeError /api/0/projects/{organization_slug}/{project_slug}/alert-rules/`
`create_alert_rule() missing 1 required positional argument: 'owner'`

```
curl \
 -X POST \
 --compressed \
 -H "Accept: application/json; charset=utf-8" \
 -H "Accept-Encoding: gzip, deflate, br" \
 -H "Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7" \
 -H "Content-Length: 377" \
 -H "Content-Type: application/json" \
 -H "Host: sentry.terra.songsterr.com" \
 -H "Origin: https://sentry.terra.songsterr.com" \
 -H "Referer: https://sentry.terra.songsterr.com/organizations/sentry/alerts/draw/new/?referrer=alert_stream" \
 -H "Sec-Ch-Ua: \"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"" \
 -H "Sec-Ch-Ua-Mobile: ?0" \
 -H "Sec-Fetch-Dest: empty" \
 -H "Sec-Fetch-Mode: cors" \
 -H "Sec-Fetch-Site: same-origin" \
 -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36" \
 -H "X-Csrftoken: TOKEN" \
 -H "X-Forwarded-For: 188.162.143.96, 172.20.0.1" \
 -H "X-Forwarded-Proto: http" \
 -H "X-Real-Ip: 188.162.143.96" \
 -H "X-Request-Id: 252e5998b7755ff8bcc7e79bb6dd7644" \
 --data "{\"aggregate\":\"count()\",\"dataset\":\"events\",\"environment\":null,\"eventTypes\":[\"error\"],\"projects\":[\"draw\"],\"query\":\"\",\"resolveThreshold\":null,\"thresholdType\":0,\"timeWindow\":1,\"triggers\":[{\"actions\":[{\"options\":\"None\",\"targetIdentifier\":\"'1'\",\"targetType\":\"'team'\",\"type\":\"'email'\"}],\"alertThreshold\":1,\"label\":\"critical\"},{\"actions\":[],\"alertThreshold\":1,\"label\":\"warning\"}]}" \
 "http://sentry.terra.songsterr.com/api/0/projects/sentry/draw/alert-rules/?referrer=alert_stream&sessionId=SESSION"
```

**Comment by BYK** [comment]
This was fixed in #24458.

You can use the latest nightlies until we release 21.3.1 with the patch included. Thanks a lot for bringing this up!

/cc @iProgramStuff @chadwhitacre
