### ISSUE TITLE
Import error on sentry upgrade

### ISSUE THREAD

**Issue by juanmas07** [getsentry/sentry#2472]
I'm following up the steps to install on ubuntu.  But I'm getting an error  when running this command, and I cannot address it

SENTRY_CONF=/etc/sentry sentry upgrade

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/sentry/runner/__init__.py", line 131, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sentry/runner/decorators.py", line 25, in inner
    configure()
  File "/usr/local/lib/python2.7/dist-packages/sentry/runner/__init__.py", line 94, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/usr/local/lib/python2.7/dist-packages/sentry/runner/settings.py", line 337, in configure
    }, skip_backend_validation=skip_backend_validation)
  File "/usr/local/lib/python2.7/dist-packages/sentry/runner/initializer.py", line 105, in initialize_app
    bootstrap_options(settings, config['options'])
  File "/usr/local/lib/python2.7/dist-packages/sentry/runner/initializer.py", line 96, in bootstrap_options
    settings.SENTRY_OPTIONS[k] = v
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/sentry/runner/importer.py", line 51, in load_module
    reraise_as(ConfigurationError(msg))
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/settings.py", line 48, in reraise_as
    six.reraise(new_type, new_exception, e_traceback)
  File "/usr/local/lib/python2.7/dist-packages/sentry/runner/importer.py", line 43, in load_module
    mod = self._load_module(fullname)
  File "/usr/local/lib/python2.7/dist-packages/sentry/runner/importer.py", line 61, in _load_module
    from django.utils.importlib import import_module
sentry.runner.importer.ConfigurationError: ImportError: No module named importlib

**Comment by mattrobenolt** [comment]
Hmm, this is a bit concerning and I can't reproduce.

Can you paste the output from `pip freeze` please? It seems that somehow you have a different version of Django than we require somehow.

**Comment by juanmas07** [comment]
yes

(sentry)juan@cloud:/etc/sentry$ pip freeze
Django==1.9
importlib==1.0.3
wheel==0.24.0

**Comment by mattrobenolt** [comment]
Yeah, we require Django 1.6. You're going to have a whole other mess of problems with Django 1.9.

Not even sure how you got Django 1.9 since we explicitly declare `Django>=1.6.0,<1.7` as a dependency.

How did you install?

**Comment by mattrobenolt** [comment]
_closing since we don't support 1.9 and don't plan to_

**Comment by juanmas07** [comment]
Yes I think I've used sudo with pip, now:

(sentry)juan@cloud:/etc/sentry$ pip freeze
amqp==1.4.8
anyjson==0.3.3
BeautifulSoup==3.2.1
billiard==3.3.0.22
celery==3.1.18
cffi==1.4.1
contextlib2==0.4.0
cryptography==1.1.2
cssselect==0.9.1
cssutils==0.9.10
Django==1.6.11
django-bitfield==1.7.1
django-crispy-forms==1.4.0
django-jsonfield==0.9.13
django-paging==0.2.5
django-picklefield==0.3.2
django-recaptcha==1.0.4
django-social-auth==0.7.28
django-statsd-mozilla==0.3.14
django-sudo==1.1.3
django-templatetag-sugar==1.0
djangorestframework==2.3.14
email-reply-parser==0.2.0
enum34==0.9.23
exam==0.10.5
funcsigs==0.4
gunicorn==19.4.1
httplib2==0.9.2
idna==2.0
importlib==1.0.3
ipaddr==2.1.11
ipaddress==1.0.15
kombu==3.0.26
logan==0.7.1
lxml==3.5.0
Markdown==2.4.1
mock==1.3.0
ndg-httpsclient==0.4.0
nydus==0.11.0
oauth2==1.9.0.post1
pbr==1.8.1
petname==1.7
progressbar==2.3
py==1.4.31
pyasn1==0.1.9
pycparser==2.14
pyOpenSSL==0.15.1
pytest==2.8.5
pytest-django==2.9.1
python-dateutil==2.4.2
python-memcached==1.57
python-openid==2.2.5
pytz==2015.7
raven==5.9.2
redis==2.10.5
requests==2.5.3
sentry==7.7.4
setproctitle==1.1.9
simplejson==3.3.3
six==1.10.0
South==1.0.1
statsd==3.1
toronado==0.0.7
ua-parser==0.5.1
urllib3==1.7.1
wheel==0.24.0

**Comment by mattrobenolt** [comment]
That output looks more correct. I'm not entirely sure what you're doing, but sounds like you've installed it wrong.

I'd start with a new virtualenv and start over. :)

**Comment by juanmas07** [comment]
thanks
