### ISSUE TITLE
Strict requirement of redis-server >= v2.8.9 in sentry 8.0

### ISSUE THREAD

**Issue by nikolaik** [getsentry/sentry#2503]
Tried to upgrade to sentry 8.0 on Ubuntu 14.04 LTS server, but sentry setup validation failed since trusty is stuck on [redis-server v2.8.4](http://packages.ubuntu.com/trusty/redis-server)

```
(sentry)sentry@iceking:/var/www/sentry# sentry --config /etc/sentry.conf.py upgrade
Traceback (most recent call last):
  File "/var/www/sentry/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 131, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 25, in inner
    configure()
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 94, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 337, in configure
    }, skip_backend_validation=skip_backend_validation)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 146, in initialize_app
    validate_backends()
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 169, in validate_backends
    backend.validate()
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 86, in validate
    label='TSDB',
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/redis.py", line 67, in check_cluster_versions
    recommended,
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/versioning.py", line 45, in check_versions
    raise InvalidConfiguration(make_upgrade_message(service, 'must', required, must_upgrade))
sentry.exceptions.InvalidConfiguration: Redis (TSDB) must be upgraded to 2.8.9 on 127.0.0.1:6379.
```

The requirement is specified in [src/sentry/tsdb/redis.py](https://github.com/getsentry/sentry/blob/master/src/sentry/tsdb/redis.py#L85)

Are there any python deps or issues blocking a minimum requirement of redis-server v2.8.4 ? I think supporting ubuntu 14.04 atleast until 16.04.1 is released could possibly increase adoption of 8.0.

**Comment by mattrobenolt** [comment]
We need 2.8.9 as a minimum for HyperLogLog support, unfortunately.

For Trusty, you can very easily install from a PPA like: https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server
