### ISSUE TITLE
Sentry fails to start

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#2515]
I'm using master branch at 09f9a1ccf74d27e8d4c9205b78d4685ee8e8b267.  click is 6.2.

This is the traceback:

```
Traceback (most recent call last):
  File "/srv/sentry8/bin/sentry", line 9, in <module>
    load_entry_point('sentry==8.0.0rc2', 'console_scripts', 'sentry')()
  File "/srv/sentry8/src/sentry/src/sentry/runner/__init__.py", line 136, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/srv/sentry8/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/srv/sentry8/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/srv/sentry8/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/sentry8/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/sentry8/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/srv/sentry8/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/sentry8/src/sentry/src/sentry/runner/decorators.py", line 26, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/srv/sentry8/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/srv/sentry8/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: start() takes exactly 7 arguments (6 given)
```

**Comment by mvaled** [comment]
@mattrobenolt I think this is due to 09fc449e3b4a525221bbaaeac97b799521aa9428 leaving the `debug` argument in the `start` function...

**Comment by mvaled** [comment]
Since the `debug` is an argument to the service being started I simply made it to be `debug=False` and this allowed me to start the sentry.

**Comment by mattrobenolt** [comment]
Oops. :( Thanks @mitsuhiko.
