### ISSUE TITLE
Can't add a user account via Django admin

### ISSUE THREAD

**Issue by LewisTehMinerz** [getsentry/sentry#25192]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 21.4.0.dev0 7794c56

## Description

Django admin panel causes 500 when attempting to add a user account.

## Steps to Reproduce

1. Go to Django admin (/admin)
2. Click "Add" next to Users
3. The following exception occurs:

<details>
<summary>Exception</summary>

```
web_1                                       | 19:43:21 [INFO] sentry.superuser: superuser.request (url='http://<REDACTED>/admin/sentry/user/add/' method='GET' ip_address='<REDACTED>' user_id=1)
web_1                                       | Traceback (most recent call last):
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1                                       |     response = get_response(request)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
web_1                                       |     response = self._get_response(request)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1                                       |     response = self.process_exception_by_middleware(e, request)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1                                       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/sentry/../sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
web_1                                       |     return callback(request, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 552, in wrapper
web_1                                       |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
web_1                                       |     response = view_func(request, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
web_1                                       |     response = view_func(request, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
web_1                                       |     return view(request, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
web_1                                       |     return bound_func(*args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
web_1                                       |     return view(request, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
web_1                                       |     return func.__get__(self, type(self))(*args2, **kwargs2)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
web_1                                       |     return bound_func(*args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
web_1                                       |     response = view_func(request, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
web_1                                       |     return func.__get__(self, type(self))(*args2, **kwargs2)
web_1                                       |   File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
web_1                                       |     return func(*args, **kwds)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/sentry/admin.py", line 265, in add_view
web_1                                       |     return super().add_view(request, form_url, extra_context)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1509, in add_view
web_1                                       |     return self.changeform_view(request, None, form_url, extra_context)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
web_1                                       |     return bound_func(*args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
web_1                                       |     response = view_func(request, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
web_1                                       |     return func.__get__(self, type(self))(*args2, **kwargs2)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1409, in changeform_view
web_1                                       |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1438, in _changeform_view
web_1                                       |     ModelForm = self.get_form(request, obj)
web_1                                       |   File "/usr/local/lib/python3.6/site-packages/sentry/admin.py", line 223, in get_form
web_1                                       |     {"form": self.add_form, "fields": admin.util.flatten_fieldsets(self.add_fieldsets)}
web_1                                       | AttributeError: module 'django.contrib.admin' has no attribute 'util'
web_1                                       | 19:43:21 [ERROR] django.request: Internal Server Error: /admin/sentry/user/add/ (status_code=500 request=<WSGIRequest: GET '/admin/sentry/user/add/'>)
```

</details>

### What you expected to happen

Can create a user account via Django admin.

**Comment by BYK** [comment]
We do not support Django admin for many tasks. Why do you need to create a user from this section instead of signing up a user or using the `createuser` command?

**Comment by LewisTehMinerz** [comment]
At the time the e-mail server was not set up so I could not add users through a regular sign up and the idea of sentry-cli completely slipped my mind. I couldn't find an option to add a user through the admin dashboard so I tried Django to no avail.

**Comment by BYK** [comment]
@LewisTehMinerz If `createuser` fixes your issue, I'll go ahead and close this issue but also take note that we should probably document this a bit clearer. Thoughts?

**Comment by LewisTehMinerz** [comment]
Yeah, it does. Thank you for the quick response.
