### ISSUE TITLE
Can't connect Github to Sentry

### ISSUE THREAD

**Issue by mikevercoelen** [getsentry/sentry#25258]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

My Github account IS connected to Sentry, but does NOT show up under configurations 

(see screenshots)

## Steps to Reproduce

See screenshots.

### What you expected to happen

It should link correctly.

<img width="1090" alt="Screenshot 2021-04-14 at 20 13 41" src="https://user-images.githubusercontent.com/3009836/114708799-6a400800-9d5e-11eb-8d4a-a117934ba650.png">
<img width="1290" alt="Screenshot 2021-04-14 at 20 12 55" src="https://user-images.githubusercontent.com/3009836/114708812-6ca26200-9d5e-11eb-8745-916cd745bb21.png">

Also the "Report issue" link is dead:

<img width="1325" alt="Screenshot 2021-04-14 at 20 14 35" src="https://user-images.githubusercontent.com/3009836/114708827-70ce7f80-9d5e-11eb-93b7-d1d2ec568f95.png">

**Comment by manuzope** [comment]
Hi @mikevercoelen, Github only allows you to install on one Sentry organization at a time and it looks like your Github is already linked to another Sentry organization. 

So, you will need to uninstall Sentry from your Github account then re-install it on the organization you want.

Thanks for reporting the broken link! We'll get that fixed.

**Comment by mikevercoelen** [comment]
Is there no way to link it to both? I'm part of multiple organisations, and I can't choose between them I need to both.

**Comment by manuzope** [comment]
Unfortunately, not at the moment. Here's a more detailed explanation https://github.com/getsentry/sentry/issues/24995#issuecomment-814497909 of why this is hard.

**Comment by mikevercoelen** [comment]
That sucks, makes it impossible for us to use Sentry properly.

**Comment by manuzope** [comment]
I'm assuming you want to use the Github integration for release tracking? My best suggestion would be do that without the Github integration: https://docs.sentry.io/product/cli/releases/#alternatively-without-a-repository-integration

**Comment by jcalonsoh** [comment]
Hi all may I add this

```
16:38:18 [INFO] sentry.superuser: superuser.request (url='https://sentry.aud-opr.augmented.globant.com/extensions/github-enterprise/setup/?code=e3dc4e60eab63b002662&state=8f8e14b23fac4cbab298667513366177' method='GET' ip_address='10.240.96.80' user_id=1)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/sentry/integrations/github_enterprise/integration.py:330: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('100.64.39.222', 42190), raddr=('10.54.2.160', 443)>
user = get_user_info(installation_data["url"], identity["access_token"])
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
return callback(request, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
return view_func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/sentry/web/frontend/base.py", line 221, in dispatch
return self.handle(request, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/sentry/web/decorators.py", line 59, in wrapped
return func(request, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/sentry/web/frontend/pipeline_advancer.py", line 53, in handle
return pipeline.current_step()
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 232, in current_step
return step.dispatch(request=self.request, pipeline=self)
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 107, in dispatch
return nested_pipeline.current_step()
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 232, in current_step
return step.dispatch(request=self.request, pipeline=self)
File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
return view_func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/sentry/identity/oauth2.py", line 235, in dispatch
return pipeline.next_step()
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 260, in next_step
return self.current_step()
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 232, in current_step
return step.dispatch(request=self.request, pipeline=self)
File "/usr/local/lib/python3.6/site-packages/sentry/identity/oauth2.py", line 336, in dispatch
return pipeline.next_step()
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 260, in next_step
return self.current_step()
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 224, in current_step
return self.finish_pipeline()
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 89, in finish_pipeline
return self.parent_pipeline.next_step()
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 260, in next_step
return self.current_step()
File "/usr/local/lib/python3.6/site-packages/sentry/pipeline/__init__.py", line 224, in current_step
return self.finish_pipeline()
File "/usr/local/lib/python3.6/site-packages/sentry/integrations/pipeline.py", line 37, in finish_pipeline
data = self.provider.build_integration(self.state.data)
File "/usr/local/lib/python3.6/site-packages/sentry/integrations/github_enterprise/integration.py", line 332, in build_integration
installation_data, identity["access_token"], state["installation_id"]
File "/usr/local/lib/python3.6/site-packages/sentry/integrations/github_enterprise/integration.py", line 317, in get_installation_info
resp.raise_for_status()
File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://github.corp.globant.com/api/v3/user/installations?access_token=c502036b3f4560647c7ce5ca1b72adde50726298
16:38:19 [ERROR] django.request: Internal Server Error: /extensions/github-enterprise/setup/ (status_code=500 request=<WSGIRequest: GET '/extensions/github-enterprise/setup/?code=e3dc4e60eab63b002662&state=8f8e14b23fac4cbab298667513366177'>)
100.64.4.218 - - [28/May/2021:16:38:18 +0000] "GET /extensions/github-enterprise/setup/?code=e3dc4e60eab63b002662&state=8f8e14b23fac4cbab298667513366177 HTTP/1.0" 500 7787 "https://github.corp.globant.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
172.29.8.219 - - [28/May/2021:16:38:24 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.17+"
```

Issue from I have 404 https://forum.sentry.io/t/unsure-about-github-enterprise-new-app-configurations/12516 forum and
Github docs on v3

https://docs.github.com/en/enterprise-server@3.0/rest/reference/apps#list-installations-for-the-authenticated-app

**Comment by jcalonsoh** [comment]
this also happens with GHE

**Comment by jcalonsoh** [comment]
Also SaaS is not working

![image](https://user-images.githubusercontent.com/1545140/120038645-9394ba80-bfd1-11eb-9b07-8dc1269dd51b.png)

**Comment by jcalonsoh** [comment]
Self Hosted and SaaS

**Comment by jcalonsoh** [comment]
The PR that fix this issue is here https://github.com/getsentry/sentry/pull/26281/files

**Comment by BYK** [comment]
@jcalonsoh hey, thanks for connecting the dots from the forum and to the PR you referred. That said this issue seems to be about something else so I'd refrain from adding more unrelated stuff here as a courtesy of the original poster and tracking their request. 

I'll be hiding your comments as "off-topic" to keep the issue to point. You may create a new issue or just follow that PR to see when it gets merged and goes out.

**Comment by jcalonsoh** [comment]
I hope PR https://github.com/getsentry/sentry/pull/26281/files finish and gets merged to use latest unknown version for sentry selfhosted

**Comment by manuzope** [comment]
Oops forgot to close this out. The report link has been fixed (https://github.com/getsentry/sentry/pull/25331) and multiple github installations is not actionable in the foreseeable future.
