### ISSUE TITLE
When merged python trace, then traced

### ISSUE THREAD

**Issue by hustcc** [getsentry/sentry#2564]
Hello, maybe I found a bug? Help me to confirm.

When I merged some trace, then open the `related events tab page`, http 500 code at `/api/0/issues/12/events/?limit=50&query=`, log below:

```py
10.240.145.127 - - [18/Jan/2016:12:42:13 +0000] "PUT /api/0/projects/xxx/ooo/issues/?id=12 HTTP/1.1" 200 17 "http://ip:9000/xx_org/xx/issues/12/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/base.py", line 81, in handle_exception
    return super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/base.py", line 143, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/endpoints/group_events.py", line 50, in get
    paginator_cls=DateTimePaginator,
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/base.py", line 178, in paginate
    results = on_results(cursor_result.results)
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/endpoints/group_events.py", line 49, in <lambda>
    on_results=lambda x: serialize(x, request.user),
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/serializers/base.py", line 32, in serialize
    attrs = serializer.get_attrs(item_list=objects, user=user)
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/serializers/models/event.py", line 27, in get_attrs
    Event.objects.bind_nodes(item_list, 'data')
  File "/usr/local/lib/python2.7/dist-packages/sentry/db/models/manager.py", line 309, in bind_nodes
    node.bind_data(data, ref=node.get_ref(item))
  File "/usr/local/lib/python2.7/dist-packages/sentry/db/models/fields/node.py", line 96, in bind_data
    self.id, ref, self.ref,
NodeIntegrityFailure: Node reference for S2O3tK4HT86w9ciMRZra4w== is invalid: 12 != 27
```
 I hide the Ip address and Organization name in the trace log. How to solve it?

**Comment by dcramer** [comment]
@hustcc this is resolved in master, but I dont think it was pushed out as part of our 8.0.1 release. We'll see about getting this out as another bugfix release.

**Comment by hustcc** [comment]
@dcramer I used 8.0.0, So I need upgrate. Thxs!

**Comment by dcramer** [comment]
Looks like it's not in 8.0.1. We will aim to get an 8.0.2 out which includes it.

**Comment by hustcc** [comment]
OK, I will be here waiting for you.

**Comment by hustcc** [comment]
upgrade to 8.0.2, But also:
```py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/base.py", line 81, in handle_exception
    return super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/base.py", line 143, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/endpoints/group_events.py", line 50, in get
    paginator_cls=DateTimePaginator,
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/base.py", line 178, in paginate
    results = on_results(cursor_result.results)
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/endpoints/group_events.py", line 49, in <lambda>
    on_results=lambda x: serialize(x, request.user),
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/serializers/base.py", line 32, in serialize
    attrs = serializer.get_attrs(item_list=objects, user=user)
  File "/usr/local/lib/python2.7/dist-packages/sentry/api/serializers/models/event.py", line 27, in get_attrs
    Event.objects.bind_nodes(item_list, 'data')
  File "/usr/local/lib/python2.7/dist-packages/sentry/db/models/manager.py", line 309, in bind_nodes
    node.bind_data(data, ref=node.get_ref(item))
  File "/usr/local/lib/python2.7/dist-packages/sentry/db/models/fields/node.py", line 96, in bind_data
    self.id, ref, self.ref,
NodeIntegrityFailure: Node reference for a/ZCxItLSJWTdjeUf50awQ== is invalid: 48 != 47
```

When merge event, and then Click into the merged event, then click `related events`.
![image](https://cloud.githubusercontent.com/assets/7856674/12442309/ea543e3e-bf89-11e5-8112-329bed072883.png)

**Comment by dcramer** [comment]
@hustcc thats not 8.0.2's code unless somethings greatly messed up in the release tarball

**Comment by hustcc** [comment]
i am sorry, my fault.
Very nice, bug has been fixed.
