### ISSUE TITLE
sentry-server 21.5.1, pip install, run web in project failed

### ISSUE THREAD

**Issue by bruce121381** [getsentry/sentry#26349]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version x.y.z
On-pip, python version 3.6.13
Saas (sentry.io)
python3 version 3.6.13

## Description
i use `sentry run web` and `sentry run worker` to start a sentry-server, it started, 
but when i click sentry web in project tag, its seems doesnt work like this
![image](https://user-images.githubusercontent.com/49523421/120435162-fc07e100-c3af-11eb-9569-7815f33a6081.png)
and then 

## Steps to Reproduce

1. [First Step]
    run `pip3 install -U sentry --user`, use `sentry run web` and `sentry run worker` to start sentry-server 
2. [Second Step]
    in chrome use http://ip:port to view sentry backend
3. and so on.
    click project tag 
Good items to include here include:

- stacktrace like this:
```
06:41:14 [INFO] sentry.superuser: superuser.request (url='http://10.218.4.97:9000/api/0/organizations/sentry/user-teams/' method='GET' ip_address='172.18.88.109' user_id=1)
06:41:14 [INFO] sentry_sdk.errors: Discarded session update because of missing release
06:41:15 [INFO] sentry.superuser: superuser.request (url='http://10.218.4.97:9000/api/0/teams/sentry/teachee-backend-test/members/' method='GET' ip_address='172.18.88.109' user_id=1)
06:41:15 [INFO] sentry.superuser: superuser.request (url='http://10.218.4.97:9000/api/0/teams/sentry/sentry/members/' method='GET' ip_address='172.18.88.109' user_id=1)
06:41:15 [INFO] sentry_sdk.errors: Discarded session update because of missing release
06:41:15 [INFO] sentry_sdk.errors: Discarded session update because of missing release
06:41:15 [INFO] sentry.superuser: superuser.request (url='http://10.218.4.97:9000/api/0/organizations/sentry/projects/?statsPeriod=24h&query=id%3A1+id%3A2&transactionStats=1' method='GET' ip_address='172.18.88.109' user_id=1)
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/python3/lib/python3.6/http/client.py", line 1287, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/python3/lib/python3.6/http/client.py", line 1333, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/python3/lib/python3.6/http/client.py", line 1282, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/python3/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/local/python3/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f10add41550>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/sentry/utils/snuba.py", line 848, in _snuba_query
    _snuba_pool.urlopen("POST", "/query", body=body, headers=headers),
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  [Previous line repeated 2 more times]
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/.local/lib/python3.6/site-packages/sentry/utils/snuba.py", line 310, in increment
    _stacktrace=_stacktrace,
  File "/root/.local/lib/python3.6/site-packages/sentry/../urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1218): Max retries exceeded with url: /query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f10add41550>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/sentry/api/base.py", line 117, in handle_exception
    response = super().handle_exception(exc)
  File "/root/.local/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.local/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/root/.local/lib/python3.6/site-packages/sentry/api/base.py", line 230, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/sentry/api/endpoints/organization_projects.py", line 119, in get
    paginator_cls=OffsetPaginator,
  File "/root/.local/lib/python3.6/site-packages/sentry/api/base.py", line 325, in paginate
    results = on_results(cursor_result.results)
  File "/root/.local/lib/python3.6/site-packages/sentry/api/endpoints/organization_projects.py", line 112, in serialize_on_result
    return serialize(result, request.user, serializer)
  File "/root/.local/lib/python3.6/site-packages/sentry/api/serializers/base.py", line 81, in serialize
    **kwargs,
  File "/root/.local/lib/python3.6/site-packages/sentry/api/serializers/models/project.py", line 440, in get_attrs
    attrs = super().get_attrs(item_list, user)
  File "/root/.local/lib/python3.6/site-packages/sentry/api/serializers/models/project.py", line 342, in get_attrs
    attrs = super().get_attrs(item_list, user)
  File "/root/.local/lib/python3.6/site-packages/sentry/api/serializers/models/project.py", line 206, in get_attrs
    stats = self.get_stats(project_ids, "!event.type:transaction")
  File "/root/.local/lib/python3.6/site-packages/sentry/api/serializers/models/project.py", line 273, in get_stats
    top_events=top_events,
  File "/root/.local/lib/python3.6/site-packages/sentry/snuba/discover.py", line 537, in top_events_timeseries
    referrer=referrer,
  File "/root/.local/lib/python3.6/site-packages/sentry/utils/snuba.py", line 657, in raw_query
    snql_option=snql_option,
  File "/root/.local/lib/python3.6/site-packages/sentry/utils/snuba.py", line 698, in bulk_raw_query
    params, referrer=referrer, use_cache=use_cache, snql_option=snql_option
  File "/root/.local/lib/python3.6/site-packages/sentry/utils/snuba.py", line 734, in _apply_cache_and_build_results
    query_results = _bulk_snuba_query(map(itemgetter(1), to_query), headers, snql_option)
  File "/root/.local/lib/python3.6/site-packages/sentry/utils/snuba.py", line 785, in _bulk_snuba_query
    query_results = [query_fn((snuba_param_list[0], Hub(Hub.current), headers))]
  File "/root/.local/lib/python3.6/site-packages/sentry/utils/snuba.py", line 853, in _snuba_query
    raise SnubaError(err)
sentry.utils.snuba.SnubaError: HTTPConnectionPool(host='127.0.0.1', port=1218): Max retries exceeded with url: /query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f10add41550>: Failed to establish a new connection: [Errno 111] Connection refused',))
06:41:15 [INFO] sentry_sdk.errors: Discarded session update because of missing release
06:41:15 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/1/store/ (status_code=403 request=<WSGIRequest: POST '/api/1/store/'>)
06:41:15 [INFO] sentry_sdk.errors: Discarded session update because of missing release
06:41:15 [ERROR] sentry_sdk.errors: Unexpected status code: 403 (body: b'\n\n\n\n\n\n\n\n\n\n<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta http-equiv="content-type" content="text/html; charset=utf-8">\n  <meta name="robots" content="NONE,NOARCHIVE">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <meta name="theme-color" content="#000000">\n\n  <link rel="icon" type="image/png" href="http://10.218.4.97:9000/_static/1622614990/sentry/images/favicon.png">\n\n  <link rel="apple-touch-icon" href="http://10.218.4.97:9000/_static/1622614990/sentry/images/logos/apple-touch-icon.png">\n  <link rel="apple-touch-icon" sizes="76x76" href="http://10.218.4.97:9000/_static/1622614990/sentry/images/logos/apple-touch-icon-76x76.png">\n  <link rel="apple-touch-icon" sizes="120x120" href="http://10.218.4.97:9000/_static/1622614990/sentry/images/logos/apple-touch-icon-120x120.png">\n  <link rel="apple-touch-icon" sizes="152x152" href="http://10.218.4.97:9000/_static/1622614990/sentry/images/logos/apple-touch-icon-152x152.png">\n\n  <link rel="mask-icon" sizes="any" href="http://10.218.4.97:9000/_static/1622614990/sentry/images/logos/logo-sentry.svg" color="#FB4226">\n\n  <link href="/_static/dist/sentry/sentry.0118e4.css" rel="stylesheet"/>\n\n  \n\n  <title>CSRF Verification Failed | Sentry</title>\n\n  \n    <script>window.__initialData = {"singleOrganization":true,"supportEmail":"mengxiangzhi@joyy.sg","urlPrefix":"http://10.218.4.97:9000","version":{"current":"21.5.1","latest":"21.5.1","build":"21.5.1","upgradeAvailable":false},"features":["auth:register"],"distPrefix":"/_static/dist/sentry/","needsUpgrade":false,"dsn":"http://07b428a62d9b485fb54a90668fc9bdd3@10.218.4.97:9000/1","dsn_requests":"","statuspage":null,"messages":[],"apmSampling":0.0,"isOnPremise":true,"invitesEnabled":true,"gravatarBaseUrl":"https://secure.gravatar.com","termsUrl":null,"privacyUrl":null,"lastOrganization":null,"languageCode":"en","userIdentity":{"ip_address":"10.218.4.97"},"csrfCookieName":"sc","sentryConfig":{"dsn":"http://07b428a62d9b485fb54a90668fc9bdd3@10.218.4.97:9000/1","release":null,"environment":"production","whitelistUrls":[]},"demoMode":false,"isAuthenticated":false,"user":null};</script>\n  \n\n  <script>try {\n    var reg = new RegExp(/\\/organizations\\/(.+?(?=(\\/|$)))(\\/|$)/, \'i\');\n    var organization = window.location.pathname;\n    var slug = organization.match(reg)[1];\n\n    function promiseRequest(url) {\n      return new Promise(function (resolve, reject) {\n        var xhr = new XMLHttpRequest();\n        xhr.open(\'GET\', url);\n        xhr.onload = function () {\n          try {\n            this.status >= 200 && this.status < 300\n              ? resolve(JSON.parse(xhr.response))\n              : reject([this.status, this.statusText]);\n          } catch(e) {\n            reject();\n          }\n        };\n        xhr.onerror = function () {\n          reject([this.status, this.statusText]);\n        };\n        xhr.send();\n      });\n    }\n\n    function makeUrl(suffix) {\n      return \'/api/0/organizations/\' + slug + suffix;\n    }\n\n\n    // There are probably more, but this is at least one case where\n    // this should not be treated as a slug\n    if (slug !== \'new\') {\n      var preloadPromises = { orgSlug: slug };\n      window.__sentry_preload = preloadPromises;\n\n      preloadPromises.organization = promiseRequest(makeUrl(\'/?detailed=0\'));\n      preloadPromises.projects =  promiseRequest(makeUrl(\'/projects/?all_projects=1&collapse=latestDeploys\'));\n      preloadPromises.teams = promiseRequest(makeUrl(\'/teams/\'));\n    }\n  } catch(_) {}</script>\n\n  \n  \n\n  \n  <script src="/_static/dist/sentry/runtime.5d028fae75e460129dc9.js"></script>\n\n  \n  <script src="/_static/dist/sentry/vendor.ec6fde335ef916d2a8eb.js"></script>\n\n  \n    \n    <script src="/_static/dist/sentry/app.c0bdb48b516abda3603c.js"></script>\n  \n\n  \n  \n\n  <script>// if the ads.js file loads below it will mark this variable as false\n    window.adblockSuspected = true;</script>\n\n  \n  <script src="/_static/1622614990/sentry/js/ads.js"></script>\n  \n</head>\n\n<body class=" narrow">\n  \n  <div class="app">\n    \n\n    \n    \n\n\n<div id="blk_alerts" class="messages-container"></div>\n<div id="blk_indicators"></div>\n\n<script>window.__onSentryInit = window.__onSentryInit || [];\n  window.__onSentryInit.push({\n    name: \'renderReact\',\n    component: \'SystemAlerts\',\n    container: \'#blk_alerts\',\n    props: {\n      className: \'alert-list\',\n    },\n  });\n  window.__onSentryInit.push({\n    name: \'renderReact \',\n    component: \'Indicators\',\n    container: \'#blk_indicators\',\n    props: {\n      className: \'indicators-container\',\n    },\n  });</script>\n\n\n\n    \n\n    <div class="container">\n      <div class="content">\n        \n<div class="pattern-bg"></div>\n<section class="org-login">\n  <div class="box box-modal">\n    <div class="box-header">\n      \n        \n          \n        \n        <a class="logo-with-action" href="/">\n          \n            <span class="icon-sentry-logo-full"></span>\n          \n          \n        </a>\n      \n    </div>\n    <div class="box-content with-padding">\n      \n    <section class="body">\n        <div class="page-header">\n            <h2>CSRF Verification Failed</h2>\n        </div>\n\n        <p>A required security token was not found or was invalid.</p>\n\n        <p>If you\'re continually seeing this issue, try the following:</p>\n\n        <ol>\n          <li>Clear cookies (at least for Sentry\'s domain).</li>\n          <li>Reload the page you\'re trying to submit (don\'t re-submit data).</li>\n          <li>Re-enter the information, and submit the form again.</li>\n        </ol>\n\n        \n\n        <p>Read more about <a href="http://en.wikipedia.org/wiki/Cross-site_request_forgery">CSRF on Wikipedia</a>.</p>\n    </section>\n\n    </div>\n  </div>\n</section>\n\n      </div>\n    </div>\n  </div>\n  \n\n  \n  \n  <script>document.addEventListener(\'DOMContentLoaded\', function() {\n      const el = document.querySelector(\'#sign-out\');\n      if (el) {\n        el.addEventListener(\'click\', function() {\n          document.modalLogoutForm.submit();\n        });\n      }\n    });</script>\n\n</body>\n</html>\n')
```
- config.yml and sentry.conf.py like this:
```
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely

system.secret-key: '628%2qafbm6(^a+#szm58zi4-alxkk&pw30*is3ea5!6xnkcf#'


redis.clusters:
  default:
    hosts:
      0:
        host: ****
        port: 4043


filestore.backend: 'filesystem'
filestore.options:
  location: '/tmp/sentry-files'
```
sentry.conf.py

```

from sentry.conf.server import *

import os.path

CONF_ROOT = os.path.dirname(__file__)

DATABASES = {
    'default': {
        'ENGINE': 'sentry.db.postgres',
        'NAME': 'mengxzh_sentry',
        'USER': 'mengxzh',
        'PASSWORD': '123456',
        'HOST': '10.218.9.67',
        'PORT': '5432',
        'AUTOCOMMIT': True,
        'ATOMIC_REQUESTS': False,
    }
}


SENTRY_USE_BIG_INTS = True


SENTRY_SINGLE_ORGANIZATION = True
DEBUG = False


SENTRY_CACHE = 'sentry.cache.redis.RedisCache'



BROKER_URL = 'redis://10.130.84.12:4043/1'



SENTRY_RATELIMITER = 'sentry.ratelimits.redis.RedisRateLimiter'


SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'



SENTRY_QUOTAS = 'sentry.quotas.redis.RedisQuota'



SENTRY_TSDB = 'sentry.tsdb.redissnuba.RedisSnubaTSDB'


SENTRY_DIGESTS = 'sentry.digests.backends.redis.RedisBackend'



SENTRY_WEB_HOST = "0.0.0.0"
SENTRY_WEB_PORT = 9000
SENTRY_WEB_OPTIONS = {
    "http": "%s:%s" % (SENTRY_WEB_HOST, SENTRY_WEB_PORT),
    "protocol": "uwsgi",
    # This is needed in order to prevent https://git.io/fj7Lw
    "uwsgi-socket": None,
    "so-keepalive": True,
    # Keep this between 15s-75s as that's what Relay supports
    "http-keepalive": 15,
    "http-chunked-input": True,
    # the number of web workers
    "workers": 3,
    "threads": 4,
    "memory-report": False,
    # Some stuff so uwsgi will cycle workers sensibly
    "max-requests": 100000,
    "max-requests-delta": 500,
    "max-worker-lifetime": 86400,
    # Duplicate options from sentry default just so we don't get
    # bit by sentry changing a default value that we depend on.
    "thunder-lock": True,
    "log-x-forwarded-for": False,
    "buffer-size": 32768,
    "limit-post": 209715200,
    "disable-logging": True,
    "reload-on-rss": 600,
    "ignore-sigpipe": True,
    "ignore-write-errors": True,
    "disable-write-exception": True,
}

SENTRY_FEATURES["projects:sample-events"] = False
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            "organizations:discover",
            "organizations:events",
            "organizations:global-views",
            "organizations:incidents",
            "organizations:integrations-issue-basic",
            "organizations:integrations-issue-sync",
            "organizations:invite-members",
            "organizations:metric-alert-builder-aggregate",
            "organizations:sso-basic",
            "organizations:sso-rippling",
            "organizations:sso-saml2",
            "organizations:performance-view",
            "organizations:advanced-search",
            "projects:custom-inbound-filters",
            "projects:data-forwarding",
            "projects:discard-groups",
            "projects:plugins",
            "projects:rate-limits",
            "projects:servicehooks",
        )
    }
)

```

### What you expected to happen
when i click project tag or dashboard tag its work

**Comment by bruce121381** [comment]
> connect

but install.sh has dependency for docker-compose, i do not use it, i need a DockerFile for sentry,but in repos its couldnt work, beacause i couldnt found /dist

**Comment by bruce121381** [comment]
@BYK

**Comment by BYK** [comment]
@bruce121381 whether you use Docker Compose or not, you need all those services. Using a docker image won't change that. 

You can see all the services and related images in the following files:

- https://github.com/getsentry/onpremise/blob/master/docker-compose.yml
- https://github.com/getsentry/onpremise/blob/21.5.1/.env
