### ISSUE TITLE
Errors Hidden in Failing Tests

### ISSUE THREAD

**Issue by mgaeta** [getsentry/sentry#26386]
## Important Details

How are you running Sentry?
> On-Premise w/ Docker, version 1.1.0.

## Description
When there is a test failure in `sentry/tests/js/spec/views/` due to an exception, the only error message is: 
```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```
`wrapErrorHandling` is catching the exception, swallowing the message, and updating `this.state.error`.

## Steps to Reproduce

1. Find a Component that inherits from `AsyncComponent`.
2. Add an error in `renderBody()`. For example, call a non-existent function: 
```
renderBody() {
  x();
  ...
}
```
3. Run the test suite for the component. The stacktrace does not mention `ReferenceError: x is not defined`:
```
console.error
  Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    at NotificationSettings (/Users/marcos/sentry/sentry/static/app/views/settings/account/notifications/notificationSettings.tsx:102:37)
    at RootFinder (/Users/marcos/sentry/sentry/node_modules/@wojtekmaj/enzyme-adapter-utils/build/RootFinder.js:42:5)
    at ThemeProvider (/Users/marcos/sentry/sentry/node_modules/@emotion/react/dist/emotion-element-cb6e9ca7.cjs.dev.js:93:21)
    at WrappingThemeProvider (/Users/marcos/sentry/sentry/tests/js/sentry-test/enzyme.js:10:48)
    at WrapperComponent (/Users/marcos/sentry/sentry/node_modules/@wojtekmaj/enzyme-adapter-utils/src/createMountWrapper.jsx:48:26)
```

### What you expected to happen

When there is an error in an `AsyncComponent` in tests, do not call `component.setState({error});`.

**Comment by billyvg** [comment]
It's possible this is swallowing it https://github.com/getsentry/sentry/blob/master/tests/js/throw-on-react-error.js#L22

**Comment by leeandher** [comment]
Component is deprecated, so by completing the project to remove AsyncComponents from the app, this will be resolved.
