### ISSUE TITLE
Database Crash

### ISSUE THREAD

**Issue by omss24** [getsentry/sentry#2640]
Hey, I got sentry (8.0.3) running on heroku. I keep getting this error and it is crashing sentry.

Keep getting this error:

`
ProgrammingError: permission denied for relation sentry_grouphash 
`

`2016-02-03T02:23:36.757350+00:00 app[worker.1]: [2016-02-03 02:23:36,756: ERROR/Worker-7] permission denied for relation sentry_grouphash
2016-02-03T02:23:36.757352+00:00 app[worker.1]: Traceback (most recent call last):
2016-02-03T02:23:36.757353+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/utils/logging.py", line 23, in wrapped
2016-02-03T02:23:36.757353+00:00 app[worker.1]:     return func(*args, **kwargs)
2016-02-03T02:23:36.757354+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/event_manager.py", line 467, in save
2016-02-03T02:23:36.757355+00:00 app[worker.1]:     **group_kwargs
2016-02-03T02:23:36.757355+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/event_manager.py", line 601, in _save_aggregate
2016-02-03T02:23:36.757356+00:00 app[worker.1]:     all_hashes = self._find_hashes(project, hashes)
2016-02-03T02:23:36.757357+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/event_manager.py", line 566, in _find_hashes
2016-02-03T02:23:36.757357+00:00 app[worker.1]:     hash=hash,
2016-02-03T02:23:36.757358+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
2016-02-03T02:23:36.757359+00:00 app[worker.1]:     return self.get_queryset().get_or_create(**kwargs)
2016-02-03T02:23:36.757359+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 391, in get_or_create
2016-02-03T02:23:36.757361+00:00 app[worker.1]:     obj.save(force_insert=True, using=self.db)
2016-02-03T02:23:36.757360+00:00 app[worker.1]:     six.reraise(*exc_info)
2016-02-03T02:23:36.757360+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get_or_create
2016-02-03T02:23:36.757362+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
2016-02-03T02:23:36.757362+00:00 app[worker.1]:     force_update=force_update, update_fields=update_fields)
2016-02-03T02:23:36.757363+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
2016-02-03T02:23:36.757364+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
2016-02-03T02:23:36.757364+00:00 app[worker.1]:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
2016-02-03T02:23:36.757365+00:00 app[worker.1]:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
2016-02-03T02:23:36.757365+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
2016-02-03T02:23:36.757366+00:00 app[worker.1]:     using=using, raw=raw)
2016-02-03T02:23:36.757367+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
2016-02-03T02:23:36.757367+00:00 app[worker.1]:     return insert_query(self.model, objs, fields, **kwargs)
2016-02-03T02:23:36.757368+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
2016-02-03T02:23:36.757369+00:00 app[worker.1]:     return query.get_compiler(using=using).execute_sql(return_id)
2016-02-03T02:23:36.757370+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
2016-02-03T02:23:36.757370+00:00 app[worker.1]:     cursor.execute(sql, params)
2016-02-03T02:23:36.757371+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
2016-02-03T02:23:36.757372+00:00 app[worker.1]:     return self.cursor.execute(sql, params)
2016-02-03T02:23:36.757373+00:00 app[worker.1]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
2016-02-03T02:23:36.757372+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
2016-02-03T02:23:36.757373+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
2016-02-03T02:23:36.757374+00:00 app[worker.1]:     return self.cursor.execute(sql, params)
2016-02-03T02:23:36.757375+00:00 app[worker.1]: ProgrammingError: permission denied for relation sentry_grouphash
`

**Comment by mattrobenolt** [comment]
The error is pretty obvious: `ProgrammingError: permission denied for relation sentry_grouphash`

It seems that your user in `DATABASES` doesn't have the right permissions.
