### ISSUE TITLE
Error in setup.py

### ISSUE THREAD

**Issue by SerafimArts** [getsentry/sentry#2641]
> thread.error: can't start new thread

```
Patching "bin_name" to properly install_scripts dir
Traceback (most recent call last):
  File "setup.py", line 479, in <module>
    'Topic :: Software Development'
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 373, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 696, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 797, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1047, in best_match
    return self.obtain(req, installer)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1059, in obtain
    return installer(requirement)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 616, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 646, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 831, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1053, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1039, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 238, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 162, in save_modules
    saved_exc.resume()
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 137, in resume
    compat.reraise(type, exc, self._tb)
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 150, in save_modules
    yield saved
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 235, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 265, in run
    return func()
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 234, in runner
    _execfile(setup_script, ns)
  File "/usr/lib64/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-WDE83d/uwsgi-2.0.12/setup.py", line 109, in <module>
    'ipaddr>=2.1.11,<2.2.0',
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-WDE83d/uwsgi-2.0.12/setup.py", line 85, in run
    ]
  File "/tmp/easy_install-WDE83d/uwsgi-2.0.12/uwsgiconfig.py", line 233, in build_uwsgi
  File "/usr/lib64/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

**Comment by mattrobenolt** [comment]
How did you trigger this?

**Comment by mattrobenolt** [comment]
Looking around, the only other case I can see of this happening during setup.py was from this calibre package, and this was the issue: https://github.com/kovidgoyal/calibre/pull/395 and the commit to fix https://github.com/kovidgoyal/calibre/commit/87073a45363e4863fceb821fa626b0197bd2c225

Now, in your case, this is coming from within the uWSGI installer, but I haven't heard of or seen any issues on this over there.

**Comment by mattrobenolt** [comment]
Could you try setting `CPUCOUNT=1` in your environment when installing?

https://github.com/unbit/uwsgi/blob/2.0.12/uwsgiconfig.py#L42 seems to bypass the threading stuff if you declare that.

**Comment by SerafimArts** [comment]
> How did you trigger this?

Just run `python setup.py install` (from github master sources)

> Could you try setting CPUCOUNT=1 in your environment when installing?

I dont know where uwsgi contains.

If i run installations from pip (`pip install  -U sentry`) i have similar error:
```
Running setup.py install for uwsgi ... error
    Complete output from command /home/virtwww/wf0df6175/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7KVEX2/uwsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-90mAkh-record/install-record.txt --single-version-externally-managed --compile:
    running install
    using profile: buildconf/default.ini
    detected include path: ['/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include', '/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include-fixed', '/usr/include']
    Patching "bin_name" to properly install_scripts dir
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
     ... etc...
```

**Comment by mattrobenolt** [comment]
Try: `CPUCOUNT=1 pip install -U sentry`

In theory, that will set the environment variable that the uwsgi installer will pick up.

**Comment by SerafimArts** [comment]
> I dont know where uwsgi contains. =(

Ouch. I can write this var in `.bashrc`, yep

**Comment by SerafimArts** [comment]
Yes, sets `CPUCOUNT` inside `.bashrc` works! Thank you. I thing its popular bug of virual hostings =(

**Comment by mattrobenolt** [comment]
I wonder if that's because the multiprocessing module reports that there are more CPUs than can actually be used? I'm not sure. Hopefully you don't hit any other snags.

**Comment by SerafimArts** [comment]
> Hopefully you don't hit any other snags.

\-_\-
Error in `cryptography`:
`Running setup.py install for cryptography ... error`
...
`ImportError: /tmp/pip-build-5F2GmN/cryptography/.eggs/cffi-1.5.0-py2.7-linux-x86_64.egg/_cffi_backend.so: failed to map segment from shared object`

**Comment by mattrobenolt** [comment]
Yeah... I'm not sure. I'm just going to assume that your environment is not compatible with Sentry. :(

**Comment by SerafimArts** [comment]
Damn virtual hostings... :D

**Comment by SerafimArts** [comment]
Problem fixed after removing `uwsgi` from `setup.py` and add:
```
export TMP=${HOME}/tmp
export TEMP=${HOME}/tmp
```
inside `.bashrc`. CLI tool successfully works. But i dont know how run sentry throw fastcgi.

**Comment by mattrobenolt** [comment]
In theory, there's a `sentry/wsgi.py` that you could use, but this is completely unsupported by us and uWSGI is the only method we support. https://github.com/getsentry/sentry/blob/master/src/sentry/wsgi.py

**Comment by SerafimArts** [comment]
Like
```
Options +FollowSymlinks

AddHandler fcgid-script .py

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /home/virtwww/f0df6175/python/lib/site-packages/sentry-8.1.1-py2.7.egg/sentry/wsgi.py/$1 [QSA,L]
```
?

Its does no works

**Comment by mattrobenolt** [comment]
I have literally no idea. :) You're going to be on your own here. I know nothing about fcgi or apache.

You know you can just pay us a few dollars over here right? https://getsentry.com/welcome/ :)

But anything else is going to have to go through our mailing list, or IRC, etc. See: https://docs.getsentry.com/on-premise/support/

**Comment by SerafimArts** [comment]
@mattrobenolt im from Russia and 1 dollar now like 3-4 dollars year ago. Current price (29$/mo) like ~110$. Its very expensive.

**Comment by mattrobenolt** [comment]
fwiw we have a $9/month hobbyist plan and a free tier if it's super low volume and a single user.

But either way, this issue at this point is outside the scope of something we can support.

**Comment by SerafimArts** [comment]
$9/mo? https://getsentry.com/pricing/ o_0

**Comment by SerafimArts** [comment]
Ouch:
>  We offer a discounted plan ($9/month) for hobbyists and side projects which includes: 30 day retention, 10 events per min, and is restricted to a single user.

Yep, thx again
