### ISSUE TITLE
dev env: Help when locale.get_locale() raises an exception

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#26450]
In the bootstrapping process, if an engineer installs oh-myzsh, they will have an issue during `make bootstrap`. This is because [it messes up](https://github.com/ohmyzsh/ohmyzsh/issues/7558) with `LC_ALL` and `LANG`.

The following command would fail:
> python -c "import locale; print(locale.getlocale())"

I believe we can make this a bit better and help engineers with a meaningful message.

```shell
(.venv) ➜  sentry git:(master) ✗ make run-dependent-services
Traceback (most recent call last):
  File "/Users/vladanpaunovic/Dev/sentry/.venv/bin/sentry", line 33, in <module>
    sys.exit(load_entry_point('sentry', 'console_scripts', 'sentry')())
...
  File "/Users/vladanpaunovic/Dev/sentry/.venv/lib/python3.6/site-packages/natsort/compat/locale.py", line 73, in get_thousands_sep
    loc = ".".join(locale.getlocale())
  File "/Users/vladanpaunovic/.pyenv/versions/3.6.13/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Users/vladanpaunovic/.pyenv/versions/3.6.13/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
make: *** [run-dependent-services] Error 1
(.venv) ➜  sentry git:(master) ✗
```

**Comment by bc-sentry** [comment]
Please reopen if still occurs.
