### ISSUE TITLE
Javascript stack parsing failures

### ISSUE THREAD

**Issue by gierschv** [getsentry/sentry#2647]
Hi there,

The JS stack parser sometimes fails to extracts URLS:

```
2016-02-04 14:36:14,928: WARNING/Worker-2] Unable to fetch 'eval at <anonymous> (https://flat.io/js/vendor.min.js?f7cf2faf23:1:0), <anonymous>'
Traceback (most recent call last):
  File "/srv/sentry/virtualenv/local/lib/python2.7/site-packages/sentry/lang/javascript/processor.py", line 292, in fetch_file
    timeout=settings.SENTRY_SOURCE_FETCH_TIMEOUT,
  File "/srv/sentry/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/srv/sentry/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/sentry/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 570, in send
    adapter = self.get_adapter(url=request.url)
  File "/srv/sentry/virtualenv/local/lib/python2.7/site-packages/requests/sessions.py", line 644, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'eval at <anonymous> (https://flat.io/js/vendor.min.js?f7cf2faf23:1:0), <anonymous>'
Disabling sources to  for 300s
```

I will try to check deeply where this bug comes from when having some free time.

Vincent

**Comment by gierschv** [comment]
Thanks!
