### ISSUE TITLE
Migration error: column "build_number" is of type bigint but expression is of type text

### ISSUE THREAD

**Issue by Tofandel** [getsentry/sentry#26513]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version latest commit

## Description
While running an update of a self hosted instance I encountered an SQL error during the migration
```
Releases: 100% |#################################################| Time: 0:00:00
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 76, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: column "build_number" is of type bigint but expression is of type text
LINE 10:     build_number = data.build_number
                            ^
HINT:  You will need to rewrite or cast the expression.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 76, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: ProgrammingError('column "build_number" is of type bigint but expression is of type text\nLINE 10:     build_number = data.build_number\n                            ^\nHINT:  You will need to rewrite or cast the expression.\n',)

SQL: b"\n    UPDATE sentry_release\n    SET package = data.package,\n    major = data.major,\n    minor = data.minor,\n    patch = data.patch,\n    revision = data.revision,\n    prerelease = data.prerelease,\n    build_code = data.build_code,\n    build_number = data.build_number\n    FROM (VALUES (3,'dummy',0,1,36,0,'lib-2.3.39',NULL,NULL)) AS data (id, package, major, minor, patch, revision, prerelease, build_code, build_number)\n    WHERE sentry_release.id = data.id"
An error occurred, caught SIGERR on line 12

```

**Comment by Tofandel** [comment]
Adding `SENTRY_USES_BIG_INTS= True` to the config.py solved it

**Comment by wedamija** [comment]
Thanks for the report @Tofandel, this should be resolved
