### ISSUE TITLE
Running service: 'http' fails with supervisor

### ISSUE THREAD

**Issue by MounirMesselmeni** [getsentry/sentry#2652]
Hi,

After upgrading Sentry from 8.0.1 to 8.1.1 I wasn't able to run sentry start from supervisor,when runninh directly sentry start this work perfectly, but when running it from supervisor this fail with this error:

Running service: 'http'
Traceback (most recent call last):
  File "/www/sentry/bin/sentry", line 11, in <module>
Feb  6 13:37:53 QoSSuite supervisord: sentry-web
sys.exit(main())
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 145, in main
Feb  6 13:37:53 QoSSuite supervisord: sentry-web
cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
Feb  6 13:37:53 QoSSuite supervisord: sentry-web
return self.main(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 696, in main
Feb  6 13:37:53 QoSSuite supervisord: sentry-web
rv = self.invoke(ctx)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
Feb  6 13:37:53 QoSSuite supervisord: sentry-web
return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
Feb  6 13:37:53 QoSSuite supervisord: sentry-web
return ctx.invoke(self.callback, **ctx.params)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 26, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/commands/start.py", line 59, in start
    workers=workers,
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/services/http.py", line 127, in run
    os.execvp('uwsgi', ('uwsgi',))
  File "/www/sentry/lib/python2.7/os.py", line 344, in execvp
    _execvpe(file, args)
  File "/www/sentry/lib/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory

I think this is also to the switch from gunicorn to uwsgi

**Comment by mattrobenolt** [comment]
Yup. :(

See: https://github.com/getsentry/sentry/pull/2650 and https://github.com/getsentry/sentry/pull/2649

I'll cut a new release today that contains this fix, but in the meantime, you can add your virtualenv bin directory on your PATH as mentioned in #2649

**Comment by mattrobenolt** [comment]
I just pushed 8.1.2 which has this addressed.

**Comment by MounirMesselmeni** [comment]
@mattrobenolt Thanks a lot for your help and the great work!

**Comment by fuhrysteve** [comment]
@mattrobenolt Confirmed fixed for me too. I no longer need to specify PATH in my environment. (See #2649) Thanks!
