### ISSUE TITLE
Wrong parsing of SENTRY_EMAIL_USE_TLS

### ISSUE THREAD

**Issue by mkatrenik** [getsentry/sentry#2653]
```bash
export SENTRY_EMAIL_USE_TLS=False
```

```bash
sentry shell
```

```
from django.core.mail import send_mail
>>> send_mail('testing','test','admin@sentry.ep.***',['martin.katrenik@***'])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/__init__.py", line 50, in send_mail
    connection=connection).send()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 51, in open
    self.connection.starttls()
  File "/usr/local/lib/python2.7/smtplib.py", line 644, in starttls
    raise SMTPException("STARTTLS extension not supported by server.")
SMTPException: STARTTLS extension not supported by server.
>>> from django.core.mail import get_connection
>>> c = get_connection()
>>> c.use_tls
(False,)
>>> c.use_tls = False
>>> send_mail('testing','test','admin@sentry.ep.***',['martin.katrenik@***'], False, None, None, c)
1
```

I think problem is that connection.use_tls is tuple, thus always True.

**Comment by mkatrenik** [comment]
Sentry 8.1.1

**Comment by mattrobenolt** [comment]
Is this related to our docker image? sentry itself doesn't handle env cars like this. If so, can this be reopened over at https://github.com/getsentry/docker-sentry ?

**Comment by MikeVL** [comment]
Same problem in v9.0

```
root@sentry-server:/# env | sort
SENTRY_DB_USER=sentry
SENTRY_EMAIL_HOST=smtp-pulse.com
SENTRY_EMAIL_PASSWORD=***
SENTRY_EMAIL_PORT=2525
SENTRY_EMAIL_USER=***
SENTRY_FILESTORE_DIR=/var/lib/sentry/files
```

```
root@sentry-server:/# sentry config get mail.use-tls
11:41:55 [INFO] sentry.plugins.github: apps-not-configured
        type: BOOLEAN
 from config: False
     current: True
```
