### ISSUE TITLE
TypeError: t[1].match is not a function

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2745]
https://app.getsentry.com/sentry/javascript/issues/102660842/

```
TypeError: t[1].match is not a function
  at map (./app/components/events/interfaces/frame.jsx:155:45)
  at renderContext (./app/components/events/interfaces/frame.jsx:146:32)
  at render (./app/components/events/interfaces/frame.jsx:187:23)
...
(44 additional frame(s) were not displayed)
```

**Comment by mattrobenolt** [comment]
Stepping through the debugging, this is coming from the `TemplateInterface`. Inside of that, we use the `<Frame/>` component, which makes an assumption about the shape of the data.

Specifically, each context is expected to be of the shape `(lineno, line)`, but in a `template` (at least in this case) `line` is a tuple itself. So we have data like:

```json
[
  0,
  [
    1,
    "foo bar"
  ]
]
```

which causes it to error when calling `.match` on the array.

**Comment by mattrobenolt** [comment]
@mitsuhiko I think this is related to Django 1.9.x. I'm having trouble figuring out if this is the expected shape, or a bug in raven-python in sending it this way.
