### ISSUE TITLE
AttributeError: 'Requirement' object has no attribute 'name'

### ISSUE THREAD

**Issue by dereckson** [getsentry/sentry#2784]
On a Celery workers, when the send_beacon task occurs, the following error is thrown (tested under Sentry 8.1.2, launched through Docker):

**Error stacktrace:**

```
Requirement' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 127, in __repr__
    return "<Requirement({0!r})>".format(str(self))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 110, in __str__
    parts = [self.name]
AttributeError: 'Requirement' object has no attribute 'name'
```

**Task stacktrace:**

```
Task sentry.tasks.send_beacon[f54d97fc-67e1-4539-b6bf-ac828befca66] raised unexpected: InvalidRequirement('Invalid requirement, parse error at "\'__main__\'"',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/beacon.py", line 72, in send_beacon
    'packages': get_all_package_versions(),
  File "/usr/local/lib/python2.7/site-packages/sentry/debug/utils/packages.py", line 60, in get_all_package_versions
    version = get_package_version(module_name, app)
  File "/usr/local/lib/python2.7/site-packages/sentry/debug/utils/packages.py", line 19, in get_package_version
    return pkg_resources.get_distribution(module_name).version
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 540, in get_distribution
    dist = Requirement.parse(dist)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2818, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2762, in parse_requirements
    req = packaging.requirements.Requirement(line)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'__main__'"
```

**Comment by mattrobenolt** [comment]
This has been fixed with https://github.com/getsentry/sentry/commit/d32b14020ec37b7e895f443409dd004afa67f298

It seems we had an issue with a newer version of setuptools. I'll get this backported into an 8.1.3 and 8.2.1 tomorrow.

**Comment by mattrobenolt** [comment]
To add context to this, this is a compatibility issue with setuptools 20.2+.

Updates have been pushed for [8.1.3](https://github.com/getsentry/sentry/releases/tag/8.1.3) and [8.2.1](https://github.com/getsentry/sentry/releases/tag/8.2.1)

**Comment by mattrobenolt** [comment]
Also, see https://github.com/docker-library/official-images/pull/1502 for updated docker image.

**Comment by dereckson** [comment]
Thanks for these comments.
