### ISSUE TITLE
redis/lua: Script attempted to access unexisting global variable 'bit'

### ISSUE THREAD

**Issue by sk1p** [getsentry/sentry#2835]
Redis version: 2.8.17 on Debian stable.
Sentry: 8.2.0

After some time, I get the following error in the sentry worker log:

```
[2016-03-12 10:18:40,377: ERROR/Worker-2] Error running script (call to f_3e3d663746e29efde08272f437568f78f65c387e): @enable_strict_lua:14: user_script:154: Script attempted to access unexisting global variable 'bit' 
Traceback (most recent call last):
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/event_manager.py", line 477, in save
    **group_kwargs
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/event_manager.py", line 693, in _save_aggregate
    ], timestamp=event.datetime)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 332, in record_frequency_multi
    self.cluster.execute_commands(commands)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/../rb/cluster.py", line 390, in execute_commands
    results[key].append(targeted.execute_command(*command))
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/../rb/clients.py", line 577, in __exit__
    self.mapping_client.join(timeout=timeout)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/../rb/clients.py", line 366, in join
    command_buffer.wait_for_responses(self)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/../rb/clients.py", line 208, in wait_for_responses
    self.connection, command_name)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/../redis/connection.py", line 582, in read_response
    raise response
ResponseError: Error running script (call to f_3e3d663746e29efde08272f437568f78f65c387e): @enable_strict_lua:14: user_script:154: Script attempted to access unexisting global variable 'bit' 
```

As far as I can see, this is caused by the use of bitwise operations in ``cmsketch.lua``, function ``mmh3``. ``bit`` is [only available since redis 3.0](http://download.redis.io/redis-stable/00-RELEASENOTES).

**Comment by mattrobenolt** [comment]
Hey @sk1p, this has gone out in a bugfix release with 8.2.3: https://github.com/getsentry/sentry/releases/tag/8.2.3

**Comment by sk1p** [comment]
Awesome, thanks!
