### ISSUE TITLE
Distributed Setup: CollectStatic Files Not Found

### ISSUE THREAD

**Issue by switchtower** [getsentry/sentry#28654]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.9.0

### Steps to Reproduce

sentry django collectstatic

### Expected Result

For the files to be found and collected properly.

### Actual Result

```
You have requested to collect static files at the destination
location as specified in your settings:

    /home/sentry/sentry/lib/python3.8/site-packages/sentry-21.9.0-py3.8.egg/sentry/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/home/sentry/sentry/bin/sentry", line 33, in <module>
    sys.exit(load_entry_point('sentry==21.9.0', 'console_scripts', 'sentry')())
  File "/home/sentry/sentry/lib/python3.8/site-packages/sentry-21.9.0-py3.8.egg/sentry/runner/__init__.py", line 191, in main
    func(**kwargs)
  File "/home/sentry/sentry/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sentry/sentry/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sentry/sentry/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sentry/sentry/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sentry/sentry/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/sentry/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/sentry/lib/python3.8/site-packages/sentry-21.9.0-py3.8.egg/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/home/sentry/sentry/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/sentry/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/sentry/lib/python3.8/site-packages/sentry-21.9.0-py3.8.egg/sentry/runner/commands/django.py", line 14, in django
    execute_from_command_line(argv=[ctx.command_path] + list(management_args))
  File "/home/sentry/sentry/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/sentry/sentry/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sentry/sentry/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sentry/sentry/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/sentry/sentry/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/home/sentry/sentry/lib/python3.8/site-packages/sentry-21.9.0-py3.8.egg/sentry/management/commands/collectstatic.py", line 40, in collect
    collected = super().collect()
  File "/home/sentry/sentry/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/home/sentry/sentry/lib/python3.8/site-packages/django/contrib/staticfiles/finders.py", line 131, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/home/sentry/sentry/lib/python3.8/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
    directories, files = storage.listdir(location)
  File "/home/sentry/sentry/lib/python3.8/site-packages/django/core/files/storage.py", line 322, in listdir
    for entry in os.scandir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/sentry/sentry/lib/python3.8/site-packages/sentry-21.9.0-py3.8.egg/sentry/static/sentry/dist'
```

**Comment by BYK** [comment]
Hi, would you mind sharing why you are using this command?

**Comment by switchtower** [comment]
`http://sentry.<removed>.com/_static/dist/sentry/entrypoints/app.js?v=None`

This is getting a 404 along with all other static files.

Docker isn't an option in the setup I have.  I have dedicated servers running memcached, redis, posgresql, kafka/zookeeper, and symbolicator.

The postgres db has been created and migrated/upgraded.

Nginx is running and forwarding requests to the sentry web instance, but I'm unable to get static files configured correctly between the Sentry Django app and Nginx; I've tried moving the static configuration to a new location with proper user permissions, but still no luck.  When I reconfigure the STATIC_ROOT in the config file, the 'sentry django collectstatic' isn't able to locate the files to move.

I hope this better describes the issues I'm having and any help would be appreciated. :)

**Comment by BYK** [comment]
@switchtower you should just be able to use our prebuilt wheel from PyPI which includes all static assets. You don't need `collectstatic`. Does that work for you?

**Comment by switchtower** [comment]
@BYK thanks for the response, I did give that a try, instead of using the source, but to get the static files to work correctly through Nginx, I had to add the following to the Nginx config:
`
location /_static/sentry/ {
   alias /home/sentry/sentry/lib/python3.6/site-packages/sentry/static/sentry/dist/;
}
`

**Comment by BYK** [comment]
@switchtower if you follow what we do in the onpremise repo and use `nginx` in front of the built-in `uwsgi` server, this should not be needed.

**Comment by switchtower** [comment]
I'll give that a try, thanks! Go ahead and close out this request, I think I have what I need.

**Comment by BYK** [comment]
@switchtower alright! Feel free to reopen/comment here if you need anything more 🙂
