### ISSUE TITLE
"sentry_project" does not exist

### ISSUE THREAD

**Issue by NoahSlv** [getsentry/sentry#2884]
This is a fresh install of sentry.  Created empty database in Postgres, and installed sentry using 
`pip install -U sentry `
This gives me Sentry version 8.3.0.dev0

My understanding is that the next step in the installation process is to call upgrade so that the tables are created.  This command fails.

I saw that this was discussed before, but am experiencing the exact same issue, using the latest install via pip.  The remedy proposed in other ticket does not work for me.

Below is the CLI session:

```
SENTRY_CONF=/etc/sentry sentry upgrade -v 3
[ERROR] Unable to fetch internal project
Traceback (most recent call last):
  File "/root/sentry/src/sentry/utils/raven.py", line 59, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/root/sentry/src/sentry/db/models/manager.py", line 259, in get_from_cache
    result = self.get(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/root/sentry/src/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/root/sentry/src/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/root/sentry/src/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/root/sentry/src/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/root/sentry/src/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/root/sentry/src/sentry/db/postgres/base.py", line 39, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "sentry_project" does not exist
LINE 1: ...ct"."status", "sentry_project"."first_event" FROM "sentry_pr...
                                                             ^

SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."callsign", "sentry_project"."forced_color", "sentry_project"."organization_id", "sentry_project"."team_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event" FROM "sentry_project" WHERE "sentry_project"."id" = %s 
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 9, in <module>
    load_entry_point('sentry', 'console_scripts', 'sentry')()
  File "/root/sentry/src/sentry/runner/__init__.py", line 148, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/sentry/src/sentry/runner/decorators.py", line 25, in inner
    configure()
  File "/root/sentry/src/sentry/runner/__init__.py", line 111, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/root/sentry/src/sentry/runner/settings.py", line 325, in configure
    }, skip_backend_validation=skip_backend_validation)
  File "/root/sentry/src/sentry/runner/initializer.py", line 162, in initialize_app
    validate_backends()
  File "/root/sentry/src/sentry/runner/initializer.py", line 185, in validate_backends
    backend.validate()
  File "/root/sentry/src/sentry/buffer/redis.py", line 37, in validate
    raise InvalidConfiguration(unicode(e))
sentry.exceptions.InvalidConfiguration: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
```

**Comment by mattrobenolt** [comment]
See https://github.com/getsentry/sentry/issues/1578#issuecomment-199636102

**Comment by mattrobenolt** [comment]
Also, how does `pip install -U sentry` give you version 8.3.0.dev0? That version isn't published to pypi.
