### ISSUE TITLE
Internal server error accessing stats

### ISSUE THREAD

**Issue by nlopes** [getsentry/sentry#2982]
Sometimes we get the following in our logs. What can we do to fix this? (version 8.3.0)

```
[ERROR] Internal Server Error: /api/0/organizations/XXXXXXXXXX/stats/
Traceback (most recent call last):
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/sentry/../django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/sentry/../django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/sentry/api/base.py", line 147, in dispatch
    response = self.handle_exception(request, exc)
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/sentry/api/base.py", line 85, in handle_exception
    event = raven.captureException(request=request)
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/raven/base.py", line 679, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 42, in capture
    if not self.can_record_current_event():
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 39, in can_record_current_event
    return self.remote.is_active() or is_current_event_safe()
AttributeError: 'SentryInternalClient' object has no attribute 'remote'
```

**Comment by mitsuhiko** [comment]
From a basic look I'm really not entirely sure how that happens. Remote is set from what I can tell.

@nlopes can you run `pip freeze` and paste the output?

**Comment by nlopes** [comment]
Sure. @mitsuhiko see below

BeautifulSoup==3.2.1
Django==1.6.11
Markdown==2.4.1
MySQL-python==1.2.5
PyYAML==3.11
Pygments==1.6
South==1.0.1
amqp==1.4.6
anyjson==0.3.3
argparse==1.2.1
billiard==3.3.0.20
celery==3.1.18
cffi==1.1.0
click==6.2
cryptography==0.9
cssselect==0.9.1
cssutils==0.9.10
datadog==0.10.0
decorator==4.0.9
django-bitfield==1.7.1
django-crispy-forms==1.4.0
django-debug-toolbar==1.3.2
django-jsonfield==0.9.13
django-paging==0.2.5
django-picklefield==0.3.1
django-recaptcha==1.0.4
django-social-auth==0.7.28
django-statsd-mozilla==0.3.14
django-sudo==1.2.1
django-templatetag-sugar==1.0
djangorestframework==2.3.14
email-reply-parser==0.2.0
enum34==0.9.23
exam==0.10.5
gevent==1.0.2
greenlet==0.4.7
gunicorn==19.3.0
hiredis==0.1.6
httplib2==0.9.1
idna==2.0
ipaddr==2.1.11
ipaddress==1.0.7
kombu==3.0.30
logan==0.7.1
lxml==3.4.4
mock==1.0.1
ndg-httpsclient==0.4.0
nydus==0.11.0
oauth2==1.5.211
petname==1.7
progressbar==2.3
psycopg2==2.6.1
py==1.4.28
pyOpenSSL==0.15.1
pyasn1==0.1.7
pycparser==2.13
pytest==2.6.4
pytest-django==2.9.1
python-dateutil==2.4.2
python-memcached==1.54
python-openid==2.2.5
pytz==2015.4
raven==5.3.1
rb==1.4
redis==2.10.5
requests==2.9.1
sentry==8.3.0
sentry-auth-google==0.2.0.dev0
sentry-webhooks==0.3.1
setproctitle==1.1.8
simplejson==3.3.3
six==1.9.0
sqlparse==0.1.18
statsd==3.1
toronado==0.0.7
uWSGI==2.0.12
ua-parser==0.6.1
urllib3==1.14
wsgiref==0.1.2

**Comment by nlopes** [comment]
Another one that is on the logs that I just noticed (pasting here as it may help debugging):

==> /var/log/upstart/sentry-worker.log <==
[2016-04-05 12:31:51,282: WARNING/Worker-2] Traceback (most recent call last):
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/raven/handlers/logging.py", line 68, in emit
    return self._emit(record)
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/raven/handlers/logging.py", line 179, in _emit
    extra=extra, date=date, **kwargs)
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 42, in capture
    if not self.can_record_current_event():
  File "/home/sentry/sentry-venv/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 39, in can_record_current_event
    return self.remote.is_active() or is_current_event_safe()
AttributeError: 'SentryInternalClient' object has no attribute 'remote'

**Comment by mitsuhiko** [comment]
Can you try to upgrade raven with `pip install --upgrade raven`?

**Comment by nlopes** [comment]
Bumped it. Went up to 5.12. Will update here after I leave this running for a couple hours. Thanks!

**Comment by nlopes** [comment]
That fixed it! Thanks!
