### ISSUE TITLE
Error during creating first user

### ISSUE THREAD

**Issue by AlexFinn** [getsentry/sentry#3002]
Log:

```
prod@ip-10-0-0-81:~/sentry/venv/bin> ./sentry createuser
Email: alexfinn@example.com
Password:
Repeat for confirmation:
Should this user be a superuser? [y/N]: y
User created: alexfinn@example.com
[ERROR] Internal project (id=1) does not exist
Traceback (most recent call last):
  File "./sentry", line 11, in <module>
    sys.exit(main())
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 148, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 26, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/sentry/runner/commands/createuser.py", line 97, in createuser
    org = Organization.get_default()
  File "/home/prod/sentry/venv/lib/python2.7/site-packages/sentry/models/organization.py", line 106, in get_default
    )[0]
  File "/home/prod/sentry/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

**Comment by AlexFinn** [comment]
sentry version: 8.3.1
postgresql 9.5

**Comment by mattrobenolt** [comment]
Sounds like `sentry upgrade` failed to complete? Normally you'd be prompted for this during that. This error is I specifying that data is missing. Data which should come from the initial `sentry upgrade` run.
