### ISSUE TITLE
Celeryd logs filled with NoneType error

### ISSUE THREAD

**Issue by adepue** [getsentry/sentry#3027]
Our on-prem sentry celery worker logs are filled with the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sentry/event_manager.py", line 493, in save
    **group_kwargs
  File "/usr/local/lib/python2.7/dist-packages/sentry/event_manager.py", line 648, in _save_aggregate
    short_id = project.next_short_id()
  File "/usr/local/lib/python2.7/dist-packages/sentry/models/project.py", line 109, in next_short_id
    return Counter.increment(self)
  File "/usr/local/lib/python2.7/dist-packages/sentry/models/counter.py", line 39, in increment
    return increment_project_counter(project, delta)
  File "/usr/local/lib/python2.7/dist-packages/sentry/models/counter.py", line 83, in increment_project_counter
    return cur.fetchone()[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

And continually growing.

This is sentry 8.3.0

**Comment by adepue** [comment]
Upgrading to 8.3.1 did not fix the issue

**Comment by dcramer** [comment]
This is on Postgres?

@mitsuhiko

**Comment by adepue** [comment]
The DB is mysql... I am in the process of migrating the DB to postgres right now though.  I saw that in the code path and figured it may be to general degrading support of mysql and preference for postgres... 

This just happens to be an install we set up initially in early 2012 and I never bothered to migrate the engines.

**Comment by mattrobenolt** [comment]
See https://github.com/getsentry/sentry/pull/3018

**Comment by mitsuhiko** [comment]
Closing as duplicate.
