### ISSUE TITLE
Migration 9.1.2 to 21.5.0 not successful

### ISSUE THREAD

**Issue by letnab** [getsentry/sentry#30315]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.5.0

### Steps to Reproduce

image: sentry:21.5.0
command: sentry upgrade --noinput

```
Applying sentry.0024_auto_20191230_2052...Events to process: 810715

Event migration done. Migrated 810715 of 810715 events.

 OK
```

```
Applying sentry.0051_fix_auditlog_pickled_data...NoneType: None
15:02:24 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Team') attrs=[] factory=<function __simple_class_factory_compat at 0x7f4ed8caa1e0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/monkey/pickle.py", line 210, in py3_compat_pickle_loads
    return original_pickle_loads(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 1: ordinal not in range(128)
15:02:25 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Team') attrs=[] factory=<function __simple_class_factory_compat at 0x7f4ed8caa1e0>)
NoneType: None
15:02:25 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Team') attrs=[] factory=<function __simple_class_factory_compat at 0x7f4ed8caa1e0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/monkey/pickle.py", line 210, in py3_compat_pickle_loads
    return original_pickle_loads(*args, **kwargs)
```
```NoneType: None
15:02:28 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Team') attrs=[] factory=<function __simple_class_factory_compat at 0x7f4ed8caa1e0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/monkey/pickle.py", line 210, in py3_compat_pickle_loads
    return original_pickle_loads(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 1: ordinal not in range(128)
```

### Expected Result

events should be rescheduled, but they are not visible

### Actual Result

events should be rescheduled, but they are not visible
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/13086266/144191232-2b17b922-9ec3-412f-9563-881b154e220b.png">

**Comment by markstory** [comment]
Looks like you have non-ascii code points in some of your pickled data. Do you have a Team that uses `ä`?

**Comment by letnab** [comment]
I find it difficult to answer. But that's why the new version does not display past events. Errors were only on event logs
