### ISSUE TITLE
InvalidResponse: Protocol error, got "\x01" as reply type byte

### ISSUE THREAD

**Issue by MikeVL** [getsentry/sentry#3044]
Redis version 3.0.7
```
[ERROR] Unable to incr internal metric
Traceback (most recent call last):
  File "/srv/sentry/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 53, in _incr_internal
    tsdb.incr(tsdb.models.internal, full_key, count=amount)
  File "/srv/sentry/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 146, in incr
    self.incr_multi([(model, key)], timestamp, count)
  File "/srv/sentry/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 168, in incr_multi
    self.calculate_expiry(rollup, max_values, timestamp),
  File "/srv/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 577, in __exit__
    self.mapping_client.join(timeout=timeout)
  File "/srv/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 366, in join
    command_buffer.wait_for_responses(self)
  File "/srv/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 208, in wait_for_responses
    self.connection, command_name)
  File "/srv/sentry/local/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/srv/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/srv/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 362, in read_response
    response = self._reader.gets()
InvalidResponse: Protocol error, got "\x01" as reply type byte
```

**Comment by mitsuhiko** [comment]
That's kinda scary. Can you share some of your setup?

* Version of python
* Version of redis
* Python package versions (`pip freeze`)

**Comment by MikeVL** [comment]
I think the problem in the hiredis v0.1.6

Ubuntu 14.04.4 LTS, Python 2.7.6

Sentry config sample:
```
SENTRY_OPTIONS = {
    ...
    'redis.clusters': {
        'default': {
            'hosts': {
                0: { 'host': '127.0.0.1', 'port': 6379 }
            }
        }
    },
    ...
}
SENTRY_CACHE = 'sentry.cache.redis.RedisCache'
SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'
SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'
```

pip freeze output:
```
BeautifulSoup==3.2.1
Django==1.6.11
Markdown==2.4.1
PyYAML==3.11
Pygments==1.6
South==1.0.1
amqp==1.4.9
anyjson==0.3.3
argparse==1.2.1
billiard==3.3.0.20
boto==2.39.0
celery==3.1.18
cffi==1.5.2
click==6.6
contextlib2==0.5.1
cryptography==1.3.1
cssselect==0.9.1
cssutils==0.9.10
django-bitfield==1.7.1
django-celery==3.0.23
django-celery-email==1.0.4
django-crispy-forms==1.4.0
django-debug-toolbar==1.3.2
django-jsonfield==0.9.13
django-paging==0.2.5
django-picklefield==0.3.2
django-recaptcha==1.0.5
django-ses-backend==0.1.1
django-social-auth==0.7.28
django-static-compiler==0.3.3
django-statsd-mozilla==0.3.14
django-sudo==1.2.1
django-templatetag-sugar==1.0
djangorestframework==2.3.14
email-reply-parser==0.2.0
enum34==1.1.2
exam==0.10.5
funcsigs==0.4
gunicorn==19.3.0
hiredis==0.1.6
httpagentparser==1.2.2
httplib2==0.9
idna==2.1
ipaddr==2.1.11
ipaddress==1.0.16
kombu==3.0.30
librabbitmq==1.6.1
logan==0.7.1
lxml==3.6.0
mock==1.0.1
ndg-httpsclient==0.4.0
nydus==0.11.0
oauth2==1.9.0.post1
pbr==1.8.1
petname==1.7
progressbar==2.3
psycopg2==2.6.1
py==1.4.31
pyOpenSSL==16.0.0
pyasn1==0.1.9
pycparser==2.14
pynliner==0.5.2
pytest==2.6.4
pytest-django==2.9.1
python-dateutil==2.5.2
python-gitlab==0.12.2
python-memcached==1.57
python-openid==2.2.5
pytz==2014.7
raven==5.12.0
rb==1.4
redis==2.10.5
requests==2.9.1
sentry==8.3.2
sentry-gitlab==0.2.0
sentry-slack==0.5.0
sentry-statsd==0.0.2
setproctitle==1.1.9
simplejson==3.8.2
six==1.10.0
sqlparse==0.1.19
statsd==3.1
toronado==0.0.7
uWSGI==2.0.12
ua-parser==0.7.0
urllib3==1.14
wsgiref==0.1.2
```

**Comment by mitsuhiko** [comment]
We're running the same version and no issues of that type are known. Is there a proxy in front of redis?

**Comment by mitsuhiko** [comment]
In which cases do you see this error and in what frequency?

**Comment by mitsuhiko** [comment]
Also are you running celery beat as a separate process or in one of the workers with the `-B` flag?

**Comment by MikeVL** [comment]
>  Is there a proxy in front of redis?
No proxy. All at on vm.

/srv/sentry/bin/sentry celery worker -B -c 4 -l info

**Comment by MikeVL** [comment]
More redis errors:

```
[2016-04-13 14:10:57,053: INFO/MainProcess] Received task: sentry.tasks.index_event_tags[c630ba49-bae9-4f41-90bf-024dfe8d327a]
[ERROR] Unable to incr internal metric
Traceback (most recent call last):
  File "/srv/sentry/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 53, in _incr_internal
    tsdb.incr(tsdb.models.internal, full_key, count=amount)
  File "/srv/sentry/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 146, in incr
    self.incr_multi([(model, key)], timestamp, count)
  File "/srv/sentry/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 168, in incr_multi
    self.calculate_expiry(rollup, max_values, timestamp),
  File "/srv/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 577, in __exit__
    self.mapping_client.join(timeout=timeout)
  File "/srv/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 366, in join
    command_buffer.wait_for_responses(self)
  File "/srv/sentry/local/lib/python2.7/site-packages/rb/clients.py", line 208, in wait_for_responses
    self.connection, command_name)
  File "/srv/sentry/local/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/srv/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/srv/sentry/local/lib/python2.7/site-packages/redis/connection.py", line 357, in read_response
    (e.args,))
ConnectionError: Error while reading from socket: ('Connection closed by server.',)
```

**Comment by mitsuhiko** [comment]
Can you run beat as a separate process? If beat runs in the same process as the worker (with the `-B`) flag then very bad things happen.  This has not been supported since the Sentry 8 upgrade. I'm willing to bet that this will solve the issue.

Instead run `sentry celery beat` on one machine separately and remove `-B` from the worker invocation.

**Comment by MikeVL** [comment]
Thanks! This works fine!
