### ISSUE TITLE
error upgrading to 8.3 from 7.7

### ISSUE THREAD

**Issue by awolde** [getsentry/sentry#3047]
I have a db that was in 7.7. Installed a new v8.3 and try to connect it to the 7.7 db, got this error.

```
$ SENTRY_CONF=/etc/sentry/sentry.conf.py /var/www/sentry/bin/sentry upgrade
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > captcha
 > crispy_forms
 > debug_toolbar
 > raven.contrib.django.raven_compat
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > south
 > sudo

Not synced (use migrations):
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
(use ./manage.py migrate to migrate these)
Running migrations for sentry:
 - Migrating forwards to 0245_auto__del_field_project_callsign__del_unique_project_organization_call.
 > sentry:0191_auto__del_alert__del_alertrelatedgroup__del_unique_alertrelatedgroup_g
Error in migration: sentry:0191_auto__del_alert__del_alertrelatedgroup__del_unique_alertrelatedgroup_g
[ERROR] Unable to fetch internal project
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 78, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 259, in get_from_cache
    result = self.get(**kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 39, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column sentry_project.forced_color does not exist
LINE 1: ..."sentry_project"."slug", "sentry_project"."name", "sentry_pr...
                                                             ^

SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."forced_color", "sentry_project"."organization_id", "sentry_project"."team_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event" FROM "sentry_project" WHERE "sentry_project"."id" = %s
[ERROR] Unable to fetch internal project
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 78, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 259, in get_from_cache
    result = self.get(**kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 39, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column sentry_project.forced_color does not exist
LINE 1: ..."sentry_project"."slug", "sentry_project"."name", "sentry_pr...
                                                             ^

SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."forced_color", "sentry_project"."organization_id", "sentry_project"."team_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event" FROM "sentry_project" WHERE "sentry_project"."id" = %s
Traceback (most recent call last):
  File "/var/www/sentry/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 148, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 26, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 37, in upgrade
    verbosity=verbosity,
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/var/www/sentry/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/var/www/sentry/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/migrations/0191_auto__del_alert__del_alertrelatedgroup__del_unique_alertrelatedgroup_g.py", line 12, in forwards
    db.delete_unique(u'sentry_alertrelatedgroup', ['group_id', 'alert_id'])
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/var/www/sentry/local/lib/python2.7/site-packages/south/db/generic.py", line 644, in delete_unique
    raise ValueError("Cannot find a UNIQUE constraint on table %s, columns %r" % (table_name, columns))
ValueError: Cannot find a UNIQUE constraint on table sentry_alertrelatedgroup, columns ['group_id', 'alert_id']
```

**Comment by mattrobenolt** [comment]
Is this on Postgres?

**Comment by mattrobenolt** [comment]
Nevermind, I see postgres in the stacktrace. :)

**Comment by mattrobenolt** [comment]
@awolde So the error here is that there expects to be a UNIQUE constraint it's removing, that doesn't exist.

> ValueError: Cannot find a UNIQUE constraint on table sentry_alertrelatedgroup, columns ['group_id', 'alert_id']

Everything else in this is noise. :(

This UNIQUE constraint should have been created back in migration 0092.

I'm not sure how you got into this state with the database. You could try manually adding this constraint then re-running.

**Comment by awolde** [comment]
I dumped the database to another box. I didn't want to run migrate on running sentry instance. Will try with the constraint.

**Comment by awolde** [comment]
It has a constrain already
```sentry_prod=> \d+ sentry_alertrelatedgroup;
                                              Table "sentry.sentry_alertrelatedgroup"
  Column  |  Type  |                               Modifiers                               | Storage  | Stats target | Description
----------+--------+-----------------------------------------------------------------------+----------+--------------+-------------
 id       | bigint | not null default nextval('sentry_alertrelatedgroup_id_seq'::regclass) | plain    |              |
 group_id | bigint | not null                                                              | plain    |              |
 alert_id | bigint | not null                                                              | plain    |              |
 data     | text   |                                                                       | extended |              |
Indexes:
    "sentry_alertrelatedgroup_pkey" PRIMARY KEY, btree (id)
    "sentry_alertrelatedgroup_group_id_50403ae25779becb_uniq" UNIQUE CONSTRAINT, btree (group_id, alert_id)
    "sentry_alertrelatedgroup_alert_id" btree (alert_id)
    "sentry_alertrelatedgroup_group_id" btree (group_id)
Foreign-key constraints:
    "alert_id_refs_id_318c5c87" FOREIGN KEY (alert_id) REFERENCES sentry_alert(id) DEFERRABLE INITIALLY DEFERRED
    "group_id_refs_id_60f6fe2e" FOREIGN KEY (group_id) REFERENCES sentry_groupedmessage(id) DEFERRABLE INITIALLY DEFERRED
Has OIDs: no
```

**Comment by the-glu** [comment]
I had the sames issues, in this (same ?) context: mysql -> postgress, sentry 7 -> 8

I used

```
ALTER TABLE sentry_alertrelatedgroup ADD CONSTRAINT sentry_alertrelatedgroup_group_id_5779becb_uniq UNIQUE (group_id, alert_id);
ALTER TABLE sentry_accessgroup ADD CONSTRAINT sentry_accessgroup_team_id_3032e57c_uniq UNIQUE (team_id, name);
```

to fix the problem :)

**Comment by hifiveszu** [comment]
@the-glu Thank you! You saved my day.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
