### ISSUE TITLE
Strange error on 8.3.4 update

### ISSUE THREAD

**Issue by foal** [getsentry/sentry#3092]
I tried update (by source build) from 8.0.4 to 8.3.4

su - sentry
cd dist/sentry.git/
#revert local changes
git checkout .
git pull
git checkout 8.3.4
cd /var/sentry/sentry.git
source /var/sentry/bin/activate
python setup.py develop

And have got the following error:

```bash
[webpack]
ModuleParseError: Module parse failed: /home/sentry/dist/sentry.git/src/sentry/static/sentry/app/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import jQuery from 'jquery';
|
| // setup jquery for CSRF tokens
    at DependenciesBlock.<anonymous> (/home/sentry/dist/sentry.git/node_modules/webpack/lib/NormalModule.js:113:20)
    at DependenciesBlock.onModuleBuild (/home/sentry/dist/sentry.git/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/sentry/dist/sentry.git/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/sentry/dist/sentry.git/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/sentry/dist/sentry.git/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/sentry/dist/sentry.git/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#removeSelf is deprecated. Use Node#remove.
Traceback (most recent call last):
  File "setup.py", line 311, in run
    self._build_static()
  File "setup.py", line 382, in _build_static
    cwd=work_path, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['node_modules/.bin/webpack', '-p', '--bail']' returned non-zero exit status 1
unable to build Sentry's static assets!
Hint: You might be running an invalid version of NPM.
```

**Comment by foal** [comment]
Update to 8.2.4 works.

**Comment by mattrobenolt** [comment]
Hmm, we don't even have an 8.3.4. Do you mean 8.3.2?

And what version of node/npm do you have? It seems like something is wrong in that area. 

You could also try just deleting your entire `node_modules` folder and trying again. 

Is there a reason you install from source vs the packages we ship to pypi? The packages are pre compiled and ready to go.

**Comment by foal** [comment]
You are right 8.3.2. 

I will try to remove node_modules. 

The reason is that I started with 8.0.0.dev, when packages on pypi did not exist. May be it is time to switch to packages back.

**Comment by foal** [comment]
remove node_modules: the same issue with some additional warnings.
```bash
building assets for Sentry v8.3.2 (build b0f8b55a5b7dc9bbe4aa88d6b0b4b0e73d94c520)
initializing git submodules
running [npm install --quiet]
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
../src/zopfli-binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodezopfli::CompressBinding::Sync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/zopfli-binding.cc:173:20: warning: ‘format’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     &out, &outsize);
                    ^
../src/zopfli-binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodezopfli::CompressBinding::Async(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/zopfli-binding.cc:105:78: warning: ‘format’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   : Nan::AsyncWorker(callback), format(format), zopfli_options(zopfli_options) {
                                                                              ^
../src/zopfli-binding.cc:150:16: note: ‘format’ was declared here
   ZopfliFormat format;
                ^
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
running [webpack]
ModuleParseError: Module parse failed: /home/sentry/dist/sentry.git/src/sentry/static/sentry/app/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import jQuery from 'jquery';
|
| // setup jquery for CSRF tokens
    at DependenciesBlock.<anonymous> (/home/sentry/dist/sentry.git/node_modules/webpack/lib/NormalModule.js:113:20)
    at DependenciesBlock.onModuleBuild (/home/sentry/dist/sentry.git/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/sentry/dist/sentry.git/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/sentry/dist/sentry.git/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/sentry/dist/sentry.git/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/sentry/dist/sentry.git/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#removeSelf is deprecated. Use Node#remove.
Traceback (most recent call last):
  File "setup.py", line 311, in run
    self._build_static()
  File "setup.py", line 382, in _build_static
    cwd=work_path, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['node_modules/.bin/webpack', '-p', '--bail']' returned non-zero exit status 1
unable to build Sentry's static assets!
Hint: You might be running an invalid version of NPM.
(sentry)sentry@loft11061:~/dist/sentry.git$
```

**Comment by foal** [comment]
(sentry)sentry@loft11061:~/dist/sentry.git$ npm -v
3.8.6

**Comment by mattrobenolt** [comment]
Yeah, I'm not sure what the issue is tbh. There are a lot of pieces involved here. If just recommend using our packages now. You can just uninstall, then `pip install sentry==8.3.4` faster than trying to figure this out. :)

**Comment by mattrobenolt** [comment]
Whoops, `pip install sentry==8.3.2` ;)

**Comment by foal** [comment]
Understand :) Will try with package.

**Comment by mattrobenolt** [comment]
I'm going to close this out since there's nothing for us to do here.

**Comment by foal** [comment]
Thank you for you help. I have successful updated my senty to 8.3.2 by pip.

**Comment by loisaidasam** [comment]
I see that this is an old issue, and maybe not super common (who installs from source anyway!) but I'm facing the same error when trying to install v9.1.2 from source.

What are acceptable node/npm versions for performing this?

I tried with node version `v0.10.29` and `v13.12.0` and `v10.19.0` and npm version `6.14.4` and `6.13.4`

(my reason for using source is that I'm trying a forked version with a few local changes)
