### ISSUE TITLE
Install error ubuntu 16:04 UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

### ISSUE THREAD

**Issue by ratt** [getsentry/sentry#3143]
Hi Guys, 

Trying to install sentry on a fresh Ubuntu server 16:04, The following exception occurs 

Exception:
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/var/www/sentry/local/lib/python2.7/site-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/var/www/sentry/local/lib/python2.7/site-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/var/www/sentry/local/lib/python2.7/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/var/www/sentry/local/lib/python2.7/site-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/var/www/sentry/local/lib/python2.7/site-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/var/www/sentry/local/lib/python2.7/site-packages/pip/req/req_install.py", line 997, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/var/www/sentry/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 535, in get_distribution
    dist = get_provider(dist)
  File "/var/www/sentry/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 415, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/var/www/sentry/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/var/www/sentry/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 808, in resolve
    if not req_extras.markers_pass(req):
  File "/var/www/sentry/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 993, in markers_pass
    return not req.marker or any(extra_evals) or req.marker.evaluate()
  File "/var/www/sentry/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/var/www/sentry/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/var/www/sentry/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

(sentry) root@loki:/var/www/sentry# pip list
pip (8.1.1)
pkg-resources (0.0.0)
setuptools (20.10.1)
wheel (0.29.0)

Any ideas on how to resolve this issue ?

**Comment by Forever-Young** [comment]
I managed to install it with easy_install.

**Comment by NightBlaze** [comment]
+1

**Comment by mattrobenolt** [comment]
This is definitely unrelated to Sentry itself. It seems to be a bug with pip and/or setuptools? https://github.com/pypa/pip

This seems related? https://github.com/pypa/pip/pull/3630 cc @dstufft ?

**Comment by GeoTob** [comment]
Came across this today, downgrading pip to 8.1.0 works for now, ie

```
pip install pip==8.1.0
pip install -U sentry
```

**Comment by RonnyPfannschmidt** [comment]
this is a typical common case of ubuntu broke the context

pkg_ressources should not be a separate magical package with a `0.0.0` version

this is entirely the fault of ubuntu mucking around with things they don't understand

**Comment by caspii** [comment]
I fixed it with `pip install pip==8.1.0`
