### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3178]
This happens on attempting to snooze an issue from the dashboard.

```
TypeError: Converting circular structure to JSON
  at request(./app/api.jsx:78:18)
  at _wrapRequest(./app/api.jsx:129:16)
  at bulkUpdate(./app/api.jsx:158:16)
  at onUpdate(./app/components/compactIssue.jsx:206:13)
  at onSnooze(./app/components/compactIssue.jsx:196:9)
  at func(./app/components/compactIssue.jsx:48:15)
  at invokeGuardedCallback(~/react/lib/ReactErrorUtils.js:27:0)
  at executeDispatch(~/react/lib/EventPluginUtils.js:79:0)
  at executeDispatchesInOrder(~/react/lib/EventPluginUtils.js:99:0)
  at executeDispatchesAndRelease(~/react/lib/EventPluginHub.js:43:0)
  at forEach(~/react/lib/EventPluginHub.js:54:0)
  at forEachAccumulated(~/react/lib/forEachAccumulated.js:23:0)
  at processEventQueue(~/react/lib/EventPluginHub.js:259:0)
  at runEventQueueInBatch(~/react/lib/ReactEventEmitterMixin.js:18:0)
  at _handleTopLevel(~/react/lib/ReactEventEmitterMixin.js:34:0)
  at handleTopLevelWithoutPath(~/react/lib/ReactEventListener.js:93:0)
  at call(~/react/lib/ReactEventListener.js:73:0)
  at perform(~/react/lib/Transaction.js:136:0)
  at batchedUpdates(~/react/lib/ReactDefaultBatchingStrategy.js:62:0)
  at batchedUpdates(~/react/lib/ReactUpdates.js:94:0)
  at apply(~/react/lib/ReactEventListener.js:204:0)
  at apply(~/raven-js/src/raven.js:264:0)
```

**Comment by mitsuhiko** [comment]
Was also reported on twitter: https://twitter.com/jamieburchell/status/728213719784816640
