### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by DaveBlooman** [getsentry/sentry#3417]
```sh
File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
self.run_command(cmd_name)
File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
self.build_extensions()
File "/www/sentry/build/Pillow/setup.py", line 512, in build_extensions
' using --disable-%s, aborting' % (f, f))
ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
----------------------------------------
Cleaning up...
Command /www/sentry/bin/python -c "import setuptools;__file__='/www/sentry/build/Pillow/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kzLFLJ-record/install-record.txt --single-version-externally-managed --install-headers /www/sentry/include/site/python2.7 failed with error code 1 in /www/sentry/build/Pillow
Traceback (most recent call last):
File "/www/sentry/bin/pip", line 9, in <module>
load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
File "/www/sentry/lib/python2.7/site-packages/pip/__init__.py", line 148, in main
return command.main(args[1:], options)
File "/www/sentry/lib/python2.7/site-packages/pip/basecommand.py", line 169, in main
text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 29: ordinal not in range(128)
```

**Comment by mattrobenolt** [comment]
Looks like you're missing libjpeg-dev which is in our docs. https://docs.getsentry.com/on-premise/server/installation/

**Comment by DaveBlooman** [comment]
Is this a new requirement, we build all about Amazon images every day, looks like it started a couple days ago, using Centos 7.

**Comment by mattrobenolt** [comment]
It has always been listed as a requirement, but with 8.5 it became a hard requirement. Whereas before it wouldn't have complained if it was missing since we didn't actually use it. 

--
Matt Robenolt
@mattrobenolt




On Mon, Jun 6, 2016 at 8:45 AM -0700, "David Blooman" <notifications@github.com> wrote:












Is this a new requirement, we build all about Amazon images every day, looks like it started a couple days ago, using Centos 7.
