### ISSUE TITLE
Error installing Pillow in Docker

### ISSUE THREAD

**Issue by kevgathuku** [getsentry/sentry#3437]
Hello,
I get the following error while trying to install Python packages, and specifically Pillow, in docker during the [`Bootstrap the container`](https://github.com/getsentry/sentry/blob/master/Dockerfile.dev#L10) step
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7Vtuei/Pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(), )
      File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-7Vtuei/Pillow/setup.py", line 512, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
```

**Comment by mattrobenolt** [comment]
Yeah, lemme get this Dockerfile.dev up to date with recent changes. We don't actively use it, so hang in there. :)

**Comment by kevgathuku** [comment]
Thanks for the merge 😄 
Looking forward to getting it set up on Docker.
