### ISSUE TITLE
Unable to fetch ProjectKey for internal project

### ISSUE THREAD

**Issue by grimurd** [getsentry/sentry#3492]
I upgraded to Sentry 8.5.1 yesterday. I'm using the docker version found at https://hub.docker.com/_/sentry/. Everything worked fine yesterday and I had no problems after the upgrade.

This morning I suddenly started having this issue where the site hangs at Loading data for your organization and is stuck there.

When I check the logs of the sentry-web process this is the error that I can find:
```
[ERROR] Unable to fetch ProjectKey for internal project
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/templatetags/sentry_react.py", line 66, in _get_public_dsn
    )[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[ERROR] Internal project (id=1) does not exist
```

This is odd to me as I haven't deleted any projects for a long time.

Any way for me to fix this easily?

UPDATE: This seems to only happen when I'm using Google Chrome(51.0.2704.84), once I switched to firefox everything worked smoothly.

**Comment by grimurd** [comment]
Incognito in google chrome works fine so this is some cache issue with my browser I presume. Closing.
