### ISSUE TITLE
[Flaky CI]: tests/relay_integration/test_sdk.py::test_recursion_breaker (test pollution)

### ISSUE THREAD

**Issue by asottile-sentry** [getsentry/sentry#35541]
### Flakiness Type

Assertion failure

### Name of Job

relay test (3.8.12)

### Name of Test

tests/relay_integration/test_sdk.py::test_recursion_breaker

### Link to Test Run

https://github.com/getsentry/sentry/runs/6821336548?check_suite_focus=true

### Details

this is a test pollution

via https://github.com/asottile/detect-test-pollution

```console
$ detect-test-pollution --testids-file testlist --failing-test tests/relay_integration/test_sdk.py::test_recursion_breaker
discovering all tests...
-> pre-discovered 29 tests!
ensuring test passes by itself...
-> OK!
ensuring test fails with test group...
-> OK!
running step 1:
- 28 tests remaining (about 5 steps)
running step 2:
- 14 tests remaining (about 4 steps)
running step 3:
- 7 tests remaining (about 3 steps)
running step 4:
- 4 tests remaining (about 2 steps)
running step 5:
- 2 tests remaining (about 1 steps)
-> the polluting test is: tests/sentry/ingest/ingest_consumer/test_ingest_consumer_kafka.py::test_ingest_consumer_reads_from_topic_and_calls_celery_task[asynchronous]
```

here's the minimal reproduction:

```console
$ pytest tests/sentry/ingest/ingest_consumer/test_ingest_consumer_kafka.py::test_ingest_consumer_reads_from_topic_and_calls_celery_task[synchronous] tests/relay_integration/test_sdk.py::test_recursion_breaker
============================================ test session starts ============================================
platform darwin -- Python 3.8.13, pytest-6.1.0, py-1.11.0, pluggy-0.13.1
rootdir: /Users/asottile/workspace/sentry, configfile: pyproject.toml
plugins: rerunfailures-9.1.1, cov-2.11.1, django-3.10.0, sentry-0.1.9
collected 2 items                                                                                           

tests/sentry/ingest/ingest_consumer/test_ingest_consumer_kafka.py .                                   [ 50%]
tests/relay_integration/test_sdk.py F                                                                 [100%]

================================================= FAILURES ==================================================
__________________________________________ test_recursion_breaker ___________________________________________
tests/relay_integration/test_sdk.py:55: in test_recursion_breaker
    post_event_with_sdk({"message": "internal client test", "event_id": event_id})
E   Failed: DID NOT RAISE <class 'ValueError'>
------------------------------------------- Captured stdout setup -------------------------------------------
13:30:24 [WARNING] batching-kafka-consumer: Topic 'ingest-events' or its partitions are not ready, retrying...
13:30:24 [WARNING] batching-kafka-consumer: Topic 'ingest-events' or its partitions are not ready, retrying...
13:30:25 [WARNING] batching-kafka-consumer: Topic 'ingest-events' or its partitions are not ready, retrying...
------------------------------------------- Captured stderr setup -------------------------------------------
%4|1654867824.860|CONFWARN|rdkafka#producer-7| [thrd:app]: Configuration property allow.auto.create.topics is a consumer property and will be ignored by this producer instance
Exception ignored in: <socket.socket fd=18, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Traceback (most recent call last):
  File "/Users/asottile/.pyenv/versions/3.8.13/lib/python3.8/functools.py", line 57, in update_wrapper
    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
ResourceWarning: unclosed <socket.socket fd=18, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Exception ignored in: <socket.socket fd=19, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Traceback (most recent call last):
  File "/Users/asottile/.pyenv/versions/3.8.13/lib/python3.8/functools.py", line 57, in update_wrapper
    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
ResourceWarning: unclosed <socket.socket fd=19, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Exception ignored in: <socket.socket fd=20, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Traceback (most recent call last):
  File "/Users/asottile/.pyenv/versions/3.8.13/lib/python3.8/functools.py", line 57, in update_wrapper
    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
ResourceWarning: unclosed <socket.socket fd=20, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Exception ignored in: <socket.socket fd=21, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Traceback (most recent call last):
  File "/Users/asottile/.pyenv/versions/3.8.13/lib/python3.8/functools.py", line 57, in update_wrapper
    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
ResourceWarning: unclosed <socket.socket fd=21, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Exception ignored in: <socket.socket fd=22, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Traceback (most recent call last):
  File "/Users/asottile/.pyenv/versions/3.8.13/lib/python3.8/functools.py", line 57, in update_wrapper
    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
ResourceWarning: unclosed <socket.socket fd=22, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
%5|1654867825.214|PARTCNT|rdkafka#consumer-4| [thrd:main]: Topic ingest-events partition count changed from 1 to 0
-------------------------------------------- Captured log setup ---------------------------------------------
WARNING  batching-kafka-consumer:batching_kafka_consumer.py:50 Topic 'ingest-events' or its partitions are not ready, retrying...
WARNING  batching-kafka-consumer:batching_kafka_consumer.py:50 Topic 'ingest-events' or its partitions are not ready, retrying...
WARNING  batching-kafka-consumer:batching_kafka_consumer.py:50 Topic 'ingest-events' or its partitions are not ready, retrying...
------------------------------------------- Captured stdout call --------------------------------------------
13:30:28 [INFO] batching-kafka-consumer: New partitions assigned: [TopicPartition{topic=ingest-events,partition=0,offset=-1001,error=None}]
------------------------------------------- Captured stderr call --------------------------------------------
%4|1654867826.106|OFFSET|rdkafka#consumer-4| [thrd:main]: ingest-events [0]: offset reset (at offset 2) to BEGINNING: fetch failed due to requested offset not available on the broker: Broker: Offset out of range
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51119)
Traceback (most recent call last):
  File "/Users/asottile/.pyenv/versions/3.8.13/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/asottile/.pyenv/versions/3.8.13/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/asottile/.pyenv/versions/3.8.13/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/asottile/workspace/sentry/.venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/Users/asottile/workspace/sentry/.venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Users/asottile/.pyenv/versions/3.8.13/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
----------------------------------------
--------------------------------------------- Captured log call ---------------------------------------------
INFO     batching-kafka-consumer:batching_kafka_consumer.py:268 New partitions assigned: [TopicPartition{topic=ingest-events,partition=0,offset=-1001,error=None}]
----------------------------------------- Captured stdout teardown ------------------------------------------
13:30:42 [INFO] batching-kafka-consumer: Partitions revoked: [TopicPartition{topic=ingest-events,partition=0,offset=-1001,error=None}]
----------------------------------------- Captured stderr teardown ------------------------------------------
Exception ignored in: <socket.socket fd=16, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Traceback (most recent call last):
  File "/Users/asottile/workspace/sentry/.venv/lib/python3.8/site-packages/_pytest/fixtures.py", line 926, in _teardown_yield_fixture
    next(it)
ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Exception ignored in: <socket.socket fd=17, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Traceback (most recent call last):
  File "/Users/asottile/workspace/sentry/.venv/lib/python3.8/site-packages/_pytest/fixtures.py", line 926, in _teardown_yield_fixture
    next(it)
ResourceWarning: unclosed <socket.socket fd=17, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Exception ignored in: <socket.socket fd=18, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Traceback (most recent call last):
  File "/Users/asottile/workspace/sentry/.venv/lib/python3.8/site-packages/_pytest/fixtures.py", line 926, in _teardown_yield_fixture
    next(it)
ResourceWarning: unclosed <socket.socket fd=18, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Exception ignored in: <socket.socket fd=19, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
Traceback (most recent call last):
  File "/Users/asottile/workspace/sentry/.venv/lib/python3.8/site-packages/_pytest/fixtures.py", line 926, in _teardown_yield_fixture
    next(it)
ResourceWarning: unclosed <socket.socket fd=19, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/Users/asottile/Library/Containers/com.docker.docker/Data/docker.raw.sock>
------------------------------------------- Captured log teardown -------------------------------------------
INFO     batching-kafka-consumer:batching_kafka_consumer.py:272 Partitions revoked: [TopicPartition{topic=ingest-events,partition=0,offset=-1001,error=None}]
========================================== short test summary info ==========================================
FAILED tests/relay_integration/test_sdk.py::test_recursion_breaker - Failed: DID NOT RAISE <class 'ValueEr...
======================================= 1 failed, 1 passed in 29.33s ========================================
%4|1654867843.369|TERMINATE|rdkafka#producer-5| [thrd:app]: Producer terminating with 1 message (181 bytes) still in queue or transit: use flush() to wait for outstanding message delivery
```

~something about the other test running first causes this test to fail -- I don't completely understand what's going on but I suspect some state in the first test is not being cleaned up which the second test expects is absent

**Comment by asottile-sentry** [comment]
this appears to have been fixed at some point
