### ISSUE TITLE
Sentry tries to parse redis password from config.yml as int?

### ISSUE THREAD

**Issue by RankoR** [getsentry/sentry#3574]
I use the following config in config.yml:

```
redis.clusters:
  default:
    hosts:
      0:
        host: 'some-sentry.redis.cache.windows.net'
        port: 6379
        password: 'someletters/d9hn+Zazs='
```

And when I run _sentry run worker_ command, it fails:
```
Traceback (most recent call last):
  File "/home/sentry/sentry/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 152, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 26, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/runner/commands/run.py", line 140, in worker
    **options
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 100, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 124, in setup_instance
    self._conninfo = self.app.connection()
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/celery/app/base.py", line 385, in connection
    'BROKER_CONNECTION_TIMEOUT', connect_timeout
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/kombu/connection.py", line 167, in __init__
    params.update(parse_url(hostname))
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/kombu/utils/url.py", line 32, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "/home/sentry/sentry/local/lib/python2.7/site-packages/kombu/utils/url.py", line 24, in _parse_url
    return (scheme, unquote(parts.hostname or '') or None, parts.port,
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'someletters' # !!! Yes, it tries to parse only the part before slash
```

So, I think it tries to parse password field as port field? As I can see from official docs (https://docs.getsentry.com/on-premise/server/installation/), the configuration is correct.
If I remove the password field, it parses well, but fails to connect (of course)

**Comment by mattrobenolt** [comment]
So _now_ this is erroring because of `BROKER_URL`. :( Unlike the last one. So you got past the first thing by configuring `redis.clusters` fine, but `BROKER_URL` is now being parsed wrong.

**Comment by RankoR** [comment]
@mattrobenolt and how to fix it? If the error is because of unusual password contents in BROKER_URL, I can't change it because it's auto-generated by Azure.

**Comment by mattrobenolt** [comment]
So the problem is ultimately because of:

```
>>> urlparse('redis://:x/y@redis/10')
ParseResult(scheme='redis', netloc=':x', path='/y@redis/10', params='', query='', fragment='')
```

I'm not sure how we can work around this tbh since this is through lots of levels of indirection in libraries that we don't control.

**Comment by RankoR** [comment]
@mattrobenolt Okay, I've regenerated the password and now it's without slashes and it works! Thanks a lot :)
