### ISSUE TITLE
Upgrading from 8.4.1 to 8.6.0, upgrade command fails to start due to missing logging config

### ISSUE THREAD

**Issue by do3cc** [getsentry/sentry#3650]
```
[sentry@sp1 sentry]$ SENTRY_CONF=/home/sentry/sentry/etc UWSGI_INI=/home/sentry/sentry/etc/uwsgi.ini https_proxy='http://someip:8090' /home/sentry/sentry/bin/sentry upgrade
Traceback (most recent call last):
  File "/home/sentry/sentry/bin/sentry", line 91, in <module>
    sys.exit(sentry.runner.main())
  File "/home/sentry/sentry/eggs/sentry-8.6.0-py2.7.egg/sentry/runner/__init__.py", line 152, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/sentry/sentry/eggs/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/sentry/sentry/eggs/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/sentry/sentry/eggs/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sentry/sentry/eggs/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sentry/sentry/eggs/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/sentry/eggs/click-6.2-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/sentry/eggs/sentry-8.6.0-py2.7.egg/sentry/runner/decorators.py", line 34, in inner
    configure()
  File "/home/sentry/sentry/eggs/sentry-8.6.0-py2.7.egg/sentry/runner/__init__.py", line 115, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/home/sentry/sentry/eggs/sentry-8.6.0-py2.7.egg/sentry/runner/settings.py", line 159, in configure
    }, skip_backend_validation=skip_backend_validation)
  File "/home/sentry/sentry/eggs/sentry-8.6.0-py2.7.egg/sentry/runner/initializer.py", line 213, in initialize_app
    configure_structlog()
  File "/home/sentry/sentry/eggs/sentry-8.6.0-py2.7.egg/sentry/runner/initializer.py", line 192, in configure_structlog
    settings.LOGGING['root'].update({
KeyError: 'root'
```

This might be related to us using buildout for deployment. In any case, I need it working so I will likely update the ticket with a fix on my own. But if you have an idea, I'll be glad for any pointers.

**Comment by do3cc** [comment]
My sentry.conf had a logging section because I needed to debug a sentry issue in the past.
Even though I set the parameter "disable_existing_logging" to false, it seems that resulted in me not having a root logger.

**Comment by DMWOO7** [comment]
I got the same error using the following code for logging: 

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'stream_to_console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler'
        },
    },
    'loggers': {
        'django_auth_ldap': {
            'handlers': ['stream_to_console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}
```
Sadly, I can't simply drop the custom logger config, since I need it for troubleshooting LDAP issues...

**Comment by TL-KenYu** [comment]
I am having the same problem trying to get logging working for LDAP in sentry. Have you found a solution?

**Comment by do3cc** [comment]
Define your own logger named 'root' explicitly. that should do the trick

**Comment by TL-KenYu** [comment]
Thanks that worked. Took me a day to figure out, I put the following into the sentry.conf.py
`

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        }
    },

    'default_level':'DEBUG',
    'root':{
        'level':'DEBUG'
    },
    'overridable': ['django_auth_ldap','django']
}

import logging
logfile = "/tmp/django-ldap-debug.log"
my_logger = logging.getLogger('django_auth_ldap')
my_logger.setLevel(logging.DEBUG)
handler = logging.handlers.RotatingFileHandler(logfile, maxBytes=1024 * 500, backupCount=5)
my_logger.addHandler(handler)
`
