### ISSUE TITLE
Cannot add or update a child row

### ISSUE THREAD

**Issue by wwwlde** [getsentry/sentry#3721]
Hello,

I got the following errors:

`IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`sentry_new`.`sentry_groupemailthread`, CONSTRAINT `group_id_refs_id_3c3dd283` FOREIGN KEY (`group_id`) REFERENCES `sentry_groupedmessage` (`id`))')`

and

`IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`sentry_new`.`sentry_grouprulestatus`, CONSTRAINT `group_id_refs_id_66981850` FOREIGN KEY (`group_id`) REFERENCES `sentry_groupedmessage` (`id`))')`

I got it after upgrading from Sentry 8.0.x -> Sentry 8.5.1

It can be connected with some failed database migration? BTW after running upgrade command there were no any errors. 

What I can do with this?

Thanks in advance.

**Comment by mattrobenolt** [comment]
Where do you get this error? And can you provide a full stacktrace?

**Comment by wwwlde** [comment]
Hello, Matt!

Sure! Here it is:

```
[2016-07-14 09:34:03,516: ERROR/MainProcess] Task sentry.tasks.digests.deliver_digest[7b6a5598-51a6-4050-9c84-a34bb228972d] raised unexpected: IntegrityError(1452, 'Cannot add or update a child row: a foreign key constraint fails (`sentr
y_new`.`sentry_groupemailthread`, CONSTRAINT `group_id_refs_id_3c3dd283` FOREIGN KEY (`group_id`) REFERENCES `sentry_groupedmessage` (`id`))')
Traceback (most recent call last):
  File "/opt/sentry/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/tasks/digests.py", line 71, in deliver_digest
    plugin.notify_digest(project, digest)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 218, in notify_digest
    return self.notify(notification)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 199, in notify
    send_to=[user_id],
  File "/opt/sentry/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 85, in _send_mail
    return message.send_async()
  File "/opt/sentry/lib/python2.7/site-packages/sentry/utils/email.py", line 353, in send_async
    messages = self.get_built_messages(to, bcc=bcc)
  File "/opt/sentry/lib/python2.7/site-packages/sentry/utils/email.py", line 340, in get_built_messages
    results = [self.build(to=email, reply_to=send_to, bcc=bcc) for email in send_to]
  File "/opt/sentry/lib/python2.7/site-packages/sentry/utils/email.py", line 314, in build
    'msgid': message_id,
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 391, in get_or_create
    six.reraise(*exc_info)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/opt/sentry/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/sentry/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/sentry/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/sentry/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`sentry_new`.`sentry_groupemailthread`, CONSTRAINT `group_id_refs_id_3c3dd283` FOREIGN KEY (`group_id`) REFERENCES `sentry_groupedmessage` (`id`))'
)
```

**Comment by mattrobenolt** [comment]
I see this is coming from MySQL. :( While we don't officially support MySQL anymore, we do attempt to maintain it and make sure it's not broken. But my guess is there's an incorrect index or a migration that didn't do the exact right thing for MySQL.

Unfortunately, there's not much we can do to debug this, but if you can figure it out and share, we can try to fix on our end. We haven't heard of this before.

Either that, or you just somehow have bad data in your database.
