### ISSUE TITLE
Notification seems not send

### ISSUE THREAD

**Issue by buxx** [getsentry/sentry#3975]
Our Sentry instance seems not send notifications emails. Configuration are:

**My account notification settings**:
![selection_001](https://cloud.githubusercontent.com/assets/1104637/17771110/bf831000-6541-11e6-9971-084e4624243a.png)

**Project exceptions** (where we not receive notification):
![selection_002](https://cloud.githubusercontent.com/assets/1104637/17771134/d66b7686-6541-11e6-8b3e-817277922056.png)

**Project settings**:
![selection_003](https://cloud.githubusercontent.com/assets/1104637/17771150/e6b2abd6-6541-11e6-98a6-a1c2f7dae9b9.png)
![selection_004](https://cloud.githubusercontent.com/assets/1104637/17771152/e7cc0e2c-6541-11e6-99aa-feebb27e2fb0.png)

Sentry web logs with grep on my email:

```
# cat /var/log/supervisor/sentry-web.log | grep -i "xxx.xxx@xxx.xx"
[INFO] root: mail.queued message_to=u'xxx.xxx@xxx.xx' message_type='organization.invite' message_id='<20160805095830.17412.36925@algoo.fr>'
[INFO] sentry.mail: mail.queued message_to=u'xxx.xxx@xxx.xx' message_id='<20160805100850.17412.65406@algoo.fr>' message_type='user.confirm_email'
[INFO] sentry.auth: User authenticated successfully [ip:109.190.10.247 username:u'xxx.xxx@xxx.xx'] 
[INFO] sentry.auth: User authenticated successfully [ip:109.190.10.247 username:u'xxx.xxx@xxx.xx'] 
[INFO] sentry.audit.entry: member.join-team actor_label=u'xxx.xxx@xxx.xx' entry_id=11L actor_id=3
[INFO] sentry.audit.entry: member.join-team actor_label=u'xxx.xxx@xxx.xx' entry_id=12L actor_id=3
[INFO] sentry.audit.entry: team.edit actor_label=u'xxx.xxx@xxx.xx' entry_id=24L actor_id=3
[INFO] sentry.audit.entry: project.edit actor_label=u'xxx.xxx@xxx.xx' entry_id=25L actor_id=3
[INFO] sentry.audit.entry: project.edit actor_label=u'xxx.xxx@xxx.xx' entry_id=26L actor_id=3
```

Sentry workers logs with grep on my email:

cat /var/log/supervisor/sentry-worker.log | grep -i "xxx.xxx@xxx.xx"
[INFO] sentry.mail: mail.queued message_to=u'xxx.xxx@xxx.xx' message_id='<20160805145615.17416.33218@algoo.fr>' message_type='notify.error'

**Note**:  The only logged mail send is on date ``20160805``, exception catched by sentry are dated at ``20160818``. And this mail sen at ``20160805`` was correctly received.

And our SMTP logs didn't receive mails requests.

**Comment by thorerik** [comment]
If you are using a multi-host or docker deployment, make sure your workers have the SMTP configuration as well

**Comment by buxx** [comment]
@thorerik It's a manual installation (python virtual env) and other mails (as account creation, password lost) are correctly received.

**Comment by tkaemming** [comment]
This sounds symptomatic of workers not having a correct SMTP configuration. You're going to want to ensure that all processes (web and worker) are using the same configuration, and have been restarted after any changes were made.

If you're still having problems with this, feel free to use the community support forum at http://forum.sentry.io/ for more support.

**Comment by buxx** [comment]
@tkaemming Hi, thank's for advice. I didn't found reason about worker configs smt. You can see here more details: https://forum.sentry.io/t/catched-errors-dont-sends-mails-notifications/87

But i found this in supervisor workers logs:

```
celery@dev.algoo.fr ready.
Traceback (most recent call last):
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/sentry/tasks/digests.py", line 71, in deliver_digest
    plugin.notify_digest(project, digest)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 221, in notify_digest
    return self.notify(notification)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 202, in notify
    send_to=[user_id],
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 87, in _send_mail
    return message.send_async()
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/sentry/utils/email.py", line 367, in send_async
    messages = self.get_built_messages(to, bcc=bcc)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/sentry/utils/email.py", line 346, in get_built_messages
    results = [self.build(to=email, reply_to=send_to, bcc=bcc) for email in send_to if email]
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/sentry/utils/email.py", line 320, in build
    'msgid': message_id,
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/django/db/models/query.py", line 391, in get_or_create
    six.reraise(*exc_info)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/django/db/transaction.py", line 316, in __exit__
    connection.commit()
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 171, in commit
    self._commit()
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/www/sentry.algoo.fr/venv2.7/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
IntegrityError: insert or update on table "sentry_groupemailthread" violates foreign key constraint "group_id_refs_id_3c3dd283"
DETAIL:  Key (group_id)=(42) is not present in table "sentry_groupedmessage".

[ERROR] celery.worker.job: Task sentry.tasks.digests.deliver_digest[b7bf5fc5-7b0a-4b10-9f0f-628748a0bd50] raised unexpected: IntegrityError('insert or update on table "sentry_groupemailthread" violates foreign key constraint "group_id_refs_id_3c3dd283"\nDETAIL:  Key (group_id)=(42) is not present in table "sentry_groupedmessage".\n',)
```

It seems to be related with the issue.

**Comment by mathiasuhl** [comment]
@buxx  it seems that I have the same problem did you solve it?

**Comment by buxx** [comment]
@mathiasuhl not solved :(

**Comment by ktosiek** [comment]
May be related to #3864
