### ISSUE TITLE
sentry.runner.importer.ConfigurationError: KeyError: 'formatters'

### ISSUE THREAD

**Issue by mwcz** [getsentry/sentry#3993]
When running `sentry upgrade` and some other `sentry foo` commands, I encountered this error:

    (sentry)[sentry@sentry ~]$ sentry upgrade
    Traceback (most recent call last):
      File "/home/sentry/.virtualenvs/sentry/bin/sentry", line 11, in <module>
        sys.exit(main())
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 159, in main
        cli(prog_name=get_prog(), obj={}, max_content_width=100)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 716, in __call__
        return self.main(*args, **kwargs)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 696, in main
        rv = self.invoke(ctx)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
        configure()
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 122, in configure
        configure(ctx, py, yaml, skip_backend_validation)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/settings.py", line 159, in configure
        }, skip_backend_validation=skip_backend_validation)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/initializer.py", line 217, in initialize_app
        bootstrap_options(settings, config['options'])
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/initializer.py", line 92, in bootstrap_options
        from sentry.options import load_defaults
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/options/__init__.py", line 10, in <module>
        from .store import OptionsStore
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/options/store.py", line 17, in <module>
        from sentry.db.models.query import create_or_update
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/db/models/__init__.py", line 11, in <module>
        from .base import *  # NOQA
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/db/models/base.py", line 13, in <module>
        from django.db import models
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/db/models/__init__.py", line 5, in <module>
        from django.db.models.query import Q
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 17, in <module>
        from django.db.models.deletion import Collector
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/db/models/deletion.py", line 4, in <module>
        from django.db.models import signals, sql
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/db/models/sql/__init__.py", line 4, in <module>
        from django.db.models.sql.subqueries import *
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 12, in <module>
        from django.db.models.sql.query import Query
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/db/models/sql/query.py", line 22, in <module>
        from django.db.models.sql import aggregates as base_aggregates_module
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/db/models/sql/aggregates.py", line 9, in <module>
        ordinal_aggregate_field = IntegerField()
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 116, in __init__
        self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
        self._setup(name)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
        self._wrapped = Settings(settings_module)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
        mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
        __import__(name)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/importer.py", line 51, in load_module
        reraise_as(ConfigurationError(msg))
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/utils/settings.py", line 48, in reraise_as
        six.reraise(new_type, new_exception, e_traceback)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/importer.py", line 43, in load_module
        mod = self._load_module(fullname)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/importer.py", line 75, in _load_module
        load_settings(self.config_path, settings=settings_mod, silent=True)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/sentry/runner/importer.py", line 85, in load_settings
        execfile(mod_or_filename, conf.__dict__)
      File "/home/sentry/.sentry/sentry.conf.py", line 166, in <module>
        'format': '[%(levelname)s] %(message)s; instance=%(instance)r; tags=%(tags)r',
    sentry.runner.importer.ConfigurationError: KeyError: 'formatters'

Versions:

    (sentry)[sentry@sentry ~]$ python --version
    Python 2.7.5
    You have mail in /var/spool/mail/sentry
    (sentry)[sentry@sentry ~]$ pip --version
    pip 8.1.2 from /home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages (python 2.7)
    (sentry)[sentry@sentry ~]$ pip freeze
    amqp==1.4.9
    anyjson==0.3.3
    BeautifulSoup==3.2.1
    billiard==3.3.0.23
    celery==3.1.18
    cffi==1.7.0
    click==6.6
    contextlib2==0.5.4
    cryptography==1.4
    cssselect==0.9.2
    cssutils==0.9.10
    Django==1.6.11
    django-auth-kerberos==1.2.4
    django-auth-ldap==1.2.6
    django-bitfield==1.7.1
    django-celery==3.0.23
    django-crispy-forms==1.4.0
    django-debug-toolbar==1.3.2
    django-jsonfield==0.9.13
    django-paging==0.2.5
    django-picklefield==0.3.2
    django-recaptcha==1.0.5
    django-social-auth==0.7.28
    django-statsd-mozilla==0.3.14
    django-sudo==2.1.0
    django-templatetag-sugar==1.0
    djangorestframework==2.3.14
    email-reply-parser==0.2.0
    enum34==1.1.6
    exam==0.10.6
    funcsigs==0.4
    gevent==1.0.1
    greenlet==0.4.6
    gunicorn==19.3.0
    hiredis==0.1.6
    honcho==0.7.1
    httplib2==0.9.2
    idna==2.1
    ipaddr==2.1.11
    ipaddress==1.0.16
    kombu==3.0.35
    logan==0.7.1
    lxml==3.6.4
    Markdown==2.4.1
    meld3==1.0.2
    mock==1.0.1
    ndg-httpsclient==0.4.2
    nydus==0.11.0
    oauth2==1.9.0.post1
    pbr==1.8.1
    petname==1.7
    Pillow==3.2.0
    progressbar==2.3
    psycopg2==2.6.2
    py==1.4.31
    pyasn1==0.1.9
    pycparser==2.14
    Pygments==1.6
    pykerberos==1.1.10
    pyOpenSSL==16.0.0
    pytest==2.6.4
    pytest-django==2.9.1
    pytest-html==1.9.0
    python-dateutil==2.5.3
    python-ldap==2.4.19
    python-memcached==1.58
    python-openid==2.2.5
    python-u2flib-server==4.0.1
    pytz==2016.6.1
    PyYAML==3.11
    qrcode==5.3
    raven==5.24.3
    rb==1.5
    redis==2.10.5
    requests==2.10.0
    selenium==2.53.6
    sentry==8.7.0
    sentry-jira==0.9.0
    setproctitle==1.1.10
    simplejson==3.8.2
    six==1.10.0
    South==1.0.1
    sqlparse==0.2.1
    statsd==3.1
    structlog==16.1.0
    supervisor==3.1.3
    toronado==0.0.10
    ua-parser==0.7.1
    urllib3==1.16
    uWSGI==2.0.13.1

It seems to happen with any `sentry foo` command that involves Django.  Do I have an incorrect version of Django?

Thanks for any help!

**Comment by mattrobenolt** [comment]
Are you doing anything weird in your own configuration for `LOGGING`?

**Comment by mattrobenolt** [comment]
It seems like you're trying to supply your own logging config, which will be problematic since we do lots of fancy things there.

**Comment by mwcz** [comment]
Huh, sure enough.

    LOGGING['loggers']['sentry.metrics'] = {
        'level': 'ERROR',
        'handlers': ['console:metrics'],
        'propagate': False,
    }

    LOGGING['formatters']['metrics'] = {
        'format': '[%(levelname)s] %(message)s; instance=%(instance)r; tags=%(tags)r',
    }

    LOGGING['handlers']['console:metrics'] = {
        'level': 'ERROR',
        'class': 'logging.StreamHandler',
        'formatter': 'metrics',
    }

I have no idea where those came from.  Axe them all?

**Comment by mattrobenolt** [comment]
Yes please. :) You shouldn't need to configure your own logging now.

**Comment by mwcz** [comment]
Worked perfectly, thank you!
