### ISSUE TITLE
BrowserPlugin conflicts with django database router

### ISSUE THREAD

**Issue by julyclyde** [getsentry/sentry#4229]
Sentry 7.7.4 from pypi
I set a write read spliting database router in settings DATABASE_ROUTERS.
When I start sentry web service, it prints many error messages like:

[ERROR] Error processing 'get_event_preprocessors' on 'BrowserPlugin': 'DatabaseWrapper' object has no attribute 'Database'
Traceback (most recent call last):
  File "/opt/meituan/sentry/lib/python2.7/site-packages/sentry/utils/safe.py", line 25, in safe_execute
    with transaction.atomic():
  File "/opt/meituan/sentry/lib/python2.7/site-packages/django/db/transaction.py", line 237, in __enter__
    if not connection.get_autocommit():
  File "/opt/meituan/sentry/lib/python2.7/site-packages/django/db/backends/__init__.py", line 331, in get_autocommit
    self.ensure_connection()
  File "/opt/meituan/sentry/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/opt/meituan/sentry/lib/python2.7/site-packages/django/db/utils.py", line 86, in __exit__
    db_exc_type = getattr(self.wrapper.Database, dj_exc_type.__name__)
AttributeError: 'DatabaseWrapper' object has no attribute 'Database'

**Comment by dcramer** [comment]
@julyclyde sentry 7 is not supported
