### ISSUE TITLE
sentry run web error

### ISSUE THREAD

**Issue by ZimmerHao** [getsentry/sentry#4251]
Sentry upgrade is done, database and user are all created. But when i run sentry run web. It shows below:
    
    Traceback (most recent call last):
      File "/usr/local/bin/sentry", line 11, in <module>
        sys.exit(main())
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/sentry/runner/__init__.py", line 159, in main
        cli(prog_name=get_prog(), obj={}, max_content_width=100)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/core.py", line 716, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/core.py", line 696, in main
        rv = self.invoke(ctx)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/sentry/runner/decorators.py", line 65, in inner
        return ctx.invoke(f, *args, **kwargs)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
        return ctx.invoke(f, *args, **kwargs)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/sentry/runner/commands/run.py", line 82, in web
        workers=workers,
      File "/usr/local/python-2.7.9/lib/python2.7/site-packages/sentry/services/http.py", line 161, in run
        os.execvp('uwsgi', ('uwsgi',))
      File "/usr/local/python-2.7.9/lib/python2.7/os.py", line 346, in execvp
        _execvpe(file, args)
      File "/usr/local/python-2.7.9/lib/python2.7/os.py", line 382, in _execvpe
        func(fullname, *argrest)
    OSError: [Errno 2] No such file or directory

**Comment by mattrobenolt** [comment]
You're missing dependencies. I'm not sure how you upgraded, but this error explicitly is because you're missing `uwsgi`, I'd recommend trying to reinstall since if you're missing this, you're likely missing other things as well.
