### ISSUE TITLE
sentry-post-process-forward-errors: Requested offset not available on the broker

### ISSUE THREAD

**Issue by Antiarchitect** [getsentry/sentry#42661]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.11.0

### Steps to Reproduce

Originally posted in sentry-kubernetes/charts: https://github.com/sentry-kubernetes/charts/issues/806

### Expected Result

post-process-forwarder-errors works normally

### Actual Result

```
08:02:55 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
08:02:59 [INFO] sentry.plugins.github: apps-not-configured
08:03:00 [INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume errors messages
08:03:00 [INFO] sentry.eventstream.kafka.postprocessworker: Starting post process forwarder with 5 threads
08:03:00 [INFO] batching-kafka-consumer: New partitions assigned: [TopicPartition{topic=events,partition=0,offset=-1001,error=None}]
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 373, in post_process_forwarder
    eventstream.run_post_process_forwarder(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 352, in run_post_process_forwarder
    self.run_consumer(
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 334, in run_consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/batching_kafka_consumer.py", line 327, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/batching_kafka_consumer.py", line 345, in _run_once
    raise Exception(msg.error())
Exception: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 0)"}
```

Resetting it manually (kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --group batching-kafka-consumer --topic events --reset-offsets --to-latest --execute) seems do the trick for a minute but after that it crashes again.

![image](https://user-images.githubusercontent.com/50209/209583696-fbb2f76e-1cf4-4507-a8b7-1d9b15ac9b77.png)

**Comment by Antiarchitect** [comment]
The only thing that helped (for now): I just deleted everything but the database and redeployed Sentry namespace again. It works about an hour from this moment. Will let you know if error will rise again.

**Comment by ethanhs** [comment]
Hi, sorry, we don't officially support deploying Sentry on Kubernetes. We have [some docs on troubleshooting](https://develop.sentry.dev/self-hosted/troubleshooting/#kafka) for the docker-compose deployment we do support, if that might help.
