### ISSUE TITLE
Error after update to 22.12.0 form 22.11.0

### ISSUE THREAD

**Issue by aamarques** [getsentry/sentry#42693]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.11.0

### Steps to Reproduce

Have a health setup running in 22.11.0 in docker machine (not in k8s).
```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED       STATUS                             PORTS                                   NAMES
c2c5df89e9d4   nginx:1.22.0-alpine                      "/docker-entrypoint.…"   5 weeks ago   Up 2 minutes                       0.0.0.0:9000->80/tcp, :::9000->80/tcp   sentry-self-hosted_nginx_1
e39f87f7deb3   getsentry/relay:22.11.0                  "/bin/bash /docker-e…"   5 weeks ago   Up 2 minutes                       3000/tcp                                sentry-self-hosted_relay_1
f16ba1f49a6f   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_post-process-forwarder-transactions_1
3de78a7cfe57   sentry-cleanup-self-hosted-local         "/entrypoint.sh '0 0…"   5 weeks ago   Up 2 minutes                       9000/tcp                                sentry-self-hosted_sentry-cleanup_1
175ba780d704   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 26 seconds                      9000/tcp                                sentry-self-hosted_subscription-consumer-events_1
38e53489c9be   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 26 seconds                      9000/tcp                                sentry-self-hosted_ingest-consumer_1
d04502dd903c   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 27 seconds (health: starting)   9000/tcp                                sentry-self-hosted_web_1
f8fd19544616   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_worker_1
a47dc19b00c5   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_subscription-consumer-transactions_1
f64bb991e17d   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_post-process-forwarder-errors_1
51ba56351e31   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   5 weeks ago   Up 25 seconds                      9000/tcp                                sentry-self-hosted_cron_1
8656fa1e0b10   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-outcomes-consumer_1
53a731fce74d   snuba-cleanup-self-hosted-local          "/entrypoint.sh '*/5…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-transactions-cleanup_1
881f571408fa   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-replacer_1
6fb5fc8e2047   snuba-cleanup-self-hosted-local          "/entrypoint.sh '*/5…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-cleanup_1
bb70c0301d0b   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-subscription-consumer-transactions_1
1a08d906cb8e   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-api_1
7a167c07c7f2   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-sessions-consumer_1
fa57aab1a0ed   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-subscription-consumer-events_1
2937f0030455   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-consumer_1
46ef3d4fe0e6   getsentry/snuba:22.11.0                  "./docker_entrypoint…"   5 weeks ago   Up 2 minutes                       1218/tcp                                sentry-self-hosted_snuba-transactions-consumer_1
bf527d53802b   clickhouse-self-hosted-local             "/entrypoint.sh"         5 weeks ago   Up 2 minutes (healthy)             8123/tcp, 9000/tcp, 9009/tcp            sentry-self-hosted_clickhouse_1
210f087d951e   symbolicator-cleanup-self-hosted-local   "/entrypoint.sh '55 …"   5 weeks ago   Up 2 minutes                       3021/tcp                                sentry-self-hosted_symbolicator-cleanup_1
6db23b9de471   maxmindinc/geoipupdate:v4.7.1            "/usr/bin/geoipupdat…"   5 weeks ago   Exited (1) 5 weeks ago                                                     sentry-self-hosted_geoipupdate_1
95f8bc5bf472   tianon/exim4                             "docker-entrypoint.s…"   5 weeks ago   Up 2 minutes                       25/tcp                                  sentry-self-hosted_smtp_1
64961ab4fd84   postgres:9.6                             "/opt/sentry/postgre…"   5 weeks ago   Up 2 minutes (healthy)             5432/tcp                                sentry-self-hosted_postgres_1
5df18467679d   memcached:1.6.9-alpine                   "docker-entrypoint.s…"   5 weeks ago   Up 2 minutes (healthy)             11211/tcp                               sentry-self-hosted_memcached_1
83519c093f3d   getsentry/symbolicator:0.5.1             "/bin/bash /docker-e…"   5 weeks ago   Up 2 minutes                       3021/tcp                                sentry-self-hosted_symbolicator_1
af4f4cf1b466   confluentinc/cp-kafka:5.5.0              "/etc/confluent/dock…"   5 weeks ago   Up 2 minutes (health: starting)    9092/tcp                                sentry-self-hosted_kafka_1
48c1821b1f49   confluentinc/cp-zookeeper:5.5.0          "/etc/confluent/dock…"   5 weeks ago   Up 2 minutes (healthy)             2181/tcp, 2888/tcp, 3888/tcp            sentry-self-hosted_zookeeper_1
d6b624554f9b   redis:6.2.4-alpine                       "docker-entrypoint.s…"   5 weeks ago   Up 2 minutes (healthy)             6379/tcp                                sentry-self-hosted_redis_1
```
run the update commands
```
git fetch
git checkout 22.12.0
export REPORT_SELF_HOSTED_ISSUES=0
SENTRY_IMAGE=getsentry/sentry:22.12.0 ./install.sh
docker-compose up -d
```

### Expected Result

A clean and health update to 22.12.0

### Actual Result

No errors were reported in the update process.
I tried to execute the troubleshooting commands but got `Error: Assignments can only be reset if the group 'snuba-consumers' is inactive, but the current state is Stable.`, So I started only `zookeeper` and `kafka`, run the commands in troubleshooting but the error still.

```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS                          PORTS                                   NAMES
d74959747729   nginx:1.22.0-alpine                      "/docker-entrypoint.…"   44 seconds ago   Up 43 seconds                   0.0.0.0:9000->80/tcp, :::9000->80/tcp   sentry-self-hosted_nginx_1
35ed76b152b1   getsentry/relay:22.12.0                  "/bin/bash /docker-e…"   45 seconds ago   Up 44 seconds                   3000/tcp                                sentry-self-hosted_relay_1
2c7e68f310ac   sentry-cleanup-self-hosted-local         "/entrypoint.sh '0 0…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_sentry-cleanup_1
b10151b70827   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_post-process-forwarder-transactions_1
d7fc1bc7b1bf   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_subscription-consumer-events_1
688ba244d7cd   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_worker_1
a40d57f0f853   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_ingest-consumer_1
93bc1fd97cf4   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes (healthy)          9000/tcp                                sentry-self-hosted_web_1
9473de391b02   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_cron_1
17d007a6b6d3   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_post-process-forwarder-errors_1
a939e27c1e80   sentry-self-hosted-local                 "/etc/sentry/entrypo…"   2 minutes ago    Up 2 minutes                    9000/tcp                                sentry-self-hosted_subscription-consumer-transactions_1
0301a5e30dc3   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Restarting (1) 10 seconds ago                                           sentry-self-hosted_snuba-consumer_1
9504b6fee05d   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-subscription-consumer-events_1
c0405d49f3fb   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Restarting (1) 1 second ago                                             sentry-self-hosted_snuba-outcomes-consumer_1
55468739a2da   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-subscription-consumer-transactions_1
10c519c12a64   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-api_1
72a013b1f688   snuba-cleanup-self-hosted-local          "/entrypoint.sh '*/5…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-cleanup_1
b11969c5a329   snuba-cleanup-self-hosted-local          "/entrypoint.sh '*/5…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-transactions-cleanup_1
87558fa2ba12   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-replacer_1
c253b4cccea7   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-sessions-consumer_1
963f8014e309   getsentry/snuba:22.12.0                  "./docker_entrypoint…"   2 minutes ago    Up 2 minutes                    1218/tcp                                sentry-self-hosted_snuba-transactions-consumer_1
ecd788831648   symbolicator-cleanup-self-hosted-local   "/entrypoint.sh '55 …"   3 minutes ago    Up 3 minutes                    3021/tcp                                sentry-self-hosted_symbolicator-cleanup_1
08a379354787   clickhouse-self-hosted-local             "/entrypoint.sh"         3 minutes ago    Up 3 minutes (healthy)          8123/tcp, 9000/tcp, 9009/tcp            sentry-self-hosted_clickhouse_1
dbbf51d51720   maxmindinc/geoipupdate:v4.7.1            "/usr/bin/geoipupdat…"   3 minutes ago    Exited (1) 3 minutes ago                                                sentry-self-hosted_geoipupdate_1
4b48708d7157   postgres:9.6                             "/opt/sentry/postgre…"   8 minutes ago    Up 3 minutes (healthy)          5432/tcp                                sentry-self-hosted_postgres_1
1251d6717d78   memcached:1.6.9-alpine                   "docker-entrypoint.s…"   8 minutes ago    Up 3 minutes (healthy)          11211/tcp                               sentry-self-hosted_memcached_1
4c57e9e1edd8   tianon/exim4                             "docker-entrypoint.s…"   8 minutes ago    Up 3 minutes                    25/tcp                                  sentry-self-hosted_smtp_1
391f88d2cbc8   getsentry/symbolicator:0.6.0             "/bin/bash /docker-e…"   8 minutes ago    Up 3 minutes                    3021/tcp                                sentry-self-hosted_symbolicator_1
dea9567c6331   confluentinc/cp-kafka:5.5.0              "/etc/confluent/dock…"   8 minutes ago    Up 2 minutes (healthy)          9092/tcp                                sentry-self-hosted_kafka_1
9bd0856ac9ff   confluentinc/cp-zookeeper:5.5.0          "/etc/confluent/dock…"   9 minutes ago    Up 3 minutes (healthy)          2181/tcp, 2888/tcp, 3888/tcp            sentry-self-hosted_zookeeper_1
1ea7b69e2a97   redis:6.2.4-alpine                       "docker-entrypoint.s…"   9 minutes ago    Up 3 minutes (healthy)          6379/tcp                                sentry-self-hosted_redis_1
```

ERRORS in `sentry-self-hosted_snuba-consumer_1`
```
2022-12-29 09:57:27,217 Initializing Snuba...
2022-12-29 09:57:29,202 Snuba initialization took 1.9857687090000127s
2022-12-29 09:57:29,805 Initializing Snuba...
2022-12-29 09:57:31,876 Snuba initialization took 2.072255584000004s
2022-12-29 09:57:31,885 Consumer Starting
2022-12-29 09:57:31,886 librdkafka log level: 6
2022-12-29 09:57:34,153 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 574624709}
2022-12-29 09:57:34,154 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 218, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/utils/streams/kafka_consumer_with_commit_log.py", line 33, in poll
    return super().poll(timeout)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
2022-12-29 09:57:34,156 Closing <snuba.utils.streams.kafka_consumer_with_commit_log.KafkaConsumerWithCommitLog object at 0x7efc7bd52730>...
2022-12-29 09:57:34,156 Partitions revoked: [Partition(topic=Topic(name='events'), index=0)]
2022-12-29 09:57:34,158 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 202, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 218, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/utils/streams/kafka_consumer_with_commit_log.py", line 33, in poll
    return super().poll(timeout)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
```

ERRORS in `sentry-self-hosted_snuba-outcomes-consumer_1`

```
2022-12-29 10:00:18,064 Initializing Snuba...
2022-12-29 10:00:20,348 Snuba initialization took 2.284905971999933s
2022-12-29 10:00:20,978 Initializing Snuba...
2022-12-29 10:00:23,262 Snuba initialization took 2.2859040410000944s
2022-12-29 10:00:23,278 Consumer Starting
2022-12-29 10:00:23,278 librdkafka log level: 6
2022-12-29 10:00:25,311 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 694350923}
2022-12-29 10:00:25,312 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 218, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
2022-12-29 10:00:25,314 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f63b36544c0>...
2022-12-29 10:00:25,314 Partitions revoked: [Partition(topic=Topic(name='outcomes'), index=0)]
2022-12-29 10:00:25,316 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 202, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 218, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}

```

**Comment by ethanhs** [comment]
Hi! Have you tried the [suggestions in the troubleshooting section of the docs](https://develop.sentry.dev/self-hosted/troubleshooting/#kafka)?

**Comment by aamarques** [comment]
> Hi! Have you tried the [suggestions in the troubleshooting section of the docs](https://develop.sentry.dev/self-hosted/troubleshooting/#kafka)?

Hi, @ethanhs. 
Yes, I tried (not the nuclear option - It's not an option for me)  but it didn't work as I wrote it in the `Actual Result` session above.

This seems to be related to `AUTO_OFFSET_RESET` and not to `OFFSET OUT OF RANGE` in Kafka but I have no expertise.

Thanks and happy new year,

**Comment by aamarques** [comment]
Closing this and opening in the right place.
https://github.com/getsentry/self-hosted/issues/1894
