### ISSUE TITLE
Sentry 8.9.0 not installable via buildout any longer

### ISSUE THREAD

**Issue by do3cc** [getsentry/sentry#4271]
Hi,

this is the error from buildout:
<details>
  <summary>Stack trace</summary>
```
Getting distribution for 'sentry==8.9.0'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2294, in main
    **kw
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/home/sentry/sentry/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-uPNkZc/sentry-8.9.0/setup.py", line 41, in <module>
AttributeError: 'module' object has no attribute '__file__'
An error occurred when trying to install sentry 8.9.0. Look above this message for any errors that were output by easy_install.
While:
  Updating sentry.
  Getting distribution for 'sentry==8.9.0'.
Error: Couldn't install: sentry 8.9.0
```

</details>

The problem appeared with this commit https://github.com/getsentry/sentry/commit/1451a2d0636e9471f6dfdab55f58107dd9eea001#diff-2eeaed663bd0d25b7e608891384b7298L48
It could be that this only works with pip.

@dcramer mentioned in an earlier ticket, https://github.com/getsentry/sentry/issues/2662#issuecomment-183460342, that this (buildout) is not something you actively support and that PRs are welcome.
Personally I'll use this as an excuse to push for using your docker deployment instead of changing the code. I only add this as pointer for other people trying to install sentry via buildout.

Feel free to close this issue.

**Comment by mattrobenolt** [comment]
Do you have any idea what the issue is? I've never used buildout before. I can't say we actively go out of our way to break buildout, so if it's something trivial, we wouldn't mind a patch. With that said, we're not restricted it _only_ working with pip, things should work just fine doing `python setup.py install`, etc. Though pip is the only thing we realistically ever use.

But as you said, I'm going to close since this isn't something we're going to actively fix, but I'm open to suggestions here, mostly as a learning experience for me since I know nothing about buildout. :)

Thanks for bringing this to our attention! :pizza:

**Comment by do3cc** [comment]
@mattrobenolt Did you see the traceback in my issue report?
I don't like how long tracebacks break the flow of writing so I googled and found out I can compress it by wrapping it with a `<details>` tag. You need to click on "Stack Trace" to expand it.
 
My commit link already points to the line of code in setup.py where the exception happens.
I don't know who is doing tricks here so that it works in pip, I know that python setup.py develop does not show the error but that running the line of code in an interactive interpreter shows a similar error, both for python2 and 3. Here my analysis stopped and I wrote the bug report.

**Comment by do3cc** [comment]
Seems the details tag hurt readability in the end ;-)
