### ISSUE TITLE
celery throw NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/sentry#42758]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.10.0

### Steps to Reproduce

i have tried to update sentry from 20.9.0 to 22.10.0,(20.9.0->21.5.0->21.6.3->22.10.0).
when i do sentry run worker i get this log, is there any way to handle this?or what affect it has in normal service?
`11:54:56 [ERROR] kombu.pidbox: pidbox command error: AttributeError("'NoneType' object has no attribute 'groups'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 104, in dispatch
    reply = handle(method, arguments)
  File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 126, in handle_cast
    return self.handle(method, arguments)
  File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 120, in handle
    return self.handlers[method](self.state, **arguments)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/control.py", line 279, in enable_events
    if dispatcher.groups and 'task' not in dispatcher.groups:
AttributeError: 'NoneType' object has no attribute 'groups'`

### Expected Result

i don`t get this error in 20.9.0

### Actual Result

![image](https://user-images.githubusercontent.com/31720199/210550745-57ed320b-00e4-4812-a70d-36c8c8283a0f.png)

**Comment by ethanhs** [comment]
Kombu is used for celery/task queues AIUI, so its pretty important. Do you have any customizations to your Sentry config?

**Comment by Chengshihao1018** [comment]
> Kombu is used for celery/task queues AIUI, so its pretty important. Do you have any customizations to your Sentry config?

i think this maybe some unuseful data in redis cause this.the previous version is 20.9.0.i have change to a new redis,the error never occur again

**Comment by ethanhs** [comment]
Ah ok. Do you think this issue is resolved then? I don't think I've seen anything like this happening before, so perhaps your redis state got corrupted somehow.
