### ISSUE TITLE
Excessive Errors from `sentry.lang.javascript.processor: SoftTimeLimitExceeded()`

### ISSUE THREAD

**Issue by aryeh-looker** [getsentry/sentry#4386]
I'm getting a lot of unhandled exceptions when attempting to fetch JavaScript source code. I believe this is being triggered by the fact that Sentry is attempting to fetch JS sources from locations that are not available (e.g. we have some servers that serve assets on LANs that are not generally accessible). 

I am concerned that these failures are taking up a tremendous amount of workers' time, making Sentry significantly inefficient at processing all errors (not just JS-related ones).

Any suggestions?

Example traces:

```
Oct 18 18:17:41 errorssentry supervisord: sentry-worker 18:17:41 [WARNING] sentry.lang.javascript.processor: Disabling sources to REDACTED.REDACTED.com for 300s
Oct 18 18:17:42 errorssentry supervisord: sentry-web 127.0.0.1 - - [18/Oct/2016:18:17:42 +0000] "POST /api/2/store/ HTTP/1.0" 200 366 "-" "Faraday v0.9.0"
Oct 18 18:17:42 errorssentry supervisord: sentry-worker Traceback (most recent call last):
Oct 18 18:17:42 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/lang/javascript/processor.py", line 345, in fetch_file
Oct 18 18:17:42 errorssentry supervisord: sentry-worker     timeout=settings.SENTRY_SOURCE_FETCH_TIMEOUT,
Oct 18 18:17:42 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
Oct 18 18:17:42 errorssentry supervisord: sentry-worker     return self.request('GET', url, **kwargs)
Oct 18 18:17:42 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
Oct 18 18:17:42 errorssentry supervisord: sentry-worker     resp = self.send(prep, **send_kwargs)
Oct 18 18:17:42 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 279, in send
Oct 18 18:17:42 errorssentry supervisord: sentry-worker     resp = real_send(self, request, *args, **kwargs)
Oct 18 18:17:42 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
Oct 18 18:17:42 errorssentry supervisord: sentry-worker     r = adapter.send(request, **kwargs)
Oct 18 18:17:42 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/http.py", line 108, in send
Oct 18 18:17:42 errorssentry supervisord: sentry-worker     return super(BlacklistAdapter, self).send(request, *args, **kwargs)
Oct 18 18:17:42 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
Oct 18 18:17:42 errorssentry supervisord: sentry-worker     raise ConnectionError(e, request=request)
Oct 18 18:17:42 errorssentry supervisord: sentry-worker ConnectionError: HTTPSConnectionPool(host='REDACTED.REDACTED.com', port=443): Max retries exceeded with url: /webpack/vendor.webpack-909d5ff2.js (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7f85509c50>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

```
Oct 18 18:17:41 errorssentry supervisord: sentry-worker Traceback (most recent call last):
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/lang/javascript/processor.py", line 345, in fetch_file
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     timeout=settings.SENTRY_SOURCE_FETCH_TIMEOUT,
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     return self.request('GET', url, **kwargs)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     resp = self.send(prep, **send_kwargs)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 279, in send
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     resp = real_send(self, request, *args, **kwargs)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     r = adapter.send(request, **kwargs)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/http.py", line 108, in send
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     return super(BlacklistAdapter, self).send(request, *args, **kwargs)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     timeout=timeout
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     chunked=chunked)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     self._validate_conn(conn)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     conn.connect()
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     conn = self._new_conn()
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     (self.host, self.port), self.timeout, **extra_kw)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     sock.connect(sa)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/usr/lib/python2.7/socket.py", line 224, in meth
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     return getattr(self._sock,name)(*args)
Oct 18 18:17:41 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
Oct 18 18:17:41 errorssentry supervisord: sentry-worker     raise SoftTimeLimitExceeded()
Oct 18 18:17:41 errorssentry supervisord: sentry-worker SoftTimeLimitExceeded: SoftTimeLimitExceeded()
```

**Comment by aryeh-looker** [comment]
For now disabling JS source fetching as a workaround.

**Comment by mattrobenolt** [comment]
> For now disabling JS source fetching as a potential workaround.

Was just going to propose this. :) Unfortunately, this is just how this feature works. If it's not useful and is just wasting resources, it's easy to disable globally by setting `SENTRY_SCRAPE_JAVASCRIPT_CONTEXT = False` in your `sentry.conf.py` or per project in the UI.

Other than that, there's not much else we can do here since the feature is effectively working as intended.

**Comment by artemkaint** [comment]
I suppose we have to  be able break source fetching after several attempts.

I found domain limit on 300 sec. But i saw cases when worker tries to fetch source every 5 sec. 
So in case of "300 sec pause" we don't handle event properly and return to it in 300 sec.

**Comment by dcramer** [comment]
Sentry will continue to move away from automated source scraping and thus we're unlikely to build any more significant changes to it. You should use artifact uploads and disable scraping, as it has many other benefits.

**Comment by artemkaint** [comment]
In  addition.  I don't tell about self hosted is. 

I met case when browser generate exception by injection js code by antivirus (Kaspersky). It generates strange exception 
http://c2n.me/3GgyISi where sentry tries infinitely to connect to nonexistent URL (host)
Of course it's a special case. But it break all worker's processing
