### ISSUE TITLE
Click to copy does not work if sentry is hosted "insecurely" (http, not https)

### ISSUE THREAD

**Issue by DAcodedBEAT** [getsentry/sentry#44025]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.1.1

### Steps to Reproduce

1. deploy sentry self-hosted as described by the documentation (would result in sentry running as http on port 9000)
2. fire off a test sentry event
3. attempt to share the event, and click the copy button

### Expected Result

Either:

* the user is not allowed to use click to copy when running sentry insecurely (button is disabled)

or

* the error is expressed on the front end, explaining how click to copy is unsupported when running sentry insecurely

### Actual Result

The user will not any indication of failure from the UI but an error raised in the console.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at onClick (shareModal.tsx:133:39)
    at button.tsx:177:7
    at Object.Ue (react-dom.profiling.min.js:52:317)
    at Qe (react-dom.profiling.min.js:52:471)
    at react-dom.profiling.min.js:53:35
    at Rr (react-dom.profiling.min.js:100:68)
    at Ar (react-dom.profiling.min.js:101:380)
    at react-dom.profiling.min.js:113:65
    at De (react-dom.profiling.min.js:305:189)
    at react-dom.profiling.min.js:50:57
    at Dr (react-dom.profiling.min.js:105:469)
    at en (react-dom.profiling.min.js:75:265)
    at Jt (react-dom.profiling.min.js:74:124)
    at M.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Qo (react-dom.profiling.min.js:124:33)
    at Le (react-dom.profiling.min.js:305:48)
    at Xt (react-dom.profiling.min.js:73:352)
    at HTMLDivElement.n (helpers.js:90:17)
```

_note_: this doesn't work when sentry is running on HTTP is because the ClipboardAPI is only available to [Secure Contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), as per https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#using_the_clipboard_api

**Comment by hubertdeng123** [comment]
This seems like it might be a Core UI issue actually with the `shareModal`, rerouting there

**Comment by evanpurkhiser** [comment]
Sounds like best we can do is show an error here.
