### ISSUE TITLE
Update from 8.8.0 to 8.9.0 is failed

### ISSUE THREAD

**Issue by le0pard** [getsentry/sentry#4406]
Hello. I have little problem to update from 8.8.0 to 8.9.0.

```
/opt/sentry/bin/pip install sentry==8.9.0
Collecting sentry==8.9.0
  Downloading sentry-8.9.0-py27-none-any.whl (11.9MB)
    100% |████████████████████████████████| 11.9MB 34kB/s
Requirement already satisfied (use --upgrade to upgrade): simplejson<3.9.0,>=3.2.0 in /opt/sentry/lib/python2.7/site-packages (from sentry==8.9.0)
Requirement already satisfied (use --upgrade to upgrade): pytest-django<2.10.0,>=2.9.1 in /opt/sentry/lib/python2.7/site-packages (from sentry==8.9.0)
Requirement already satisfied (use --upgrade to upgrade): requests[security]<2.12.0,>=2.9.1 in /opt/sentry/lib/python2.7/site-packages (from sentry==8.9.0)
Requirement already satisfied (use --upgrade to upgrade): django-picklefield<0.4.0,>=0.3.0 in /opt/sentry/lib/python2.7/site-packages (from sentry==8.9.0)
Requirement already satisfied (use --upgrade to upgrade): django-sudo<3.0.0,>=2.1.0 in /opt/sentry/lib/python2.7/site-packages (from sentry==8.9.0)
Requirement already satisfied (use --upgrade to upgrade): toronado<0.1.0,>=0.0.10 in /opt/sentry/lib/python2.7/site-packages (from sentry==8.9.0)
Requirement already satisfied (use --upgrade to upgrade): selenium<2.60,>=2.53 in /opt/sentry/lib/python2.7/site-packages (from sentry==8.9.0)
Requirement already satisfied (use --upgrade to upgrade): click<7.0,>=5.0 in /opt/sentry/lib/python2.7/site-packages (from sentry==8.9.0)
Requirement already satisfied (use --upgrade to upgrade): pytest-html<1.10.0,>=1.9.0 in /opt/sentry/lib/python2.7/site-packages (from sentry==8.9.0)
Collecting symsynd<2.0.0,>=1.1.0 (from sentry==8.9.0)
  Downloading symsynd-1.2.0.zip (40.2MB)
    99% |████████████████████████████████| 40.2MB 10.0MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/commands/install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/utils/ui.py", line 133, in iter
    for x in it:
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/download.py", line 586, in resp_read
    decode_content=False):
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 224, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/opt/sentry/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 81, in dumps
    ).encode("utf8"),
MemoryError
```

Maybe I miss some dependency or package for new release (do not found anything in CHANGES)?

**Comment by le0pard** [comment]
Just need to update `pip` from 7.x to 8.x.
