### ISSUE TITLE
Installed sentry onpremises but accessing url throws internal error

### ISSUE THREAD

**Issue by Thamaraiselvam** [getsentry/sentry#4489]
http://ip:9000/auth/login/
```
 Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!
If you're daring, you may want to try the following:
Give it a few seconds and reload the page.
If all else fails, create an issue with more details.
```

```
compiled with version: 4.9.2 on 02 November 2016 20:05:03
os: Linux-3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016
nodename: cfc930779cc8
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /usr/src/sentry
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 524288
your memory page size is 4096 bytes
detected max file descriptor number: 524288
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:9000 fd 3
Python version: 2.7.12 (default, Oct 31 2016, 23:50:21)  [GCC 4.9.2]
Set PythonHome to /usr/local
Python main interpreter initialized at 0xa296b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 1922048 bytes (1877 KB) for 12 cores
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 12)
spawned uWSGI worker 1 (pid: 17, cores: 4)
spawned uWSGI worker 2 (pid: 18, cores: 4)
spawned uWSGI worker 3 (pid: 19, cores: 4)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0xa296b0 pid: 17 (default app)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0xa296b0 pid: 18 (default app)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0xa296b0 pid: 19 (default app)
09:46:08 [ERROR] sentry.errors: Internal project (id=1) does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 186, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 140, in handle
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 117, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
09:46:08 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest
path:/auth/login/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'sentrysid': 'gAJ9cQFVBV9uZXh0WAEAAAAvcy4:1c3gQ9:vsel1uyK2FtH8CZ3hKqAJJgP848'},
META:{u'CSRF_COOKIE': u'fXBlb5AbYEFLyanmVLbNopYUR4SlFwRq',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'sentrysid="gAJ9cQFVBV9uZXh0WAEAAAAvcy4:1c3gQ9:vsel1uyK2FtH8CZ3hKqAJJgP848"',
 'HTTP_HOST': '52.26.62.201:9000',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_REFERER': 'http://52.26.62.201:9000/auth/login/',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36',
 'PATH_INFO': u'/auth/login/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '123.201.137.254',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/auth/login/',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'cfc930779cc8',
 'SERVER_PORT': '9000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.core': 0,
 'uwsgi.node': 'cfc930779cc8',
 'uwsgi.version': '2.0.14',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f47b35b8780>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7f47b39b6f18>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/error_500.py", line 22, in get_embed_config
    )[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
09:46:08 [ERROR] root: Unable to fetch ProjectKey for internal project
09:46:08 [ERROR] sentry.errors: Internal project (id=1) does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/templatetags/sentry_react.py", line 66, in _get_public_dsn
    )[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
09:46:08 [ERROR] root: Unable to fetch ProjectKey for internal project
09:46:08 [ERROR] sentry.errors: Internal project (id=1) does not exist
123.201.137.254 - - [07/Nov/2016:09:46:08 +0000] "GET /auth/login/ HTTP/1.1" 500 8637 "http://52.26.62.201:9000/auth/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
123.201.137.254 - - [07/Nov/2016:09:46:09 +0000] "GET /_static/1478511968/sentry/dist/sentry.css HTTP/1.1" 200 52259 "http://52.26.62.201:9000/auth/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
123.201.137.254 - - [07/Nov/2016:09:46:09 +0000] "GET /_static/1478511968/sentry/dist/vendor.js HTTP/1.1" 200 223893 "http://52.26.62.201:9000/auth/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
123.201.137.254 - - [07/Nov/2016:09:46:09 +0000] "GET /_static/1478511968/sentry/dist/app.js HTTP/1.1" 200 137474 "http://52.26.62.201:9000/auth/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
123.201.137.254 - - [07/Nov/2016:09:46:10 +0000] "GET /_static/1478511968/sentry/dist/sentry.js.map HTTP/1.1" 200 350 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"

```

**Comment by Thamaraiselvam** [comment]
```
root@ip:/home/ubuntu/onpremise# docker run --rm -it sentry-onpremise upgrade
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 158, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 121, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 159, in configure
    }, skip_backend_validation=skip_backend_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 204, in initialize_app
    bootstrap_options(settings, config['options'])
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 79, in bootstrap_options
    from sentry.options import load_defaults
  File "/usr/local/lib/python2.7/site-packages/sentry/options/__init__.py", line 10, in <module>
    from .store import OptionsStore
  File "/usr/local/lib/python2.7/site-packages/sentry/options/store.py", line 19, in <module>
    from sentry.db.models.query import create_or_update
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/__init__.py", line 11, in <module>
    from .base import *  # NOQA
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 14, in <module>
    from django.db import models
  File "/usr/local/lib/python2.7/site-packages/django/db/models/__init__.py", line 5, in <module>
    from django.db.models.query import Q
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 17, in <module>
    from django.db.models.deletion import Collector
  File "/usr/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 4, in <module>
    from django.db.models import signals, sql
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/__init__.py", line 4, in <module>
    from django.db.models.sql.subqueries import *
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 12, in <module>
    from django.db.models.sql.query import Query
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 22, in <module>
    from django.db.models.sql import aggregates as base_aggregates_module
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/aggregates.py", line 9, in <module>
    ordinal_aggregate_field = IntegerField()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 116, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 52, in load_module
    reraise_as(ConfigurationError(msg))
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/settings.py", line 48, in reraise_as
    six.reraise(new_type, new_exception, e_traceback)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 44, in load_module
    mod = self._load_module(fullname)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 76, in _load_module
    load_settings(self.config_path, settings=settings_mod, silent=True)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 90, in load_settings
    six.exec_(source_file.read(), conf.__dict__)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 95, in <module>
sentry.runner.importer.ConfigurationError: Exception: Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, did you forget to `--link` a redis container?

```

**Comment by dcramer** [comment]
Our issue tracker isn't used for support. Hosting sentry yourself means you have the pleasure of debugging errors. If the debug information is incorrect please open a new issue accordingly.

**Comment by Thamaraiselvam** [comment]
the problem was RAM , upgraded server then it issue solved

**Comment by farhansalam** [comment]
@Thamaraiselvam Thanks man! it helped me.
I was trying to run the server on `t2.micro` which was causing this error and now it works fine on `t2.small`

**Comment by smalltwo** [comment]
i got same issue

bug my console is 
08:13:34 [ERROR] sentry.errors: Internal project (id=1) does not exist
Traceback (most recent call last):
  File "/www/sentry/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 212, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 151, in handle
    return super(AuthLoginView, self).handle(request, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in handle
    return super(BaseView, self).dispatch(request, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 166, in get
    org = Organization.get_default()
  File "/www/sentry/lib/python2.7/site-packages/sentry/models/organization.py", line 128, in get_default
    )[0]
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
08:13:34 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
Traceback (most recent call last):
  File "/www/sentry/lib/python2.7/site-packages/sentry/web/frontend/error_500.py", line 22, in get_embed_config
    )[0]
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
08:13:34 [ERROR] root: Unable to fetch ProjectKey for internal project
08:13:34 [ERROR] sentry.errors: Internal project (id=1) does not exist
Traceback (most recent call last):
  File "/www/sentry/lib/python2.7/site-packages/sentry/templatetags/sentry_react.py", line 67, in _get_public_dsn
    )[0]
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
08:13:34 [ERROR] root: Unable to fetch ProjectKey for internal project
08:13:34 [ERROR] sentry.errors: Internal project (id=1) does not exist
10.8.0.67 - - [11/Feb/2018:08:13:34 +0000] "GET /auth/login/ HTTP/1.1" 500 8714 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36"
