### ISSUE TITLE
Need to 'sentry init' does not allow for automation

### ISSUE THREAD

**Issue by ldelossa** [getsentry/sentry#4541]
Hey there,

I'm using terraform and variable interpolation in order to setup Sentry. Because of the need for Sentry to run the 'init' command to do migrations, I need to use manual intervention to fill out the configuration files 'init' makes.

Is it possible to make 'init' take arguments to setup the config files ?

**Comment by mattrobenolt** [comment]
`init` isn't _required_. You can just stamp out your own however you want. The defaults used for `init` come from: https://github.com/getsentry/sentry/tree/master/src/sentry/data/config
 
So I'd just say not to run `init` with automation stuff since there's no way to populate values.

**Comment by ldelossa** [comment]
What about the generate of the key? My install falls unless I manually run init.

**Comment by mattrobenolt** [comment]
You can obviously generate that yourself however you wish and put it in the config file. :) Just something like a uuid would be sufficient.

**Comment by ldelossa** [comment]
Ahh, see I tried to create my own, place them into /etc/sentry and then point all commands with the adhoc SENTRY_CONF=/etc/sentry variable, but no good.

**Comment by ldelossa** [comment]
```
louis@sentry-postgresql-01:~$ sudo su -s /bin/bash -c 'source /home/sentry/www/sentry/bin/activate; SENTRY_CONF=/etc/sentry sentry upgrade --noinput' sentry

Traceback (most recent call last):
  File "/home/sentry/www/sentry/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 158, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 121, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 159, in configure
    }, skip_backend_validation=skip_backend_validation)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 210, in initialize_app
    apply_legacy_settings(settings)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 373, in apply_legacy_settings
    url_prefix = options.get('system.url-prefix', silent=True)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/options/manager.py", line 151, in get
    result = self.store.get(opt, silent=silent)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/options/store.py", line 77, in get
    result = self.get_store(key, silent=silent)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/options/store.py", line 168, in get_store
    except self.model.DoesNotExist:
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.func.__name__] = self.func(instance)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/options/store.py", line 63, in model
    from sentry.models.option import Option
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/models/__init__.py", line 13, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/utils/imports.py", line 51, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/models/dsymfile.py", line 24, in <module>
    from sentry.models.file import File
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/models/file.py", line 24, in <module>
    from sentry.app import locks
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/app.py", line 46, in <module>
    buffer = get_instance('SENTRY_BUFFER', settings.SENTRY_BUFFER_OPTIONS)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/app.py", line 41, in get_instance
    return cls(**options)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/buffer/redis.py", line 32, in __init__
    self.cluster, options = get_cluster_from_options('SENTRY_BUFFER_OPTIONS', options)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/utils/redis.py", line 118, in get_cluster_from_options
    cluster = cluster_manager.get(options.pop(cluster_option_name, default_cluster_name))
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/utils/redis.py", line 78, in get
    cluster = self.__clusters[key] = _make_rb_cluster(**configuration)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/rb/cluster.py", line 105, in __init__
    for host_config in _iter_hosts(hosts):
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/rb/cluster.py", line 56, in _iter_hosts
    cfg = dict(cfg)
TypeError: 'NoneType' object is not iterable
```

This is what I get if I do not run 'init' first.

**Comment by ldelossa** [comment]
Here are my config files:

```
# While a lot of configuration in Sentry can be changed via the UI, for all
# new-style config (as of 8.0) you can also declare values here in this file
# to enforce defaults or to ensure they cannot be changed via the UI. For more
# information see the Sentry documentation.

###############
# Mail Server #
###############

mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
# mail.host: 'localhost'
# mail.port: 25
# mail.username: ''
# mail.password: ''
# mail.use-tls: false
# The email address to send on behalf of
# mail.from: 'root@localhost'

# If you'd like to configure email replies, enable this.
# mail.enable-replies: false

# When email-replies are enabled, this value is used in the Reply-To header
# mail.reply-hostname: ''

# If you're using mailgun for inbound mail, set your API key and configure a
# route to forward to /api/hooks/mailgun/inbound/
# mail.mailgun-api-key: ''

###################
# System Settings #
###################

# If this file ever becomes compromised, it's important to regenerate your a new key
# Changing this value will result in all current sessions being invalidated.
# A new key can be generated with `$ sentry config generate-secret-key`
system.secret-key: 'h5xz-tic94vsnux(aign6o63a@#e=3f@*)h!pl!xhp+5*_zl*&'

# The ``redis.clusters`` setting is used, unsurprisingly, to configure Redis
# clusters. These clusters can be then referred to by name when configuring
# backends such as the cache, digests, or TSDB backend.
redis.clusters:
  default:
    hosts:
      0:
      host: 10.241.1.2
      port: 6379

################
# File storage #
################

# Uploaded media uses these `filestore` settings. The available
# backends are either `filesystem` or `s3`.

filestore.backend: 'filesystem'
filestore.options:
  location: '/tmp/sentry-files'

# filestore.backend: 's3'
# filestore.options:
#   access_key: 'AKIXXXXXX'
#   secret_key: 'XXXXXXX'
#   bucket_name: 's3-bucket-name'
```

```
# This file is just Python, with a touch of Django which means
# you can inherit and tweak settings to your hearts content.
from sentry.conf.server import *

import os.path

CONF_ROOT = os.path.dirname(__file__)

DATABASES = {
    'default': {
        'ENGINE': 'sentry.db.postgres',
        'NAME': 'sentry',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '5432',
        'AUTOCOMMIT': True,
        'ATOMIC_REQUESTS': False,
    }
}

# You should not change this setting after your database has been created
# unless you have altered all schemas first
SENTRY_USE_BIG_INTS = True

# If you're expecting any kind of real traffic on Sentry, we highly recommend
# configuring the CACHES and Redis settings

###########
# General #
###########

# Instruct Sentry that this install intends to be run by a single organization
# and thus various UI optimizations should be enabled.
SENTRY_SINGLE_ORGANIZATION = True
DEBUG = False

#########
# Cache #
#########

# Sentry currently utilizes two separate mechanisms. While CACHES is not a
# requirement, it will optimize several high throughput patterns.

# If you wish to use memcached, install the dependencies and adjust the config
# as shown:
#
#   pip install python-memcached
#
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': ['127.0.0.1:11211'],
#     }
# }

# A primary cache is required for things such as processing events
SENTRY_CACHE = 'sentry.cache.redis.RedisCache'

#########
# Queue #
#########

# See https://docs.sentry.io/on-premise/server/queue/ for more
# information on configuring your queue broker and workers. Sentry relies
# on a Python framework called Celery to manage queues.

BROKER_URL = 'redis://localhost:6379'

###############
# Rate Limits #
###############

# Rate limits apply to notification handlers and are enforced per-project
# automatically.

SENTRY_RATELIMITER = 'sentry.ratelimits.redis.RedisRateLimiter'

##################
# Update Buffers #
##################

# Buffers (combined with queueing) act as an intermediate layer between the
# database and the storage API. They will greatly improve efficiency on large
# numbers of the same events being sent to the API in a short amount of time.
# (read: if you send any kind of real data to Sentry, you should enable buffers)

SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'

##########
# Quotas #
##########

# Quotas allow you to rate limit individual projects or the Sentry install as
# a whole.

SENTRY_QUOTAS = 'sentry.quotas.redis.RedisQuota'

########
# TSDB #
########

# The TSDB is used for building charts as well as making things like per-rate
# alerts possible.

SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'

###########
# Digests #
###########

# The digest backend powers notification summaries.

SENTRY_DIGESTS = 'sentry.digests.backends.redis.RedisBackend'

##############
# Web Server #
##############

# If you're using a reverse SSL proxy, you should enable the X-Forwarded-Proto
# header and uncomment the following settings
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# If you're not hosting at the root of your web server,
# you need to uncomment and set it to the path where Sentry is hosted.
# FORCE_SCRIPT_NAME = '/sentry'

SENTRY_WEB_HOST = '0.0.0.0'
SENTRY_WEB_PORT = 9000
SENTRY_WEB_OPTIONS = {
    # 'workers': 3,  # the number of web workers
    # 'protocol': 'uwsgi',  # Enable uwsgi protocol instead of http
}
```

If I run init first, no issues anymore.

**Comment by mattrobenolt** [comment]
This has nothing to do with running `init`. It has everything to do with your config being wrong. Your config file is either missing something or is malformed. If you start with the files I linked, it should be fine.

**Comment by mattrobenolt** [comment]
To be clear, `init` doesn't really do much other than copy files. This is all it does: https://github.com/getsentry/sentry/blob/master/src/sentry/runner/settings.py#L30-L44

**Comment by ldelossa** [comment]
The configs are simply replacing the ip address of redis, and I did directly pull your files as samples.

**Comment by dcramer** [comment]
Sentrys issue tracker isn't a support forum. Please take general questions to a more appropriate venue (such as our forums), or contact us if you are interested in paid support.

**Comment by ldelossa** [comment]
Fair enough, I'll close out and go to forums.

**Comment by ayyazdaniaryan** [comment]
@ldelossa Perhaps a link to the forum post? I'm automating the sentry installation like yourself. Thanks!
