### ISSUE TITLE
install sentry using python failed when creating user

### ISSUE THREAD

**Issue by weishen** [getsentry/sentry#4592]
Sentry version is  8.10.0. 
[root@cent sentry2]# SENTRY_CONF=/etc/sentry bin/sentry createuser
Email: test2@example.com
Password:
Repeat for confirmation:
Should this user be a superuser? [y/N]: y
User created: test2@example.com
Traceback (most recent call last):
  File "bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/opt/sentry2/lib/python2.7/site-packages/sentry/runner/__init__.py", line 158, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/opt/sentry2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/sentry2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/sentry2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/sentry2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/sentry2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/sentry2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/sentry2/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/opt/sentry2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/sentry2/lib/python2.7/site-packages/sentry/runner/commands/createuser.py", line 97, in createuser
    org = Organization.get_default()
  File "/opt/sentry2/lib/python2.7/site-packages/sentry/models/organization.py", line 117, in get_default
    )[0]
  File "/opt/sentry2/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range

**Comment by mattrobenolt** [comment]
Sounds like something messed up doing the initial `upgrade` run. You should drop the database and try again. My assumption is the process crashed and things are left in a partial state. And my assumption is the process crashed because it ran out of memory because this scenario is reported semi frequently. :)

**Comment by weishen** [comment]
Yup, the database initialization was interrupted by a programming error " no language  plpgsql", it was not mentioned in the installation guide. Then I created it with "createlang -d sentry plpgsql" and run sentry upgrade again,  there was no issues until sentry createuser.  Rebuilding the database solved this issue. Thanks.
