### ISSUE TITLE
GitLab integration option `verify_ssl` does not apply to token refresh flow

### ISSUE THREAD

**Issue by spawnia** [getsentry/sentry#46491]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.3.1

### Steps to Reproduce

We set up the GitLab integration in our self-hosted Sentry instance, following [these docs](https://docs.sentry.io/product/integrations/source-code-mgmt/gitlab/#install).
Because our GitLab instance is self-hosted too and uses a self-signed certificate, I unchecked the option `Verify SSL` in the UI.

The integration works at first, but stops working after a couple of hours (probably exactly 2, which is the token expiry time in GitLab 15). Sentry can no longer link issues to GitLab issues or fetch commit data from GitLab. These problems have also been described in https://github.com/getsentry/sentry/issues/34903.

### Expected Result

https://github.com/getsentry/sentry/pull/29747 adds the refresh token flow to the GitLab integration. I would expect Sentry to be able to refresh the OAuth Token after its expiry.

### Actual Result

Sentry fails to refresh the authentication token, see the following log entry I retrieved through `docker-compose logs worker`:

```
worker_1  | 19:24:14 [INFO] sentry.tasks.commits: fetch_commits.error (organization_id=1 user_id=14 repository='limes / limes-api' provider='integrations:gitlab' error='An internal error occurred with the integration and the Sentry team has been notified' end_sha='aacb927e54536ea35f2f4326b337c9ac2f73d750')
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/shared_integrations/client/base.py", line 138, in _request
worker_1  |     resp.raise_for_status()
worker_1  |   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
worker_1  |     raise HTTPError(http_error_msg, response=self)
worker_1  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://gitlab.mll/api/v4/projects/14/repository/commits/aacb927e54536ea35f2f4326b337c9ac2f73d750
worker_1  |
worker_1  | The above exception was the direct cause of the following exception:
worker_1  |
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/client.py", line 103, in request
worker_1  |     return self._request(method, url, headers=headers, data=data, params=params)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/shared_integrations/client/base.py", line 158, in _request
worker_1  |     raise ApiError.from_response(resp, url=full_url) from e
worker_1  | sentry.shared_integrations.exceptions.ApiUnauthorized: {"error":"invalid_token","error_description":"Token is expired. You can either do re-authorization or token refresh."}
worker_1  |
worker_1  | During handling of the above exception, another exception occurred:
worker_1  |
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
worker_1  |     httplib_response = self._make_request(
worker_1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
worker_1  |     self._validate_conn(conn)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
worker_1  |     conn.connect()
worker_1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
worker_1  |     self.sock = ssl_wrap_socket(
worker_1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
worker_1  |     ssl_sock = _ssl_wrap_socket_impl(
worker_1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
worker_1  |     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
worker_1  |   File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
worker_1  |     return self.sslsocket_class._create(
worker_1  |   File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
worker_1  |     self.do_handshake()
worker_1  |   File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
worker_1  |     self._sslobj.do_handshake()
worker_1  | ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)
worker_1  |
worker_1  | During handling of the above exception, another exception occurred:
worker_1  |
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
worker_1  |     resp = conn.urlopen(
worker_1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
worker_1  |     retries = retries.increment(
worker_1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
worker_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
worker_1  | urllib3.exceptions.MaxRetryError: SafeHTTPSConnectionPool(host='gitlab.mll', port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
worker_1  |
worker_1  | During handling of the above exception, another exception occurred:
worker_1  |
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/repository.py", line 70, in compare_commits
worker_1  |     res = client.get_last_commits(repo.config["project_id"], end_sha)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/client.py", line 255, in get_last_commits
worker_1  |     commit = self.get(path)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/shared_integrations/client/base.py", line 192, in get
worker_1  |     return self.request("GET", *args, **kwargs)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/client.py", line 108, in request
worker_1  |     new_identity = self.refresh_auth()
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/client.py", line 126, in refresh_auth
worker_1  |     return self.identity.get_provider().refresh_identity(
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/identity/gitlab/provider.py", line 101, in refresh_identity
worker_1  |     req = safe_urlopen(url=refresh_token_url, headers={}, data=data)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/http.py", line 98, in safe_urlopen
worker_1  |     response = session.request(
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/net/http.py", line 154, in request
worker_1  |     response = _Session.request(self, *args, **kwargs)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
worker_1  |     resp = self.send(prep, **send_kwargs)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
worker_1  |     r = adapter.send(request, **kwargs)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
worker_1  |     raise SSLError(e, request=request)
worker_1  | requests.exceptions.SSLError: SafeHTTPSConnectionPool(host='gitlab.mll', port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
worker_1  |
worker_1  | During handling of the above exception, another exception occurred:
worker_1  |
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/commits.py", line 136, in fetch_commits
worker_1  |     repo_commits = provider.compare_commits(repo, start_sha, end_sha)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/repository.py", line 76, in compare_commits
worker_1  |     raise installation.raise_error(e)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/base.py", line 373, in raise_error
worker_1  |     raise IntegrationError(self.message_from_error(exc)).with_traceback(sys.exc_info()[2])
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/repository.py", line 70, in compare_commits
worker_1  |     res = client.get_last_commits(repo.config["project_id"], end_sha)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/client.py", line 255, in get_last_commits
worker_1  |     commit = self.get(path)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/shared_integrations/client/base.py", line 192, in get
worker_1  |     return self.request("GET", *args, **kwargs)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/client.py", line 108, in request
worker_1  |     new_identity = self.refresh_auth()
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/integrations/gitlab/client.py", line 126, in refresh_auth
worker_1  |     return self.identity.get_provider().refresh_identity(
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/identity/gitlab/provider.py", line 101, in refresh_identity
worker_1  |     req = safe_urlopen(url=refresh_token_url, headers={}, data=data)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/http.py", line 98, in safe_urlopen
worker_1  |     response = session.request(
worker_1  |   File "/usr/local/lib/python3.8/site-packages/sentry/net/http.py", line 154, in request
worker_1  |     response = _Session.request(self, *args, **kwargs)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
worker_1  |     resp = self.send(prep, **send_kwargs)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
worker_1  |     r = adapter.send(request, **kwargs)
worker_1  |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
worker_1  |     raise SSLError(e, request=request)
```

I believe this issue can be fixed by passing the option `verify_ssl` from the GitLab integration down to the refresh token flow.
My python knowledge is very limited, but I tried my hands at a merge request with https://github.com/getsentry/sentry/pull/46492.

**Comment by n19htz** [comment]
we got exactly the same problem, is there any way to fix it?
