### ISSUE TITLE
Sentry Eventmapping Integrity Constraint Errors

### ISSUE THREAD

**Issue by aryeh-looker** [getsentry/sentry#4787]
Getting a ton of these errors which are quickly filling up our logs:

```
Jan 19 05:50:12 errorssentry supervisord: sentry-web 127.0.0.1 - - [19/Jan/2017:05:50:12 +0000] "POST /api/3/store/?sentry_version=7&sentry_client=raven-js/3.7.0&sentry_key=XXX&sentry_secret=XXX HTTP/1.0" 200 366 "-" "Ruby"
Jan 19 05:50:12 errorssentry supervisord: sentry-worker Traceback (most recent call last):
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 566, in save
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     project=project, group=group, event_id=event_id)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return self.get_queryset().create(**kwargs)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     obj.save(force_insert=True, using=self.db)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     force_update=force_update, update_fields=update_fields)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     using=using, raw=raw)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return insert_query(self.model, objs, fields, **kwargs)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return query.get_compiler(using=using).execute_sql(return_id)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     cursor.execute(sql, params)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return real_execute(self, sql, params)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return self.cursor.execute(sql, params)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     six.reraise(dj_exc_type, dj_exc_value, traceback)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return self.cursor.execute(sql, params)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     raise_the_exception(self.db, e)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return func(self, *args, **kwargs)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return func(self, *args, **kwargs)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return func(self, sql, *args, **kwargs)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 39, in execute
Jan 19 05:50:12 errorssentry supervisord: sentry-worker     return self.cursor.execute(sql, params)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker IntegrityError: IntegrityError('duplicate key value violates unique constraint "sentry_eventmapping_project_id_eb6c54bf8930ba6_uniq"\nDETAIL:  Key (project_id, event_id)=(3, 78ec8a2a7ef94c429a395d1b520365ab) already exists.\n',)
Jan 19 05:50:12 errorssentry supervisord: sentry-worker SQL: INSERT INTO "sentry_eventmapping" ("project_id", "group_id", "event_id", "date_added") VALUES (%s, %s, %s, %s) RETURNING "sentry_eventmapping"."id"
Jan 19 05:50:12 errorssentry supervisord: sentry-worker 05:50:12 [INFO] sentry.events: duplicate.found
Jan 19 05:50:13 errorssentry supervisord: sentry-web 127.0.0.1 - - [19/Jan/2017:05:50:13 +0000] "POST /api/2/store/ HTTP/1.0" 200 366 "-" "Faraday v0.9.0"
```

Sentry 8.8.0. There is some possibility that it might be related to the fact that we proxy errors from our front-end via a backend server before going to our self-hosted Sentry Instance — but this is doubtful because we have otherwise haven't had issues with this approach for months.

**Comment by aryeh-looker** [comment]
Upgraded to 8.12.0 and restarted the instance. Looks like one of those two operations really helped.

**Comment by mattrobenolt** [comment]
Looks like you're generating non-unique event ids in your proxy. But this would be expected behavior on the server side. It's just simply logging that it's a duplicate and it's being dropped.

**Comment by aryeh-looker** [comment]
> Looks like you're generating non-unique event ids in your proxy.

I don't think this is the case. This is our proxying code. We point `raven-js` at this route for capturing events. 

```
    post '/api/internal/public/sentry/*' do
      base_path = "/api/#{Application::Sentry::FRONT_END_PROJECT}/store/"
      base_query = "sentry_version=#{params[:sentry_version]}&sentry_client=#{params[:sentry_client]}"
      auth = "sentry_key=#{Application::Sentry::FRONT_END_KEY}&sentry_secret=#{Application::Sentry::FRONT_END_SECRET}"
      path = "#{base_path}?#{base_query}&#{auth}"

      Net::HTTP.start(
        Application::Sentry::FRONT_END_HOST,
        Application::Sentry::FRONT_END_PORT,
        :use_ssl => true,
      ) do |http|
        ans = http.post(path, request.body.read)
        content_type ans['Content-Type']       
        ans.body
      end
    end
```

Three potential theories based on admittedly imperfect understanding of Sentry event reporting:
* something else is going on — for example, Sentry is attempting to re-try to insert an event that has already been inserted — e.g. something weird with broker events
* there is something going on with event ids:
   * there is a bug in `raven-js` wherein event ids are being reused
   * we are (incorrectly?) not creating an event id at all and Sentry is creating a duplicate one on our behalf

Thoughts?
