### ISSUE TITLE
Experiencing 500 errors on source map upload

### ISSUE THREAD

**Issue by ldelossa** [getsentry/sentry#4796]
## Reporting Bugs

- The version of Sentry you're using
  sentry, version 8.10.0
- Whether you're using Docker or another installation method
   No docker, all GCE cloud instances
- Include a stacktrace or other logs when relevant
   During time period of error I found the following stack traces across uwsgi logs:
```
  Traceback (most recent call last):
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 86, in handle_exception
    return super(Endpoint, self).handle_exception(exc)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 176, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/api/endpoints/release_files.py", line 168, in post
    file.putfile(fileobj)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/models/file.py", line 194, in putfile
    blob = FileBlob.from_file(blob_fileobj)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/models/file.py", line 99, in from_file
    storage.save(blob.path, fileobj)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/../django/core/files/storage.py", line 49, in save
    name = self._save(name, content)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 479, in _save
    obj = self.bucket.Object(encoded_name)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 339, in bucket
    self._bucket = self._get_or_create_bucket(self.bucket_name)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 371, in _get_or_create_bucket
    bucket = self.connection.Bucket(name)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 328, in connection
    config=self.config
Traceback (most recent call last):
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 86, in handle_exception
    return super(Endpoint, self).handle_exception(exc)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 176, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/api/endpoints/release_details.py", line 205, in delete
    release.delete()
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/../django/db/models/base.py", line 695, in delete
    collector.delete()
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/../django/db/models/deletion.py", line 282, in delete
    sender=model, instance=obj, using=self.using
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/../django/db/transaction.py", line 316, in __exit__
    connection.commit()
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/../django/db/backends/__init__.py", line 171, in commit
    self._commit()
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/../django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/../django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/../django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
IntegrityError: update or delete on table "sentry_release" violates foreign key constraint "release_id_refs_id_8c214aaf" on table "sentry_releasefile"
DETAIL:  Key (id)=(257) is still referenced from table "sentry_releasefile".
Traceback (most recent call last):
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 86, in handle_exception
    return super(Endpoint, self).handle_exception(exc)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 176, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/api/endpoints/release_files.py", line 168, in post
    file.putfile(fileobj)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/models/file.py", line 194, in putfile
    blob = FileBlob.from_file(blob_fileobj)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/models/file.py", line 99, in from_file
    storage.save(blob.path, fileobj)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/../django/core/files/storage.py", line 49, in save
    name = self._save(name, content)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 479, in _save
    obj = self.bucket.Object(encoded_name)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 339, in bucket
    self._bucket = self._get_or_create_bucket(self.bucket_name)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 371, in _get_or_create_bucket
    bucket = self.connection.Bucket(name)
  File "/home/sentry/www/sentry/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 328, in connection
    config=self.config
```

We are assuming the foreign key constraint is a non-issue because we attempt posts of source maps (which fail) BEFORE we attempt a delete of the source maps.

I have reason to believe this is boto related. Within sentry we log the following events during 500 reposes from uwsgi processes:

https://hastebin.com/defixefedi.sm

Here are also the HTTP access logs 

130.211.1.77 - - [20/Jan/2017:16:10:35 +0000] "POST /api/0/projects/{obfuscated}/collintest11484928635090/files/ HTTP/1.1" 500 340 "-" "grunt-sentry-release"

**Comment by ldelossa** [comment]
Also this DB query:

```
SELECT "sentry_fileblob"."id", "sentry_fileblob"."path", "sentry_fileblob"."size", "sentry_fileblob"."checksum", "sentry_fileblob"."timestamp" FROM "sentry_fileblob" WHERE "sentry_fileblob"."checksum" = 'ed255059a7ea75f9c2b3e12f7d5911f24b81f6cd'
```

Returns nothing - not sure the latest db call needs to supply json key values to the botocore routine.

**Comment by mattrobenolt** [comment]
You should upgrade. This was a bug in boto3 that I fixed. I'll dig up the commit. But this is for sure fixed in latest version.

**Comment by mattrobenolt** [comment]
https://github.com/getsentry/sentry/pull/4593 Which is in 8.11.

**Comment by ldelossa** [comment]
Thank you! I'll give this a try.

**Comment by ldelossa** [comment]
@mattrobenolt any breaking changes or config changes I should be aware of ?

**Comment by mattrobenolt** [comment]
Everything is documented in CHANGES.

**Comment by ldelossa** [comment]
Noted, thank you.
