### ISSUE TITLE
Traceback on bad DSym Uploads

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#4807]
If one uploads bad dsyms this error can be triggered:

```
00:02:18 server  | Traceback (most recent call last):
00:02:18 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/api/base.py", line 86, in handle_exception
00:02:18 server  |     return super(Endpoint, self).handle_exception(exc)
00:02:18 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/api/base.py", line 180, in dispatch
00:02:18 server  |     response = handler(request, *args, **kwargs)
00:02:18 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/api/endpoints/dsym_files.py", line 92, in post
00:02:18 server  |     return upload_from_request(request, project=project)
00:02:18 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/api/endpoints/dsym_files.py", line 23, in upload_from_request
00:02:18 server  |     files = create_files_from_macho_zip(fileobj, project=project)
00:02:18 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/models/dsymfile.py", line 414, in create_files_from_macho_zip
00:02:18 server  |     uuids = get_macho_uuids(fn)
00:02:18 server  |   File "/Users/mitsuhiko/.virtualenvs/sentry/lib/python2.7/site-packages/symsynd/macho/arch.py", line 236, in get_macho_uuids
00:02:18 server  |     get_macho_image_info(filename)]
00:02:18 server  |   File "/Users/mitsuhiko/.virtualenvs/sentry/lib/python2.7/site-packages/symsynd/macho/arch.py", line 205, in get_macho_image_info
00:02:18 server  |     bin = MachO(filename)
00:02:18 server  |   File "/Users/mitsuhiko/.virtualenvs/sentry/lib/python2.7/site-packages/symsynd/macho/header.py", line 61, in __init__
00:02:18 server  |     self.load(fp)
00:02:18 server  |   File "/Users/mitsuhiko/.virtualenvs/sentry/lib/python2.7/site-packages/symsynd/macho/header.py", line 68, in load
00:02:18 server  |     header = struct.unpack('>I', fh.read(4))[0]
00:02:18 server  | error: unpack requires a string argument of length 4
```

**Comment by mitsuhiko** [comment]
Another bug one can trigger by uploading malformed files:

```
01:02:39 server  | Traceback (most recent call last):
01:02:39 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/api/base.py", line 86, in handle_exception
01:02:39 server  |     return super(Endpoint, self).handle_exception(exc)
01:02:39 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/api/base.py", line 180, in dispatch
01:02:39 server  |     response = handler(request, *args, **kwargs)
01:02:39 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/api/endpoints/dsym_files.py", line 92, in post
01:02:39 server  |     return upload_from_request(request, project=project)
01:02:39 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/api/endpoints/dsym_files.py", line 23, in upload_from_request
01:02:39 server  |     files = create_files_from_macho_zip(fileobj, project=project)
01:02:39 server  |   File "/Users/mitsuhiko/Development/sentry/src/sentry/models/dsymfile.py", line 414, in create_files_from_macho_zip
01:02:39 server  |     uuids = get_macho_uuids(fn)
01:02:39 server  |   File "/Users/mitsuhiko/.virtualenvs/sentry/lib/python2.7/site-packages/symsynd/macho/arch.py", line 236, in get_macho_uuids
01:02:39 server  |     get_macho_image_info(filename)]
01:02:39 server  | KeyError: 'uuid'
```

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
