### ISSUE TITLE
when installing sentry its spiting out an error

### ISSUE THREAD

**Issue by BotWilliam** [getsentry/sentry#4865]
Traceback (most recent call last):
  File "/www/sentry/bin/sentry", line 7, in <module>
    from sentry.runner import main
  File "/www/sentry/lib/python3.5/site-packages/sentry/runner/__init__.py", line 73, in <module>
    'sentry.runner.commands.dsym.dsym',
  File "/www/sentry/lib/python3.5/site-packages/sentry/runner/__init__.py", line 54, in <lambda>
    list(map(lambda cmd: cli.add_command(import_string(cmd)), (
  File "/www/sentry/lib/python3.5/site-packages/sentry/utils/imports.py", line 38, in import_string
    result = _cache[path]
  File "/www/sentry/lib/python3.5/site-packages/sentry/utils/imports.py", line 21, in __missing__
    module = __import__(module_name, {}, {}, [class_name])
  File "/www/sentry/lib/python3.5/site-packages/sentry/runner/commands/tsdb.py", line 12, in <module>
    from sentry.utils.iterators import chunked
  File "/www/sentry/lib/python3.5/site-packages/sentry/utils/iterators.py", line 21
    lambda (i, iterator): advance(i, iterator),
using the latest version
python install

**Comment by dcramer** [comment]
You likely have something misconfigured if its erroring, and should investigate the error that its reporting.

https://sentry.io/support/

**Comment by mattrobenolt** [comment]
Sentry doesn't run on python 3.5. This is clearly stated in our docs that we require 2.7.
