### ISSUE TITLE
sentry.models.alert.AlertRelatedGroup model has not defined

### ISSUE THREAD

**Issue by konformjs** [getsentry/sentry#4914]
upgrade from: sentry, version 8.8.0
upgrade to: sentry, version 8.13.0
os: Centos 7

after package upgrades
when running: sentry upgrade
following error comes: 

Traceback (most recent call last):
  File "/usr/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/sentry/runner/__init__.py", line 158, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/usr/lib/python2.7/site-packages/sentry/runner/__init__.py", line 121, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/usr/lib/python2.7/site-packages/sentry/runner/settings.py", line 159, in configure
    }, skip_backend_validation=skip_backend_validation)
  File "/usr/lib/python2.7/site-packages/sentry/runner/initializer.py", line 248, in initialize_app
    register_plugins(settings)
  File "/usr/lib/python2.7/site-packages/sentry/runner/initializer.py", line 20, in register_plugins
    from sentry.plugins import bindings, plugins
  File "/usr/lib/python2.7/site-packages/sentry/plugins/__init__.py", line 10, in <module>
    from sentry.plugins.base import *  # NOQA
  File "/usr/lib/python2.7/site-packages/sentry/plugins/base/__init__.py", line 10, in <module>
    from .bindings import BindingManager
  File "/usr/lib/python2.7/site-packages/sentry/plugins/base/bindings.py", line 5, in <module>
    from sentry.plugins import providers
  File "/usr/lib/python2.7/site-packages/sentry/plugins/providers/__init__.py", line 5, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/usr/lib/python2.7/site-packages/sentry/utils/imports.py", line 51, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/sentry/plugins/providers/dummy/__init__.py", line 5, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/usr/lib/python2.7/site-packages/sentry/utils/imports.py", line 51, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/sentry/plugins/providers/dummy/repository.py", line 3, in <module>
    from sentry.plugins.providers.repository import RepositoryProvider
  File "/usr/lib/python2.7/site-packages/sentry/plugins/providers/repository.py", line 6, in <module>
    from sentry.api.serializers import serialize
  File "/usr/lib/python2.7/site-packages/sentry/api/serializers/__init__.py", line 4, in <module>
    from .models import *  # NOQA
  File "/usr/lib/python2.7/site-packages/sentry/api/serializers/models/__init__.py", line 5, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/usr/lib/python2.7/site-packages/sentry/utils/imports.py", line 51, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/sentry/api/serializers/models/activity.py", line 6, in <module>
    from sentry.models import Activity
  File "/usr/lib/python2.7/site-packages/sentry/models/__init__.py", line 13, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/usr/lib/python2.7/site-packages/sentry/utils/imports.py", line 51, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/sentry/models/alert.py", line 104, in <module>
    class AlertRelatedGroup(Model):
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 243, in __new__
    new_class._prepare()
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 307, in _prepare
    signals.class_prepared.send(sender=cls)
  File "/usr/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/lib/python2.7/site-packages/sentry/db/models/base.py", line 121, in __model_class_prepared
    raise ValueError('{!r} model has not defined __core__'.format(sender))
ValueError: <class 'sentry.models.alert.AlertRelatedGroup'> model has not defined __core__

**Comment by dcramer** [comment]
You need to remove .pyc files which are cached.

**Comment by konformjs** [comment]
I have now removed all .pyc files from server but it didn't helped. Are there other tricks

**Comment by dcramer** [comment]
All I can tell you is this model no longer exists and its not a bug in the codebase. If you need more support: https://docs.sentry.io/support/
