### ISSUE TITLE
unable to build Sentry's static assets!

### ISSUE THREAD

**Issue by herolyle** [getsentry/sentry#49167]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

```
[yarn build-production --bail] failed with exit code [139] on [/workspace]:
b'yarn run v1.22.5\n$ NODE_ENV=production yarn webpack --mode production --bail\n$ /workspace/node_modules/.bin/webpack --mode production --bail\nSegmentation fault\nerror Command failed with exit code 139.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\nerror Command failed with exit code 139.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n'
Traceback (most recent call last):
  File "/workspace/src/sentry/utils/distutils/commands/build_assets.py", line 113, in _build
    self._build_static()
  File "/workspace/src/sentry/utils/distutils/commands/build_assets.py", line 133, in _build_static
    self._run_command(["yarn", "build-production", "--bail"], env=env)
  File "/workspace/src/sentry/utils/distutils/commands/base.py", line 131, in _run_command
    return check_output(cmd, cwd=self.work_path, env=env, stderr=STDOUT)
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yarn', 'build-production', '--bail']' returned non-zero exit status 139.
unable to build Sentry's static assets!
```

### Expected Result

```
[yarn build-production --bail] failed with exit code [139] on [/workspace]:
b'yarn run v1.22.5\n$ NODE_ENV=production yarn webpack --mode production --bail\n$ /workspace/node_modules/.bin/webpack --mode production --bail\nSegmentation fault\nerror Command failed with exit code 139.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\nerror Command failed with exit code 139.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n'
Traceback (most recent call last):
  File "/workspace/src/sentry/utils/distutils/commands/build_assets.py", line 113, in _build
    self._build_static()
  File "/workspace/src/sentry/utils/distutils/commands/build_assets.py", line 133, in _build_static
    self._run_command(["yarn", "build-production", "--bail"], env=env)
  File "/workspace/src/sentry/utils/distutils/commands/base.py", line 131, in _run_command
    return check_output(cmd, cwd=self.work_path, env=env, stderr=STDOUT)
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yarn', 'build-production', '--bail']' returned non-zero exit status 139.
unable to build Sentry's static assets!
```

### Actual Result

```
[yarn build-production --bail] failed with exit code [139] on [/workspace]:
b'yarn run v1.22.5\n$ NODE_ENV=production yarn webpack --mode production --bail\n$ /workspace/node_modules/.bin/webpack --mode production --bail\nSegmentation fault\nerror Command failed with exit code 139.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\nerror Command failed with exit code 139.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n'
Traceback (most recent call last):
  File "/workspace/src/sentry/utils/distutils/commands/build_assets.py", line 113, in _build
    self._build_static()
  File "/workspace/src/sentry/utils/distutils/commands/build_assets.py", line 133, in _build_static
    self._run_command(["yarn", "build-production", "--bail"], env=env)
  File "/workspace/src/sentry/utils/distutils/commands/base.py", line 131, in _run_command
    return check_output(cmd, cwd=self.work_path, env=env, stderr=STDOUT)
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yarn', 'build-production', '--bail']' returned non-zero exit status 139.
unable to build Sentry's static assets!
```

### Product Area

Unknown

**Comment by scttcper** [comment]
I need a few more details about your setup. What sdk are you using? What build command is this running?

**Comment by chadwhitacre** [comment]
@herolyle Closing as this report is low quality and unactionable, if you file a new issue please fill out the information requested rather than duplicating the traceback in all fields.
