### ISSUE TITLE
sentry upgrade fails with syntax error

### ISSUE THREAD

**Issue by kamikaze** [getsentry/sentry#5036]
`$ sentry upgrade`
```
Traceback (most recent call last):
  File "/.venv_sentry/bin/sentry", line 11, in <module>
    load_entry_point('sentry==8.14.0', 'console_scripts', 'sentry')()
  File "/.venv_sentry/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/.venv_sentry/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/.venv_sentry/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/.venv_sentry/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/.venv_sentry/lib64/python3.6/site-packages/sentry/runner/__init__.py", line 73, in <module>
    'sentry.runner.commands.dsym.dsym',
  File "/.venv_sentry/lib64/python3.6/site-packages/sentry/runner/__init__.py", line 54, in <lambda>
    list(map(lambda cmd: cli.add_command(import_string(cmd)), (
  File "/.venv_sentry/lib64/python3.6/site-packages/sentry/utils/imports.py", line 38, in import_string
    result = _cache[path]
  File "/.venv_sentry/lib64/python3.6/site-packages/sentry/utils/imports.py", line 21, in __missing__
    module = __import__(module_name, {}, {}, [class_name])
  File "/.venv_sentry/lib64/python3.6/site-packages/sentry/runner/commands/tsdb.py", line 12, in <module>
    from sentry.utils.iterators import chunked
  File "/.venv_sentry/lib64/python3.6/site-packages/sentry/utils/iterators.py", line 21
    lambda (i, iterator): advance(i, iterator),
           ^
SyntaxError: invalid syntax
```

**Comment by kamikaze** [comment]
sentry-8.14.0

`$ sentry --version` fails too, I think it's a global problem

**Comment by mattrobenolt** [comment]
You need python 2.7.
