### ISSUE TITLE
Sentry worker stops sending e-mail with error gaierror: [Errno -5] 

### ISSUE THREAD

**Issue by fredvd** [getsentry/sentry#5136]
Using Sentry 8.13 running as separate processes, managed by supervisord (no Docker).

gaierror: [Errno -5] No address associated with hostname

Running sentry internally with one worker on a small scale setup. Suddenly the worker stops sending outbound e-mails where e-mails have been working previously, the worker process has been up and running for 6 days.  Backtrace included at the end. I spotted this when inviting a co-worker to Sentry who didn't receive the invitation e-mail.

Unfortunately because of #3990 I thought I couldn't trigger another manual e-mail through the worker (the Django web proces was able to send the testing email, running on the same host). After this I restarted the worker and remembered there's a profile setting to receive e-mail notifications from your own actions, so I enabled this and assigned an event to myself to check outbound e-mail sending. After the worker restart e-mail sending is working again, I received the workflow notification. 

DNS is working fine on the host, connection to the outbound smtp-relay is working correctly. (the django process sent the testig-email)

For the time being I've set up a cron job to restart the worker every night. Any tips/advice on how I can debug and provide more feedback for this issue? "After a number of days the sentryworker suddenly cannot send any e-mail" is a bit vague :-(

Comment on the stdout logging of the celeryworker as captured by supervisor below: there is only a time component of the timestamp, not a datetime. That would be helpfull as I cannot figure out from the logs when the last succesful e-mail was sent. (will create a separate issue for this).

celeryworker stdout log:

15:06:21 [ERROR] celery.worker.job: Task sentry.tasks.email.send_email[08f311a6-a86b-41eb-9b6b-cfd128d69c1c] raised unexpected: gaierror(-5, 'No address associated with hostname') (dat
a={u'hostname': 'celery@zzz-servernamewithoutdomain-zzz', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMu
ltiAlternatives object at 0x7f8563322d10>}", u'id': '08f311a6-a86b-41eb-9b6b-cfd128d69c1c'})
Traceback (most recent call last):
  File "/var/zope/sentry/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/zope/sentry/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/zope/sentry/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/var/zope/sentry/lib/python2.7/site-packages/sentry/tasks/email.py", line 72, in send_email
    send_messages([message])
  File "/var/zope/sentry/lib/python2.7/site-packages/sentry/utils/email.py", line 405, in send_messages
    sent = connection.send_messages(messages)
  File "/var/zope/sentry/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "/var/zope/sentry/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 48, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/var/zope/python27/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/var/zope/python27/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/var/zope/python27/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/var/zope/python27/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -5] No address associated with hostname

**Comment by xoco70** [comment]
I have the same issue!

**Comment by bonniechen1119** [comment]
I have the same issue!

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
