### ISSUE TITLE
Cannot run Relay tests

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#51471]
I'm trying to run the Relay tests but it is failing with relay did not start in time.

This command: `pytest -s -v tests/relay_integration/test_sdk.py -k test_simple`

@getsentry/ingest do you know what's happening? (CC @getsentry/dev-infra )

I hacked the test to try `http://0.0.0.0:33331` instead of `http://127.0.0.1:33331

I saw this info from `docker ps -a` when I added a breakpoint
```
3000/tcp, 0.0.0.0:33331->33331/tcp                                             sentry_test_relay_server
```

This is the test output (I removed `\n` from the output).
```
src/sentry/utils/pytest/relay.py:156: in relay_server
    raise ValueError(f"relay did not start in time:
{container.logs()}") from ex
E   ValueError: relay did not start in time:
E   b'<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
2023-06-22T18:49:36.775425Z  INFO relay::setup: launching relay from config folder /etc/relay
2023-06-22T18:49:36.780076Z  INFO relay::setup:   relay mode: managed
2023-06-22T18:49:36.780314Z  INFO relay::setup:   relay id: 88888888-4444-4444-8444-cccccccccccc
2023-06-22T18:49:36.780628Z  INFO relay::setup:   public key: SMSesqan65THCV6M4qs4kBzPai60LzuDn-xNsvYpuP8
2023-06-22T18:49:36.781357Z  INFO relay::setup:   log level: TRACE
2023-06-22T18:49:36.781700Z  INFO relay_server: relay server starting
2023-06-22T18:49:36.948002Z  INFO relay_server::actors::upstream: registering with upstream descriptor=http://host.docker.internal:58617/
2023-06-22T18:49:37.072283Z ERROR r2d2: failed to lookup address information: Name or service not known 
... 
2023-06-22T18:49:37.618513Z ERROR r2d2: failed to lookup address information: Name or service not known    
```

**Comment by iker-barriocanal** [comment]
Running the command `pytest -s -v tests/relay_integration/test_sdk.py -k test_simple` on my local machine results in flaky test outcomes (sometimes fails, sometimes passes) but always throws a bunch of exceptions.

I think this test has been problematic in the past. I can't remember why, but I _think_ it was related to how we set up the SDK at Sentry with a lot of custom stuff.

**Comment by olksdr** [comment]
> 2023-06-22T18:49:37.072283Z ERROR r2d2: failed to lookup address information: Name or service not known

This error says it cannot connect to Redis, do you have it running and. configured? That might be a problem.

**Comment by armenzg** [comment]
This is still happening. We can use #51241 to track this networking issue.

```
pytest -s -v tests/relay_integration/test_sdk.py -k test_simple
============================================================================================= test session starts ==============================================================================================
platform darwin -- Python 3.8.16, pytest-7.2.1, pluggy-0.13.1 -- /Users/armenzg/code/sentry/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/armenzg/code/sentry, configfile: pyproject.toml
plugins: fail-slow-0.3.0, rerunfailures-11.0, sentry-0.1.11, typeguard-3.0.2, xdist-3.0.2, cov-4.0.0, django-4.4.0
collected 6 items / 5 deselected / 1 selected

tests/relay_integration/test_sdk.py::test_simple Creating test database for alias 'default'...
Created internal Sentry project (slug=internal, id=1)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51418)
Traceback (most recent call last):
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 178, in handle
    self.handle_one_request()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 186, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
----------------------------------------
Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 124, in getresponse
    return real_getresponse(self, *args, **kwargs)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 124, in getresponse
    return real_getresponse(self, *args, **kwargs)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/src/sentry/testutils/pytest/relay.py", line 149, in relay_server
    requests.get(url)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
13:15:55 [ERROR] sentry.testutils.pytest.relay: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
ERRORDestroying test database for alias 'default'...


==================================================================================================== ERRORS ====================================================================================================
________________________________________________________________________________________ ERROR at setup of test_simple _________________________________________________________________________________________
.venv/lib/python3.8/site-packages/urllib3/connectionpool.py:703: in urlopen
    httplib_response = self._make_request(
.venv/lib/python3.8/site-packages/urllib3/connectionpool.py:449: in _make_request
    six.raise_from(e, None)
<string>:3: in raise_from
    ???
.venv/lib/python3.8/site-packages/urllib3/connectionpool.py:444: in _make_request
    httplib_response = conn.getresponse()
.venv/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py:124: in getresponse
    return real_getresponse(self, *args, **kwargs)
../../.pyenv/versions/3.8.16/lib/python3.8/http/client.py:1348: in getresponse
    response.begin()
../../.pyenv/versions/3.8.16/lib/python3.8/http/client.py:316: in begin
    version, status, reason = self._read_status()
../../.pyenv/versions/3.8.16/lib/python3.8/http/client.py:285: in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
E   http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:
.venv/lib/python3.8/site-packages/requests/adapters.py:486: in send
    resp = conn.urlopen(
.venv/lib/python3.8/site-packages/urllib3/connectionpool.py:787: in urlopen
    retries = retries.increment(
.venv/lib/python3.8/site-packages/urllib3/util/retry.py:550: in increment
    raise six.reraise(type(error), error, _stacktrace)
.venv/lib/python3.8/site-packages/urllib3/packages/six.py:769: in reraise
    raise value.with_traceback(tb)
.venv/lib/python3.8/site-packages/urllib3/connectionpool.py:703: in urlopen
    httplib_response = self._make_request(
.venv/lib/python3.8/site-packages/urllib3/connectionpool.py:449: in _make_request
    six.raise_from(e, None)
<string>:3: in raise_from
    ???
.venv/lib/python3.8/site-packages/urllib3/connectionpool.py:444: in _make_request
    httplib_response = conn.getresponse()
.venv/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py:124: in getresponse
    return real_getresponse(self, *args, **kwargs)
../../.pyenv/versions/3.8.16/lib/python3.8/http/client.py:1348: in getresponse
    response.begin()
../../.pyenv/versions/3.8.16/lib/python3.8/http/client.py:316: in begin
    version, status, reason = self._read_status()
../../.pyenv/versions/3.8.16/lib/python3.8/http/client.py:285: in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
E   urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:
src/sentry/testutils/pytest/relay.py:149: in relay_server
    requests.get(url)
.venv/lib/python3.8/site-packages/requests/api.py:73: in get
    return request("get", url, params=params, **kwargs)
.venv/lib/python3.8/site-packages/requests/api.py:59: in request
    return session.request(method=method, url=url, **kwargs)
.venv/lib/python3.8/site-packages/requests/sessions.py:589: in request
    resp = self.send(prep, **send_kwargs)
.venv/lib/python3.8/site-packages/requests/sessions.py:703: in send
    r = adapter.send(request, **kwargs)
.venv/lib/python3.8/site-packages/requests/adapters.py:501: in send
    raise ConnectionError(err, request=request)
E   requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:
src/sentry/testutils/pytest/relay.py:154: in relay_server
    raise ValueError(
E   ValueError: relay did not start in time http://127.0.0.1:33331:
E   2023-08-17T13:15:42.574298Z  INFO relay::setup: launching relay from config folder /etc/relay
E   2023-08-17T13:15:42.585616Z  INFO relay::setup:   relay mode: managed
E   2023-08-17T13:15:42.585697Z  INFO relay::setup:   relay id: 88888888-4444-4444-8444-cccccccccccc
E   2023-08-17T13:15:42.586084Z  INFO relay::setup:   public key: SMSesqan65THCV6M4qs4kBzPai60LzuDn-xNsvYpuP8
E   2023-08-17T13:15:42.586708Z  INFO relay::setup:   log level: TRACE
E   2023-08-17T13:15:42.588146Z  INFO relay_server: relay server starting
E   2023-08-17T13:15:42.735980Z  INFO relay_server::actors::upstream: registering with upstream descriptor=http://host.docker.internal:51411/
E   2023-08-17T13:15:43.831915Z DEBUG relay_server::actors::upstream: got register challenge token="eyJ0aW1lc3RhbXAiOjE2OTIyNzgxNDQsInJlbGF5X2lkIjoiODg4ODg4ODgtNDQ0NC00NDQ0LTg0NDQtY2NjY2NjY2NjY2NjIiwicHVibGljX2tleSI6IlNNU2VzcWFuNjVUSENWNk00cXM0a0J6UGFpNjBMenVEbi14TnN2WXB1UDgiLCJyYW5kIjoid01IV0pfcFpRM1E2algxUHN5OTZkbWJFLVRlQnVUejBwblQ2OXlPSmVqX3BVTWhuOXc1M1BCS3loRHVsNzJzMHNOTTUxeGJackRtUU51YXJCcDRodlEifQ:ujgZqDixO3c-GmKRsZI330vFv_wqmxCy9jRBsMjqAzOPuV28gSDiYAVnqAISIV94iXK_I_8kloBJ_KfRms5LUg"
E   2023-08-17T13:15:43.832356Z DEBUG relay_server::actors::upstream: sending register challenge response
E   2023-08-17T13:15:43.858404Z  INFO relay_server::actors::upstream: relay successfully registered with upstream
E   2023-08-17T13:15:44.886582Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:44.886621Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:44.886659Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:46.905712Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:46.905712Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:46.905712Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:48.911961Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:48.912016Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:48.911961Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:50.917529Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:50.917554Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:50.917474Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:52.922339Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:52.922364Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:52.922339Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:54.926871Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:54.926872Z ERROR r2d2: failed to lookup address information: Name or service not known
E   2023-08-17T13:15:54.927209Z ERROR r2d2: failed to lookup address information: Name or service not known
---------------------------------------------------------------------------------------------- Captured log setup ----------------------------------------------------------------------------------------------
ERROR    sentry.testutils.pytest.relay:relay.py:153 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 124, in getresponse
    return real_getresponse(self, *args, **kwargs)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 124, in getresponse
    return real_getresponse(self, *args, **kwargs)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/src/sentry/testutils/pytest/relay.py", line 149, in relay_server
    requests.get(url)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
=========================================================================================== short test summary info ============================================================================================
ERROR tests/relay_integration/test_sdk.py::test_simple - ValueError: relay did not start in time http://127.0.0.1:33331:
======================================================================================= 5 deselected, 1 error in 23.94s ========================================================================================
```

**Comment by armenzg** [comment]
Not using `--project test` makes it work.
