### ISSUE TITLE
8.10 -> 8.15

### ISSUE THREAD

**Issue by hadifarnoud** [getsentry/sentry#5229]
```
flynn run sentry --config=sentry.conf.py upgrade

Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > crispy_forms
 > debug_toolbar
 > raven.contrib.django.raven_compat
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > sudo
 > south
 > djangosecure
 > django_bcrypt
 > sentry_plugins.slack

Not synced (use migrations):
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
 - sentry_plugins.hipchat_ac
 - sentry_plugins.jira_ac
(use ./manage.py migrate to migrate these)
Running migrations for sentry:
 - Migrating forwards to 0311_auto__add_releaseheadcommit__add_unique_releaseheadcommit_repository_i.
 > sentry:0275_auto__del_index_grouptagvalue_project_key_value__add_index_grouptagval
FATAL ERROR - The following SQL query failed: DROP INDEX "sentry_messagefiltervalue_project_id_6247d29b6df74b1d"
The error was: index "sentry_messagefiltervalue_project_id_6247d29b6df74b1d" does not exist

Error in migration: sentry:0275_auto__del_index_grouptagvalue_project_key_value__add_index_grouptagval
Traceback (most recent call last):
  File "/app/.heroku/python/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python2.7/site-packages/sentry/runner/__init__.py", line 158, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/app/.heroku/python/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 60, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/app/.heroku/python/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 29, in _upgrade
    verbosity=verbosity,
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/app/.heroku/python/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/app/.heroku/python/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/app/.heroku/python/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/app/.heroku/python/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/app/.heroku/python/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/app/.heroku/python/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/app/.heroku/python/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/app/.heroku/python/lib/python2.7/site-packages/sentry/south_migrations/0275_auto__del_index_grouptagvalue_project_key_value__add_index_grouptagval.py", line 23, in forwards
    db.delete_index('sentry_messagefiltervalue', ['project_id', 'key', 'value'])
  File "/app/.heroku/python/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/app/.heroku/python/lib/python2.7/site-packages/south/db/generic.py", line 901, in delete_index
    self.execute(sql)
  File "/app/.heroku/python/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: index "sentry_messagefiltervalue_project_id_6247d29b6df74b1d" does not exist
```

how can I fix this?

**Comment by hadifarnoud** [comment]
I get error 500 after deploying. in logs this is the error I see

```
017-04-12T13:34:04.846644312Z]                                                              ^
[2017-04-12T13:34:04.846716944Z] 2017-04-12T13:34:04+0000 [stdout#info] 13:34:04 [ERROR] sentry.errors: Unable to fetch internal project
[2017-04-12T13:34:04.849816823Z] 2017-04-12T13:34:04+0000 [stderr#error] Traceback (most recent call last):
[2017-04-12T13:34:04.849905897Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/api/base.py", line 87, in handle_exception
[2017-04-12T13:34:04.850023038Z] 2017-04-12T13:34:04+0000 [stderr#error]     return super(Endpoint, self).handle_exception(exc)
[2017-04-12T13:34:04.850117739Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/api/base.py", line 173, in dispatch
[2017-04-12T13:34:04.850213679Z] 2017-04-12T13:34:04+0000 [stderr#error]     self.initial(request, *args, **kwargs)
[2017-04-12T13:34:04.850299206Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/views.py", line 319, in initial
[2017-04-12T13:34:04.850422624Z] 2017-04-12T13:34:04+0000 [stderr#error]     self.perform_authentication(request)
[2017-04-12T13:34:04.85049932Z]  2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/views.py", line 269, in perform_authentication
[2017-04-12T13:34:04.850605313Z] 2017-04-12T13:34:04+0000 [stderr#error]     request.user
[2017-04-12T13:34:04.850781746Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/request.py", line 226, in user
[2017-04-12T13:34:04.850821167Z] 2017-04-12T13:34:04+0000 [stderr#error]     self._authenticate()
[2017-04-12T13:34:04.850909428Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/request.py", line 401, in _authenticate
[2017-04-12T13:34:04.85093332Z]  2017-04-12T13:34:04+0000 [stderr#error]     user_auth_tuple = authenticator.authenticate(self)
[2017-04-12T13:34:04.85108347Z]  2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/authentication.py", line 117, in authenticate
[2017-04-12T13:34:04.851345979Z] 2017-04-12T13:34:04+0000 [stderr#error]     if not user or not user.is_active:
[2017-04-12T13:34:04.851507909Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/utils/functional.py", line 213, in inner
[2017-04-12T13:34:04.851932051Z] 2017-04-12T13:34:04+0000 [stderr#error]     self._setup()
[2017-04-12T13:34:04.852318492Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/utils/functional.py", line 298, in _setup
[2017-04-12T13:34:04.852433731Z] 2017-04-12T13:34:04+0000 [stderr#error]     self._wrapped = self._setupfunc()
[2017-04-12T13:34:04.852698377Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/middleware/auth.py", line 49, in <lambda>
[2017-04-12T13:34:04.852841603Z] 2017-04-12T13:34:04+0000 [stderr#error]     request.user = SimpleLazyObject(lambda: get_user(request))
[2017-04-12T13:34:04.853007926Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/middleware/auth.py", line 13, in get_user
[2017-04-12T13:34:04.85314737Z]  2017-04-12T13:34:04+0000 [stderr#error]     user = auth_get_user(request)
[2017-04-12T13:34:04.85327513Z]  2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/contrib/auth/__init__.py", line 144, in get_user
[2017-04-12T13:34:04.853657979Z] 2017-04-12T13:34:04+0000 [stderr#error]     user = backend.get_user(user_id) or AnonymousUser()
[2017-04-12T13:34:04.853797365Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/contrib/auth/backends.py", line 69, in get_user
[2017-04-12T13:34:04.854105292Z] 2017-04-12T13:34:04+0000 [stderr#error]     return UserModel._default_manager.get(pk=user_id)
[2017-04-12T13:34:04.85428254Z]  2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/manager.py", line 151, in get
[2017-04-12T13:34:04.854694083Z] 2017-04-12T13:34:04+0000 [stderr#error]     return self.get_queryset().get(*args, **kwargs)
[2017-04-12T13:34:04.854820044Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 304, in get
[2017-04-12T13:34:04.854983889Z] 2017-04-12T13:34:04+0000 [stderr#error]     num = len(clone)
[2017-04-12T13:34:04.855110847Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 77, in __len__
[2017-04-12T13:34:04.855231909Z] 2017-04-12T13:34:04+0000 [stderr#error]     self._fetch_all()
[2017-04-12T13:34:04.855366182Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 857, in _fetch_all
[2017-04-12T13:34:04.855506809Z] 2017-04-12T13:34:04+0000 [stderr#error]     self._result_cache = list(self.iterator())
[2017-04-12T13:34:04.855662469Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 220, in iterator
[2017-04-12T13:34:04.855813468Z] 2017-04-12T13:34:04+0000 [stderr#error]     for row in compiler.results_iter():
[2017-04-12T13:34:04.855969942Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/sql/compiler.py", line 713, in results_iter
[2017-04-12T13:34:04.856096841Z] 2017-04-12T13:34:04+0000 [stderr#error]     for rows in self.execute_sql(MULTI):
[2017-04-12T13:34:04.856216187Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/sql/compiler.py", line 786, in execute_sql
[2017-04-12T13:34:04.856369483Z] 2017-04-12T13:34:04+0000 [stderr#error]     cursor.execute(sql, params)
[2017-04-12T13:34:04.856787287Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
[2017-04-12T13:34:04.856911296Z] 2017-04-12T13:34:04+0000 [stderr#error]     return real_execute(self, sql, params)
[2017-04-12T13:34:04.857356485Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/backends/util.py", line 53, in execute
[2017-04-12T13:34:04.85756101Z]  2017-04-12T13:34:04+0000 [stderr#error]     return self.cursor.execute(sql, params)
[2017-04-12T13:34:04.857713318Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/utils.py", line 99, in __exit__
[2017-04-12T13:34:04.857854324Z] 2017-04-12T13:34:04+0000 [stderr#error]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[2017-04-12T13:34:04.858021507Z] 2017-04-12T13:34:04+0000 [stderr#error]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/backends/util.py", line 53, in execute
[2017-04-12T13:34:04.858162419Z] 2017-04-12T13:34:04+0000 [stderr#error]     return self.cursor.execute(sql, params)
[2017-04-12T13:34:04.858296425Z] 2017-04-12T13:34:04+0000 [stderr#error] ProgrammingError: column auth_user.session_nonce does not exist
[2017-04-12T13:34:04.85845258Z]  2017-04-12T13:34:04+0000 [stderr#error] LINE 1: ...ord_expired", "auth_user"."last_password_change", "auth_user...
[2017-04-12T13:34:04.858573065Z] 2017-04-12T13:34:04+0000 [stderr#error]                                                              ^
[2017-04-12T13:34:04.953640501Z] Traceback (most recent call last):
[2017-04-12T13:34:04.95373254Z]    File "/app/.heroku/python/lib/python2.7/site-packages/sentry/utils/raven.py", line 78, in send
[2017-04-12T13:34:04.95384195Z]      project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
[2017-04-12T13:34:04.953860095Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/db/models/manager.py", line 252, in get_from_cache
[2017-04-12T13:34:04.953922704Z]     result = self.get(**kwargs)
[2017-04-12T13:34:04.953943857Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/manager.py", line 151, in get
[2017-04-12T13:34:04.954007319Z]     return self.get_queryset().get(*args, **kwargs)
[2017-04-12T13:34:04.954023831Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 304, in get
[2017-04-12T13:34:04.954074753Z]     num = len(clone)
[2017-04-12T13:34:04.954106475Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 77, in __len__
[2017-04-12T13:34:04.954146406Z]     self._fetch_all()
[2017-04-12T13:34:04.954161106Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 857, in _fetch_all
[2017-04-12T13:34:04.954225662Z]     self._result_cache = list(self.iterator())
[2017-04-12T13:34:04.954240807Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 220, in iterator
[2017-04-12T13:34:04.954334942Z]     for row in compiler.results_iter():
[2017-04-12T13:34:04.954353805Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/sql/compiler.py", line 713, in results_iter
[2017-04-12T13:34:04.954637818Z]     for rows in self.execute_sql(MULTI):
[2017-04-12T13:34:04.954652979Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/models/sql/compiler.py", line 786, in execute_sql
[2017-04-12T13:34:04.954695093Z]     cursor.execute(sql, params)
[2017-04-12T13:34:04.954727198Z]   File "/app/.heroku/python/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
[2017-04-12T13:34:04.954779624Z]     return real_execute(self, sql, params)
[2017-04-12T13:34:04.954814049Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/backends/util.py", line 53, in execute
[2017-04-12T13:34:04.954861904Z]     return self.cursor.execute(sql, params)
[2017-04-12T13:34:04.95487414Z]    File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/utils.py", line 99, in __exit__
[2017-04-12T13:34:04.954931692Z]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[2017-04-12T13:34:04.954945535Z]   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/../django/db/backends/util.py", line 53, in execute
[2017-04-12T13:34:04.955004156Z]     return self.cursor.execute(sql, params)
[2017-04-12T13:34:04.955031212Z] ProgrammingError: column sentry_project.flags does not exist
[2017-04-12T13:34:04.955085157Z] LINE 1: ...roject"."status", "sentry_project"."first_event", "sentry_pr...
[2017-04-12T13:34:04.955099259Z]                                
```

**Comment by dcramer** [comment]
Is this on Postgres?

**Comment by hadifarnoud** [comment]
Yes
		

		
	





On Wed, Apr 12, 2017 at 8:01 PM +0430, "David Cramer" <notifications@github.com> wrote:












Is this on Postgres?

**Comment by bsergean** [comment]
Have you tried going from 8.10 to 8.11, then 8.11 to 8.12, etc... to see which migration was problematic for you version wise ?

**Comment by hadifarnoud** [comment]
I just installed latest version via Python. below is my requirements.txt (I can't use docker install method on Heroku/Flynn)

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
amqp==1.4.9               # via kombu
anyjson==0.3.3            # via kombu
appdirs==1.4.3            # via setuptools
asn1crypto==0.22.0        # via cryptography
attrs==16.3.0             # via service-identity
beautifulsoup==3.2.1      # via sentry-plugins
billiard==3.3.0.23        # via celery
boto3==1.4.4              # via sentry
boto==2.46.1
botocore==1.5.39          # via boto3, s3transfer
celery==3.1.18            # via sentry
cffi==1.10.0              # via cryptography, libsourcemap, symsynd
click==6.7                # via sentry
contextlib2==0.5.4        # via raven
cryptography==1.8.1       # via pyopenssl, python-u2flib-server, requests
cssselect==1.0.1          # via toronado
cssutils==0.9.10          # via sentry, toronado
dj-database-url==0.4.2
django-bcrypt==0.9.2
django-crispy-forms==1.4.0  # via sentry
django-debug-toolbar==1.3.2  # via sentry
django-jsonfield==0.9.13  # via sentry
django-picklefield==0.3.2  # via sentry
django-secure==1.0.1
django-storages==1.5.2
django-sudo==2.1.0        # via sentry
django-templatetag-sugar==1.0  # via sentry
django==1.6.11            # via django-debug-toolbar, django-secure, sentry
djangorestframework==2.4.8  # via sentry
docutils==0.13.1          # via botocore
email-reply-parser==0.2.0  # via sentry
enum34==1.1.6             # via cryptography, python-u2flib-server, sentry
exam==0.10.6              # via sentry
futures==3.0.5            # via s3transfer
hiredis==0.1.6            # via sentry
honcho==0.7.1             # via sentry
httplib2==0.10.3          # via oauth2
idna==2.5                 # via cryptography, requests
ipaddress==1.0.18         # via cryptography, sentry
jmespath==0.9.2           # via boto3, botocore
kombu==3.0.35             # via celery, sentry
libsourcemap==0.5.0       # via sentry
loremipsum==1.0.5         # via sentry
lxml==3.7.3               # via sentry, toronado
mmh3==2.3.1               # via sentry
mock==1.0.1               # via exam, sentry
ndg-httpsclient==0.4.2
oauth2==1.9.0.post1       # via sentry
oauthlib==2.0.2           # via requests-oauthlib
packaging==16.8           # via cryptography, setuptools
percy==0.4.4              # via sentry
petname==2.0              # via sentry
pillow==3.2.0             # via sentry
progressbar2==3.10.1      # via sentry
psycopg2==2.6.2
py-bcrypt==0.4            # via django-bcrypt
py==1.4.33                # via pytest
pyasn1-modules==0.0.8     # via service-identity
pyasn1==0.2.3             # via pyasn1-modules, service-identity
pycparser==2.17           # via cffi
pyjwt==1.4.2              # via sentry-plugins
pyopenssl==16.2.0         # via ndg-httpsclient, requests, service-identity
pyparsing==2.2.0          # via packaging
pytest-django==2.9.1      # via sentry
pytest-html==1.9.0        # via sentry
pytest==2.6.4             # via pytest-django, pytest-html, sentry
python-dateutil==2.6.0    # via botocore, sentry, sentry-plugins
python-memcached==1.58    # via sentry
python-openid==2.2.5      # via sentry
python-u2flib-server==4.0.1  # via sentry
python-utils==2.1.0       # via progressbar2
pytz==2017.2              # via celery
pyyaml==3.11              # via sentry
qrcode==5.3               # via sentry
raven==5.33.0             # via sentry
rb==1.6                   # via sentry
redis==2.10.5             # via rb, sentry
requests-oauthlib==0.8.0  # via sentry-plugins
requests[security]==2.12.5  # via percy, requests-oauthlib, sentry
s3transfer==0.1.10        # via boto3
selenium==3.0.0b3         # via sentry
sentry-auth-google==0.1.0
sentry-plugins==8.16.0
sentry-telegram==0.1.2
sentry==8.16.0
service-identity==16.0.0
setproctitle==1.1.10      # via sentry
simplejson==3.8.2         # via sentry
six==1.10.0               # via cryptography, packaging, pyopenssl, python-dateutil, python-memcached, python-utils, qrcode, sentry, setuptools, structlog
south==1.0.1              # via sentry
sqlparse==0.2.3           # via django-debug-toolbar
statsd==3.1               # via sentry
structlog==16.1.0         # via sentry
symsynd==2.4.0            # via sentry
toronado==0.0.11          # via sentry
twisted==16.4.1
ua-parser==0.7.3          # via sentry
urllib3==1.16             # via sentry
uwsgi==2.0.15             # via sentry
zope.interface==4.3.3     # via twisted

# The following packages are considered to be unsafe in a requirements file:
# setuptools                # via cryptography, zope.interface
```

**Comment by MarkMagnus** [comment]
index "sentry_messagefiltervalue_project_id_6247d29b6df74b1d"
when the index name is too large the naming function creates a hash, the funny thing or not so funny thing, is that python hash() function relies on PYTHONHASHSEED this is normally set to random. So if you transfer the database to a new environment or simply if the hash seed changes for whatever reason then the migrations will fail. To get around this is to set you python has seed, run migration to fail again, rename the index with sql and then re-run the migration. You may have to do this multiple times.

**Comment by dcherman** [comment]
I'm running into this as well.  Isn't the usage of a non-deterministic function (in this case affected by the randomness of the hash seed) for something like generating table/index names not a good idea?

The only way to work around this seems to be to set the seed to a known/constant value, but doesn't that have security implications?

https://stackoverflow.com/questions/27522626/hash-function-in-python-3-3-returns-different-results-between-sessions?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

We can't simply shut it off for the migration script either since without auditing the codebase / knowing implementation details, we don't know if this method is used for generating objects that'd be used in queries (tables, views, etc..)

**Comment by dcherman** [comment]
Hey @dcramer, any update here?  I think we've identified the piece of code that's causing the problem here, but I'm not sure how you'd want to approach this in order to make it a non-breaking change.

Whatever route you decide on, I'd suggest adding in checks for existing indexes given the current implementation so that for users that have defined a known `PYTHONHASHSEED` to try and work around this, it's not a breaking change.

**Comment by dcramer** [comment]
I'm also not sure of a reasonable way to resolve this in a non-breaking change. This hasn't been a high priority for us (it hasn't come up in customers convos) , so I'm going to leave this up to the community at this time. It seems like if its really PYTHONHASHSEED you could just set it to whatever it was originally, no?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
