### ISSUE TITLE
[Flaky CI]: Timeout with MetricRulesEdit › renders and edits trigger

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry#54216]
### Flakiness Type

Timeout

### Name of Job

Jest (2)

### Name of Test

static/app/views/alerts/rules/metric/edit.spec.tsx

### Link to Test Run

https://github.com/getsentry/sentry/actions/runs/5765859507/job/15632672314

### Details

```
FAIL  static/app/views/alerts/rules/metric/edit.spec.tsx (10.189 s)
  ● MetricRulesEdit › renders and edits trigger

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      69 |       url: `/organizations/${organization.slug}/alert-rules/${rule.id}/`,
      70 |       body: rule,
    > 71 |     });
         |   ^
      72 |
      73 |     const editRule = MockApiClient.addMockResponse({
      74 |       url: `/projects/${organization.slug}/project-slug/alert-rules/${rule.id}/`,

      at static/app/views/alerts/rules/metric/edit.spec.tsx:71:3
      at Object.<anonymous> (static/app/views/alerts/rules/metric/edit.spec.tsx:29:1)
```

**Comment by markstory** [comment]
Closing as this issue is a year+ old and we've likely addressed the flaky test already.
