### ISSUE TITLE
Android Sentry sdk cause ANR

### ISSUE THREAD

**Issue by cj3479** [getsentry/sentry#54435]
Description
The Sentry flutter version is 6.22.0

When I monitor weak network，I can reproduce the ANR. The below is ANR stack trace

"main" prio=5 tid=1 TimedWaiting
| group="main" sCount=1 dsCount=0 flags=1 obj=0x72ead6a8 self=0x6fa1862380
| sysTid=14241 nice=-10 cgrp=default sched=0/0 handle=0x70c81764f8
| state=S schedstat=( 124935273208 15636228127 402071 ) utm=8709 stm=3783 core=6 HZ=100
| stack=0x7fecc02000-0x7fecc04000 stackSize=8192KB
| held mutexes=
at sun.misc.Unsafe.park(Native method)

waiting on an unknown object
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1486)
at io.sentry.transport.AsyncHttpTransport.close(AsyncHttpTransport.java:3)
at io.sentry.SentryClient.close(SentryClient.java:3)
at io.sentry.Hub.close(Hub.java:10)
at io.sentry.Sentry.init(Sentry.java:22)
locked <0x070858c1> (a java.lang.Class<io.sentry.Sentry>)
at io.sentry.Sentry.init(Sentry.java:6)
at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:7)
locked <0x0fdec866> (a java.lang.Class<io.sentry.android.core.SentryAndroid>)
at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:3)
at io.sentry.flutter.SentryFlutterPlugin.initNativeSdk(SentryFlutterPlugin.kt:7)
at io.sentry.flutter.SentryFlutterPlugin.onMethodCall(SentryFlutterPlugin.kt:18)
at o.a.d.a.i$a.a(MethodChannel.java:4)
at o.a.c.b.f.c.d(DartMessenger.java:1)
at o.a.c.b.f.a.run(lambda:11)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by ceorourke** [comment]
Should this go to the https://github.com/getsentry/sentry-dart repo? This seems like an SDK issue rather than something to do with issues.

**Comment by arc-yong** [comment]
any update on this. I face the same issue.
