### ISSUE TITLE
Sentry - JIRA integration not working, can't create new issue after upgrading JIRA to 7.3.6

### ISSUE THREAD

**Issue by strangeman** [getsentry/sentry#5465]
Sentry version: 8.16.0 and 8.14.1 (running with Docker)
JIRA version: 7.3.6 (JIRA 7.1.7 worked correctly)

Steps to reproduce:
* Connect Sentry to JIRA
* Go to the Issue
* Click on 'Jira - Create New Issue' button
* 'An unknown error occurred.' message appeared

Stacktrace:
```
172.18.0.1 - - [29/May/2017:01:41:40 +0000] "GET /api/0/issues/5726/plugins/jira/link/ HTTP/1.0" 200 598 "https://sentry.unitedtraders.work/unitedtraders/hive/issues/5726/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/bases/issue2.py", line 198, in view_create
    fields = self.get_new_issue_fields(request, group, event, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_plugins/jira/plugin.py", line 207, in get_new_issue_fields
    mb_field = self.build_dynamic_field(group, issue_type_meta['fields'][field])
  File "/usr/local/lib/python2.7/site-packages/sentry_plugins/jira/plugin.py", line 98, in build_dynamic_field
    fkwargs['url'] = '%s?jira_url=%s' % (sentry_url, quote_plus(field_meta.get('autoCompleteUrl')))
  File "/usr/local/lib/python2.7/urllib.py", line 1303, in quote_plus
    if ' ' in s:
TypeError: argument of type 'NoneType' is not iterable
01:41:45 [ERROR] sentry.plugins.jira: argument of type 'NoneType' is not iterable
172.18.0.1 - - [29/May/2017:01:41:43 +0000] "GET /api/0/issues/5726/plugins/jira/create/ HTTP/1.0" 500 305 "https://sentry.unitedtraders.work/unitedtraders/hive/issues/5726/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
```

Sentry connecting to the JIRA successfully, 'Link with Existing Issue' working correctly.

**Comment by mitsuhiko** [comment]
Adding link to forum post about this topic for reference: https://forum.sentry.io/t/jira-issue-creation-is-broken-since-jira-7-3/1660

**Comment by mitsuhiko** [comment]
Closing this here in favour of the one against the integration.
