### ISSUE TITLE
UNIQUE INDEX ON sentry_environment

### ISSUE THREAD

**Issue by arthru** [getsentry/sentry#5502]
When I upgraded to 8.17.0, and while running migrations, I met an error when creating unique index on sentry_environment fields organisation_id and name.
In my cas, I has same environment name for different projects in the same organization, that is why it failed.
But I believe the correct constraint would be on fields organisation_id, name and project_id.

- Sentry version : 8.17.0
- installed with pip/virtualenv
- stacktrace :

```
 > sentry:0321_auto__add_unique_environment_organization_id_name
FATAL ERROR - The following SQL query failed: CREATE UNIQUE INDEX CONCURRENTLY sentry_environment_organization_id_6c9098a3d53d6a9a ON sentry_environment (organization_id, name)
The error was: IntegrityError("ERREUR:  n'a pas pu cr\xc3\xa9er l'index unique \xc2\xab sentry_environment_organization_id_6c9098a3d53d6a9a \xc2\xbb\nDETAIL:  La cl\xc3\xa9 (organization_id, name)=(1, production) est dupliqu\xc3\xa9e.\n",)
SQL: CREATE UNIQUE INDEX CONCURRENTLY sentry_environment_organization_id_6c9098a3d53d6a9a ON sentry_environment (organization_id, name)
Traceback (most recent call last):
  File "/srv/venv/sentry/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/srv/venv/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 160, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/srv/venv/sentry/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/srv/venv/sentry/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/srv/venv/sentry/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/venv/sentry/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/venv/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/venv/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/venv/sentry/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/srv/venv/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/venv/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/venv/sentry/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 60, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/srv/venv/sentry/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 29, in _upgrade
    verbosity=verbosity,
  File "/srv/venv/sentry/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/srv/venv/sentry/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/srv/venv/sentry/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/srv/venv/sentry/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/srv/venv/sentry/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/srv/venv/sentry/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/srv/venv/sentry/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/srv/venv/sentry/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/srv/venv/sentry/lib/python2.7/site-packages/south/migration/migrators.py", line 91, in run_migration
    south.db.db.rollback_transaction()
  File "/srv/venv/sentry/lib/python2.7/site-packages/south/db/generic.py", line 1000, in rollback_transaction
    transaction.leave_transaction_management(using=self.db_alias)
  File "/srv/venv/sentry/lib/python2.7/site-packages/django/db/transaction.py", line 78, in leave_transaction_management
    get_connection(using).leave_transaction_management()
  File "/srv/venv/sentry/lib/python2.7/site-packages/django/db/backends/__init__.py", line 310, in leave_transaction_management
    "This code isn't under transaction management")
django.db.transaction.TransactionManagementError: This code isn't under transaction management

```

**Comment by arthru** [comment]
update : I was using postgresql database

**Comment by ernetas** [comment]
Using official Docker images and PostgreSQL, can replicate.

**Comment by mattrobenolt** [comment]
What versions were you upgrading from? Because there was a previous migration that removed and merged all the dupes.

**Comment by ernetas** [comment]
1.16.1 to 1.17.0. I had also upgraded from 1.16.0 to 1.16.1.

**Comment by JannKleen** [comment]
Same for me

**Comment by arthru** [comment]
In my case, I upgraded from 1.16.0

**Comment by mattrobenolt** [comment]
So, unfortuantely, for the time being, this is the solution: You need to fire up `sentry shell` and run the following to remove the duplicates:

```python
from sentry.models import *

dupe_envs = Environment.objects.values('name', 'organization_id')\
                                           .annotate(ecount=Count('id'))\
                                           .filter(ecount__gt=1)

for env in dupe_envs:
    name = env['name']
    organization_id = env['organization_id']

    envs = list(Environment.objects.filter(
        name=name,
        organization_id=organization_id,
    ).order_by('date_added'))
    to_env = envs[0]
    from_envs = envs[1:]

    try:
        with transaction.atomic():
            EnvironmentProject.objects.filter(
                environment__in=from_envs,
            ).update(environment=to_env)
    except IntegrityError:
        for ep in EnvironmentProject.objects.filter(environment__in=from_envs):
            try:
                with transaction.atomic():
                    EnvironmentProject.objects.filter(
                        id=ep.id,
                    ).update(environment=to_env)
            except IntegrityError:
                ep.delete()

    from_env_ids = [e.id for e in from_envs]
    try:
        with transaction.atomic():
            ReleaseEnvironment.objects.filter(
                environment_id__in=from_env_ids,
            ).update(environment_id=to_env.id)
    except IntegrityError:
        for re in ReleaseEnvironment.objects.filter(environment_id__in=from_env_ids):
            try:
                with transaction.atomic():
                    ReleaseEnvironment.objects.filter(
                        id=re.id,
                    ).update(environment_id=to_env.id)
            except IntegrityError:
                re.delete()

    Environment.objects.filter(id__in=from_env_ids).delete()

dupe_release_envs = ReleaseEnvironment.objects.values(
    'release_id', 'organization_id', 'environment_id'
).annotate(
    recount=Count('id')
).filter(recount__gt=1)

for renv in dupe_release_envs:
    release_id = renv['release_id']
    organization_id = renv['organization_id']
    environment_id = renv['environment_id']
    renvs = list(ReleaseEnvironment.objects.filter(
        release_id=release_id,
        organization_id=organization_id,
        environment_id=environment_id,
    ).order_by('first_seen'))
    to_renv = renvs[0]
    from_renvs = renvs[1:]
    last_seen = max([re.last_seen for re in renvs])
    ReleaseEnvironment.objects.filter(
        id=to_renv.id,
    ).update(last_seen=last_seen)
    ReleaseEnvironment.objects.filter(
        id__in=[re.id for re in from_renvs],
    ).delete()
```

So what's happening here is that there was a migration in a few(?) versions back, migration 0302 that runs this to merge and remove the dupes. But somewhere along the lines, our attempts at preventing new duplicates from entering apparently failed in some cases. So since you ran 0302 already, you have gotten new rows that now violate the constraint.

This code is the same code being run inside 0302 to dedupe them. So it's essentially just running it again. Then migrations will proceed. And beyond this, duplicates can't happen again because of the correct database constraint.

**Comment by ernetas** [comment]
Executed the code above (had to remove some empty lines so it would be pasteable to the shell) and the migration is still failing.

**Comment by mattrobenolt** [comment]
What do you get back from:

```python
from sentry.models import *

dupe_envs = Environment.objects.values('name', 'organization_id')\
                                           .annotate(ecount=Count('id'))\
                                           .filter(ecount__gt=1)

print(dupe_envs)
```

This will tell us exactly which ones are dupes. But I'm really not sure why the script didn't resolve the issue.

**Comment by fuhrysteve** [comment]
I'm also experiencing this issue. I ran the script, and it removed all except one row in `sentry_environment`.  When I ran the above with `print(dupe_envs)`, I got an empty list back `[]`.


Full stack trace:

```bash
$ sentry upgrade
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > crispy_forms
 > debug_toolbar
 > raven.contrib.django.raven_compat
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > sudo
 > south
 > sentry_plugins.slack

Not synced (use migrations):
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
 - sentry_plugins.jira_ac
 - sentry_plugins.hipchat_ac
(use ./manage.py migrate to migrate these)
Running migrations for sentry:
 - Migrating forwards to 0326_auto__add_field_groupsnooze_count__add_field_groupsnooze_window__add_f.
 > sentry:0321_auto__add_unique_environment_organization_id_name
FATAL ERROR - The following SQL query failed: CREATE UNIQUE INDEX CONCURRENTLY sentry_environment_organization_id_6c9098a3d53d6a9a ON sentry_environment (organization_id, name)
The error was: relation "sentry_environment_organization_id_6c9098a3d53d6a9a" already exists

Traceback (most recent call last):
  File "/home/sentry/.virtualenvs/sentry/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 160, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 60, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 29, in _upgrade
    verbosity=verbosity,
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/south/migration/migrators.py", line 91, in run_migration
    south.db.db.rollback_transaction()
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/south/db/generic.py", line 1000, in rollback_transaction
    transaction.leave_transaction_management(using=self.db_alias)
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/django/db/transaction.py", line 78, in leave_transaction_management
    get_connection(using).leave_transaction_management()
  File "/home/sentry/.virtualenvs/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 310, in leave_transaction_management
    "This code isn't under transaction management")
django.db.transaction.TransactionManagementError: This code isn't under transaction management
```

```bash
$ psql sentry
psql (9.4.12)
Type "help" for help.

sentry=> select * from sentry_environment;
 id | project_id | name |          date_added           | organization_id 
----+------------+------+-------------------------------+-----------------
  1 |          8 |      | 2016-08-14 18:06:12.230736-04 |               2
(1 row)
```

```bash
$ sentry shell
from sentry.models import *Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
Type "copyright", "credits" or "license" for more information.

IPython 5.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sentry.models import *

In [2]: dupe_envs = Environment.objects.values('name', 'organization_id')\
   ...:                                            .annotate(ecount=Count('id'))\
   ...:                                            .filter(ecount__gt=1)

In [3]: print(dupe_envs)
[]
```

**Comment by mattrobenolt** [comment]
@fuhrysteve Ah, so now the index has succeeded in being created, and it won't let you recreate it. So I guess now you need to skip this migration and you should be able to continue on.

```
$ sentry django migrate --fake sentry 0321
```

**Comment by ernetas** [comment]
Thanks! I also had an empty list of `dupe_envs`. Skipping the migration fixed the upgrade.

**Comment by Siecje** [comment]
When I try to do
```shell
$ sentry django migrate --fake sentry 0321
```

I have two migrations with that prefix.

```
Traceback (most recent call last):
  File "/home/sentry/venv/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 160, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/sentry/runner/commands/django.py", line 23, in django
    execute_from_command_line(argv=[ctx.command_path] + list(management_args))
  File "/home/sentry/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/sentry/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/sentry/venv/local/lib/python2.7/site-packages/south/migration/__init__.py", line 203, in migrate_app
    target = migrations.guess_migration(target_name)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/south/migration/base.py", line 222, in guess_migration
    return self._guess_migration(prefix=target_name)
  File "/home/sentry/venv/local/lib/python2.7/site-packages/south/migration/base.py", line 212, in _guess_migration
    raise exceptions.MultiplePrefixMatches(prefix, matches)
south.exceptions.MultiplePrefixMatches: Prefix '0321' matches more than one migration:
    sentry:0321_auto__add_field_projectkey_rate_limit_count__add_field_projectkey_rate
    sentry:0321_auto__add_unique_environment_organization_id_name
```

**Comment by mattrobenolt** [comment]
:(

Then do `$ sentry django migrate --fake sentry 0321_auto__add_unique_environment_organization_id_name`

**Comment by ktosiek** [comment]
Just a quick note: the script is not easy to run from `sentry shell`. I'd recommend putting it in a file, and running `sentry exec /path/to/script.py`

**Comment by zehome** [comment]
Be carefull if you tried to upgrade, then removed the "duplicate" environments and skipped the migration because, in PostgreSQL, create index concurrently will try to create the index "in background", which will fail (duplicate entries). So the index will be marked "INVALID".

You NEED to remove the index before re-running the update.
