### ISSUE TITLE
celeryd keeps crashing

### ISSUE THREAD

**Issue by uwemaurer** [getsentry/sentry#577]
sentry celeryd keeps crashing with this error:

Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/celery-3.0.6-py2.7.egg/celery/worker/__init__.py", line 353, in start
    component.start()
  File "/www/sentry/local/lib/python2.7/site-packages/celery-3.0.6-py2.7.egg/celery/worker/consumer.py", line 369, in start
    self.consume_messages()
  File "/www/sentry/local/lib/python2.7/site-packages/celery-3.0.6-py2.7.egg/celery/worker/consumer.py", line 449, in consume_messages
    on_poll_empty()
  File "/www/sentry/local/lib/python2.7/site-packages/kombu-2.4.0-py2.7.egg/kombu/transport/redis.py", line 637, in on_poll_empty
    self.cycle.on_poll_empty()
  File "/www/sentry/local/lib/python2.7/site-packages/kombu-2.4.0-py2.7.egg/kombu/transport/redis.py", line 209, in on_poll_empty
    channel.qos.restore_visible()
  File "/www/sentry/local/lib/python2.7/site-packages/kombu-2.4.0-py2.7.egg/kombu/transport/redis.py", line 102, in restore_visible
    start=start, num=num, withscores=True)
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 1076, in zrevrangebyscore
    return self.execute_command(*pieces, **options)
  File "/www/sentry/local/lib/python2.7/site-packages/kombu-2.4.0-py2.7.egg/kombu/transport/redis.py", line 546, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 347, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 127, in zset_score_pairs
    return list(izip(it, imap(score_cast_func, it)))
ValueError: could not convert string to float: {"body": "gAJ9cQEoVQdy

**Comment by thedrow** [comment]
Can we close this? It ahs been a long time since this was opened and no reply has been received since.

Ping @dcramer
