### ISSUE TITLE
Sentry init client crashes

### ISSUE THREAD

**Issue by pnemonic78** [getsentry/sentry#5772]
- The version of Sentry you're using: 1.2.2
- Include a stacktrace or other logs when relevant:
```
io.sentry.android.event.helper.AndroidEventBuilderHelper: Exception while attempting to read kernel information
java.io.FileNotFoundException: /proc/version (Permission denied)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:200)
at java.io.FileInputStream.(FileInputStream.java:150)
at java.io.FileInputStream.(FileInputStream.java:103)
at java.io.FileReader.(FileReader.java:58)
at io.sentry.android.event.helper.AndroidEventBuilderHelper.getKernelVersion(AndroidEventBuilderHelper.java:331)
at io.sentry.android.event.helper.AndroidEventBuilderHelper.(AndroidEventBuilderHelper.java:43)
at io.sentry.android.AndroidSentryClientFactory.createSentryClient(AndroidSentryClientFactory.java:68)
at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:55)
at io.sentry.Sentry.init(Sentry.java:80)
at MySdk.a(MySdk.java:2035)
at MyContentProvider.onCreate(MyContentProvider.java:21)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1912)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1887)
at android.app.ActivityThread.installProvider(ActivityThread.java:6284)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:5850)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5771)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6540)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by pnemonic78** [comment]
duplicate of https://github.com/getsentry/sentry-java/issues/472
