### ISSUE TITLE
IntegrityError during POST to /auth/login/ emits POST data to the logs

### ISSUE THREAD

**Issue by mdaniel** [getsentry/sentry#5933]
# Details

* Version: [sentry:8.18.0](https://hub.docker.com/r/library/sentry/tags/)
* Docker image, with the following two pip-installed plugins:
  * `pip install 'git+https://github.com/banno/getsentry-ldap-auth.git#2.1'`
  * `pip install sentry-plugins==8.18.0`
* Please find the very lightly redacted traceback below

# Behavior

As seen in the traceback, an error during login prints the user's password in the logs (_which in many circumstances is then indexed into a centralized log store where many actors can search at will_)

# Expected Behavior

That the same mechanism used to filter POST data for Sentry events would filter sensitive fields from the logger -- or, if that's too heavy handed, then perhaps a specialized try-except for POSTs to `/auth/login/`

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 187, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_organization_login.py", line 132, in handle
    response = self.handle_basic_auth(request, organization)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_organization_login.py", line 66, in handle_basic_auth
    elif login_form.is_valid():
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/usr/local/lib/python2.7/site-packages/sentry/web/forms/accounts.py", line 139, in clean
    password=password)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 172, in authenticate
    user = ldap_user.authenticate(password)
  File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 347, in authenticate
    self._get_or_create_user()
  File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 571, in _get_or_create_user
    self._user, created = self.backend.get_or_create_user(username, self)
  File "/usr/local/lib/python2.7/site-packages/sentry_ldap_auth/backend.py", line 42, in get_or_create_user
    userEmail.save()
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 510, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/sql/compiler.py", line 980, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 39, in execute
    return self.cursor.execute(sql, params)
IntegrityError: IntegrityError('duplicate key value violates unique constraint "sentry_useremail_user_id_469ffbb142507df2_uniq"\nDETAIL:  Key (user_id, email)=(19, someone@example.com) already exists.\n',)
SQL: UPDATE "sentry_useremail" SET "user_id" = %s, "email" = %s, "validation_hash" = %s, "date_hash_added" = %s, "is_verified" = %s WHERE "sentry_useremail"."id" = %s
21:28:20 [ERROR] django.request: Internal Server Error: /auth/login/SC/ (status_code=500 request=<WSGIRequest
path:/auth/login/SC/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'username': [u'someone@example.com'], u'csrfmiddlewaretoken': [u'alphabetacharlie'], u'password': [u'hunter22'], u'op': [u'login']}>,
```

**Comment by mattrobenolt** [comment]
> hunter22

But yeah, this isn't good. @JTCunning can we apply this as a filter in our logger stuff? I assume we can easily write our own parser for `WSGIRequest` objects somehow.

**Comment by mdaniel** [comment]
Thank you so much for actioning this so quickly!
