### ISSUE TITLE
NoClassDefFoundError java.nio.file.Path

### ISSUE THREAD

**Issue by jrjohnson1231** [getsentry/sentry#5939]
Sentry Android Version: 1.5.0

When I call `Sentry.capture("This is a test");` I get the following error and stacktrace:

```

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Path;
                                                                            at io.sentry.marshaller.json.SentryJsonGenerator.writeObject(SentryJsonGenerator.java:75)
                                                                            at io.sentry.marshaller.json.SentryJsonGenerator.writeObject(SentryJsonGenerator.java:60)
                                                                            at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1662)
                                                                            at io.sentry.marshaller.json.JsonMarshaller.writeContexts(JsonMarshaller.java:317)
                                                                            at io.sentry.marshaller.json.JsonMarshaller.writeContent(JsonMarshaller.java:195)
                                                                            at io.sentry.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:157)
                                                                            at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:155)
                                                                            at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71)
                                                                            at io.sentry.connection.BufferedConnection.send(BufferedConnection.java:102)
                                                                            at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)

```

Possibly relevant configuration
```
    compileSdkVersion 25
    buildToolsVersion '26'
    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 25
    }
```
Is their something wrong with my Android configuration that is causing this to fail?

**Comment by bretthoerner** [comment]
Hey @jrjohnson1231, thanks for the report. I've moved this issue over to the `sentry-java` repo and I'll handle it right now: https://github.com/getsentry/sentry-java/issues/493
