### ISSUE TITLE
AggregateError error message is ignored during processing

### ISSUE THREAD

**Issue by kamilogorek** [getsentry/sentry#62299]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/browser

### SDK Version

7.91.0

### Steps to Reproduce

```js
function foo () {
  const rejections = [new Error('Message 1'), new Error('Message 2'), new Error('Message 3')]
  throw new AggregateError(rejections, 'wat')
}

try {
  foo()
} catch(e) {
  Sentry.captureException(e)
}
```

### Expected Result

When creating a new `AggregateError` instance, it accepts an optional 2nd argument, which should be used as the error message per https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-aggregate-error

Currently `LinkedErrors` will ignore that property and use the message from the first child instead.
In the case above, `wat` should be the message for the root error.

### Actual Result

First child error is used as the source of the message.

![image](https://github.com/getsentry/sentry-javascript/assets/1523305/18a62a8e-df98-452f-a4fc-b7ff2aab8b85)

**Comment by jjbayer** [comment]
This seems to happen because the `main_exception_id` is set, which should only happen if there's only one distinct exception in the group:

https://github.com/getsentry/sentry/blob/24f4a83ca31a70bc396a5f5311fe5b8cde20cd1b/src/sentry/grouping/strategies/newstyle.py#L813-L819

There might be a bug in the logic that identifies the main exception.

**Comment by lforst** [comment]
@jjbayer Dayum that could be it! Thanks for the investigation!

**Comment by lforst** [comment]
One thing though... the SDK doesn't set that. Does Sentry default to setting it to 1?

**Comment by jjbayer** [comment]
> the SDK doesn't set that. Does Sentry default to setting it to 1?

It's a server-side helper flag that only ever gets set in the code i linked above, IIUC. If the flag is not set, we default to the last exception:

https://github.com/getsentry/sentry/blob/e01885215ff1a5b4e0da3046b4d929398a946360/src/sentry/eventtypes/error.py#L36-L40

**Comment by malwilley** [comment]
Thanks everyone for the help debugging! I'll add this to our backlog and notify the people working on grouping improvements so they can prioritize as needed.

**Comment by lobsterkatie** [comment]
This is related to, but not the same as, https://github.com/getsentry/sentry/issues/59679 and, more generally, https://github.com/getsentry/sentry/issues/64088. In those cases, we have chained errors rather than aggregate errors, and the problem is that we've been labeling linked errors as aggregate errors, and the main/top error has therefore been getting ignored. https://github.com/getsentry/sentry-javascript/pull/10850 fixes that, but only just got merged and hasn't yet been released.

And @jjbayer, yeah, all of the above matches what I found [here](https://github.com/getsentry/sentry/issues/59679#issuecomment-1815286406). It also matches what's in [the RFC](https://github.com/getsentry/rfcs/blob/main/text/0079-exception-groups.md#issue-titles). So I think this is indeed a backend fix, rather than an SDK fix as the above was.

From your comment above:

> This seems to happen because the `main_exception_id` is set, which should only happen if there's only one distinct exception in the group
> There might be a bug in the logic that identifies the main exception.

I'm not sure it's a bug - it seems to match the RFC - but I do think the approach makes some assumptions which are backfiring here. Specifically, @kamilogorek (BTW, hey, Kamil! 🙂), in your example above, were your three child errors separate events, they'd all fall into the same group (matching stacktraces), which then makes them count as only a single distinct exception... which in turn lets us ignore the root error. The only way we'd not ignore the root is if we couldn't collapse all the child exceptions into one, at which point it's sort of like, _ugh, I guess we have to use the root, 'cause we can't decide between the kids..._ - the backfiring assumption being that the root isn't useful and we should only consider it when we have no other choice. (The full logic, from which Joris quoted above, is [here](https://github.com/getsentry/sentry/blob/d8d248d2188c96f56074db22da1bf2112fc2587e/src/sentry/grouping/strategies/newstyle.py#L775-L831).)

Now, in some cases, that's a perfectly reasonable assumption. Run the following and you will indeed get a root error worth ignoring:

```js
await Promise.any(
  [1, 2, 3].map((num) => {
    return Promise.reject(new Error(`Rejected promise #${num}`));
  })
);
```

which results in

```
AggregateError: All promises were rejected {
  [errors]: [
    Error: Rejected promise #1
        at index.js:5:31
        at Array.map (<anonymous>)
        at ...
    Error: Rejected promise #2
        at index.js:5:31
        at Array.map (<anonymous>)
        at ...
    Error: Rejected promise #3
        at index.js:5:31
        at Array.map (<anonymous>)
        at ...
  ]
}
```

The question is, how do we tell the difference between that and one where ignoring the root is the wrong choice? And how common is the second situation? I'm not sure I know the answer to either question, especially a platform-independent answer. Kamil, or anyone else, thoughts on that?

**Comment by kamilogorek** [comment]
> in your example above, were your three child errors separate events, they'd all fall into the same group (matching stacktraces), which then makes them count as only a single distinct exception...

In this specific example yes, but imagine something like this:

```ts
async function deleteIntegration(integration) {
  await runTransaction(integration, [
    cleanupConnections,
    removeAuthorization,
    notifyUser,
  ])
}

const deleteIntegrationResults = await Promise.allSettled(
  integrations.map(async (integration) => deleteIntegration(integration))
)

const deleteIntegrationRejections = deleteIntegrationResults
  .filter(isRejected)
  .map((r) => r.reason)

if (deleteIntegrationRejections.length) {
  Sentry.captureException(new AggregateError(deleteIntegrationRejections, `Failed to delete integrations ${integration.id} for user ${user.id}`))
}
```

It can break on any of 3 operations inside the transaction, and those should _not_ be grouped together.
Tbh I don't know the answer myself either from the top of my head.

Hey 👋

**Comment by lobsterkatie** [comment]
Hmmm, yeah. That's a perfectly valid use case, and you're right that we don't handle it. 

As a workaround for specific errors, I think it should work to use the project-level [fingerprint rules](https://docs.sentry.io/product/data-management-settings/event-grouping/fingerprint-rules/) to both fix the grouping and [give it the right title](https://docs.sentry.io/product/data-management-settings/event-grouping/fingerprint-rules/#custom-titles). So, for your example above, it'd be 

```
message:"Failed to delete integrations * for user *" -> {{ message }} title="{{ message }}"
```

(Or you could do `... -> {{ default }} title="{{ message }}` if you're happy with the grouping and only want to fix the title.)

That said, doing it that way could get to be a pain if you've got lots of different errors like this, plus most users have no idea it's even an option. 

A(slightly) better way would be for our backend to recognize a new `this_is_a_meaningful_aggregate_error_so_please_actually_use_it_when_grouping_and_titling_the_issue` flag, which one could set as capture context directly in the `captureException` call. (We'd obviously think of a better name.) So you'd do

```js
Sentry.captureException(
  new AggregateError(
    deleteIntegrationRejections,
    `Failed to delete integrations ${integration.id} for user ${user.id}`
  ),
  {
    mechanism: {
      this_is_a_meaningful_aggregate_error_so_please_actually_use_it_when_grouping_and_titling_the_issue: true,
    },
  }
);
```

Even better would be for the SDK to recognize a manual call to `captureException` with an instance of `AggregateError` having a non-empty message and set the flag for you. (There was talk of making the SDK able to distinguish between manual and internal `captureException` calls (I actually played around with it a bit shortly before I got transferred), but IDK if that ever happened.)

Anyway, for now I think the fingerprint rules are your best bet.

**Comment by moonray** [comment]
I'm trying to decipher what's going on with this issue.
Can someone TL;DR?

I'm trying to figure out if displaying AggregateError's sub-errors requires some config (I would appreciate a link to the relevant docs), or if it's something that still needs dev work.

**Comment by lforst** [comment]
@moonray it doesn't require any config. This issue is about the message that is being rendered in Sentry alongside the issue.

**Comment by mogelbrod** [comment]
I also encountered this bug just now, which unfortunately makes using AggregateErrors significantly less useful 🙁  Happy to provide more info/feedback if requested!

**Comment by lobsterkatie** [comment]
@mogelbrod - I'm curious: Is the `AggregateError` in question one that you're capturing manually using `captureException`, or one being automatically caught by the SDK? 

The reason I ask is that if it's the former, it might not take any SDK changes to introduce a (better-named) `this_is_a_meaningful_aggregate_error_so_please_actually_use_it_when_grouping_and_titling_the_issue` flag that the server could be taught to recognize and handle appropriately. It's been a few years since I worked on the SDK, so @lforst , correct me if I'm wrong, but I don't think manually-set `mechanism` data would get overwritten, would it? (I think I might have even been the one to write the code to safely merge `mechanism` data, but IDK if anything's been changed since then.)

**Comment by mogelbrod** [comment]
> [@mogelbrod](https://github.com/mogelbrod) - I'm curious: Is the `AggregateError` in question one that you're capturing manually using `captureException`, or one being automatically caught by the SDK?

It is indeed a `AggregateError instantiated via our own code that is then manually reported via `Sentry.captureException()`. The context is that we're building a diagnostics feature into our app where users can run a bunch of checks, and we'd like to collect all errors in this diagnostics report for a single user into a single sentry error event. `AggregateError` felt like a great fit, although we're open to any solution (workaround or not), as long as it results in a single error report that includes all errors.

**Comment by lobsterkatie** [comment]
These checks you're trying to collect into a single sentry event - are they related in any way besides that they're being run as part of a series of checks for that user? And is this a Sentry event that they'd look at our that you'd look at?

My concern is that unless I'm understanding your use case incorrectly, it's using Sentry in a way it's not designed to be used, and while you're certainly _allowed_ to do that, I suspect it's going to lead to some unexpected and potentially-not-really-what-you-want product side effects.

Would you mind giving me a hypothetical concrete example of what you're talking about?

**Comment by mogelbrod** [comment]
> These checks you're trying to collect into a single sentry event - are they related in any way besides that they're being run as part of a series of checks for that user? And is this a Sentry event that they'd look at our that you'd look at?
>
> My concern is that unless I'm understanding your use case incorrectly, it's using Sentry in a way it's not designed to be used, and while you're certainly _allowed_ to do that, I suspect it's going to lead to some unexpected and potentially-not-really-what-you-want product side effects.
> 
> Would you mind giving me a hypothetical concrete example of what you're talking about?

Sure thing! We regularly get support tickets from customers who can't use our service for various reasons. Oftentimes this is due to restrictive firewalls, aggressive adblockers, or ISP DNS issues. The checks in questions make a bunch of requests to various endpoints and collects the results. The reason for using `AggregateError` is to allow us to also report the original errors thrown by the browser in case they can provide additional clues. For us to be able to properly help the customer we typically also need the IP, geolocation, browser, OS, etc. which our customer support then has to ask for and forward to our dev team. As Sentry already collects this automatically in error reports we figured we could skip the customer support step and instead report everything directly in Sentry. Does that make sense?

**Comment by lforst** [comment]
I think AggregateError is probably even a good medium for the diagnostics feature you're describing. HOWEVER, as @lobsterkatie already mentioned, it is not really what Sentry was designed around.

What I would do is report the errors individually (maybe tagged by user or something similar) instead of aggregating them via `AggregateError`. Then I would build a dashboard in Sentry that groups the errors by the user.

**Comment by mogelbrod** [comment]
I tried reporting a sub-classed version of `AggregateError` to Sentry and now it looks like the correct `message` is shown in the UI 🎉  This might be usable as a temporary workaround for others that manually create these errors.
```ts
export class ConnectivityReportError extends AggregateError {
  constructor(report: ConnectivityReport) {
    super(errors, 'My custom message')
  }
}
```

<img width="734" alt="Image" src="https://github.com/user-attachments/assets/f1e94881-536a-4d6a-b384-1a9f91e221aa" />

> [@mogelbrod](https://github.com/mogelbrod) I think AggregateError is probably even a good medium for the diagnostics feature you're describing. HOWEVER, as [@lobsterkatie](https://github.com/lobsterkatie) already mentioned, it is not really what Sentry was designed around.
>
> What I would do is report the errors individually (maybe tagged by user or something similar) instead of aggregating them via `AggregateError`. Then I would build a dashboard in Sentry that groups the errors by the user.

I definitely agree that this is somewhat of an hack, but we figured it'd be an interesting experiment that's quick to try and iterate on 😄 

The primary reason for collecting all errors into a single sentry event is that it enables us to treat the sentry event id as an unique identifier passed between customer and support. Our customer may or may not be logged in when the diagnostics are being run (the suite is available outside of the primary application), so having an easily communicated ID makes it much easier to quickly find the relevant event(s) in sentry.

BTW I really appreciate the quick turn-around time and feedback from both of you!

**Comment by lobsterkatie** [comment]
Glad you got it working! Your reasoning makes sense, I'd just watch out for odd side effects with things like auto assignment and suspect commits. But if what you're doing works for now, great. 🙂
