### ISSUE TITLE
IOException: Cannot run program: error=2, No such file or directory

### ISSUE THREAD

**Issue by valeriyo** [getsentry/sentry#62563]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Getting this error with latest (plugin 4.1.1  and library 7.1.0) on Mac:

```
A problem occurred starting process 'command '/var/folders/7g/xj1p0_gs45d8wnd_nxn9wrv40000gn/T/.sentry-cli4102292845813930247.exe''
> Could not start '/var/folders/7g/xj1p0_gs45d8wnd_nxn9wrv40000gn/T/.sentry-cli4102292845813930247.exe'

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/var/folders/7g/xj1p0_gs45d8wnd_nxn9wrv40000gn/T/.sentry-cli4102292845813930247.exe''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:386)
	at org.gradle.process.internal.ExecHandleRunner.lambda$run$3(ExecHandleRunner.java:102)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:101)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/var/folders/7g/xj1p0_gs45d8wnd_nxn9wrv40000gn/T/.sentry-cli4102292845813930247.exe'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:122)
	at org.gradle.process.internal.ExecHandleRunner.lambda$run$0(ExecHandleRunner.java:80)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:79)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/var/folders/7g/xj1p0_gs45d8wnd_nxn9wrv40000gn/T/.sentry-cli4102292845813930247.exe" (in directory "/Users/blah/Projects/here-android"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	... 8 more

BUILD FAILED in 76ms
``` 

### Expected Result

not fail my builds

### Actual Result

sentry fails my build

### Product Area

Unknown

**Comment by valeriyo** [comment]
Downgraded to 3.14.0

**Comment by hubertdeng123** [comment]
Which Sentry plugin are you using? I can transfer this over to that repository.

**Comment by valeriyo** [comment]
I think this issue should go into https://github.com/getsentry/sentry-android-gradle-plugin/issues
