### ISSUE TITLE
Problem after Upgrade sentry from 8.17 to 8.21

### ISSUE THREAD

**Issue by amiri27** [getsentry/sentry#6397]
Hi,

I just updated sentry from 8.17 to 8.21 But I see this error after running upgrade command.. How can I solve this error..

```
postgres_1   | ERROR:  duplicate key value violates unique constraint "sentry_eventuser_project_id_1a96e3b719e55f9a_uniq"
postgres_1   | DETAIL:  Key (project_id, hash)=(1, 31c2d7515f3704099aae274b35e0a696) already exists.
postgres_1   | STATEMENT:  INSERT INTO "sentry_eventuser" ("project_id", "hash", "ident", "email", "username", "name", "ip_address", "date_added") VALUES (1, '31c2d7515f3704099aae274b35e0a696', NULL, NULL, NULL, NULL, '84.241.1.251', '2017-10-21 20:56:11.963637+00:00') RETURNING "sentry_eventuser"."id"
postgres_1   | ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
postgres_1   | DETAIL:  Key (project_id, environment_id)=(1, 3) already exists.
postgres_1   | STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id") VALUES (1, 3) RETURNING "sentry_environmentproject"."id"
web_1        | 84.241.1.251 - - [21/Oct/2017:20:56:10 +0000] "GET /auth/login/sentry/ HTTP/1.1" 500 9171 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
web_1        | 84.241.1.251 - - [21/Oct/2017:20:56:12 +0000] "GET /_static/1508619359/sentry/dist/sentry.css HTTP/1.1" 200 64059 "http://91.239.55.195:9000/auth/login/sentry/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
postgres_1   | ERROR:  duplicate key value violates unique constraint "sentry_featureadoption_organization_id_78451b8747a9e638_uniq"
postgres_1   | DETAIL:  Key (organization_id, feature_id)=(1, 0) already exists.
postgres_1   | STATEMENT:  INSERT INTO "sentry_featureadoption" ("organization_id", "feature_id", "date_completed", "complete", "applicable", "data") VALUES (1, 0, '2017-10-21 20:56:12.234890+00:00', true, true, '{}'), (1, 48, '2017-10-21 20:56:12.235218+00:00', true, true, '{}'), (1, 42, '2017-10-21 20:56:12.235333+00:00', true, true, '{}')
```

I also did reindex but there's no chance also..

```
REINDEX SYSTEM sentry;
REINDEX DATABASE sentry;
VACUUM (FULL, ANALYZE);
```

Please help us to solve this problem..

Regards,

**Comment by mattrobenolt** [comment]
Those Postgres logs are all fine. What’s the actual problem you’re having?

**Comment by mattrobenolt** [comment]
To be specific, I need an application stack trace. The Postgres logs don’t mean much.

**Comment by amiri27** [comment]
Hi,

I got these errors when I tried to update sentry from version 8.17 to 8.21.. I see these errors on output when I tried to run docker machines with docker-compose up --build command.. How can I get the stack trace?

Regards,

**Comment by amiri27** [comment]
Maybe these could help:

```
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
web_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
web_1        |     return self.dispatch(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
web_1        |     return view_func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 194, in dispatch
web_1        |     return self.handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/react_page.py", line 47, in handle
web_1        |     return self.handle_react(request)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/react_page.py", line 30, in handle_react
web_1        |     template = loader.render_to_string('sentry/bases/react.html', context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
web_1        |     return t.render(Context(dictionary))
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
web_1        |     return self._render(context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 85, in instrumented_test_render
web_1        |     return self.nodelist.render(context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
web_1        |     bit = self.render_node(node, context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
web_1        |     return node.render(context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
web_1        |     return compiled_parent._render(context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 85, in instrumented_test_render
web_1        |     return self.nodelist.render(context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
web_1        |     bit = self.render_node(node, context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
web_1        |     return node.render(context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
web_1        |     result = block.nodelist.render(context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
web_1        |     bit = self.render_node(node, context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
web_1        |     return node.render(context)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
web_1        |     return func(*resolved_args, **resolved_kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/templatetags/sentry_react.py", line 131, in get_react_config
web_1        |     'user': serialize(user, user),
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 17, in serialize
web_1        |     return serialize([objects], user=user, serializer=serializer, *args, **kwargs)[0]
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 42, in serialize
web_1        |     return [serializer(o, attrs=attrs.get(o, {}), user=user, *args, **kwargs) for o in objects]
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 57, in __call__
web_1        |     return self.serialize(obj, attrs, user, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/user.py", line 125, in serialize
web_1        |     } for i in attrs['identities']
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/models/authprovider.py", line 47, in get_provider
web_1        |     return manager.get(self.provider, **self.config)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/auth/manager.py", line 23, in get
web_1        |     raise ProviderNotRegistered(key)
web_1        | ProviderNotRegistered: github
web_1        | 06:52:17 [ERROR] django.request: Internal Server Error: /sentry/ (status_code=500 request=<WSGIRequest: GET u'/sentry/'>)
postgres_1   | ERROR:  duplicate key value violates unique constraint "sentry_eventuser_project_id_1a96e3b719e55f9a_uniq"
postgres_1   | DETAIL:  Key (project_id, hash)=(1, 45c48cce2e2d7fbdea1afc51c7c6ad26) already exists.
postgres_1   | STATEMENT:  INSERT INTO "sentry_eventuser" ("project_id", "hash", "ident", "email", "username", "name", "ip_address", "date_added") VALUES (1, '45c48cce2e2d7fbdea1afc51c7c6ad26', '9', 'm.amiri@zarinpal.com', '4629848ef22a4fca8187a283dd5f4db3', NULL, '84.241.1.251', '2017-10-22 06:52:17.492238+00:00') RETURNING "sentry_eventuser"."id"
postgres_1   | ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
postgres_1   | DETAIL:  Key (project_id, environment_id)=(1, 3) already exists.
postgres_1   | STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id") VALUES (1, 3) RETURNING "sentry_environmentproject"."id"
```

We have multiple logs inside sentry and multiple systems demands on sentry.. Can you please help us to solve this problem asap?!

Regards

**Comment by amiri27** [comment]
I solved the problem by re-adding Github provider to Dockerfile..

Regards,
