### ISSUE TITLE
KeyError: 'ingest-replay-recordings' when running ingest-replay-recordings consumer

### ISSUE THREAD

**Issue by actuallyKasi** [getsentry/sentry#64033]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Using 23.12.1 image of sentry and trying out `sentry run consumer` command.
```
sentry run consumer ingest-replay-recordings --consumer-group ingest-replay-recordings-staging --topic sentry.staging.ingest-replay-recordings
```

### Expected Result

Consumer should have started

### Actual Result

```
1000@sentry-ingest-consumer-transactions-84844b999f:/$ sentry run consumer ingest-replay-recordings --consumer-group ingest-replay-recordings-staging --topic sentry.staging.ingest-replay-recordings
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/sentry/runner/__init__.py", line 195, in main
    func(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/runner/commands/run.py", line 601, in basic_consumer
    processor = get_stream_processor(consumer_name, consumer_args, topic=topic, **options)
  File "/usr/local/lib/python3.10/site-packages/sentry/consumers/__init__.py", line 347, in get_stream_processor
    topic_def = settings.KAFKA_TOPICS[logical_topic]
KeyError: 'ingest-replay-recordings'

1000@sentry-ingest-consumer-transactions-84844b999f:/$ sentry --version
sentry, version 23.12.1+unknown


```

### Product Area

Replays

**Comment by actuallyKasi** [comment]
Key `ingest-replay-recordings` already exists here

**Comment by m0nikasingh** [comment]
It seems you are missing KAFKA_CONSUMERS[ingest-replay-recordings] mapping.
This can be fixed by updating KAFKA_TOPICS array with KAFKA_INGEST_REPLAYS_RECORDINGS.

Please note that the env variable is REPLAYS - `KAFKA_INGEST_REPLAYS_RECORDINGS`
