### ISSUE TITLE
Sentry - Celery can't save to mysql - SAVEPOINT does not exist

### ISSUE THREAD

**Issue by hifiveszu** [getsentry/sentry#6520]
My Sentry can't save event detail

sentry celery log following:
```
Traceback (most recent call last):
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/sentry/tasks/store.py", line 292, in save_event
    manager.save(project)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/sentry/event_manager.py", line 686, in save
    event.save()
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 902, in execute_sql
    for sql, params in self.as_sql():
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 860, in as_sql
    for obj in self.query.objs
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 350, in get_db_prep_save
    prepared=False)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 342, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/sentry/db/models/fields/node.py", line 161, in get_prep_value
    value.id = nodestore.create(value.data)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/sentry/utils/services.py", line 76, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/sentry/nodestore/base.py", line 31, in create
    self.set(node_id, data)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/sentry/nodestore/django/backend.py", line 43, in set
    'timestamp': timezone.now(),
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/sentry/db/models/query.py", line 96, in create_or_update
    return objects.create(**create_kwargs), True
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/transaction.py", line 303, in __exit__
    connection.savepoint_commit(sid)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/backends/__init__.py", line 256, in savepoint_commit
    self._savepoint_commit(sid)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/backends/__init__.py", line 210, in _savepoint_commit
    self.cursor().execute(self.ops.savepoint_commit_sql(sid))
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 51, in execute
    return self.cursor.execute(sql)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/push/.virtualenv/iportal_sentry/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1305, 'SAVEPOINT s140508592924480_x1 does not exist')
12:14:10 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[bed7dc31-afd7-48cb-a725-dac860058b48] raised unexpected: OperationalError(1305, 'SAVEPOINT s140508592924480_x1 does not exist') (data={u'hostname': 'celery@nfjd-*-*-*.*.com', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'event_id': '1fe5cfc76e174e40b43863109fe91406', 'start_time': 1510056850.21424, 'cache_key': 'e:1fe5cfc76e174e40b43863109fe91406:1', 'data': None}", u'id': 'bed7dc31-afd7-48cb-a725-dac860058b48'})
```

Savepoint name is different for every call. 

Any advice would be greatly appreciated : )

**Comment by mattrobenolt** [comment]
I honestly have no idea and we don’t officially support running Sentry on MySQL, unfortunately. If there’s something we can fix here, feel free to send a patch. My hunch is this is something on your side though since we do run tests against MySQL.
