### ISSUE TITLE
Can't find resource when using Sentry JAR on Android

### ISSUE THREAD

**Issue by davkutalek** [getsentry/sentry#6543]
I am building an Android Library which depends on Sentry. For my debug build I downloaded the JAR files for Sentry and Sentry Android (plus slf4j and jackson-core) and include them in my build so that I don't have to put transitive dependencies in my apps. This was working fine until I upgraded to Android Studio 3.0, now I get the following runtime exception when calling `Sentry.init()`:

```
java.lang.ExceptionInInitializerError
      at io.sentry.connection.AbstractConnection.<init>(AbstractConnection.java:44)
      at io.sentry.connection.HttpConnection.<init>(HttpConnection.java:86)
      at io.sentry.DefaultSentryClientFactory.createHttpConnection(DefaultSentryClientFactory.java:419)
      at io.sentry.DefaultSentryClientFactory.createConnection(DefaultSentryClientFactory.java:322)
      at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:235)
      at io.sentry.android.AndroidSentryClientFactory.createSentryClient(AndroidSentryClientFactory.java:75)
      at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64)
      at io.sentry.Sentry.init(Sentry.java:81)
      at com.hover.sdk.utils.Utils.addSentry(Utils.java:148)
      at com.hover.sdk.onboarding.HoverIntegrationActivity.onCreate(HoverIntegrationActivity.java:58)
      at android.app.Activity.performCreate(Activity.java:6251)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
      at android.app.ActivityThread.-wrap11(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5452)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
Caused by: java.util.MissingResourceException: Can't find resource for bundle 'sentry-build_en_US', key ''
      at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
      at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
      at java.util.ResourceBundle.getBundle(ResourceBundle.java:139)
      at io.sentry.environment.SentryEnvironment.<clinit>(SentryEnvironment.java:23)
      at io.sentry.connection.AbstractConnection.<init>(AbstractConnection.java:44) 
      at io.sentry.connection.HttpConnection.<init>(HttpConnection.java:86) 
      at io.sentry.DefaultSentryClientFactory.createHttpConnection(DefaultSentryClientFactory.java:419) 
      at io.sentry.DefaultSentryClientFactory.createConnection(DefaultSentryClientFactory.java:322) 
      at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:235) 
      at io.sentry.android.AndroidSentryClientFactory.createSentryClient(AndroidSentryClientFactory.java:75) 
      at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64) 
      at io.sentry.Sentry.init(Sentry.java:81) 
      at com.hover.sdk.utils.Utils.addSentry(Utils.java:148) 
      at com.hover.sdk.onboarding.HoverIntegrationActivity.onCreate(HoverIntegrationActivity.java:58) 
      at android.app.Activity.performCreate(Activity.java:6251) 
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370) 
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477) 
      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.app.ActivityThread.main(ActivityThread.java:5452) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652) 
 
```

This happens with Sentry 1.3.0 and 1.6.3.

**Comment by MaxBittker** [comment]
hi @davkutalek this repository is for the sentry server + web application, would you mind posting your question on the [sentry java repository](https://github.com/getsentry/sentry-java/) , or, if you have questions about installations but it's not necessarily a bug, the forums or sentry support? https://forum.sentry.io/
