### ISSUE TITLE
Error migrating to 8.22: ValueError: Cannot find a FOREIGN KEY constraint on table sentry_eventuser, column project_id

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry#6572]
I got this error trying to migrate to 8.22 from 8.20. What's strange is that it worked OK on a staging instance.

The thing that broke is:
0353_auto__del_field_eventuser_project__add_field_eventuser_project_id__del.py

I remember a similar issue a long time ago, but I can't find it. The DB is MySQL ...

```
$ sentry upgrade
04:45:56 [INFO] sentry.plugins.github: apps-not-configured
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > crispy_forms
 > debug_toolbar
 > raven.contrib.django.raven_compat
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > sudo
 > south
 > sentry_plugins.slack

Not synced (use migrations):
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
 - sentry_plugins.jira_ac
 - sentry_plugins.hipchat_ac
(use ./manage.py migrate to migrate these)
Running migrations for sentry:
 - Migrating forwards to 0364_backfill_grouplink_from_groupcommitresolution.
 > sentry:0352_add_index_release_coalesce_date_released_date_added
 > sentry:0353_auto__del_field_eventuser_project__add_field_eventuser_project_id__del
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: sentry:0353_auto__del_field_eventuser_project__add_field_eventuser_project_id__del
Traceback (most recent call last):
  File "/opt/sentry/venv/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/opt/sentry/venv/lib/python2.7/site-packages/sentry/runner/__init__.py", line 161, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/opt/sentry/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/sentry/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/sentry/venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/sentry/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/sentry/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/sentry/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/sentry/venv/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/opt/sentry/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/sentry/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/sentry/venv/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 67, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/opt/sentry/venv/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 29, in _upgrade
    verbosity=verbosity,
  File "/opt/sentry/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/opt/sentry/venv/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/management/commands/migrate.py", line 115, in handle
    ignore_ghosts=ignore_ghosts,
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/migration/__init__.py", line 234, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 341, in migrate_many
    result = self.migrate(migration, database)
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 132, in migrate
    result = self.run(migration, database)
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 291, in run
    return super(Forwards, self).run(migration, database)
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 85, in run_migration
    migration_function()
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 61, in <lambda>
    return (lambda: direction(orm))
  File "/opt/sentry/venv/lib/python2.7/site-packages/sentry/south_migrations/0353_auto__del_field_eventuser_project__add_field_eventuser_project_id__del.py", line 13, in forwards
    db.delete_foreign_key('sentry_eventuser', 'project_id')
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/db/generic.py", line 49, in _cache_clear
    return func(self, table, *args, **opts)
  File "/opt/sentry/venv/lib/python2.7/site-packages/south/db/generic.py", line 820, in delete_foreign_key
    (table_name, column))
ValueError: Cannot find a FOREIGN KEY constraint on table sentry_eventuser, column project_id
(venv)sentry@sentryweb-2-001.shared.live.las1:/opt/sentry 
```

**Comment by Siecje** [comment]
I know that only Postgres is supported and that MySQL was just still working.

**Comment by mattrobenolt** [comment]
@bsergean I honestly don't know. :( I don't use MySQL. All that I can think is maybe you manually deleted this constraint before? Can you potentially just add it manually so it can be removed and migration continue?

**Comment by bsergean** [comment]
(I really want us to get to postgres but it's not that easy)

Sure I can try to add this constraint. Do you know what the syntax would be to do so ?

```
ValueError: Cannot find a FOREIGN KEY constraint on table sentry_eventuser, column project_id`
```

The error message doesn't tell me everything. Here's the MySQL ref on adding a contraint:

```
ALTER TABLE tbl_name
    ADD [CONSTRAINT [symbol]] FOREIGN KEY
    [index_name] (index_col_name, ...)
    REFERENCES tbl_name (index_col_name,...)
    [ON DELETE reference_option]
    [ON UPDATE reference_option]
```

**Comment by mattrobenolt** [comment]
Sorry, I literally haven't used MySQL in at least 8 years. I am assuming anyone who is running MySQL probably would have a better idea than me. :)

But based on your ref, probably like:

`ALTER TABLE sentry_eventuser ADD FOREIGN KEY sentry_eventuser_project_id_fk (project_id) REFERENCES sentry_project (project_id);`

Maybe? I'm just guessing here.

**Comment by bsergean** [comment]
This is what my 2 tables look like. I can't find a project_id on the sentry_project table.

```
mysql> describe sentry_eventuser;
+------------+--------------+------+-----+---------+-------+
| Field      | Type         | Null | Key | Default | Extra |
+------------+--------------+------+-----+---------+-------+
| id         | bigint(20)   | NO   |     | 0       |       |
| project_id | bigint(20)   | NO   |     | NULL    |       |
| ident      | varchar(128) | YES  |     | NULL    |       |
| email      | varchar(75)  | YES  |     | NULL    |       |
| username   | varchar(128) | YES  |     | NULL    |       |
| ip_address | char(39)     | YES  |     | NULL    |       |
| date_added | datetime     | NO   |     | NULL    |       |
| hash       | varchar(32)  | NO   |     | NULL    |       |
| name       | varchar(128) | YES  |     | NULL    |       |
+------------+--------------+------+-----+---------+-------+
9 rows in set (0.01 sec)

mysql> describe sentry_project;
+-----------------+------------------+------+-----+---------+----------------+
| Field           | Type             | Null | Key | Default | Extra          |
+-----------------+------------------+------+-----+---------+----------------+
| id              | bigint(20)       | NO   | PRI | NULL    | auto_increment |
| name            | varchar(200)     | NO   |     | NULL    |                |
| public          | tinyint(1)       | NO   |     | NULL    |                |
| date_added      | datetime         | NO   |     | NULL    |                |
| status          | int(10) unsigned | NO   | MUL | NULL    |                |
| slug            | varchar(50)      | YES  | MUL | NULL    |                |
| team_id         | bigint(20)       | NO   | MUL | NULL    |                |
| organization_id | bigint(20)       | NO   | MUL | NULL    |                |
| first_event     | datetime         | YES  |     | NULL    |                |
| forced_color    | varchar(6)       | YES  |     | NULL    |                |
| flags           | bigint(20)       | YES  |     | NULL    |                |
| platform        | varchar(64)      | YES  |     | NULL    |                |
+-----------------+------------------+------+-----+---------+----------------+
12 rows in set (0.01 sec)

```

I tried running your command (on our staging db) but got an error:

```
mysql> ALTER TABLE sentry_eventuser ADD FOREIGN KEY sentry_eventuser_project_id_fk (project_id) REFERENCES sentry_project (project_id);
ERROR 1215 (HY000): Cannot add foreign key constraint
```

**Comment by mattrobenolt** [comment]
Oh, sorry, it's just `id`.

So try:

```
ALTER TABLE sentry_eventuser ADD FOREIGN KEY sentry_eventuser_project_id_fk (project_id) REFERENCES sentry_project (id);
```

I'm just writing this by hand, so not sure if this is even close to correct.

**Comment by bsergean** [comment]
Ah ah, that one time it worked on the staging instance. I will try to run that on the live instance later and hopefully it will get the migration going. Thanks again.

```

mysql> ALTER TABLE sentry_eventuser ADD FOREIGN KEY sentry_eventuser_project_id_fk (project_id) REFERENCES sentry_project (id);
Query OK, 1357118 rows affected (25.38 sec)
Records: 1357118  Duplicates: 0  Warnings: 0

```

**Comment by bsergean** [comment]
YAY that command worked on the live DB, the south migration completed, we're on 8.22 now.
Thanks !

I've reached out to our DB team to migrate us to Postgres and it looks like we'll be able to do that at some point.
