### ISSUE TITLE
Sentry docker (8.21 and 8.22): no module named importlib

### ISSUE THREAD

**Issue by rakshazi** [getsentry/sentry#6609]
Dockerfile:

```Dockerfile
FROM sentry:8.21
RUN apt-get update && apt-get install -y libsasl2-dev python-dev libldap2-dev libssl-dev
RUN pip install sentry-ldap-auth sentry-plugins
COPY ./config/sentry.conf.py /etc/sentry/sentry.conf.py
```

Log:

```
Attaching to sentry_sentry_1
sentry_1    | Traceback (most recent call last):
sentry_1    |   File "/usr/local/bin/sentry", line 11, in <module>
sentry_1    |     sys.exit(main())
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 160, in main
sentry_1    |     cli(prog_name=get_prog(), obj={}, max_content_width=100)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
sentry_1    |     return self.main(*args, **kwargs)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
sentry_1    |     rv = self.invoke(ctx)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
sentry_1    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
sentry_1    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
sentry_1    |     return ctx.invoke(self.callback, **ctx.params)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
sentry_1    |     return callback(*args, **kwargs)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
sentry_1    |     return f(get_current_context(), *args, **kwargs)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 73, in inner
sentry_1    |     return ctx.invoke(f, *args, **kwargs)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
sentry_1    |     return callback(*args, **kwargs)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
sentry_1    |     return f(get_current_context(), *args, **kwargs)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
sentry_1    |     configure()
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 123, in configure
sentry_1    |     configure(ctx, py, yaml, skip_service_validation)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 152, in configure
sentry_1    |     skip_service_validation=skip_service_validation
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 260, in initialize_app
sentry_1    |     bootstrap_options(settings, config['options'])
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 133, in bootstrap_options
sentry_1    |     from sentry.options import load_defaults
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/options/__init__.py", line 10, in <module>
sentry_1    |     from .store import OptionsStore
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/options/store.py", line 19, in <module>
sentry_1    |     from sentry.db.models.query import create_or_update
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/__init__.py", line 11, in <module>
sentry_1    |     from .base import *  # NOQA
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 17, in <module>
sentry_1    |     from .fields.bounded import BoundedBigAutoField
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/fields/__init__.py", line 11, in <module>
sentry_1    |     from .array import *  # NOQA
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/fields/array.py", line 10, in <module>
sentry_1    |     SOUTH = 'south' in settings.INSTALLED_APPS
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
sentry_1    |     self._setup(name)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
sentry_1    |     self._wrapped = Settings(settings_module)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
sentry_1    |     mod = importlib.import_module(self.SETTINGS_MODULE)
sentry_1    |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
sentry_1    |     __import__(name)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 52, in load_module
sentry_1    |     reraise_as(ConfigurationError(msg))
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/utils/settings.py", line 48, in reraise_as
sentry_1    |     six.reraise(new_type, new_exception, e_traceback)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 44, in load_module
sentry_1    |     mod = self._load_module(fullname)
sentry_1    |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 62, in _load_module
sentry_1    |     from django.utils.importlib import import_module
sentry_1    | sentry.runner.importer.ConfigurationError: ImportError: No module named importlib
sentry_sentry_1 exited with code 1
```

Problem was found only today, after rebuild

**Comment by mattrobenolt** [comment]
I’m not sure exactly what you’re doing, but you shouldn’t be installing python-dev that way. It should already exist in the container. Also sentry-plugins is already installed for you, so that’s not needed either. 

But either way, this somehow looks like something you’re doing wrong.

**Comment by mattrobenolt** [comment]
Or it looks like the error is coming from your config file, sentry.conf.py?

**Comment by rakshazi** [comment]
@mattrobenolt sorry for that issue, it was problem with django-ldap-auth + getsentry-ldap-auth packages (version mismatch), my fault :(

**Comment by xeor** [comment]
So what is the best way to add ldap support in the docker sentry image? I guess that was your problem @rakshazi ?
Installing it now with it's deps ends up in the same error you got.

**Comment by rakshazi** [comment]
@xeor here is my dockerfile with LDAP auth plugin and Sentry 8.22:

```Dockerfile
FROM sentry

#ENVs here...

# Required packages for ldap plugin
RUN apt-get update && apt-get install -y libsasl2-dev python-dev libldap2-dev libssl-dev
# Freezed 100% compability version of django-auth-ldap (for sentry-ldap-auth)
RUN pip install django-auth-ldap==1.2.13 sentry-ldap-auth sentry-plugins
# Private custom configs, just appending them to default sentry configuration
COPY ./config/sentry.py /tmp/conf.py
RUN cat /tmp/conf.py >> /etc/sentry/sentry.conf.py && rm /tmp/conf.py
```

**Comment by HackToday** [comment]
Hi  @rakshazi , I followed  https://docs.sentry.io/server/installation/docker/  and above  like Dockerfile,

It seems LDAP not work with sentry, and also I did not find logs in the sentry web docker container

**Comment by rakshazi** [comment]
It works, but you should configure it yourself in Django config file, just append configuration from LDAP plugin docs to your Sentry config and rebuild image

**Comment by HackToday** [comment]
Hi  @rakshazi  I appended those thing like

```
AUTH_LDAP_SERVER_URI = 'ldap://xxxxx:389'
AUTH_LDAP_BIND_DN = ''
AUTH_LDAP_BIND_PASSWORD = ''

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    'dc=xxx,dc=xxx',
    ldap.SCOPE_SUBTREE,
    '(mail=%(user)s)',
)

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    '',
    ldap.SCOPE_SUBTREE,
    '(objectClass=groupOfUniqueNames)'
)

AUTH_LDAP_GROUP_TYPE = GroupOfUniqueNamesType()
AUTH_LDAP_REQUIRE_GROUP = None
AUTH_LDAP_DENY_GROUP = None

AUTH_LDAP_USER_ATTR_MAP = {
    'name': 'cn',
    'email': 'mail'
}

```

And did rebuild the image,  the rebuilt image can not work,  the strange issue is that not have any logging error for the docker container
