### ISSUE TITLE
creating superuser throws traceback

### ISSUE THREAD

**Issue by jamesbeedy** [getsentry/sentry#6647]
Following a successful migration of the db, I go to create an su and get this traceback.

```bash
$ /snap/bin/sentry.sentry-cli --version
sentry, version 8.22.0

$ /snap/bin/sentry.sentry-cli createuser --email admin@adminn.com --password mysecret --no-input --superuser
User created: admin@adminn.com
Added to organization: sentry
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/snap/sentry/x1/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/snap/sentry/x1/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/snap/sentry/x1/lib/python2.7/site-packages/sentry/utils/metrics.py", line 67, in worker
    logger.exception('Unable to incr internal metric')
  File "/snap/sentry/x1/usr/lib/python2.7/logging/__init__.py", line 1197, in exception
    Convenience method for logging an ERROR with exception information.
  File "/snap/sentry/x1/usr/lib/python2.7/logging/__init__.py", line 1200, in exception
    self.error(msg, *args, **kwargs)
  File "/snap/sentry/x1/usr/lib/python2.7/logging/__init__.py", line 1185, in error
    Log 'msg % args' with severity 'ERROR'.
  File "/snap/sentry/x1/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/snap/sentry/x1/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/snap/sentry/x1/lib/python2.7/site-packages/celery/utils/log.py", line 276, in makeRecord
    record.processName = current_process()._name
AttributeError: 'NoneType' object has no attribute '_name'
```

**Comment by mattrobenolt** [comment]
The fact that `current_process()` returns `None` sounds like some fundamental flaw here in your setup.

Like, just looking at how that's even set in: https://github.com/celery/billiard/blob/master/billiard/process.py

I don't even understand how that'd return `None` because it's being set here: https://github.com/celery/billiard/blob/master/billiard/process.py#L385

So I'm not sure what you're doing, but something is really wrong and I don't see how this could be Sentry's fault or anything we can do to fix this.
