### ISSUE TITLE
When app is under load sentry is not able to recognize host name

### ISSUE THREAD

**Issue by anshbansal** [getsentry/sentry#6660]
* We are using Java.
* We are not using docker to run sentry
* We are using logback to send information to sentry
* We are using Maven artifact  'io.sentry:sentry-logback:1.4.0' to use sentry
* When the application is under very heavy load then sentry is not able to resolve DNS. 
```io.sentry.connection.AsyncConnection - An exception occurred while sending the event to Sentry.
io.sentry.connection.ConnectionException: An exception occurred while submitting the event to the Sentry server.
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:182)
	at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71)
	at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: sentry.io
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:580)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:635)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:980)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:153)
	... 5 common frames omitted
``` 
 
Solutions proposed is Cache DNS to IP mapping or provide option for direct IP. If there is any other way by which this can be solved that would be great

**Comment by bretthoerner** [comment]
Hmm, you can adjust the JVM DNS caching like so: http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-jvm-ttl.html

But I'm curious what DNS provider you are using? Is it just not responding in time? Seems like that'd cause a lot of other issues..

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
