### ISSUE TITLE
RuntimeError in slack action

### ISSUE THREAD

**Issue by kimxogus** [getsentry/sentry#67679]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Basically, this issue is recurred issue of #63656

1. Setup slack app with self-hosted sentry
2. initiate slack action with slack issue message's button

### Expected Result

Slack action succeeds

### Actual Result

As https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/slack/requests/base.py#L127 is still using `get_field_id`, not `get_field_id_option`, RunitmeError occurs because team field is None.

Please make it to use `get_field_id_option`

error log
```
[INFO] sentry.integrations.slack: slack.action\nTraceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/api/base.py", line 273, in handle_exception
    response = super().handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/sentry/api/base.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/integrations/slack/webhooks/action.py", line 737, in post
    slack_request.validate()
  File "/usr/local/lib/python3.11/site-packages/sentry/integrations/slack/requests/base.py", line 77, in validate
    self.validate_integration()
  File "/usr/local/lib/python3.11/site-packages/sentry/integrations/slack/requests/base.py", line 223, in validate_integration
    provider="slack", external_id=self.team_id
                                  ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/integrations/slack/requests/base.py", line 127, in team_id
    return get_field_id(self.data, "team")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/integrations/slack/requests/base.py", line 33, in get_field_id
    raise RuntimeError
RuntimeError
```

sentry error data info
```
{
action_ts: '1711446327.472760', 
actions: [
{
name: 'assign', 
selected_options: ["{'value': 'user:1'}"], 
type: 'select'
}
], 
attachment_id: '1', 
callback_id: '{"issue":1111}', 
channel: {
id: 'AAAAAAAAA', 
name: 'slack_channel'
}, 
message_ts: '1711446320.222329', 
team: None, 
token: [Filtered], 
type: 'interactive_message', 
user: {
id: 'user-id', 
name: 'name', 
team_id: 'team-id'
}
}
```

### Product Area

Settings - Integrations

### Version

24.2.0

**Comment by kimxogus** [comment]
@roggenkemper Hi, the issue #63656 hasn't completely resolved when `team` field is None.
Please take a look at this issue.

**Comment by cathteng** [comment]
This is on our radar, and we'll be taking a look.
