### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'get'" in LambdaClient.captureMessage()

### ISSUE THREAD

**Issue by flurischt** [getsentry/sentry#6811]
## 'NoneType' object has no attribute 'get'
I added LambdaClient to my AWS Lambda functions. Using the latest version of sentry installed using pip I get ```AttributeError: 'NoneType' object has no attribute 'get'``` when calling `client.captureMessage()`.

This happens inside my Lambdas on AWS as well as on my local computer.

## Steps to reproduce
```
$ pip install raven
$ python3.6
>>> from raven.contrib.awslambda import LambdaClient
>>> client = LambdaClient('https://********')
>>> client.captureMessage('My event just happened!')
Error in sys.excepthook:
Traceback (most recent call last):
  File "/****/raven/base.py", line 274, in handle_exception
    self.captureException(exc_info=exc_info, level='fatal')
  File "/****/raven/base.py", line 814, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/****/raven/contrib/awslambda/__init__.py", line 67, in capture
    user_info = self._get_user_interface(event)
  File "/****/raven/contrib/awslambda/__init__.py", line 128, in _get_user_interface
    if event.get('requestContext'):
AttributeError: 'NoneType' object has no attribute 'get'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/****/raven/base.py", line 792, in captureMessage
    return self.capture('raven.events.Message', message=message, **kwargs)
  File "/****/raven/contrib/awslambda/__init__.py", line 67, in capture
    user_info = self._get_user_interface(event)
  File "/****/raven/contrib/awslambda/__init__.py", line 128, in _get_user_interface
    if event.get('requestContext'):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by flurischt** [comment]
Sorry, just noticed this is the wrong repo! I reported the issue in the raven-python repository.
