### ISSUE TITLE
[Android] NullPointerException - captureEvent

### ISSUE THREAD

**Issue by ou2s** [getsentry/sentry#6899]
Sentry is reporting an android crash within its Native Module.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
    at io.sentry.RNSentryModule.captureEvent(RNSentryModule.java:244)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:154)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:762)
```

I try to find this null reference in my code but I don't understand because I don't call `Sentry.captureEvent`. But maybe adding safe guard or try catch in java code can help prevent this?

RN: 0.48.4
react-native-sentry: 0.32.0

Thanks for the help

**Comment by ou2s** [comment]
To delete. I should have posted here https://github.com/getsentry/react-native-sentry/
