### ISSUE TITLE
Syntax error after upgrade to 8.22 from 8.0.5

### ISSUE THREAD

**Issue by pehrsoderman** [getsentry/sentry#6969]
I used `pip install --upgrade sentry` to upgrade from 8.0.5 to 8.22.0 (yea, I know, I should have done this ages ago...), and now I get a syntax error from the sentry command: 

```
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    load_entry_point('sentry==8.22.0', 'console_scripts', 'sentry')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/sentry/runner/__init__.py", line 67, in <module>
    'sentry.runner.commands.upgrade.upgrade',
  File "/usr/local/lib/python3.5/dist-packages/sentry/runner/__init__.py", line 56, in <lambda>
    lambda cmd: cli.add_command(import_string(cmd)), (
  File "/usr/local/lib/python3.5/dist-packages/sentry/utils/imports.py", line 49, in import_string
    result = _cache[path]
  File "/usr/local/lib/python3.5/dist-packages/sentry/utils/imports.py", line 30, in __missing__
    module = __import__(module_name, {}, {}, [class_name])
  File "/usr/local/lib/python3.5/dist-packages/sentry/runner/commands/tsdb.py", line 12, in <module>
    from sentry.utils.iterators import chunked
  File "/usr/local/lib/python3.5/dist-packages/sentry/utils/iterators.py", line 21
    lambda (i, iterator): advance(i, iterator),
           ^
SyntaxError: invalid syntax
```

Python version is `Python 3.5.2`. Installation is pretty standard through pip. I have tried to look through the release notes and issues, but I haven't found anything that looks relevant other than possibly #6030. The server runs `Ubuntu 16.04.3 LTS`

**Comment by pehrsoderman** [comment]
The problem seems to be Python 3 related, which as far as I can tell is not supported by sentry, and that pip defaults to python 3 on the machine. I am not sure exactly how to protect people from this little trap.

**Comment by mattrobenolt** [comment]
Yeah, you need Python 2.7 which is documented in our docs.
