### ISSUE TITLE
Can't create tables on MySql

### ISSUE THREAD

**Issue by zuroc** [getsentry/sentry#703]
sentry@vps08 ~/42qu-sentry $ sentry  --config=/home/sentry/42qu-sentry/sentry.conf.py upgrade
Syncing...
Creating tables ...
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_user_permissions
Creating table auth_user_groups
Creating table auth_user
Creating table django_admin_log
Creating table django_content_type
Creating table django_session
Creating table django_site
Creating table social_auth_usersocialauth
Creating table social_auth_nonce
Creating table social_auth_association
Traceback (most recent call last):
  File "/usr/bin/sentry", line 9, in <module>
    load_entry_point('sentry==5.1.1.2', 'console_scripts', 'sentry')()
  File "/usr/lib64/python2.7/site-packages/sentry-5.1.1.2-py2.7.egg/sentry/utils/runner.py", line 193, in main
    initializer=initialize_app,
  File "/usr/lib64/python2.7/site-packages/logan-0.5.4-py2.7.egg/logan/runner.py", line 155, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python2.7/site-packages/sentry-5.1.1.2-py2.7.egg/sentry/management/commands/upgrade.py", line 26, in handle
    call_command('syncdb', migrate=True, interactive=(not options['noinput']))
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/__init__.py", line 150, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/usr/lib64/python2.7/site-packages/South-0.7.6-py2.7.egg/south/management/commands/syncdb.py", line 90, in handle_noargs
    syncdb.Command().execute(**options)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/core/management/commands/syncdb.py", line 102, in handle_noargs
    cursor.execute(statement)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/Django-1.4.3-py2.7.egg/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.DatabaseError: (1071, 'Specified key was too long; max key length is 1000 bytes')
sentry@vps08 ~/42qu-sentry $ locate social_auth_association

========================

sentry@vps08 ~/42qu-sentry $ mysql -v
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 328271
Server version: 5.1.61-log Gentoo Linux mysql-5.1.61

mysql> show create database sentry;
+----------+-----------------------------------------------------------------+
| Database | Create Database                                                 |
+----------+-----------------------------------------------------------------+
| sentry   | CREATE DATABASE `sentry` /*!40100 DEFAULT CHARACTER SET utf8 */ |
+----------+-----------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by jonnung** [comment]
I had resolved to modify the 'my.cnf'.
```
[mysqld]
default-storage-engine=InnoDB
```

**Comment by dcramer** [comment]
Closing due to age.
