### ISSUE TITLE
AWS Lambda Problem

### ISSUE THREAD

**Issue by benjaminmatthews-dev** [getsentry/sentry#71658]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Attempted to setup Aws Lambda Integration

### Expected Result

I expected it to work

### Actual Result

White screen and chrome console errors

```
Error: useRouteContext called outside of routes provider
    at s (useRouteContext.tsx:8:11)
    at n (useRouter.tsx:10:17)
    at c (withSentryRouter.tsx:18:20)
    at gl (react-dom.production.js:11737:18)
    at yu (react-dom.production.js:14081:13)
    at hu (react-dom.production.js:19326:12)
    at Zd (react-dom.production.js:19265:5)
    at uo (react-dom.production.js:19237:7)
    at Wl (react-dom.production.js:18687:22)
    at du (react-dom.production.js:18591:22)
    at f (scheduler.production.min.js:13:203)
    at MessagePort.W (scheduler.production.min.js:14:128)
```
    
 `Uncaught Error: useRouteContext called outside of routes provider
    at s (useRouteContext.tsx:8:11)
    at n (useRouter.tsx:10:17)
    at c (withSentryRouter.tsx:18:20)
    at gl (react-dom.production.js:11737:18)
    at yu (react-dom.production.js:14081:13)
    at hu (react-dom.production.js:19326:12)
    at Zd (react-dom.production.js:19265:5)
    at uo (react-dom.production.js:19237:7)
    at Wl (react-dom.production.js:18687:22)
    at du (react-dom.production.js:18591:22)
    at f (scheduler.production.min.js:13:203)
    at MessagePort.W (scheduler.production.min.js:14:128)`

### Product Area

Settings - Integrations

**Comment by sentaur-athena** [comment]
Tracking this issue here: https://github.com/getsentry/sentry/issues/71491
