### ISSUE TITLE
Duplicate release ID causes failures to open related tabs

### ISSUE THREAD

**Issue by cocomoco-git** [getsentry/sentry#71655]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Open Releases and select any release with same version number a few projects share. ( in our case 1.123.1, but there are more cases )
![releases](https://github.com/getsentry/sentry/assets/157035930/bba438bb-5f80-4532-9263-8d8508bbe2ef)

OR alternatively open Issue of the release with ID, that a few projects share.

### Expected Result

All Releases and all Issues open without errors.

### Actual Result

We get the following error when opening Issues or Releases with duplicate ID:
![Releases](https://github.com/getsentry/sentry/assets/157035930/a44b5346-f6b3-4c4b-ba91-ed3d9f3774d3)

![Issues](https://github.com/getsentry/sentry/assets/157035930/7c0348f9-7a62-4c29-a967-35c45231fe3e)

Logs from web-1 container:

> sentry.models.release.Release.MultipleObjectsReturned: get() returned more than one Release -- it returned 2!
> 14:21:40 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_release_meta.OrganizationReleaseMetaEndpoint' response=500 user_id='19' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/company/releases/1.123.1/meta/' caller_ip='141.101.99.15' user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.04949188232421875 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
> 14:21:40 [ERROR] django.request: Internal Server Error: /api/0/organizations/company/releases/1.123.1/meta/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/company/releases/1.123.1/meta/'>)

Is there any way to prevent and fix this? Perhaps our setup is incorrect, causing versioning across different projects to not work together correctly? We have over 140 projects, so it is normal that by using semantic versioning some projects eventually get same version number.

Thank you.

### Product Area

Releases

### Version

24.5.0

**Comment by farfromrefug** [comment]
I have the same issue. It is also preventing me from make releases because:
* i cant remove the release
* sentry webpack will fail because it cant create the release  https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/631

**Comment by farfromrefug** [comment]
@ceorourke sorry to bump this and ask you but this is breaking issue for me right now. I am not sure why 2 releases are created but it is unsolvable and makes sentry unusable. 
The strange thing is that it happens only for one project while others projects share the exact same build/release process.
Here is the stack
```
2025/01/03 21:39:06	stderr	20:39:06 [ERROR] django.request: Internal Server Error: /api/0/organizations/akylas/releases/com.akylas.documentscanner@1.11.5+48/meta/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/akylas/releases/com.akylas.documentscanner@1.11.5+48/meta/'>)
2025/01/03 21:39:06	stderr	20:39:06 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_release_meta.OrganizationReleaseMetaEndpoint' response=500 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/akylas/releases/com.akylas.documentscanner@1.11.5+48/meta/' caller_ip='84.7.38.124' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.13092350959777832 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2025/01/03 21:39:06	stderr	sentry.models.release.Release.MultipleObjectsReturned: get() returned more than one Release -- it returned 2!
2025/01/03 21:39:06	stderr	    raise self.model.MultipleObjectsReturned(
2025/01/03 21:39:06	stderr	  File "/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
2025/01/03 21:39:06	stderr	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/03 21:39:06	stderr	    return getattr(self.get_queryset(), name)(*args, **kwargs)
2025/01/03 21:39:06	stderr	  File "/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
2025/01/03 21:39:06	stderr	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/03 21:39:06	stderr	    release = Release.objects.get(organization_id=organization.id, version=version)
2025/01/03 21:39:06	stderr	  File "/usr/src/sentry/src/sentry/api/endpoints/organization_release_meta.py", line 49, in get
2025/01/03 21:39:06	stderr	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/03 21:39:06	stderr	    response = handler(request, *args, **kwargs)
2025/01/03 21:39:06	stderr	  File "/usr/src/sentry/src/sentry/api/base.py", line 456, in dispatch
2025/01/03 21:39:06	stderr	    raise exc
2025/01/03 21:39:06	stderr	  File "/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2025/01/03 21:39:06	stderr	    self.raise_uncaught_exception(exc)
2025/01/03 21:39:06	stderr	  File "/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
2025/01/03 21:39:06	stderr	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025/01/03 21:39:06	stderr	    response = super().handle_exception(exc)
2025/01/03 21:39:06	stderr	  File "/usr/src/sentry/src/sentry/api/base.py", line 324, in handle_exception
2025/01/03 21:39:06	stderr	Traceback (most recent call last):
2025/01/03 21:38:59	stderr	20:38:59 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.broadcast_index.BroadcastIndexEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/akylas/broadcasts/' caller_ip='84.7.38.124' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.10380196571350098 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2025/01/03 21:09:14	stderr	20:09:14 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.broadcast_index.BroadcastIndexEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/akylas/broadcasts/' caller_ip='84.7.38.124' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.07677221298217773 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2025/01/03 21:08:01	stderr	20:08:01 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.project_release_stats.ProjectReleaseStatsEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/projects/akylas/documentscanner/releases/com.akylas.documentscanner@1.11.4+47/stats/' caller_ip='84.7.38.124' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=8.242072343826294 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2025/01/03 21:08:01	stderr	[uwsgi-http key: bugs.akylas.fr client_addr: 172.19.0.56 client_port: 33416] hr_write(): Broken pipe [plugins/http/http.c line 565]
2025/01/03 21:08:01	stderr	20:08:01 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_sessions.OrganizationSessionsEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/akylas/sessions/' caller_ip='84.7.38.124' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=7.803162336349487 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2025/01/03 21:08:01	stderr	20:08:00 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_issues_count.OrganizationIssuesCountEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/akylas/issues-count/' caller_ip='84.7.38.124' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=7.322273254394531 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2025/01/03 21:08:01	stderr	[uwsgi-http key: bugs.akylas.fr client_addr: 172.19.0.56 client_port: 35976] hr_write(): Broken pipe [plugins/http/http.c line 565]
2025/01/03 21:08:01	stderr	20:08:00 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_sessions.OrganizationSessionsEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/akylas/sessions/' caller_ip='84.7.38.124' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=7.275306224822998 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2025/01/03 21:08:00	stderr	20:08:00 [INFO] sentry.access.api: api.access (method='GET' view='sentry.issues.endpoints.organization_group_index.OrganizationGroupIndexEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/akylas/issues/' caller_ip='84.7.38.124' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=6.957909345626831 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
```
I cant even solve that locally as i have no way to delete any of those releases as the UI wont let me access that release (because of that error)

**Comment by cmanallen** [comment]
This is a really strange issue because we have a unique constraint in the database schema which should prevent this. Because this only appears to affect self-hosted I'm wondering if there's some issue with your database's schema definition. Perhaps migrations weren't properly run or your database doesn't support unique constraints?  If you're able to show the `sentry_release` table's schema that would be helpful.

**Comment by farfromrefug** [comment]
@cmanallen sure. Is there a easy way, admin panel, to view the database?

**Comment by NicoPennec** [comment]
We are facing the same problem, which is generated randomly, on a self-hosted instance (ping @nledez).

We do have a duplicate version ID in the `sentry_release` table.

Find below the `sentry_release` table's schema on PgSQL 14.11 (Debian 14.11-1.pgdg120+2) and Sentry 25.5.168ffa9b

```
                                         Table "public.sentry_release"
     Column      |           Type           | Collation | Nullable |                  Default
-----------------+--------------------------+-----------+----------+--------------------------------------------
 id              | bigint                   |           | not null | nextval('sentry_release_id_seq'::regclass)
 version         | character varying(250)   |           | not null |
 ref             | character varying(250)   |           |          |
 url             | character varying(200)   |           |          |
 date_added      | timestamp with time zone |           | not null |
 date_started    | timestamp with time zone |           |          |
 date_released   | timestamp with time zone |           |          |
 data            | text                     |           | not null |
 commit_count    | integer                  |           |          |
 last_commit_id  | bigint                   |           |          |
 authors         | text[]                   |           |          |
 total_deploys   | integer                  |           |          |
 last_deploy_id  | integer                  |           |          |
 organization_id | bigint                   |           | not null |
 owner_id        | integer                  |           |          |
 status          | integer                  |           |          |
 build_code      | text                     |           |          |
 build_number    | bigint                   |           |          |
 major           | bigint                   |           |          |
 minor           | bigint                   |           |          |
 patch           | bigint                   |           |          |
 prerelease      | text                     |           |          |
 revision        | bigint                   |           |          |
 package         | text                     |           |          |
 user_agent      | text                     |           |          |
Indexes:
    "sentry_release_pkey" PRIMARY KEY, btree (id)
    "sentry_rele_organiz_4ed947_idx" btree (organization_id, date_added)
    "sentry_rele_organiz_6975e7_idx" btree (organization_id, status)
    "sentry_rele_organiz_6b035f_idx" btree (organization_id, build_number)
    "sentry_rele_organiz_ffeeb2_idx" btree (organization_id, build_code)
    "sentry_release_organization_id_45a8c0c8" btree (organization_id)
    "sentry_release_organization_id_version_65da5843_uniq" UNIQUE CONSTRAINT, btree (organization_id, version)
    "sentry_release_owner_id_478d2967" btree (owner_id)
    "sentry_release_semver_by_package_idx" btree (organization_id, package, major DESC, minor DESC, patch DESC, revision DESC, (
CASE
    WHEN prerelease = ''::text THEN 1
    ELSE 0
END) DESC, prerelease DESC)
    "sentry_release_semver_idx" btree (organization_id, major DESC, minor DESC, patch DESC, revision DESC, (
CASE
    WHEN prerelease = ''::text THEN 1
    ELSE 0
END) DESC, prerelease DESC)
    "sentry_release_version_btree" btree (organization_id, version text_pattern_ops)
Check constraints:
    "sentry_release_commit_count_check" CHECK (commit_count >= 0)
    "sentry_release_last_deploy_id_check" CHECK (last_deploy_id >= 0)
    "sentry_release_status_check" CHECK (status >= 0)
    "sentry_release_total_deploys_check" CHECK (total_deploys >= 0)
Foreign-key constraints:
    "sentry_release_organization_id_45a8c0c8_fk_sentry_or" FOREIGN KEY (organization_id) REFERENCES sentry_organization(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "sentry_deploy" CONSTRAINT "sentry_deploy_release_id_1de764c5_fk_sentry_release_id" FOREIGN KEY (release_id) REFERENCES sentry_release(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_distribution" CONSTRAINT "sentry_distribution_release_id_886801af_fk_sentry_release_id" FOREIGN KEY (release_id) REFERENCES sentry_release(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_groupedmessage" CONSTRAINT "sentry_groupedmessag_first_release_id_c8ed807e_fk_sentry_re" FOREIGN KEY (first_release_id) REFERENCES sentry_release(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_groupresolution" CONSTRAINT "sentry_groupresolution_release_id_173a3d74_fk_sentry_release_id" FOREIGN KEY (release_id) REFERENCES sentry_release(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_release_project" CONSTRAINT "sentry_release_project_release_id_babf7578_fk_sentry_release_id" FOREIGN KEY (release_id) REFERENCES sentry_release(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_releaseactivity" CONSTRAINT "sentry_releaseactivity_release_id_6c117a63_fk_sentry_release_id" FOREIGN KEY (release_id) REFERENCES sentry_release(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_releasecommit" CONSTRAINT "sentry_releasecommit_release_id_b875f881_fk_sentry_release_id" FOREIGN KEY (release_id) REFERENCES sentry_release(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_releaseheadcommit" CONSTRAINT "sentry_releaseheadco_release_id_c90760fb_fk_sentry_re" FOREIGN KEY (release_id) REFERENCES sentry_release(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "sentry_releaseprojectenvironment" CONSTRAINT "sentry_releaseprojec_release_id_9fda2fad_fk_sentry_re" FOREIGN KEY (release_id) REFERENCES sentry_release(id) DEFERRABLE INITIALLY DEFERRED
```

**Comment by cmanallen** [comment]
@NicoPennec Your schema is correct. Are you able to run this query and paste the output?

```sql
SELECT organization_id, version, COUNT(*)
FROM sentry_release
GROUP BY organization_id, version
HAVING COUNT(*) > 1;
```

**Comment by nledez** [comment]
Hi @cmanallen we have:
```
 organization_id |    version    | count
-----------------+---------------+-------
               1 | kitsu@0.20.76 |     2
               1 | kitsu@0.19.45 |     2
               1 | kitsu@0.19.47 |     2
               1 | kitsu@0.20.81 |     2
               1 | kitsu@0.20.40 |     2
               1 | kitsu@0.19.50 |     2
               1 | kitsu@0.19.44 |     2
(7 rows)
```
We have 341 other versions of count=1.

And for a specific version:
```
select * from sentry_release where version = 'kitsu@0.20.76';

 id  |    version    | ref | url |       date_added       | date_started | date_released | data | commit_count | last_commit_id | authors | total_deploys | last_deploy_id | organization_id | owner_id | status | build_code | build_number | major | minor | patch | prerelease | revision | package | user_agent
-----+---------------+-----+-----+------------------------+--------------+---------------+------+--------------+----------------+---------+---------------+----------------+-----------------+----------+--------+------------+--------------+-------+-------+-------+------------+----------+---------+------------
 397 | kitsu@0.20.76 |     |     | 2025-07-17 12:00:00+00 |              |               | {}   |            0 |                | {}      |             0 |                |               1 |          |      0 |            |              |     0 |    20 |    76 |            |        0 | kitsu   |
 398 | kitsu@0.20.76 |     |     | 2025-07-17 12:00:00+00 |              |               | {}   |            0 |                | {}      |             0 |                |               1 |          |      0 |            |              |     0 |    20 |    76 |            |        0 | kitsu   |
(2 rows)
```

I also check others versions:
```
select id, version, date_added, organization_id from sentry_release where version in ('kitsu@0.20.76', 'kitsu@0.19.45', 'kitsu@0.19.47', 'kitsu@0.20.81', 'kitsu@0.20.40', 'kitsu@0.19.50', 'kitsu@0.19.44')
;
 id  |    version    |          date_added           | organization_id
-----+---------------+-------------------------------+-----------------
 224 | kitsu@0.19.44 | 2024-06-25 08:26:14.072+00    |               1
 226 | kitsu@0.19.44 | 2024-06-25 20:36:16.87735+00  |               1

 228 | kitsu@0.19.45 | 2024-07-02 12:25:55.542+00    |               1
 230 | kitsu@0.19.45 | 2024-07-02 20:12:10.352749+00 |               1

 232 | kitsu@0.19.47 | 2024-07-09 15:05:22.474+00    |               1
 234 | kitsu@0.19.47 | 2024-07-09 20:14:19.050256+00 |               1

 237 | kitsu@0.19.50 | 2024-07-16 16:47:21.704+00    |               1
 239 | kitsu@0.19.50 | 2024-07-16 19:46:30.530756+00 |               1

 344 | kitsu@0.20.40 | 2025-03-04 14:00:00+00        |               1
 345 | kitsu@0.20.40 | 2025-03-04 14:00:00+00        |               1

 397 | kitsu@0.20.76 | 2025-07-17 12:00:00+00        |               1
 398 | kitsu@0.20.76 | 2025-07-17 12:00:00+00        |               1

 403 | kitsu@0.20.81 | 2025-07-30 21:00:00+00        |               1
 404 | kitsu@0.20.81 | 2025-07-30 21:00:00+00        |               1
(14 rows)
```

**Comment by cmanallen** [comment]
@nledez Thanks.  I'm taking a look at it now.  I'll update you when I know whats going on.

**Comment by cmanallen** [comment]
@nledez What is the output of this query?


```sql
SELECT convalidated
FROM pg_constraint
WHERE conname = 'sentry_release_organization_id_version_65da5843_uniq';
```

**Comment by nledez** [comment]
@cmanallen "et voilà":
```
SELECT convalidated
FROM pg_constraint
WHERE conname = 'sentry_release_organization_id_version_65da5843_uniq';
 convalidated
--------------
 t
(1 row)
```

**Comment by cmanallen** [comment]
@nledez Hopefully my last ask. What is the output of this query?

```sql
SELECT
    indexrelid::regclass AS index_name,
    indisvalid,
    indisready
FROM
    pg_index
WHERE
    indexrelid = 'sentry_release_organization_id_version_65da5843_uniq'::regclass;
```

**Comment by nledez** [comment]
You can ask all what you need :)
```
                      index_name                      | indisvalid | indisready
------------------------------------------------------+------------+------------
 sentry_release_organization_id_version_65da5843_uniq | t          | t
(1 row)
```

**Comment by cmanallen** [comment]
@nledez Did this issue begin after upgrading to a specific version of Sentry? I see your first dupe was on `2024-06-25 20:36:16.87735+00`. Do you happen to recall the version you upgraded from/to?  Do you run the default Postgres setup or is it custom in some way?

**Comment by cmanallen** [comment]
@nledez I've re-assigned this to the self-hosted team. This is something that has happened in the past. They should be able to provide fix instructions. Please reach out to me if you don't get a response.

**Comment by nledez** [comment]
Hello @cmanallen, thank you for your help.
This installation was carried out a few years ago and has been updated regularly since then.
The Postgres is the one provided by Docker Compose.

**Comment by hubertdeng123** [comment]
By any chance, did you happen to upgrade to 24.4.2, 24.5.0, or 24.5.1?

If so, in order to resolve this issue you may need to follow instructions similar to those specified here: https://github.com/getsentry/self-hosted/issues/3167#issuecomment-2223701471. Please note that this is dangerous and can potentially lead to data loss

Edit: Nvm, I see you are on 24.5.0 so you are directly on a problematic version
