### ISSUE TITLE
Sentry 23.3.1 Jira Integration Failing 

### ISSUE THREAD

**Issue by cah-michel-bitar** [getsentry/sentry#73340]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

1.29.2

### Steps to Reproduce

After an upgrade all the way from 21.8.0 where Jira integration was functioning normally to 23.3.1, Jira Cloud integration stopped working.

We tried reconfiguring everything multiple times and the integration was still failing.

### Expected Result

We expect to be able to create Jira tickets through Sentry

### Actual Result

It is actually failing with the following error:
![image](https://github.com/getsentry/self-hosted/assets/167771263/44784209-479c-4eac-b8b6-e5e4dba953d5)

And the only indicative log I was able to find was the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 188, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 305, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/group_integration_details.py", line 116, in get
    config = installation.get_create_issue_config(
  File "/usr/local/lib/python3.8/site-packages/sentry/integrations/jira_server/integration.py", line 721, in get_create_issue_config
    (choice["id"], choice["name"]) for choice in issue_type_choices["values"]
KeyError: 'values'
```

And actually, if I am quick enough to click on the "Link" tab that opens up before the error comes up, I am able to Link issues. Just not to create them. After taking a look at the code, it seems like sentry tries to get a list of issue types from Jira, but it seems like it is being returned as null/empty.

**Comment by sentaur-athena** [comment]
I'll send this over to the team and get back to you.

**Comment by cah-michel-bitar** [comment]
Update that the integration is not failing to "Link" to existing issues, just failing to create issues on Jira from Sentry.

**Comment by sentaur-athena** [comment]
Unfortunately we don't have bandwidth to prioritize this. There are some ongoing Jira refactory that the team is doing and might fix this issue as a side effect and we're also open to community contributions if you or someone on your team have a fix for it.
