### ISSUE TITLE
Unable to create alerts for Crash Free Session Rate - 500 KeyError

### ISSUE THREAD

**Issue by 3ventic** [getsentry/sentry#78815]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Go to Alerts
2. Create Alert
3. Select Alert: Sessions > Crash Free Session Rate
4. Choose a project with sessions under Filter events
5. Set a critical threshold, e.g. `95`
6. Set a valid action
7. Set a name and owner
8. Click save rule

### Expected Result

Alert is created

### Actual Result

![Image](https://github.com/user-attachments/assets/11bda7c3-dd58-435f-8eb9-7732c28d3ebb)

Log shows:
```
Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/api/base.py", line 320, in handle_exception
    response = super().handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/src/sentry/src/sentry/api/base.py", line 452, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/incidents/endpoints/organization_alert_rule_index.py", line 612, in post
    return self.create_metric_alert(request, organization)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/incidents/endpoints/organization_alert_rule_index.py", line 108, in create_metric_alert
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 445, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/incidents/serializers/alert_rule.py", line 230, in validate
    self._validate_query(data)
  File "/usr/src/sentry/src/sentry/incidents/serializers/alert_rule.py", line 289, in _validate_query
    query_type = data.setdefault("query_type", query_datasets_to_type[dataset])
                                               ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: <Dataset.Sessions: 'sessions'>
```

### Product Area

Alerts

### Link

https://snip.example.com/organizations/snip/alerts/new/metric/?aggregate=percentage(sessions_crashed%2C+sessions)+AS+_crash_rate_alert_aggregate&dataset=sessions&eventTypes=session&project=client&referrer=alert_stream

### Version

24.7.0

**Comment by 3ventic** [comment]
This appears to happen, because Dataset.Sessions [used in query validation](<https://github.com/getsentry/sentry/blob/906235e0aa31248c7cdec52f300f5801de61fec2/src/sentry/incidents/serializers/alert_rule.py#L289>) is not present in [the "temporary" mapping](<https://github.com/getsentry/sentry/blame/906235e0aa31248c7cdec52f300f5801de61fec2/src/sentry/incidents/logic.py#L474>).
