### ISSUE TITLE
" Oops! Something went wrong" sentry access issue

### ISSUE THREAD

**Issue by abdul-devops01** [getsentry/sentry#79075]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Trying to log into sentry

### How are you getting stuck?

We have been using sentry selfhosted for a while now, I tried integrating slack to sentry and I needed to make modifications to the config.yml file according to sentry documentation, after making required documentation, I tried running the `./insall.sh` to rebuild and make changes but I got stuck with the issue of docker could not pull images because of authorization issues and I needed to run docker login, so I saw a solution online to delete sentry self hosted directory and install from scratch which I did, but all previous volumes were still existing, so I reinstalled and everything was file but on trying to accesses sentry I got the error;
```
Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, [contact us](https://github.com/getsentry/sentry/issues/new/choose) with more details.

```

and the only error I am getting is from the nginx sentry, all other containers are running perfectly fine

`172.24.0.1 - - [12/Oct/2024:07:23:06 +0000] "GET /saml/metadata/sentry/ HTTP/1.1" 500 7700 "https://sentry.makerble.org/saml/metadata/sentry/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "20.235.244.24"`

### Where in the product are you?

Sign In

### Link

https://sentry.makerble.org

**Comment by abdul-devops01** [comment]
got this log from sentry-web-1

```
SQL: SELECT "sentry_team"."id", "sentry_team"."organization_id", "sentry_team"."slug", "sentry_team"."name", "sentry_team"."status", "sentry_team"."actor_id", "sentry_team"."idp_provisioned", "sentry_team"."date_added", "sentry_team"."org_role" FROM "sentry_team" WHERE "sentry_team"."organization_id" = %s
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/../sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/silo/base.py", line 145, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/web/frontend/base.py", line 390, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/web/frontend/auth_login.py", line 97, in handle
    return super().handle(request=request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/web/frontend/base.py", line 405, in handle
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/web/frontend/auth_login.py", line 111, in get
    return self.redirect_to_default_org_login()
  File "/usr/local/lib/python3.10/site-packages/sentry/web/frontend/auth_login.py", line 152, in redirect_to_default_org_login
    org = organization_service.get_default_organization()
  File "/usr/local/lib/python3.10/site-packages/sentry/services/hybrid_cloud/organization/impl.py", line 139, in get_default_organization
    return serialize_rpc_organization(Organization.get_default())
  File "/usr/local/lib/python3.10/site-packages/sentry/services/hybrid_cloud/organization/serial.py", line 150, in serialize_rpc_organization
    rpc_org.teams.extend(serialize_rpc_team(team) for team in teams)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 641, in execute
    result = real_execute(self, sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.10/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/db/postgres/decorators.py", line 93, in inner
    raise type(e)(f"{e!r}\nSQL: {sql}").with_traceback(e.__traceback__)
  File "/usr/local/lib/python3.10/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.ProgrammingError: UndefinedColumn('column sentry_team.actor_id does not exist\nLINE 1: ...g", "sentry_team"."name", "sentry_team"."status", "sentry_te...\n                                                             ^\n')

```
