### ISSUE TITLE
SAML ACS cause 500 error

### ISSUE THREAD

**Issue by xrl** [getsentry/sentry#7995]
## General Support

If you're looking for general support, please utilize our [community forum](https://forum.sentry.io/) rather than GitHub Issues.

## Reporting Bugs

Sentry 8.22, docker image running in kubernetes, with the sentry-saml2 pip installed.

Only line I have added to the config, at the end:

```
SENTRY_FEATURES['organizations:sso-saml2'] = True
```

My Dockerfile:

```
FROM sentry:8.22.0

RUN apt-get update \
	&& apt-get install -y pkg-config libxmlsec1-dev \
	&& pip install https://github.com/getsentry/sentry-auth-saml2/archive/master.zip \
	&& apt-get purge

ADD sentry.conf.py /etc/sentry/sentry.conf.py
```

Here is the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/site-packages/sentry/auth/providers/saml2.py", line 92, in dispatch
    return sso_login.handle(request)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_provider_login.py", line 19, in handle
    return helper.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 215, in current_step
    return self.finish_pipeline()
  File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 233, in finish_pipeline
    identity = self.provider.build_identity(data)
  File "/usr/local/lib/python2.7/site-packages/sentry/auth/providers/saml2.py", line 284, in build_identity
    for key, provider_key in iteritems(self.config['attribute_mapping']):
KeyError: 'attribute_mapping'
18:47:01 [ERROR] django.request: Internal Server Error: /saml/acs/scientist/ (status_code=500 request=<WSGIRequest: POST u'/saml/acs/scientist/'>)
```

**Comment by xrl** [comment]
Turns out I had the wrong callback URL. I had it for the team but I needed it for `/saml/acs/sentry/`. Works now.
