### ISSUE TITLE
24.9.0+: ingest-replay-recordings container crashing with Permission denied: '/opt/sentry'

### ISSUE THREAD

**Issue by hostalp** [getsentry/sentry#80501]
### Self-Hosted Version

24.10.0

### CPU Architecture

x86_64

### Docker Version

26.1.3

### Docker Compose Version

2.27.0

### Steps to Reproduce

Recently we noticed that the container **ingest-replay-recordings** started to cause a high CPU utilization due to its frequent restarts.
This was identified (see part of the log below) to be related to unsuccessful attempts to create some directory structure in /opt (inside the container).

First it was `/opt/sentry`, after we created this directory manually it was `/opt/sentry/data`, then `/opt/sentry/data/files`, then `/opt/sentry/data/files/90` and `/opt/sentry/data/files/90/5`
To make it simple, we've done the following (inside the container) which allowed the process to create the subdirectories (and then files) itself:
```
mkdir /opt/sentry
chown sentry: /opt/sentry
```
Unless we've done this, it simply failed to start and just kept restarting.

We don't know why it didn't occur before, perhaps some user activity caused the attempt to store some data there for the first time ever, however it looks like something's missing in the container as the directory structure can't be created by the running process itself.
Also, if the data stored there are supposed to be persistent, it should be stored in a mounted volume that can persist which isn't the case.

Notes:
- While the issue was first observed at Sentry 24.9.0, it also occurs at 24.10.0.
- Once started, it created a few more directories and files such as `01139aa65db64edc93930fea2702ff9a/0`, `12646cbdc35a46a6a7e7e504f2e8e2df/0` in the directory `5`.

### Expected Result

Normal operation/startup without any manual intervention.

### Actual Result

- ingest-replay-recordings container log (for Sentry version 24.10.0 to which we meanwhile updated)
```
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
19:11:14 [INFO] arroyo.processing.processor: New partitions assigned: {Partition(topic=Topic(name='ingest-replay-recordings'), index=0): 0}
Traceback (most recent call last):
  File "/.venv/lib/python3.12/site-packages/arroyo/processing/processor.py", line 322, in run
    self._run_once()
  File "/.venv/lib/python3.12/site-packages/arroyo/processing/processor.py", line 396, in _run_once
    self.__processing_strategy.poll()
  File "/.venv/lib/python3.12/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/.venv/lib/python3.12/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/.venv/lib/python3.12/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/.venv/lib/python3.12/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/replays/consumers/recording.py", line 129, in process_message_threaded
    ingest_recording(message_dict, context.transaction, context.isolation_scope)
  File "/usr/src/sentry/src/sentry/utils/metrics.py", line 229, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/replays/usecases/ingest/__init__.py", line 90, in ingest_recording
    _ingest_recording(message, transaction)
  File "/usr/src/sentry/src/sentry/replays/usecases/ingest/__init__.py", line 154, in _ingest_recording
    storage_kv.set(make_recording_filename(segment_data), compressed_segment)
  File "/usr/src/sentry/src/sentry/utils/metrics.py", line 229, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/replays/lib/storage.py", line 209, in set
    storage.save(key, BytesIO(value))
  File "/.venv/lib/python3.12/site-packages/django/core/files/storage/base.py", line 49, in save
    name = self._save(name, content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/django/core/files/storage/filesystem.py", line 100, in _save
    os.makedirs(directory, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 2 more times]
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/opt/sentry'
19:11:16 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
19:11:16 [INFO] arroyo.processing.processor: Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7fb8a13af500>...
19:11:16 [INFO] arroyo.processing.processor: Partitions to revoke: [Partition(topic=Topic(name='ingest-replay-recordings'), index=0)]
19:11:16 [INFO] arroyo.processing.processor: Partition revocation complete.
19:11:17 [INFO] arroyo.processing.processor: Processor terminated
Traceback (most recent call last):
  File "/.venv/bin/sentry", line 4, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/usr/src/sentry/src/sentry/runner/main.py", line 149, in main
    func(**kwargs)
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/decorators.py", line 83, in inner
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/decorators.py", line 35, in inner
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/commands/run.py", line 386, in basic_consumer
    run_processor_with_signals(processor, consumer_name)
  File "/usr/src/sentry/src/sentry/utils/kafka.py", line 46, in run_processor_with_signals
    processor.run()
  File "/.venv/lib/python3.12/site-packages/arroyo/processing/processor.py", line 322, in run
    self._run_once()
  ... (same as above at 19:11:14)
  File "/.venv/lib/python3.12/site-packages/django/core/files/storage/filesystem.py", line 100, in _save
    os.makedirs(directory, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 2 more times]
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/opt/sentry'
```

**Comment by bruno-garcia** [comment]
Is this how we run things on SaaS? Not sure if the Replay team will have insights here tbqh. If anyone would, it would be @cmanallen but he's on PTO so we won't hear from him for a week or two.

@hubertdeng123 might have some ideas

**Comment by hostalp** [comment]
No, that particular path /opt/sentry is inside a container (ingest-replay-recordings running as part of https://github.com/getsentry/self-hosted) with nothing mounted to the local filesystem.

We haven't done anything about that directory structure until that particular container started crashing - in which case we just manually created them inside the running container (no relationship to the local filesystem). However that isn't a solution of course. Restarting the container, updating the self-hosted Sentry installation - all of this will clear the directory contents (there are some files placed there now) and the container will likely start crashing until we recreate the directory structure inside it again.

**Comment by cmanallen** [comment]
@hostalp Unless configured replay uses the filestore configuration.  Have you modified these values?  Are you seeing similar issues for other products that save to the filesystem?

https://github.com/getsentry/sentry/blob/3b1626b8f57af772e1c030d0b756dd943b0a245b/src/sentry/replays/lib/storage.py#L229-L233
https://github.com/getsentry/sentry/blob/3b1626b8f57af772e1c030d0b756dd943b0a245b/src/sentry/models/files/utils.py#L84-L85

**Comment by hostalp** [comment]
Thanks for the hint. I found some related modifications in **sentry/config.yml** for which I don't know the reason. Typically, we have all the changes documented and it's the case for everything except this.
```diff
-  location: '/data/files'
-dsym.cache-path: '/data/dsym-cache'
-releasefile.cache-path: '/data/releasefile-cache'
+  location: '/opt/sentry/data/files'
+dsym.cache-path: '/opt/sentry/data/dsym-cache'
+releasefile.cache-path: '/opt/sentry/data/releasefile-cache'
```
I changed this back to the defaults (/data/...), updated the Sentry installation to the current 24.11.1 release along with that and will keep an eye on it. I believe that it should work fine now.

**Comment by cmanallen** [comment]
@hostalp Glad I could help!  Thanks for your patience.  Long PTO.  Please re-open if this issue persists.
