### ISSUE TITLE
[Sentry `24.7.1` cleanup] `sentry_rulefirehistory` foreign key constraint

### ISSUE THREAD

**Issue by AnthonyDugarte** [getsentry/sentry#81176]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Sentry version: 24.7.1

running `sentry cleanup --days 30` leads to the error:

```bash
django.db.utils.IntegrityError: ForeignKeyViolation('update or delete on table "sentry_rulefirehistory" violates foreign key constraint "sentry_notificationm_rule_fire_history_id_ada7feba_fk_sentry_ru" on table "sentry_notificationmessage"\nDETAIL:  Key (id)=(593) is still referenced from table "sentry_notificationmessage".\n')
SQL: 
            delete from sentry_rulefirehistory
            where id = any(array(
                select id
                from sentry_rulefirehistory
                where "date_added" < '2024-10-23T14:22:28.189471+00:00'::timestamptz
                
                limit 10000
            ));
```

### Expected Result

Cleanup runs correctly

### Actual Result

```bash
# sentry cleanup --days 30
Removing expired values for LostPasswordHash
Removing expired values for OrganizationMember
Removing expired values for ApiGrant
Removing expired values for ApiToken
Removing expired files associated with ExportedData
Removing old NodeStore values
Running bulk query deletes in BULK_QUERY_DELETES
Removing UserReport for days=30 project=*
Removing GroupEmailThread for days=30 project=*
Removing RuleFireHistory for days=30 project=*
Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/postgres/base.py", line 85, in execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.ForeignKeyViolation: update or delete on table "sentry_rulefirehistory" violates foreign key constraint "sentry_notificationm_rule_fire_history_id_ada7feba_fk_sentry_ru" on table "sentry_notificationmessage"
DETAIL:  Key (id)=(593) is still referenced from table "sentry_notificationmessage".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 93, in inner
    raise type(e)(f"{e!r}\nSQL: {sql}").with_traceback(e.__traceback__)
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/postgres/base.py", line 85, in execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.ForeignKeyViolation: ForeignKeyViolation('update or delete on table "sentry_rulefirehistory" violates foreign key constraint "sentry_notificationm_rule_fire_history_id_ada7feba_fk_sentry_ru" on table "sentry_notificationmessage"\nDETAIL:  Key (id)=(593) is still referenced from table "sentry_notificationmessage".\n')
SQL: 
            delete from sentry_rulefirehistory
            where id = any(array(
                select id
                from sentry_rulefirehistory
                where "date_added" < '2024-10-23T14:22:28.189471+00:00'::timestamptz
                
                limit 10000
            ));
        

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.venv/bin/sentry", line 4, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/usr/src/sentry/src/sentry/runner/main.py", line 149, in main
    func(**kwargs)
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/decorators.py", line 83, in inner
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/commands/cleanup.py", line 313, in cleanup
    ).execute(chunk_size=chunk_size)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/deletion.py", line 68, in execute
    return self._continuous_query(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/deletion.py", line 74, in _continuous_query
    cursor.execute(query)
  File "/.venv/lib/python3.11/site-packages/sentry_sdk/utils.py", line 1713, in runner
    return sentry_patched_function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 650, in execute
    result = real_execute(self, sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/.venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 93, in inner
    raise type(e)(f"{e!r}\nSQL: {sql}").with_traceback(e.__traceback__)
  File "/usr/src/sentry/src/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/db/postgres/base.py", line 85, in execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: ForeignKeyViolation('update or delete on table "sentry_rulefirehistory" violates foreign key constraint "sentry_notificationm_rule_fire_history_id_ada7feba_fk_sentry_ru" on table "sentry_notificationmessage"\nDETAIL:  Key (id)=(593) is still referenced from table "sentry_notificationmessage".\n')
SQL: 
            delete from sentry_rulefirehistory
            where id = any(array(
                select id
                from sentry_rulefirehistory
                where "date_added" < '2024-10-23T14:22:28.189471+00:00'::timestamptz
                
                limit 10000
            ));   
```

### Product Area

Unknown

### Version

24.7.1

**Comment by AnthonyDugarte** [comment]
Fixed in the 24.9.0
