### ISSUE TITLE
Normalise Javassist generated proxies during exception grouping

### ISSUE THREAD

**Issue by stringbean** [getsentry/sentry#8165]
## Environment

* Sentry version: hosted at sentry.io
* Client: Sentry Java 1.3.0-41286
* Server stack: JBoss EAP 6.4 + JBoss Seam

## Issue

Proxy classes generated by [Javassist](http://jboss-javassist.github.io/javassist/) prevent otherwise identical stack traces from being grouped. On our account this has caused 17 issues to be created for the same fault.

By default Javassist creates proxy classes with the following naming: `<classname>_$$_javassist_<num>` (eg `com.example.FooService_$$_javassist_42`). When using JBoss Seam this gets changed to `<classname>_$$_javassist_seam_<num>`.

These proxy classes should be normalised to `<classname>_$$_javassist_seam` / `<classname>_$$_javassist_seam`

## Redacted stack traces

Example 1:
```
com.example.api.exception.RestDetailedNotFoundException: entry not found (resource = "null" field = "null")
    at com.example.api.core.EntityResource$$anonfun$getEntity$1.apply(EntityResource.scala:14)
    at com.example.api.core.EntityResource$$anonfun$getEntity$1.apply(EntityResource.scala:14)
    ...
    at com.example.timing.TimingInterceptor.timeCall(TimingInterceptor.java:40)
    at sun.reflect.GeneratedMethodAccessor72.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    ...
    at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:103)
    at com.example.api.entry.EntriesResource_$$_javassist_seam_74.showForInline(EntriesResource_$$_javassist_seam_74.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    ...
```

Example 2:
```
com.example.api.exception.RestDetailedNotFoundException: entry not found (resource = "null" field = "null")
    at com.example.api.core.EntityResource$$anonfun$getEntity$1.apply(EntityResource.scala:14)
    at com.example.api.core.EntityResource$$anonfun$getEntity$1.apply(EntityResource.scala:14)
    ...
    at com.example.timing.TimingInterceptor.timeCall(TimingInterceptor.java:40)
    at sun.reflect.GeneratedMethodAccessor82.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    ...
    at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:103)
    at com.example.api.entry.EntriesResource_$$_javassist_seam_92.showForInline(EntriesResource_$$_javassist_seam_92.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    ...
```

These are identical apart from:

1. `sun.reflect.GeneratedMethodAccessor72.invoke` - a Java reflections proxy (which I believe is handled by [this code](https://github.com/getsentry/sentry/blob/master/src/sentry/interfaces/stacktrace.py#L189) in Sentry).
1. `com.example.api.entry.EntriesResource_$$_javassist_seam_74.showForInline(EntriesResource_$$_javassist_seam_74.java)` - a Javassist proxy generated by JBoss Seam.

**Comment by bretthoerner** [comment]
PR is merged and will deploy soon.
