### ISSUE TITLE
make develop: node is not pinned to 8.9.1

### ISSUE THREAD

**Issue by JoshuaRLi** [getsentry/sentry#8364]
`sentry, version 8.23.0.dev0 (8347d9f5ae44)`

`make develop-only` requires `node 8.9.1` to finish successfully, but does not enforce this. `node` is currently `10.0.0` and `node@8` is `8.11.1` (also does not work) ﻿in `homebrew/core`.

Will need to rely on `nvm` to install and actively use the version specified in `.nvmrc` throughout the `develop-only` recipe. I'll be submitting a PR for this soon.

**Comment by JoshuaRLi** [comment]
More specifically, the failure happens like this:

```
/Library/Developer/CommandLineTools/usr/bin/make install-python-pkgs-base
--> Installing Python dependencies
LDFLAGS="-L/usr/local/opt/libxmlsec1/lib -L/usr/local/opt/openssl/lib" pip -q install "setuptools>=0.9.8" "pip>=8.0.0"
# order matters here, base package must install first
LDFLAGS="-L/usr/local/opt/libxmlsec1/lib -L/usr/local/opt/openssl/lib" pip -q install -e .
Command "/Users/josh/.virtualenvs/sentry-test-1/bin/python2.7 -c "import setuptools, tokenize;__file__='/Users/josh/sentry/sentry/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/josh/sentry/sentry/
make[1]: *** [install-python-pkgs-base] Error 1
make: *** [install-python-pkgs] Error 2
```

Running the command directly against the 2.7 interpreter results in a more specific error report:

```
$ /Users/josh/.virtualenvs/sentry-test-1/bin/python2.7 -c "import setuptools, tokenize;__file__='/Users/josh/sentry/sentry/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
running develop
running egg_info
writing requirements to src/sentry.egg-info/requires.txt
writing src/sentry.egg-info/PKG-INFO
writing top-level names to src/sentry.egg-info/top_level.txt
writing dependency_links to src/sentry.egg-info/dependency_links.txt
writing entry points to src/sentry.egg-info/entry_points.txt
reading manifest file 'src/sentry.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
writing manifest file 'src/sentry.egg-info/SOURCES.txt'
running build_ext
Creating /Users/josh/.virtualenvs/sentry-test-1/lib/python2.7/site-packages/sentry.egg-link (link to src)
sentry 8.23.0.dev0 is already the active version in easy-install.pth
Installing sentry script to /Users/josh/.virtualenvs/sentry-test-1/bin

Installed /Users/josh/sentry/sentry/src
running build_integration_docs
running build_assets
pulled version information from 'sentry' module
initializing git submodules
using node (v10.0.0) and yarn (1.6.0)
(node:28902) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
pulled version information from 'sentry' module
building assets for sentry v8.23.0.dev0 (build 63f094c3c1d598ab3f764602e019a58761b50985)
node[28903]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::Assert(char const* const (*) [4]) [/usr/local/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x1c1da5f0427d
 8: 0x1c1da5f0f755
 9: 0x1c1da5f8bc20
10: 0x1c1da5f144f7
11: 0x1c1da5f144f7
command failed [node_modules/.bin/webpack --bail] via [/Users/josh/sentry/sentry]
Traceback (most recent call last):
  File "/Users/josh/sentry/sentry/src/sentry/utils/distutils/commands/build_assets.py", line 117, in _build
    self._build_static()
  File "/Users/josh/sentry/sentry/src/sentry/utils/distutils/commands/build_assets.py", line 139, in _build_static
    self._run_command(['node_modules/.bin/webpack', '--bail'], env=env)
  File "/Users/josh/sentry/sentry/src/sentry/utils/distutils/commands/base.py", line 150, in _run_command
    return check_output(cmd, cwd=self.work_path, env=env)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['node_modules/.bin/webpack', '--bail']' returned non-zero exit status -6
unable to build Sentry's static assets!
Hint: You might be running an invalid version of NPM.
```
