### ISSUE TITLE
Trailing slash in URL breaks U2F.

### ISSUE THREAD

**Issue by tld** [getsentry/sentry#8657]
Testing latest master (I believe, listed as 8.23.0.dev0) if we run with a trailing slash in the configured URL, then U2F fails thinking it's an URL mismatch:

(company-internal domain replaced by `our.site` below, and some IPs changed)

```
ValueError: Invalid facet! Was: u'https://our.site', expecting one of: [u'https://our.site/']
```
Notice that the only difference is the trailing slash.

For more context:
```
17:59:34 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'https://our.site/api/0/users/me/authenticators/u2f/enroll/' method=u'POST' ip_address=u'10.123.123.123')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry-8.23.0.dev0-py2.7.egg/sentry/api/base.py", line 87, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry-8.23.0.dev0-py2.7.egg/sentry/api/base.py", line 170, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry-8.23.0.dev0-py2.7.egg/sentry/api/decorators.py", line 28, in wrapped
    return func(self, request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry-8.23.0.dev0-py2.7.egg/sentry/api/endpoints/user_authenticator_enroll.py", line 182, in post
    serializer.data['deviceName']
  File "/usr/local/lib/python2.7/site-packages/sentry-8.23.0.dev0-py2.7.egg/sentry/models/authenticator.py", line 554, in try_enroll
    binding, cert = u2f.complete_register(enrollment_data, response_data, self.u2f_facets)
  File "/usr/local/lib/python2.7/site-packages/u2flib_server/u2f.py", line 64, in complete_register
    valid_facets)
  File "/usr/local/lib/python2.7/site-packages/u2flib_server/u2f_v2.py", line 203, in complete_register
    "navigator.id.finishEnrollment", valid_facets)
  File "/usr/local/lib/python2.7/site-packages/u2flib_server/u2f_v2.py", line 184, in _validate_client_data
    client_data.origin, valid_facets))
ValueError: Invalid facet! Was: u'https://our.site', expecting one of: [u'https://our.site/']
10.123.123.123 - - [05/Jun/2018:17:59:34 +0000] "POST /api/0/users/me/authenticators/u2f/enroll/ HTTP/1.1" 500 576 "https://our.site/settings/account/security/u2f/enroll/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
```

Changing the URL through the admin interface and restarting web server resolved the issue.  It's an easy fix, but it's not obvious what's going on until checking the locks.

**Comment by BYK** [comment]
I'll add docs to https://develop.sentry.dev/config/#general under `system.url-prefix` for this.

**Comment by BYK** [comment]
Closing in favor of #10808 now as it captures the issue more clearly.
