### ISSUE TITLE
Sentry 9 clean install - Crash on iOS is not displayed

### ISSUE THREAD

**Issue by yeleleo** [getsentry/sentry#8936]
- Sentry 9.0.0
- pip install with systemd
- iOS SDK 3.13.1 (tested also with the most recent version with the same result)

What we see in the dashboard:

- In the Stats - /organizations/xxx/stats/ - I see all crashes which I generate in the app (not released version)
![2018-07-04_21-36-57](https://user-images.githubusercontent.com/1327411/42291451-5ff750f6-7fd4-11e8-8e95-bc10a0cec72e.png)

"Accepted" is the number of all crashes generated on device

- In the Project Overview I don't see anything:
![2018-07-04_21-45-55](https://user-images.githubusercontent.com/1327411/42291497-b175c250-7fd4-11e8-85b2-2b47546c2d57.png)

- In the Project Release I see the current build with no events and no issues
![2018-07-04_21-38-30](https://user-images.githubusercontent.com/1327411/42291532-f3d74998-7fd4-11e8-8e34-4b4776c032b4.png)

- At the same time we have debug files successfully uploaded. 
![2018-07-04_21-46-22](https://user-images.githubusercontent.com/1327411/42291584-47d888d6-7fd5-11e8-9f2c-73f68cc183ad.png)

Before we've used sentry.io and the same crash was reported and displayed there sucessfully.

Please advice what is wrong in the configuration?

**Comment by dcramer** [comment]
@yeleleo I might be mistaken, but I think you might need to run the symbol service as well. Are you doing that?

Note there's the preprocessing feature which could be intercepting it waiting for it to actually go through processing.

**Comment by yeleleo** [comment]
@dcramer could you please specify what you are referring to?

**Comment by dcramer** [comment]
@mitsuhiko might be able to provide more context

**Comment by mitsuhiko** [comment]
For system symbols to show up `symbolserver` has to be running as well but this should not make the event not show up entirely. If you look into the sentry server logs you should see why symbolication fails.

**Comment by mrPsycho** [comment]
i see this:
```
Jul 17 14:31:58 server sentry[863]: 14:31:58 [ERROR] celery.worker.job: Task sentry.tasks.assemble.assemble_dif[2e0a2b57-b7f4-4862-ad43-7bf4abc2b4eb] raised unexpected: IOError(2, 'No such file or directory') (data={u'hostname': 'celery@server', u'name': 'sentry.tasks.assemble.assemble_dif', u'args': '[]', u'internal': False, u'kwargs': "{'chunks': ['29c356aab8d52767b5efba3b7734b19a8a1da9ea', 'e4dac69976379da69b59b53288ed9297c2467952'], 'checksum': 'd3d5b610ba629fd89829a0433669756454c0c3dd', 'project_id': 3L, 'name': 'LTHPasscodeViewController'}", u'id': '2e0a2b57-b7f4-4862-ad43-7bf4abc2b4eb'})
Jul 17 14:31:58 server sentry[863]: Traceback (most recent call last):
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
Jul 17 14:31:58 server sentry[863]:     R = retval = fun(*args, **kwargs)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
Jul 17 14:31:58 server sentry[863]:     return self.run(*args, **kwargs)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
Jul 17 14:31:58 server sentry[863]:     result = func(*args, **kwargs)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/tasks/store.py", line 332, in save_event
Jul 17 14:31:58 server sentry[863]:     manager.save(project_id)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 760, in save
Jul 17 14:31:58 server sentry[863]:     event=event, hashes=hashes, release=release, **group_kwargs
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 1080, in _save_aggregate
Jul 17 14:31:58 server sentry[863]:     short_id = project.next_short_id()
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/models/project.py", line 133, in next_short_id
Jul 17 14:31:58 server sentry[863]:     return Counter.increment(self)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/models/counter.py", line 33, in increment
Jul 17 14:31:58 server sentry[863]:     return increment_project_counter(project, delta)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/models/counter.py", line 47, in increment_project_counter
Jul 17 14:31:58 server sentry[863]:     ''', [project.id, delta]
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 123, in execute
Jul 17 14:31:58 server sentry[863]:     return real_execute(self, sql, params)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
Jul 17 14:31:58 server sentry[863]:     return self.cursor.execute(sql, params)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
Jul 17 14:31:58 server sentry[863]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
Jul 17 14:31:58 server sentry[863]:     return self.cursor.execute(sql, params)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
Jul 17 14:31:58 server sentry[863]:     raise_the_exception(self.db, e)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
Jul 17 14:31:58 server sentry[863]:     return func(self, *args, **kwargs)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
Jul 17 14:31:58 server sentry[863]:     return func(self, *args, **kwargs)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
Jul 17 14:31:58 server sentry[863]:     six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
Jul 17 14:31:58 server sentry[863]:     return func(self, sql, *args, **kwargs)
Jul 17 14:31:58 server sentry[863]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 47, in execute
Jul 17 14:31:58 server sentry[863]:     return self.cursor.execute(sql, params)
Jul 17 14:31:58 server sentry[863]: ProgrammingError: ProgrammingError('function sentry_increment_project_counter(integer, integer) does not exist\nLINE 2:                 select sentry_increment_project_counter(1, 1...\n                               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n',)
Jul 17 14:31:58 server sentry[863]: SQL:
Jul 17 14:31:58 server sentry[863]:                 select sentry_increment_project_counter(%s, %s)
Jul 17 14:31:58 server sentry[863]:
Jul 17 14:31:58 server sentry[863]: 14:31:58 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[27c27efc-e0e2-4cb3-9db7-e688fefb277c] raised unexpected: ProgrammingError("ProgrammingError('function sentry_increment_project_counter(integer, integer) does not exist\\nLINE 2:                 select sentry_increment_project_counter(1, 1...\\n                               ^\\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\\n',)\nSQL: \n                select sentry_increment_project_counter(%s, %s)\n            ",) (data={u'hostname': 'celery@server', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'event_id': u'813033d850354a2a86fa21220afb5d96', 'cache_key': 'e:813033d850354a2a86fa21220afb5d96:1', 'start_time': 1531837690.544274, 'project_id': 1, 'data': None}", u'id': '27c27efc-e0e2-4cb3-9db7-e688fefb277c'})
```

why it is so? 

i'm working with @yeleleo, so we both suffer from it.

**Comment by dcramer** [comment]
Looks like somethings wrong with your database (unrelated to this issue). What is the Postgres version and the result of running the upgrade command? This function should have been automatically created by the migration scripts.

**Comment by mrPsycho** [comment]
ok.... could it be connected to #8862? 
cause from the scratch there were errors with db.

**Comment by dcramer** [comment]
Seems plausible

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
