### ISSUE TITLE
[fix] Upgrade 8.22 -> 9.0.0 ValidationError: [u"'' is not a valid JSON string."]

### ISSUE THREAD

**Issue by cajbecu** [getsentry/sentry#9090]
Upgrading from 8.22 -> 9.0.0, when accessing the web interface I received the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/handlers/logging.py", line 94, in emit
    return self._emit(record)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/handlers.py", line 33, in _emit
    return super(SentryHandler, self)._emit(record, request=request)
  File "/usr/local/lib/python2.7/site-packages/raven/handlers/logging.py", line 187, in _emit
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 46, in capture
    return super(SentryInternalClient, self).capture(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 297, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 641, in capture
    self.send(**data)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 75, in send
    key = ProjectKey.get_default(settings.SENTRY_PROJECT)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/projectkey.py", line 121, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 230, in iterator
    obj = model(*row_data)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 54, in __init__
    super(BaseModel, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 347, in __init__
    setattr(self, field.attname, val)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/subclassing.py", line 35, in __set__
    obj.__dict__[self.field.name] = self.field.to_python(value)
  File "/usr/local/lib/python2.7/site-packages/jsonfield/fields.py", line 101, in to_python
    raise ValidationError(msg)
ValidationError: [u"'' is not a valid JSON string."]
```

Debug:
```
# sentry shell
>>> from sentry.models import ProjectKey
>>> ProjectKey.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 71, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 230, in iterator
    obj = model(*row_data)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 54, in __init__
    super(BaseModel, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 347, in __init__
    setattr(self, field.attname, val)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/subclassing.py", line 35, in __set__
    obj.__dict__[self.field.name] = self.field.to_python(value)
  File "/usr/local/lib/python2.7/site-packages/jsonfield/fields.py", line 101, in to_python
    raise ValidationError(msg)
ValidationError: [u"'' is not a valid JSON string."]
```

Fix:
```
ProjectKey.objects.update(data='{}')
```

**Comment by onebuckrule** [comment]
Ran into the same issue. One fix is to change the Postgres db and run sentry upgrade. 9.0 stores data in the sentry_projectkey table which is not in previous versions.

**Comment by BYK** [comment]
Since this is quite old and we don't plan to fix this at all, closing the issue.
