### ISSUE TITLE
Error with database even though I did the upgrade.

### ISSUE THREAD

**Issue by tomgie** [getsentry/sentry#9860]
I am using the latest version of sentry on Docker, 9.0.0.

Error Log
```
Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/middleware.py", line 100, in __call__
    iterable = self.application(environ, start_response)
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/raven/middleware.py", line 27, in common_exception_handling
    client.handle_exception(environ)
  File "/usr/local/lib/python2.7/site-packages/raven/middleware.py", line 115, in handle_exception
    return self.client.captureException()
  File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 814, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 46, in capture
    return super(SentryInternalClient, self).capture(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 297, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 641, in capture
    self.send(**data)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 75, in send
    key = ProjectKey.get_default(settings.SENTRY_PROJECT)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/projectkey.py", line 121, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 123, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 47, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ProgrammingError('column sentry_projectkey.rate_limit_count does not exist\nLINE 1: ...tkey"."status", "sentry_projectkey"."date_added", "sentry_pr...\n                                                             ^\n',)
SQL: SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = %s  AND "sentry_projectkey"."status" = %s  AND "sentry_projectkey"."roles" =  ("sentry_projectkey"."roles" | 1)) LIMIT 1
```

Not sure where to get the config because its the docker container.

**Comment by tomgie** [comment]
bump

**Comment by tomgie** [comment]
Seems like 2 GB is the minimum amount of ram, otherwise the upgrade fails.

**Comment by daniel5gh** [comment]
FWIW I think the migrations did not run to completion. At least I ran into a similar situation when upgrading from 8.10 to 9.0 in one go using 9.0.

In my case `0291_merge_legacy_releases` raised that same `ProgrammingError` (which is why I found this issue). After a quick look I noticed that this `rate_limit_count` field is added in a later migration ([321](https://github.com/getsentry/sentry/blob/c269e6cbb41bf4e22ad4c9fe633d01ea7cb8c549/src/sentry/south_migrations/0321_auto__add_field_projectkey_rate_limit_count__add_field_projectkey_rate.py#L11)). So I concluded that the migration code for 0291 ran with the 9.0 version of sentry _somehow_ requires a field from a later migration, perhaps some utility function.

With this realization I rolled back the failed migrated DB and started over migrating from 8.10 up to 9.0 in smaller steps. (8.12, 8.13, 8.14 (in this step I ran into known issues documented in other github issues), 8.22, 9.0).

Hopefully this info is useful to someone.

**Comment by TheKigen** [comment]
I ran into this as well.  I started with Sentry 8.13 and upgraded to 8.20 then 8.22, and finally to 9.0.  It worked then.
