### ISSUE TITLE
Installing Sentry with python failed because symbolic & semaphore 

### ISSUE THREAD

**Issue by a9tm** [getsentry/sentry#9969]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [X ] Other [briefly describe your environment]

OS: FreeBSD 11.2
Python 2.7
pip

## Description

[What happened]

## Steps to Reproduce

1. pip install -U pip
2. source bin/activate.csh
3. pip install -U sentry

```
Collecting sentry
  Using cached https://files.pythonhosted.org/packages/bb/ee/edda27f5f59a98adb2aa1c0c939d7a15cada155eea73f5b56dc0b593deaa/sentry-9.0.0-py27-none-any.whl
Requirement already satisfied, skipping upgrade: click<7.0,>=5.0 in ./lib/python2.7/site-packages (from sentry) (6.7)
Requirement already satisfied, skipping upgrade: functools32<3.3,>=3.2.3 in ./lib/python2.7/site-packages (from sentry) (3.2.3.post2)
Requirement already satisfied, skipping upgrade: pytest-django<2.10.0,>=2.9.1 in ./lib/python2.7/site-packages (from sentry) (2.9.1)
Requirement already satisfied, skipping upgrade: django-jsonfield<0.9.14,>=0.9.13 in ./lib/python2.7/site-packages (from sentry) (0.9.13)
Requirement already satisfied, skipping upgrade: python-dateutil<3.0.0,>=2.0.0 in ./lib/python2.7/site-packages (from sentry) (2.7.3)
Requirement already satisfied, skipping upgrade: Django<1.7,>=1.6.11 in ./lib/python2.7/site-packages (from sentry) (1.6.11)
Requirement already satisfied, skipping upgrade: unidiff>=0.5.4 in ./lib/python2.7/site-packages (from sentry) (0.5.5)
Requirement already satisfied, skipping upgrade: cssutils<0.10.0,>=0.9.9 in ./lib/python2.7/site-packages (from sentry) (0.9.10)
Requirement already satisfied, skipping upgrade: python-memcached<2.0.0,>=1.53 in ./lib/python2.7/site-packages (from sentry) (1.59)
Collecting semaphore<0.2.0,>=0.1.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/7f/93/af09573ec5f447a44973aee3c26cfe1b7a4c658c00262ae73b8c879c013e/semaphore-0.1.3.zip
Collecting rb<2.0.0,>=1.7.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/4c/a5/bab74a0ea263cdd4954c6784cbbed9787d3dec2341b23a7448f40f718be2/rb-1.7-py2-none-any.whl
Collecting exam>=0.5.1 (from sentry)
Collecting requests[security]<2.19.0,>=2.18.4 (from sentry)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting PyJWT<1.6.0,>=1.5.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/8a/a6/4d931a2c77a224d27c78382f4ce8ec07542d4426ea2793bea77a689273c2/PyJWT-1.5.3-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.22 (from sentry)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Collecting kombu==3.0.35 (from sentry)
  Using cached https://files.pythonhosted.org/packages/34/e6/a81b9cbcb107fc45af2d77b9f4b9745448be42b9952cc4c974f69a9239e7/kombu-3.0.35-py2.py3-none-any.whl
Collecting loremipsum<1.1.0,>=1.0.5 (from sentry)
Collecting setproctitle<1.2.0,>=1.1.7 (from sentry)
Collecting django-sudo<3.0.0,>=2.1.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/a2/89/10a6e48ced1bf78ccd18c8b291a6a04906a8ad8950894b43929adb5f2ff5/django_sudo-2.1.0-py2.py3-none-any.whl
Collecting petname<2.1,>=2.0 (from sentry)
Collecting querystring-parser<2.0.0,>=1.2.3 (from sentry)
Collecting qrcode<6.0.0,>=5.2.2 (from sentry)
  Using cached https://files.pythonhosted.org/packages/39/71/c01d42a3fc1a9c768c93980f26159ec682dc7bd49407e756f671b52b8344/qrcode-5.3-py2.py3-none-any.whl
Collecting jsonschema==2.6.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting BeautifulSoup>=3.2.1 (from sentry)
Collecting django-crispy-forms<1.5.0,>=1.4.0 (from sentry)
Requirement already satisfied, skipping upgrade: pytest<3.6.0,>=3.5.0 in ./lib/python2.7/site-packages (from sentry) (3.5.1)
Collecting python-openid>=2.2 (from sentry)
Collecting uwsgi<2.1.0,>2.0.0 (from sentry)
Collecting simplejson<3.9.0,>=3.2.0 (from sentry)
Collecting hiredis<0.2.0,>=0.1.0 (from sentry)
Collecting raven<=6.4.0,>=6.0.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/0c/0a/76de154a3a8f9fdeeff3463db37cb0e5616740a7d7c5d099ac78127d5fbf/raven-6.4.0-py2.py3-none-any.whl
Collecting celery<3.1.19,>=3.1.8 (from sentry)
  Using cached https://files.pythonhosted.org/packages/94/50/2b824c2a2b53a05763a71138fa494f913b272511ead9757522a9ab3c0077/celery-3.1.18-py2.py3-none-any.whl
Collecting botocore<1.5.71 (from sentry)
  Using cached https://files.pythonhosted.org/packages/b4/87/7ca29ef8d210de618b4510d3c98131edd17ba1e2617f80e6f6bd3498caa6/botocore-1.5.70-py2.py3-none-any.whl
Collecting mmh3<2.4,>=2.3.1 (from sentry)
Collecting pytest-html<1.10.0,>=1.9.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/f7/08/225d5929808239856890cc797215ecaa4894c5dc2cf843f193192928e9c5/pytest_html-1.9.0-py2.py3-none-any.whl
Collecting djangorestframework<2.5.0,>=2.4.8 (from sentry)
  Using cached https://files.pythonhosted.org/packages/f9/fd/00c8b6764cac6cfc2c2ef1df53849cd597384da135fb0d5055354a2c1f38/djangorestframework-2.4.8-py2.py3-none-any.whl
Collecting percy>=1.1.2 (from sentry)
  Using cached https://files.pythonhosted.org/packages/7f/ee/32956d89039adbaecbee5c59d1d9c6b7385f956e0f92c853ec636264c23e/percy-2.0.0-py2.py3-none-any.whl
Collecting PyYAML<3.12,>=3.11 (from sentry)
Collecting django-templatetag-sugar>=0.1.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/72/61/ec7b883ff5f8d0641eea522b23e382918d214b27c1f63c5449ac0bcba1e7/django_templatetag_sugar-1.0-py2.py3-none-any.whl
Collecting boto3<1.4.6,>=1.4.1 (from sentry)
  Using cached https://files.pythonhosted.org/packages/fb/8a/95ae869835746b8ff51fd7cd799e19e7ecd10b4c668fbc3d187dcf8db27e/boto3-1.4.5-py2.py3-none-any.whl
Collecting parsimonious==0.8.0 (from sentry)
Collecting futures<4.0.0,>=3.2.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting strict-rfc3339>=0.7 (from sentry)
Collecting ipaddress<1.1.0,>=1.0.16 (from sentry)
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting symbolic<6.0.0,>=5.0.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/2f/c0/aa9e01de1dbcb4cac0b04ca75004cb49d766d7c67b840328ca44ecd05277/symbolic-5.3.0.zip
Collecting sqlparse<0.2.0,>=0.1.16 (from sentry)
Collecting lxml>=3.4.1 (from sentry)
Collecting progressbar2<3.11,>=3.10 (from sentry)
  Using cached https://files.pythonhosted.org/packages/aa/13/7fc75289f0f6a46d83913bfbe3db8003f0d56fd96a8564f6b334b830d461/progressbar2-3.10.1-py2.py3-none-any.whl
Collecting mock==2.0.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
Collecting structlog==16.1.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/c5/bf/f87b8273e5016618d750e79a2dae7f42b0a6310bc1f4368dcb217b426e8e/structlog-16.1.0-py2.py3-none-any.whl
Collecting psycopg2<2.8.0,>=2.6.0 (from sentry)
Collecting Pillow<=4.2.1,>=3.2.0 (from sentry)
Collecting statsd<3.2.0,>=3.1.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/fc/29/b935cacecab8bd6b20d3895a69592cca76711229e7d9a0b2e18234652beb/statsd-3.1-py2.py3-none-any.whl
Collecting ua-parser<0.8.0,>=0.6.1 (from sentry)
  Using cached https://files.pythonhosted.org/packages/28/a6/9c4d9a1da685376e369312ac522c13725dd29cf7d5354e69baa19c7c188f/ua_parser-0.7.3-py2.py3-none-any.whl
Collecting email-reply-parser<0.3.0,>=0.2.0 (from sentry)
Collecting django-picklefield<0.4.0,>=0.3.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/b1/67/0f7f24e61f71aa7c604dab55497495f599906a20187e92edf70939c71d80/django_picklefield-0.3.2-py2.py3-none-any.whl
Collecting oauth2>=1.5.167 (from sentry)
  Using cached https://files.pythonhosted.org/packages/a0/6f/86db603912ecd04109af952c38bc08928886cf0e34c723481fa7db98b4b5/oauth2-1.9.0.post1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: redis-py-cluster<1.4.0,>=1.3.4 in ./lib/python2.7/site-packages (from sentry) (1.3.5)
Collecting enum34<1.2.0,>=1.1.6 (from sentry)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Requirement already satisfied, skipping upgrade: six<1.11.0,>=1.10.0 in ./lib/python2.7/site-packages (from sentry) (1.10.0)
Collecting selenium==3.11.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/5e/1f/6c2204b9ae14eddab615c5e2ee4956c65ed533e0a9986c23eabd801ae849/selenium-3.11.0-py2.py3-none-any.whl
Collecting toronado<0.1.0,>=0.0.11 (from sentry)
Collecting python-u2flib-server<4.1.0,>=4.0.1 (from sentry)
Collecting redis<2.10.6,>=2.10.3 (from sentry)
  Using cached https://files.pythonhosted.org/packages/08/c1/457428f7507e27ba7144758a7b716ea35766e6d602f4a0c16e443ab3d381/redis-2.10.5-py2.py3-none-any.whl
Collecting honcho<1.1.0,>=1.0.0 (from sentry)
  Using cached https://files.pythonhosted.org/packages/12/c2/95faf9e062e37f50fb685972692395bef019a554c08447282a81e35bf031/honcho-1.0.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: milksnake>=0.1.2 in ./lib/python2.7/site-packages (from semaphore<0.2.0,>=0.1.0->sentry) (0.1.5)
Collecting chardet<3.1.0,>=3.0.2 (from requests[security]<2.19.0,>=2.18.4->sentry)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests[security]<2.19.0,>=2.18.4->sentry)
  Using cached https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests[security]<2.19.0,>=2.18.4->sentry)
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting cryptography>=1.3.4; extra == "security" (from requests[security]<2.19.0,>=2.18.4->sentry)
Collecting pyOpenSSL>=0.14; extra == "security" (from requests[security]<2.19.0,>=2.18.4->sentry)
  Using cached https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl
Collecting amqp<2.0,>=1.4.9 (from kombu==3.0.35->sentry)
  Using cached https://files.pythonhosted.org/packages/ed/09/314d2788aba0aa91f2578071a6484f87a615172a98c309c2aad3433da90b/amqp-1.4.9-py2.py3-none-any.whl
Collecting anyjson>=0.3.3 (from kombu==3.0.35->sentry)
Requirement already satisfied, skipping upgrade: setuptools in ./lib/python2.7/site-packages (from pytest<3.6.0,>=3.5.0->sentry) (40.4.3)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in ./lib/python2.7/site-packages (from pytest<3.6.0,>=3.5.0->sentry) (18.2.0)
Requirement already satisfied, skipping upgrade: funcsigs; python_version < "3.0" in ./lib/python2.7/site-packages (from pytest<3.6.0,>=3.5.0->sentry) (1.0.2)
Requirement already satisfied, skipping upgrade: pluggy<0.7,>=0.5 in ./lib/python2.7/site-packages (from pytest<3.6.0,>=3.5.0->sentry) (0.6.0)
Requirement already satisfied, skipping upgrade: more-itertools>=4.0.0 in ./lib/python2.7/site-packages (from pytest<3.6.0,>=3.5.0->sentry) (4.3.0)
Requirement already satisfied, skipping upgrade: py>=1.5.0 in ./lib/python2.7/site-packages (from pytest<3.6.0,>=3.5.0->sentry) (1.6.0)
Collecting contextlib2; python_version < "3.2" (from raven<=6.4.0,>=6.0.0->sentry)
  Using cached https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl
Collecting billiard<3.4,>=3.3.0.20 (from celery<3.1.19,>=3.1.8->sentry)
Collecting pytz>dev (from celery<3.1.19,>=3.1.8->sentry)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from botocore<1.5.71->sentry)
  Using cached https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.5.71->sentry)
  Using cached https://files.pythonhosted.org/packages/50/09/c53398e0005b11f7ffb27b7aa720c617aba53be4fb4f4f3f06b9b5c60f28/docutils-0.14-py2-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3<1.4.6,>=1.4.1->sentry)
  Using cached https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl
Collecting python-utils>=2.0.0 (from progressbar2<3.11,>=3.10->sentry)
  Using cached https://files.pythonhosted.org/packages/eb/a0/19119d8b7c05be49baf6c593f11c432d571b70d805f2fe94c0585e55e4c8/python_utils-2.3.0-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->sentry)
  Using cached https://files.pythonhosted.org/packages/69/1c/98cba002ed975a91a0294863d9c774cc0ebe38e05bbb65e83314550b1677/pbr-4.2.0-py2.py3-none-any.whl
Collecting olefile (from Pillow<=4.2.1,>=3.2.0->sentry)
Collecting httplib2 (from oauth2>=1.5.167->sentry)
Collecting cssselect (from toronado<0.1.0,>=0.0.11->sentry)
  Using cached https://files.pythonhosted.org/packages/7b/44/25b7283e50585f0b4156960691d951b05d061abf4a714078393e51929b30/cssselect-1.0.3-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: cffi>=1.6.0 in ./lib/python2.7/site-packages (from milksnake>=0.1.2->semaphore<0.2.0,>=0.1.0->sentry) (1.11.5)
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4; extra == "security"->requests[security]<2.19.0,>=2.18.4->sentry)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pycparser in ./lib/python2.7/site-packages (from cffi>=1.6.0->milksnake>=0.1.2->semaphore<0.2.0,>=0.1.0->sentry) (2.19)
Building wheels for collected packages: semaphore, symbolic
  Running setup.py bdist_wheel for semaphore ... error
  Complete output from command /usr/local/sentry/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-MydaDL/semaphore/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-U97vaG --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build/lib
  creating build/lib/semaphore
  copying semaphore/_compat.py -> build/lib/semaphore
  copying semaphore/exceptions.py -> build/lib/semaphore
  copying semaphore/auth.py -> build/lib/semaphore
  copying semaphore/__init__.py -> build/lib/semaphore
  copying semaphore/utils.py -> build/lib/semaphore
  error: [Errno 2] No such file or directory
  
  ----------------------------------------
  Failed building wheel for semaphore
  Running setup.py clean for semaphore
  Running setup.py bdist_wheel for symbolic ... error
  Complete output from command /usr/local/sentry/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-MydaDL/symbolic/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-otnDVh --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build/lib
  creating build/lib/symbolic
  copying symbolic/__init__.py -> build/lib/symbolic
  copying symbolic/_compat.py -> build/lib/symbolic
  copying symbolic/common.py -> build/lib/symbolic
  copying symbolic/debuginfo.py -> build/lib/symbolic
  copying symbolic/demangle.py -> build/lib/symbolic
  copying symbolic/exceptions.py -> build/lib/symbolic
  copying symbolic/minidump.py -> build/lib/symbolic
  copying symbolic/proguard.py -> build/lib/symbolic
  copying symbolic/sourcemap.py -> build/lib/symbolic
  copying symbolic/symcache.py -> build/lib/symbolic
  copying symbolic/utils.py -> build/lib/symbolic
  error: [Errno 2] No such file or directory
  
  ----------------------------------------
  Failed building wheel for symbolic
  Running setup.py clean for symbolic
Failed to build semaphore symbolic
redis-py-cluster 1.3.5 has requirement redis>=2.10.6, but you'll have redis 2.10.5 which is incompatible.
Installing collected packages: semaphore, redis, rb, pbr, mock, exam, chardet, certifi, urllib3, idna, asn1crypto, enum34, ipaddress, cryptography, pyOpenSSL, requests, PyJWT, amqp, anyjson, kombu, loremipsum, setproctitle, django-sudo, petname, querystring-parser, qrcode, jsonschema, BeautifulSoup, django-crispy-forms, python-openid, uwsgi, simplejson, hiredis, contextlib2, raven, billiard, pytz, celery, jmespath, docutils, botocore, mmh3, pytest-html, djangorestframework, percy, PyYAML, django-templatetag-sugar, futures, s3transfer, boto3, parsimonious, strict-rfc3339, symbolic, sqlparse, lxml, python-utils, progressbar2, structlog, psycopg2, olefile, Pillow, statsd, ua-parser, email-reply-parser, django-picklefield, httplib2, oauth2, selenium, cssselect, toronado, python-u2flib-server, honcho, sentry
  Running setup.py install for semaphore ... error
    Complete output from command /usr/local/sentry/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-MydaDL/semaphore/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-GM9HNH/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/sentry/include/site/python2.7/semaphore:
    running install
    running build
    running build_py
    creating build/lib
    creating build/lib/semaphore
    copying semaphore/_compat.py -> build/lib/semaphore
    copying semaphore/exceptions.py -> build/lib/semaphore
    copying semaphore/auth.py -> build/lib/semaphore
    copying semaphore/__init__.py -> build/lib/semaphore
    copying semaphore/utils.py -> build/lib/semaphore
    error: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "/usr/local/sentry/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-MydaDL/semaphore/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-GM9HNH/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/sentry/include/site/python2.7/semaphore" failed with error code 1 in /tmp/pip-install-MydaDL/semaphore/
```

```
# pip list
Package          Version    
---------------- -----------
attrs            18.2.0     
awscli           1.16.25    
botocore         1.12.15    
cffi             1.11.5     
click            6.7        
colorama         0.3.9      
cssutils         0.9.10     
Django           1.6.11     
django-jsonfield 0.9.13     
docutils         0.14       
funcsigs         1.0.2      
functools32      3.2.3.post2
futures          3.2.0      
jmespath         0.9.3      
milksnake        0.1.5      
more-itertools   4.3.0      
pip              18.0       
pluggy           0.6.0      
py               1.6.0      
pyasn1           0.4.4      
pycparser        2.19       
pytest           3.5.1      
pytest-django    2.9.1      
python-dateutil  2.7.3      
python-memcached 1.59       
PyYAML           3.13       
redis            2.10.6     
redis-py-cluster 1.3.5      
rsa              3.4.2      
s3transfer       0.1.13     
setuptools       40.4.3     
six              1.10.0     
unidiff          0.5.5      
urllib3          1.23       
wheel            0.32.   
```

### What you expected to happen

Successfully installed Sentry

### Possible Solution

I don't know

**Comment by mattrobenolt** [comment]
We don’t support FreeBSD. Please use Ubuntu/Debian and it would work.

**Comment by maznu** [comment]
Getting the same on Ubuntu 16.04 LTS

```
pipenv install sentry

[blahblahblah]

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches redis<2.10.6,>=2.10.3,>=2.10.6,>=2.6
Tried: 0.6.0, 0.6.1, 1.34, 1.34.1, 2.0.0, 2.2.0, 2.2.2, 2.2.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.5, 2.10.5, 2.10.6, 2.10.6
There are incompatible versions in the resolved dependencies.
```

This is with a Pipfile of:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
pip = "*"
sentry = "*"

[requires]
python_version = "2.7"
```

The dependency graph shows:

```
  - rb [required: >=1.7.0,<2.0.0, installed: 1.7]
    - redis [required: >=2.6, installed: 2.10.5]
  - redis [required: >=2.10.3,<2.10.6, installed: 2.10.5]
  - redis-py-cluster [required: >=1.3.4,<1.4.0, installed: 1.3.5]
    - redis [required: >=2.10.6, installed: 2.10.5]
```

**Comment by Salamek** [comment]
I'm havig same issues on Debian 9

```sh
 Running setup.py install for semaphore
    Running command /var/www/sentry.salamek.cz/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-BRdYLZ/semaphore/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Y9Ifwk-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/sentry.salamek.cz/include/site/python2.7
    running install
    running build
    running build_py
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/semaphore
    copying semaphore/__init__.py -> build/lib.linux-x86_64-2.7/semaphore
    copying semaphore/exceptions.py -> build/lib.linux-x86_64-2.7/semaphore
    copying semaphore/_compat.py -> build/lib.linux-x86_64-2.7/semaphore
    copying semaphore/utils.py -> build/lib.linux-x86_64-2.7/semaphore
    copying semaphore/auth.py -> build/lib.linux-x86_64-2.7/semaphore
    error: [Errno 2] No such file or directory
    Complete output from command /var/www/sentry.salamek.cz/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-BRdYLZ/semaphore/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Y9Ifwk-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/sentry.salamek.cz/include/site/python2.7:
    running install

running build

running build_py

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/semaphore

copying semaphore/__init__.py -> build/lib.linux-x86_64-2.7/semaphore

copying semaphore/exceptions.py -> build/lib.linux-x86_64-2.7/semaphore

copying semaphore/_compat.py -> build/lib.linux-x86_64-2.7/semaphore

copying semaphore/utils.py -> build/lib.linux-x86_64-2.7/semaphore

copying semaphore/auth.py -> build/lib.linux-x86_64-2.7/semaphore

error: [Errno 2] No such file or directory

----------------------------------------
Cleaning up...
Command /var/www/sentry.salamek.cz/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-BRdYLZ/semaphore/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Y9Ifwk-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/sentry.salamek.cz/include/site/python2.7 failed with error code 1 in /tmp/pip-build-BRdYLZ/semaphore
Exception information:
Traceback (most recent call last):
  File "/var/www/sentry.salamek.cz/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/var/www/sentry.salamek.cz/local/lib/python2.7/site-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/var/www/sentry.salamek.cz/local/lib/python2.7/site-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/var/www/sentry.salamek.cz/local/lib/python2.7/site-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/var/www/sentry.salamek.cz/local/lib/python2.7/site-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /var/www/sentry.salamek.cz/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-BRdYLZ/semaphore/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Y9Ifwk-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/sentry.salamek.cz/include/site/python2.7 failed with error code 1 in /tmp/pip-build-BRdYLZ/semaphore

```

**Comment by vokimon** [comment]
Just in case somebody else fall into this error. The missing file is `cargo` the rust package installer. A check and a descriptive message about missing Rust would be nice.
